// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="VMRouterTop_L1PHID,hls_ip_2020_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xcvu7p-flvb2104-1-e,HLS_INPUT_CLOCK=4.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.238000,HLS_SYN_LAT=112,HLS_SYN_TPT=none,HLS_SYN_MEM=2,HLS_SYN_DSP=0,HLS_SYN_FF=788,HLS_SYN_LUT=1574,HLS_VERSION=2020_1}" *)

module VMRouterTop_L1PHID (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        bx_V,
        bx_o_V,
        bx_o_V_ap_vld,
        inputStubs_0_dataarray_data_V_address0,
        inputStubs_0_dataarray_data_V_ce0,
        inputStubs_0_dataarray_data_V_q0,
        inputStubs_1_dataarray_data_V_address0,
        inputStubs_1_dataarray_data_V_ce0,
        inputStubs_1_dataarray_data_V_q0,
        inputStubs_2_dataarray_data_V_address0,
        inputStubs_2_dataarray_data_V_ce0,
        inputStubs_2_dataarray_data_V_q0,
        inputStubs_0_nentries_0_V,
        inputStubs_0_nentries_1_V,
        inputStubs_1_nentries_0_V,
        inputStubs_1_nentries_1_V,
        inputStubs_2_nentries_0_V,
        inputStubs_2_nentries_1_V,
        memoriesAS_0_dataarray_data_V_address0,
        memoriesAS_0_dataarray_data_V_ce0,
        memoriesAS_0_dataarray_data_V_we0,
        memoriesAS_0_dataarray_data_V_d0,
        memoriesTEI_0_0_dataarray_data_V_address0,
        memoriesTEI_0_0_dataarray_data_V_ce0,
        memoriesTEI_0_0_dataarray_data_V_we0,
        memoriesTEI_0_0_dataarray_data_V_d0,
        memoriesTEI_0_1_dataarray_data_V_address0,
        memoriesTEI_0_1_dataarray_data_V_ce0,
        memoriesTEI_0_1_dataarray_data_V_we0,
        memoriesTEI_0_1_dataarray_data_V_d0,
        memoriesTEI_0_2_dataarray_data_V_address0,
        memoriesTEI_0_2_dataarray_data_V_ce0,
        memoriesTEI_0_2_dataarray_data_V_we0,
        memoriesTEI_0_2_dataarray_data_V_d0,
        memoriesTEI_0_3_dataarray_data_V_address0,
        memoriesTEI_0_3_dataarray_data_V_ce0,
        memoriesTEI_0_3_dataarray_data_V_we0,
        memoriesTEI_0_3_dataarray_data_V_d0,
        memoriesTEI_1_0_dataarray_data_V_address0,
        memoriesTEI_1_0_dataarray_data_V_ce0,
        memoriesTEI_1_0_dataarray_data_V_we0,
        memoriesTEI_1_0_dataarray_data_V_d0,
        memoriesTEI_1_1_dataarray_data_V_address0,
        memoriesTEI_1_1_dataarray_data_V_ce0,
        memoriesTEI_1_1_dataarray_data_V_we0,
        memoriesTEI_1_1_dataarray_data_V_d0,
        memoriesTEI_1_2_dataarray_data_V_address0,
        memoriesTEI_1_2_dataarray_data_V_ce0,
        memoriesTEI_1_2_dataarray_data_V_we0,
        memoriesTEI_1_2_dataarray_data_V_d0,
        memoriesTEI_1_3_dataarray_data_V_address0,
        memoriesTEI_1_3_dataarray_data_V_ce0,
        memoriesTEI_1_3_dataarray_data_V_we0,
        memoriesTEI_1_3_dataarray_data_V_d0,
        memoriesTEI_2_0_dataarray_data_V_address0,
        memoriesTEI_2_0_dataarray_data_V_ce0,
        memoriesTEI_2_0_dataarray_data_V_we0,
        memoriesTEI_2_0_dataarray_data_V_d0,
        memoriesTEI_2_1_dataarray_data_V_address0,
        memoriesTEI_2_1_dataarray_data_V_ce0,
        memoriesTEI_2_1_dataarray_data_V_we0,
        memoriesTEI_2_1_dataarray_data_V_d0,
        memoriesTEI_2_2_dataarray_data_V_address0,
        memoriesTEI_2_2_dataarray_data_V_ce0,
        memoriesTEI_2_2_dataarray_data_V_we0,
        memoriesTEI_2_2_dataarray_data_V_d0,
        memoriesTEI_2_3_dataarray_data_V_address0,
        memoriesTEI_2_3_dataarray_data_V_ce0,
        memoriesTEI_2_3_dataarray_data_V_we0,
        memoriesTEI_2_3_dataarray_data_V_d0,
        memoriesTEI_3_0_dataarray_data_V_address0,
        memoriesTEI_3_0_dataarray_data_V_ce0,
        memoriesTEI_3_0_dataarray_data_V_we0,
        memoriesTEI_3_0_dataarray_data_V_d0,
        memoriesTEI_3_1_dataarray_data_V_address0,
        memoriesTEI_3_1_dataarray_data_V_ce0,
        memoriesTEI_3_1_dataarray_data_V_we0,
        memoriesTEI_3_1_dataarray_data_V_d0,
        memoriesTEI_3_2_dataarray_data_V_address0,
        memoriesTEI_3_2_dataarray_data_V_ce0,
        memoriesTEI_3_2_dataarray_data_V_we0,
        memoriesTEI_3_2_dataarray_data_V_d0,
        memoriesTEI_3_3_dataarray_data_V_address0,
        memoriesTEI_3_3_dataarray_data_V_ce0,
        memoriesTEI_3_3_dataarray_data_V_we0,
        memoriesTEI_3_3_dataarray_data_V_d0
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_pp0_stage0 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [2:0] bx_V;
output  [2:0] bx_o_V;
output   bx_o_V_ap_vld;
output  [7:0] inputStubs_0_dataarray_data_V_address0;
output   inputStubs_0_dataarray_data_V_ce0;
input  [35:0] inputStubs_0_dataarray_data_V_q0;
output  [7:0] inputStubs_1_dataarray_data_V_address0;
output   inputStubs_1_dataarray_data_V_ce0;
input  [35:0] inputStubs_1_dataarray_data_V_q0;
output  [7:0] inputStubs_2_dataarray_data_V_address0;
output   inputStubs_2_dataarray_data_V_ce0;
input  [35:0] inputStubs_2_dataarray_data_V_q0;
input  [6:0] inputStubs_0_nentries_0_V;
input  [6:0] inputStubs_0_nentries_1_V;
input  [6:0] inputStubs_1_nentries_0_V;
input  [6:0] inputStubs_1_nentries_1_V;
input  [6:0] inputStubs_2_nentries_0_V;
input  [6:0] inputStubs_2_nentries_1_V;
output  [9:0] memoriesAS_0_dataarray_data_V_address0;
output   memoriesAS_0_dataarray_data_V_ce0;
output   memoriesAS_0_dataarray_data_V_we0;
output  [35:0] memoriesAS_0_dataarray_data_V_d0;
output  [7:0] memoriesTEI_0_0_dataarray_data_V_address0;
output   memoriesTEI_0_0_dataarray_data_V_ce0;
output   memoriesTEI_0_0_dataarray_data_V_we0;
output  [21:0] memoriesTEI_0_0_dataarray_data_V_d0;
output  [7:0] memoriesTEI_0_1_dataarray_data_V_address0;
output   memoriesTEI_0_1_dataarray_data_V_ce0;
output   memoriesTEI_0_1_dataarray_data_V_we0;
output  [21:0] memoriesTEI_0_1_dataarray_data_V_d0;
output  [7:0] memoriesTEI_0_2_dataarray_data_V_address0;
output   memoriesTEI_0_2_dataarray_data_V_ce0;
output   memoriesTEI_0_2_dataarray_data_V_we0;
output  [21:0] memoriesTEI_0_2_dataarray_data_V_d0;
output  [7:0] memoriesTEI_0_3_dataarray_data_V_address0;
output   memoriesTEI_0_3_dataarray_data_V_ce0;
output   memoriesTEI_0_3_dataarray_data_V_we0;
output  [21:0] memoriesTEI_0_3_dataarray_data_V_d0;
output  [7:0] memoriesTEI_1_0_dataarray_data_V_address0;
output   memoriesTEI_1_0_dataarray_data_V_ce0;
output   memoriesTEI_1_0_dataarray_data_V_we0;
output  [21:0] memoriesTEI_1_0_dataarray_data_V_d0;
output  [7:0] memoriesTEI_1_1_dataarray_data_V_address0;
output   memoriesTEI_1_1_dataarray_data_V_ce0;
output   memoriesTEI_1_1_dataarray_data_V_we0;
output  [21:0] memoriesTEI_1_1_dataarray_data_V_d0;
output  [7:0] memoriesTEI_1_2_dataarray_data_V_address0;
output   memoriesTEI_1_2_dataarray_data_V_ce0;
output   memoriesTEI_1_2_dataarray_data_V_we0;
output  [21:0] memoriesTEI_1_2_dataarray_data_V_d0;
output  [7:0] memoriesTEI_1_3_dataarray_data_V_address0;
output   memoriesTEI_1_3_dataarray_data_V_ce0;
output   memoriesTEI_1_3_dataarray_data_V_we0;
output  [21:0] memoriesTEI_1_3_dataarray_data_V_d0;
output  [7:0] memoriesTEI_2_0_dataarray_data_V_address0;
output   memoriesTEI_2_0_dataarray_data_V_ce0;
output   memoriesTEI_2_0_dataarray_data_V_we0;
output  [21:0] memoriesTEI_2_0_dataarray_data_V_d0;
output  [7:0] memoriesTEI_2_1_dataarray_data_V_address0;
output   memoriesTEI_2_1_dataarray_data_V_ce0;
output   memoriesTEI_2_1_dataarray_data_V_we0;
output  [21:0] memoriesTEI_2_1_dataarray_data_V_d0;
output  [7:0] memoriesTEI_2_2_dataarray_data_V_address0;
output   memoriesTEI_2_2_dataarray_data_V_ce0;
output   memoriesTEI_2_2_dataarray_data_V_we0;
output  [21:0] memoriesTEI_2_2_dataarray_data_V_d0;
output  [7:0] memoriesTEI_2_3_dataarray_data_V_address0;
output   memoriesTEI_2_3_dataarray_data_V_ce0;
output   memoriesTEI_2_3_dataarray_data_V_we0;
output  [21:0] memoriesTEI_2_3_dataarray_data_V_d0;
output  [7:0] memoriesTEI_3_0_dataarray_data_V_address0;
output   memoriesTEI_3_0_dataarray_data_V_ce0;
output   memoriesTEI_3_0_dataarray_data_V_we0;
output  [21:0] memoriesTEI_3_0_dataarray_data_V_d0;
output  [7:0] memoriesTEI_3_1_dataarray_data_V_address0;
output   memoriesTEI_3_1_dataarray_data_V_ce0;
output   memoriesTEI_3_1_dataarray_data_V_we0;
output  [21:0] memoriesTEI_3_1_dataarray_data_V_d0;
output  [7:0] memoriesTEI_3_2_dataarray_data_V_address0;
output   memoriesTEI_3_2_dataarray_data_V_ce0;
output   memoriesTEI_3_2_dataarray_data_V_we0;
output  [21:0] memoriesTEI_3_2_dataarray_data_V_d0;
output  [7:0] memoriesTEI_3_3_dataarray_data_V_address0;
output   memoriesTEI_3_3_dataarray_data_V_ce0;
output   memoriesTEI_3_3_dataarray_data_V_we0;
output  [21:0] memoriesTEI_3_3_dataarray_data_V_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg inputStubs_0_dataarray_data_V_ce0;
reg inputStubs_1_dataarray_data_V_ce0;
reg inputStubs_2_dataarray_data_V_ce0;
reg memoriesAS_0_dataarray_data_V_ce0;
reg memoriesAS_0_dataarray_data_V_we0;
reg memoriesTEI_0_0_dataarray_data_V_ce0;
reg memoriesTEI_0_0_dataarray_data_V_we0;
reg memoriesTEI_0_1_dataarray_data_V_ce0;
reg memoriesTEI_0_1_dataarray_data_V_we0;
reg memoriesTEI_0_2_dataarray_data_V_ce0;
reg memoriesTEI_0_2_dataarray_data_V_we0;
reg memoriesTEI_0_3_dataarray_data_V_ce0;
reg memoriesTEI_0_3_dataarray_data_V_we0;
reg memoriesTEI_1_0_dataarray_data_V_ce0;
reg memoriesTEI_1_0_dataarray_data_V_we0;
reg memoriesTEI_1_1_dataarray_data_V_ce0;
reg memoriesTEI_1_1_dataarray_data_V_we0;
reg memoriesTEI_1_2_dataarray_data_V_ce0;
reg memoriesTEI_1_2_dataarray_data_V_we0;
reg memoriesTEI_1_3_dataarray_data_V_ce0;
reg memoriesTEI_1_3_dataarray_data_V_we0;
reg memoriesTEI_2_0_dataarray_data_V_ce0;
reg memoriesTEI_2_0_dataarray_data_V_we0;
reg memoriesTEI_2_1_dataarray_data_V_ce0;
reg memoriesTEI_2_1_dataarray_data_V_we0;
reg memoriesTEI_2_2_dataarray_data_V_ce0;
reg memoriesTEI_2_2_dataarray_data_V_we0;
reg memoriesTEI_2_3_dataarray_data_V_ce0;
reg memoriesTEI_2_3_dataarray_data_V_we0;
reg memoriesTEI_3_0_dataarray_data_V_ce0;
reg memoriesTEI_3_0_dataarray_data_V_we0;
reg memoriesTEI_3_1_dataarray_data_V_ce0;
reg memoriesTEI_3_1_dataarray_data_V_we0;
reg memoriesTEI_3_2_dataarray_data_V_ce0;
reg memoriesTEI_3_2_dataarray_data_V_we0;
reg memoriesTEI_3_3_dataarray_data_V_ce0;
reg memoriesTEI_3_3_dataarray_data_V_we0;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] icmp_ln672_fu_1113_p2;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
wire    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_state4_pp0_stage0_iter2;
wire    ap_block_state5_pp0_stage0_iter3;
wire    ap_block_state6_pp0_stage0_iter4;
reg    bx_o_V_1_ack_in;
reg    ap_block_state7_pp0_stage0_iter5;
reg    ap_enable_reg_pp0_iter5;
reg    ap_block_pp0_stage0_11001;
reg   [2:0] bx_o_V_1_data_reg;
reg    bx_o_V_1_vld_reg;
reg    bx_o_V_1_vld_in;
wire   [5:0] lut_1_address0;
reg    lut_1_ce0;
wire   [14:0] lut_1_q0;
wire   [10:0] lut_address0;
reg    lut_ce0;
wire   [10:0] lut_q0;
reg   [0:0] do_init_reg_699;
reg   [6:0] addr_index_assign6_reg_715;
reg   [6:0] addr_index_assign6_reg_715_pp0_iter1_reg;
reg   [6:0] addr_index_assign6_reg_715_pp0_iter2_reg;
reg   [6:0] addr_index_assign6_reg_715_pp0_iter3_reg;
reg   [6:0] addr_index_assign6_reg_715_pp0_iter4_reg;
reg   [6:0] nInputs_2_V_1_rewind_reg_730;
reg   [6:0] nInputs_1_V_rewind_reg_744;
reg   [6:0] nInputs_0_V_rewind_reg_758;
reg   [0:0] p_rewind_reg_772;
reg   [2:0] bx_V7_rewind_reg_786;
reg   [2:0] p_what2_4_rewind_reg_800;
reg   [6:0] nInputs_2_V_01_rewind_reg_814;
reg   [6:0] nInputs_1_V_02_rewind_reg_828;
reg   [6:0] nInputs_2_V3_rewind_reg_842;
reg   [6:0] p_05_reg_856;
reg   [6:0] nInputs_2_V_1_phi_reg_910;
reg   [6:0] nInputs_1_V_phi_reg_922;
reg   [6:0] nInputs_0_V_phi_reg_934;
reg   [0:0] p_phi_reg_946;
reg   [0:0] p_phi_reg_946_pp0_iter2_reg;
reg   [0:0] p_phi_reg_946_pp0_iter3_reg;
reg   [0:0] p_phi_reg_946_pp0_iter4_reg;
reg   [2:0] bx_V7_phi_reg_958;
reg   [2:0] bx_V7_phi_reg_958_pp0_iter2_reg;
reg   [2:0] bx_V7_phi_reg_958_pp0_iter3_reg;
reg   [2:0] bx_V7_phi_reg_958_pp0_iter4_reg;
reg   [0:0] ap_phi_mux_do_init_phi_fu_703_p6;
wire   [0:0] trunc_ln209_fu_971_p1;
wire   [6:0] nInputs_0_V_fu_975_p3;
wire   [6:0] nInputs_1_V_fu_989_p3;
wire   [6:0] nInputs_2_V_fu_1003_p3;
wire   [2:0] p_Result_5_2_fu_1017_p4;
wire   [6:0] i_fu_1107_p2;
reg   [6:0] i_reg_2166;
reg   [0:0] icmp_ln672_reg_2171;
reg   [0:0] icmp_ln672_reg_2171_pp0_iter1_reg;
reg   [0:0] icmp_ln672_reg_2171_pp0_iter2_reg;
reg   [0:0] icmp_ln672_reg_2171_pp0_iter3_reg;
reg   [0:0] icmp_ln672_reg_2171_pp0_iter4_reg;
wire   [0:0] noStubsLeft_fu_1119_p2;
reg   [0:0] noStubsLeft_reg_2175;
reg   [0:0] noStubsLeft_reg_2175_pp0_iter2_reg;
reg   [0:0] noStubsLeft_reg_2175_pp0_iter3_reg;
reg   [0:0] noStubsLeft_reg_2175_pp0_iter4_reg;
wire   [0:0] icmp_ln687_fu_1137_p2;
reg   [0:0] icmp_ln687_reg_2181;
reg   [0:0] icmp_ln687_reg_2181_pp0_iter2_reg;
wire   [1:0] trunc_ln42_fu_1158_p1;
reg   [1:0] trunc_ln42_reg_2202;
reg   [1:0] trunc_ln42_reg_2202_pp0_iter2_reg;
wire   [6:0] nInputs_2_V_7_fu_1236_p3;
reg   [6:0] nInputs_2_V_7_reg_2207;
reg    ap_enable_reg_pp0_iter1;
wire   [6:0] nInputs_2_V_8_fu_1252_p3;
reg   [6:0] nInputs_2_V_8_reg_2212;
wire   [6:0] nInputs_2_V_10_fu_1260_p3;
reg   [6:0] nInputs_2_V_10_reg_2217;
wire   [2:0] p_what2_s_fu_1268_p3;
reg   [2:0] p_what2_s_reg_2222;
wire   [6:0] read_addr_V_1_fu_1294_p3;
reg   [6:0] read_addr_V_1_reg_2227;
wire   [35:0] p_Val2_s_fu_1320_p3;
reg   [35:0] p_Val2_s_reg_2232;
reg   [35:0] p_Val2_s_reg_2232_pp0_iter4_reg;
wire   [0:0] or_ln675_1_fu_1327_p2;
reg   [0:0] or_ln675_1_reg_2238;
reg   [0:0] or_ln675_1_reg_2238_pp0_iter4_reg;
wire   [2:0] bend_V_fu_1341_p1;
reg   [2:0] bend_V_reg_2242;
reg   [2:0] bend_V_reg_2242_pp0_iter4_reg;
reg   [0:0] tmp_13_reg_2258;
wire   [13:0] trunc_ln214_fu_1464_p1;
reg   [13:0] trunc_ln214_reg_2263;
reg    ap_block_pp0_stage0_subdone;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
wire    ap_block_pp0_stage0;
reg   [6:0] ap_phi_mux_addr_index_assign6_phi_fu_719_p6;
reg   [6:0] ap_phi_mux_nInputs_2_V_1_rewind_phi_fu_734_p6;
reg   [6:0] ap_phi_mux_nInputs_1_V_rewind_phi_fu_748_p6;
reg   [6:0] ap_phi_mux_nInputs_0_V_rewind_phi_fu_762_p6;
reg   [0:0] ap_phi_mux_p_rewind_phi_fu_776_p6;
reg   [2:0] ap_phi_mux_bx_V7_rewind_phi_fu_790_p6;
reg   [2:0] ap_phi_mux_p_what2_4_rewind_phi_fu_804_p6;
reg   [6:0] ap_phi_mux_nInputs_2_V_01_rewind_phi_fu_818_p6;
reg   [6:0] ap_phi_mux_nInputs_1_V_02_rewind_phi_fu_832_p6;
reg   [6:0] ap_phi_mux_nInputs_2_V3_rewind_phi_fu_846_p6;
reg   [6:0] ap_phi_mux_p_05_phi_fu_860_p6;
reg   [2:0] ap_phi_mux_p_what2_4_phi_fu_873_p4;
wire   [2:0] ap_phi_reg_pp0_iter0_p_what2_4_reg_870;
reg   [2:0] ap_phi_reg_pp0_iter1_p_what2_4_reg_870;
reg   [6:0] ap_phi_mux_nInputs_2_V3_phi_fu_883_p4;
wire   [6:0] ap_phi_reg_pp0_iter0_nInputs_2_V3_reg_880;
reg   [6:0] ap_phi_reg_pp0_iter1_nInputs_2_V3_reg_880;
reg   [6:0] ap_phi_mux_nInputs_1_V_02_phi_fu_893_p4;
wire   [6:0] ap_phi_reg_pp0_iter0_nInputs_1_V_02_reg_890;
reg   [6:0] ap_phi_reg_pp0_iter1_nInputs_1_V_02_reg_890;
reg   [6:0] ap_phi_mux_nInputs_2_V_01_phi_fu_903_p4;
wire   [6:0] ap_phi_reg_pp0_iter0_nInputs_2_V_01_reg_900;
reg   [6:0] ap_phi_reg_pp0_iter1_nInputs_2_V_01_reg_900;
wire   [6:0] ap_phi_reg_pp0_iter0_nInputs_2_V_1_phi_reg_910;
reg   [6:0] ap_phi_reg_pp0_iter1_nInputs_2_V_1_phi_reg_910;
wire   [6:0] ap_phi_reg_pp0_iter0_nInputs_1_V_phi_reg_922;
reg   [6:0] ap_phi_reg_pp0_iter1_nInputs_1_V_phi_reg_922;
wire   [6:0] ap_phi_reg_pp0_iter0_nInputs_0_V_phi_reg_934;
reg   [6:0] ap_phi_reg_pp0_iter1_nInputs_0_V_phi_reg_934;
reg   [0:0] ap_phi_mux_p_phi_phi_fu_950_p4;
wire   [0:0] ap_phi_reg_pp0_iter0_p_phi_reg_946;
reg   [0:0] ap_phi_reg_pp0_iter1_p_phi_reg_946;
wire   [2:0] ap_phi_reg_pp0_iter0_bx_V7_phi_reg_958;
reg   [2:0] ap_phi_reg_pp0_iter1_bx_V7_phi_reg_958;
wire   [63:0] zext_ln42_fu_1151_p1;
wire   [63:0] zext_ln544_fu_1369_p1;
wire   [63:0] zext_ln400_fu_1408_p1;
wire   [63:0] zext_ln321_fu_1476_p1;
wire   [63:0] zext_ln321_1_fu_1669_p1;
wire   [0:0] icmp_ln807_fu_1542_p2;
wire   [0:0] p_Result_s_fu_1564_p2;
wire   [0:0] icmp_ln792_fu_1623_p2;
wire   [63:0] zext_ln321_2_fu_1779_p1;
wire   [0:0] icmp_ln792_1_fu_1733_p2;
wire   [63:0] zext_ln321_3_fu_1879_p1;
wire   [0:0] icmp_ln792_2_fu_1833_p2;
wire   [63:0] zext_ln321_4_fu_1985_p1;
wire   [0:0] icmp_ln792_4_fu_1939_p2;
reg   [6:0] addrCountTEI_0_0_V_fu_300;
wire   [6:0] addrCountTEI_0_0_V_2_fu_1677_p2;
wire   [1:0] trunc_ln_fu_1570_p4;
reg   [6:0] addrCountTEI_0_1_V_fu_304;
wire   [6:0] addrCountTEI_0_1_V_2_fu_1787_p2;
reg   [6:0] addrCountTEI_0_2_V_fu_308;
wire   [6:0] addrCountTEI_0_2_V_2_fu_1887_p2;
reg   [6:0] addrCountTEI_0_3_V_fu_312;
wire   [6:0] addrCountTEI_0_3_V_2_fu_1993_p2;
reg   [6:0] addrCountTEI_1_0_V_fu_316;
reg   [6:0] addrCountTEI_1_1_V_fu_320;
reg   [6:0] addrCountTEI_1_2_V_fu_324;
reg   [6:0] addrCountTEI_1_3_V_fu_328;
reg   [6:0] addrCountTEI_2_0_V_fu_332;
reg   [6:0] addrCountTEI_2_1_V_fu_336;
reg   [6:0] addrCountTEI_2_2_V_fu_340;
reg   [6:0] addrCountTEI_2_3_V_fu_344;
reg   [6:0] addrCountTEI_3_0_V_fu_348;
reg   [6:0] addrCountTEI_3_1_V_fu_352;
reg   [6:0] addrCountTEI_3_2_V_fu_356;
reg   [6:0] addrCountTEI_3_3_V_fu_360;
reg    ap_block_pp0_stage0_01001;
wire   [21:0] p_Result_2_fu_1515_p5;
wire   [0:0] icmp_ln841_2_fu_1011_p2;
wire   [0:0] icmp_ln841_1_fu_997_p2;
wire   [0:0] icmp_ln841_fu_983_p2;
wire   [31:0] zext_ln684_fu_1125_p1;
reg   [31:0] mem_index_fu_1129_p3;
wire   [7:0] tmp_9_fu_1143_p3;
wire   [6:0] tmp_fu_1162_p5;
wire   [0:0] resetNext_fu_1174_p2;
wire   [0:0] p_Repl2_s_fu_1180_p2;
wire   [0:0] icmp_ln701_1_fu_1208_p2;
wire   [6:0] nInputs_2_V_9_fu_1196_p2;
wire   [0:0] icmp_ln701_fu_1202_p2;
wire   [0:0] or_ln675_fu_1222_p2;
wire   [6:0] select_ln675_fu_1228_p3;
wire   [6:0] select_ln675_2_fu_1244_p3;
wire   [6:0] nInputs_2_V_6_fu_1214_p3;
reg   [2:0] p_Result_1_fu_1186_p4;
wire   [0:0] xor_ln675_fu_1276_p2;
wire   [0:0] and_ln675_fu_1282_p2;
wire   [6:0] read_addr_V_fu_1288_p2;
wire   [35:0] stub_data_V_fu_1302_p5;
wire   [35:0] select_ln687_fu_1313_p3;
wire   [6:0] r_V_fu_1331_p4;
wire   [6:0] ret_V_fu_1345_p2;
wire   [2:0] rBin_V_fu_1351_p4;
wire   [5:0] tmp_i_i_fu_1361_p3;
wire   [6:0] tmp_12_fu_1374_p4;
wire   [6:0] indexz_V_fu_1384_p2;
wire   [3:0] indexr_V_fu_1390_p4;
wire   [10:0] tmp_18_fu_1400_p3;
wire   [13:0] phi_V_fu_1413_p4;
wire   [15:0] zext_ln215_fu_1422_p1;
wire  signed [15:0] sext_ln215_fu_1426_p1;
wire   [15:0] ret_V_2_fu_1430_p2;
wire   [0:0] tmp_11_fu_1440_p3;
wire   [14:0] trunc_ln1354_fu_1436_p1;
wire   [14:0] phiCorr_V_2_fu_1448_p3;
wire   [9:0] tmp_10_fu_1468_p3;
wire   [13:0] phiCorr_V_fu_1481_p3;
wire   [4:0] iphivm_V_fu_1497_p4;
wire   [1:0] p_Result_i6_i_fu_1487_p4;
wire   [9:0] trunc_ln301_fu_1511_p1;
wire   [15:0] zext_ln215_1_fu_1507_p1;
wire   [15:0] shl_ln792_fu_1548_p2;
wire   [2:0] tmp_19_fu_1554_p4;
wire   [3:0] shl_ln_fu_1580_p3;
wire   [0:0] icmp_ln792_6_fu_1594_p2;
wire   [7:0] zext_ln792_fu_1608_p1;
wire   [7:0] select_ln792_fu_1600_p3;
wire   [7:0] shl_ln792_1_fu_1611_p2;
wire   [7:0] and_ln792_fu_1617_p2;
wire   [1:0] tmp_1_fu_1647_p5;
wire   [6:0] tmp_1_fu_1647_p6;
wire   [7:0] tmp_14_fu_1661_p3;
wire   [3:0] add_ln792_fu_1588_p2;
wire   [1:0] phi_ln792_1_fu_1713_p5;
wire   [7:0] phi_ln792_1_fu_1713_p6;
wire   [7:0] and_ln792_1_fu_1727_p2;
wire   [1:0] tmp_4_fu_1757_p5;
wire   [6:0] tmp_4_fu_1757_p6;
wire   [7:0] tmp_15_fu_1771_p3;
wire   [1:0] phi_ln792_2_fu_1813_p5;
wire   [7:0] phi_ln792_2_fu_1813_p6;
wire   [7:0] and_ln792_2_fu_1827_p2;
wire   [1:0] tmp_5_fu_1857_p5;
wire   [6:0] tmp_5_fu_1857_p6;
wire   [7:0] tmp_16_fu_1871_p3;
wire   [3:0] or_ln792_fu_1913_p2;
wire   [0:0] icmp_ln792_3_fu_1919_p2;
wire   [7:0] select_ln792_1_fu_1925_p3;
wire   [7:0] and_ln792_3_fu_1933_p2;
wire   [1:0] tmp_7_fu_1963_p5;
wire   [6:0] tmp_7_fu_1963_p6;
wire   [7:0] tmp_17_fu_1977_p3;
reg   [1:0] ap_NS_fsm;
reg    ap_idle_pp0_0to4;
reg    ap_reset_idle_pp0;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_1174;
reg    ap_condition_1182;
reg    ap_condition_1186;
reg    ap_condition_1190;
reg    ap_condition_1194;
reg    ap_condition_1197;
reg    ap_condition_1200;
reg    ap_condition_1203;
reg    ap_condition_1206;
reg    ap_condition_1209;
reg    ap_condition_1212;
reg    ap_condition_1215;
reg    ap_condition_1218;
reg    ap_condition_1221;
reg    ap_condition_1224;
reg    ap_condition_1227;
reg    ap_condition_1230;
reg    ap_condition_401;
reg    ap_condition_49;
reg    ap_condition_347;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 bx_o_V_1_data_reg = 3'd0;
#0 bx_o_V_1_vld_reg = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
end

VMRouterTop_L1PHID_lut_1 #(
    .DataWidth( 15 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
lut_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(lut_1_address0),
    .ce0(lut_1_ce0),
    .q0(lut_1_q0)
);

VMRouterTop_L1PHID_lut #(
    .DataWidth( 11 ),
    .AddressRange( 2048 ),
    .AddressWidth( 11 ))
lut_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(lut_address0),
    .ce0(lut_ce0),
    .q0(lut_q0)
);

VMRouterTop_L1PHID_mux_32_7_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 7 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 7 ))
VMRouterTop_L1PHID_mux_32_7_1_1_U1(
    .din0(ap_phi_mux_nInputs_2_V3_phi_fu_883_p4),
    .din1(ap_phi_mux_nInputs_1_V_02_phi_fu_893_p4),
    .din2(ap_phi_mux_nInputs_2_V_01_phi_fu_903_p4),
    .din3(trunc_ln42_fu_1158_p1),
    .dout(tmp_fu_1162_p5)
);

VMRouterTop_L1PHID_mux_32_36_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 36 ),
    .din1_WIDTH( 36 ),
    .din2_WIDTH( 36 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 36 ))
VMRouterTop_L1PHID_mux_32_36_1_1_U2(
    .din0(inputStubs_0_dataarray_data_V_q0),
    .din1(inputStubs_1_dataarray_data_V_q0),
    .din2(inputStubs_2_dataarray_data_V_q0),
    .din3(trunc_ln42_reg_2202_pp0_iter2_reg),
    .dout(stub_data_V_fu_1302_p5)
);

VMRouterTop_L1PHID_mux_42_7_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 7 ),
    .din3_WIDTH( 7 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 7 ))
VMRouterTop_L1PHID_mux_42_7_1_1_U3(
    .din0(addrCountTEI_0_0_V_fu_300),
    .din1(addrCountTEI_1_0_V_fu_316),
    .din2(addrCountTEI_2_0_V_fu_332),
    .din3(addrCountTEI_3_0_V_fu_348),
    .din4(tmp_1_fu_1647_p5),
    .dout(tmp_1_fu_1647_p6)
);

VMRouterTop_L1PHID_mux_42_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
VMRouterTop_L1PHID_mux_42_8_1_1_U4(
    .din0(8'd241),
    .din1(8'd159),
    .din2(8'd159),
    .din3(8'd159),
    .din4(phi_ln792_1_fu_1713_p5),
    .dout(phi_ln792_1_fu_1713_p6)
);

VMRouterTop_L1PHID_mux_42_7_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 7 ),
    .din3_WIDTH( 7 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 7 ))
VMRouterTop_L1PHID_mux_42_7_1_1_U5(
    .din0(addrCountTEI_0_1_V_fu_304),
    .din1(addrCountTEI_1_1_V_fu_320),
    .din2(addrCountTEI_2_1_V_fu_336),
    .din3(addrCountTEI_3_1_V_fu_352),
    .din4(tmp_4_fu_1757_p5),
    .dout(tmp_4_fu_1757_p6)
);

VMRouterTop_L1PHID_mux_42_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
VMRouterTop_L1PHID_mux_42_8_1_1_U6(
    .din0(8'd0),
    .din1(8'd255),
    .din2(8'd255),
    .din3(8'd255),
    .din4(phi_ln792_2_fu_1813_p5),
    .dout(phi_ln792_2_fu_1813_p6)
);

VMRouterTop_L1PHID_mux_42_7_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 7 ),
    .din3_WIDTH( 7 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 7 ))
VMRouterTop_L1PHID_mux_42_7_1_1_U7(
    .din0(addrCountTEI_0_2_V_fu_308),
    .din1(addrCountTEI_1_2_V_fu_324),
    .din2(addrCountTEI_2_2_V_fu_340),
    .din3(addrCountTEI_3_2_V_fu_356),
    .din4(tmp_5_fu_1857_p5),
    .dout(tmp_5_fu_1857_p6)
);

VMRouterTop_L1PHID_mux_42_7_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 7 ),
    .din3_WIDTH( 7 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 7 ))
VMRouterTop_L1PHID_mux_42_7_1_1_U8(
    .din0(addrCountTEI_0_3_V_fu_312),
    .din1(addrCountTEI_1_3_V_fu_328),
    .din2(addrCountTEI_2_3_V_fu_344),
    .din3(addrCountTEI_3_3_V_fu_360),
    .din4(tmp_7_fu_1963_p5),
    .dout(tmp_7_fu_1963_p6)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter5 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if ((1'b1 == ap_condition_1182)) begin
            addrCountTEI_0_0_V_fu_300 <= addrCountTEI_0_0_V_2_fu_1677_p2;
        end else if ((1'b1 == ap_condition_1174)) begin
            addrCountTEI_0_0_V_fu_300 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if ((1'b1 == ap_condition_1186)) begin
            addrCountTEI_0_1_V_fu_304 <= addrCountTEI_0_1_V_2_fu_1787_p2;
        end else if ((1'b1 == ap_condition_1174)) begin
            addrCountTEI_0_1_V_fu_304 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if ((1'b1 == ap_condition_1190)) begin
            addrCountTEI_0_2_V_fu_308 <= addrCountTEI_0_2_V_2_fu_1887_p2;
        end else if ((1'b1 == ap_condition_1174)) begin
            addrCountTEI_0_2_V_fu_308 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if ((1'b1 == ap_condition_1194)) begin
            addrCountTEI_0_3_V_fu_312 <= addrCountTEI_0_3_V_2_fu_1993_p2;
        end else if ((1'b1 == ap_condition_1174)) begin
            addrCountTEI_0_3_V_fu_312 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if ((1'b1 == ap_condition_1197)) begin
            addrCountTEI_1_0_V_fu_316 <= addrCountTEI_0_0_V_2_fu_1677_p2;
        end else if ((1'b1 == ap_condition_1174)) begin
            addrCountTEI_1_0_V_fu_316 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if ((1'b1 == ap_condition_1200)) begin
            addrCountTEI_1_1_V_fu_320 <= addrCountTEI_0_1_V_2_fu_1787_p2;
        end else if ((1'b1 == ap_condition_1174)) begin
            addrCountTEI_1_1_V_fu_320 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if ((1'b1 == ap_condition_1203)) begin
            addrCountTEI_1_2_V_fu_324 <= addrCountTEI_0_2_V_2_fu_1887_p2;
        end else if ((1'b1 == ap_condition_1174)) begin
            addrCountTEI_1_2_V_fu_324 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if ((1'b1 == ap_condition_1206)) begin
            addrCountTEI_1_3_V_fu_328 <= addrCountTEI_0_3_V_2_fu_1993_p2;
        end else if ((1'b1 == ap_condition_1174)) begin
            addrCountTEI_1_3_V_fu_328 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if ((1'b1 == ap_condition_1209)) begin
            addrCountTEI_2_0_V_fu_332 <= addrCountTEI_0_0_V_2_fu_1677_p2;
        end else if ((1'b1 == ap_condition_1174)) begin
            addrCountTEI_2_0_V_fu_332 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if ((1'b1 == ap_condition_1212)) begin
            addrCountTEI_2_1_V_fu_336 <= addrCountTEI_0_1_V_2_fu_1787_p2;
        end else if ((1'b1 == ap_condition_1174)) begin
            addrCountTEI_2_1_V_fu_336 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if ((1'b1 == ap_condition_1215)) begin
            addrCountTEI_2_2_V_fu_340 <= addrCountTEI_0_2_V_2_fu_1887_p2;
        end else if ((1'b1 == ap_condition_1174)) begin
            addrCountTEI_2_2_V_fu_340 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if ((1'b1 == ap_condition_1218)) begin
            addrCountTEI_2_3_V_fu_344 <= addrCountTEI_0_3_V_2_fu_1993_p2;
        end else if ((1'b1 == ap_condition_1174)) begin
            addrCountTEI_2_3_V_fu_344 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if ((1'b1 == ap_condition_1221)) begin
            addrCountTEI_3_0_V_fu_348 <= addrCountTEI_0_0_V_2_fu_1677_p2;
        end else if ((1'b1 == ap_condition_1174)) begin
            addrCountTEI_3_0_V_fu_348 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if ((1'b1 == ap_condition_1224)) begin
            addrCountTEI_3_1_V_fu_352 <= addrCountTEI_0_1_V_2_fu_1787_p2;
        end else if ((1'b1 == ap_condition_1174)) begin
            addrCountTEI_3_1_V_fu_352 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if ((1'b1 == ap_condition_1227)) begin
            addrCountTEI_3_2_V_fu_356 <= addrCountTEI_0_2_V_2_fu_1887_p2;
        end else if ((1'b1 == ap_condition_1174)) begin
            addrCountTEI_3_2_V_fu_356 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if ((1'b1 == ap_condition_1230)) begin
            addrCountTEI_3_3_V_fu_360 <= addrCountTEI_0_3_V_2_fu_1993_p2;
        end else if ((1'b1 == ap_condition_1174)) begin
            addrCountTEI_3_3_V_fu_360 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln672_reg_2171 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        addr_index_assign6_reg_715 <= i_reg_2166;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln672_reg_2171 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        addr_index_assign6_reg_715 <= 7'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_49)) begin
        if ((ap_phi_mux_do_init_phi_fu_703_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_bx_V7_phi_reg_958 <= bx_V;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_bx_V7_phi_reg_958 <= ap_phi_reg_pp0_iter0_bx_V7_phi_reg_958;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_49)) begin
        if ((ap_phi_mux_do_init_phi_fu_703_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_nInputs_0_V_phi_reg_934 <= nInputs_0_V_fu_975_p3;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_nInputs_0_V_phi_reg_934 <= ap_phi_reg_pp0_iter0_nInputs_0_V_phi_reg_934;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_49)) begin
        if ((ap_phi_mux_do_init_phi_fu_703_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_nInputs_1_V_02_reg_890 <= nInputs_1_V_fu_989_p3;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_nInputs_1_V_02_reg_890 <= ap_phi_reg_pp0_iter0_nInputs_1_V_02_reg_890;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_49)) begin
        if ((ap_phi_mux_do_init_phi_fu_703_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_nInputs_1_V_phi_reg_922 <= nInputs_1_V_fu_989_p3;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_nInputs_1_V_phi_reg_922 <= ap_phi_reg_pp0_iter0_nInputs_1_V_phi_reg_922;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_49)) begin
        if ((ap_phi_mux_do_init_phi_fu_703_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_nInputs_2_V3_reg_880 <= nInputs_0_V_fu_975_p3;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_nInputs_2_V3_reg_880 <= ap_phi_reg_pp0_iter0_nInputs_2_V3_reg_880;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_49)) begin
        if ((ap_phi_mux_do_init_phi_fu_703_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_nInputs_2_V_01_reg_900 <= nInputs_2_V_fu_1003_p3;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_nInputs_2_V_01_reg_900 <= ap_phi_reg_pp0_iter0_nInputs_2_V_01_reg_900;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_49)) begin
        if ((ap_phi_mux_do_init_phi_fu_703_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_nInputs_2_V_1_phi_reg_910 <= nInputs_2_V_fu_1003_p3;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_nInputs_2_V_1_phi_reg_910 <= ap_phi_reg_pp0_iter0_nInputs_2_V_1_phi_reg_910;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_49)) begin
        if ((ap_phi_mux_do_init_phi_fu_703_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_p_phi_reg_946 <= trunc_ln209_fu_971_p1;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_p_phi_reg_946 <= ap_phi_reg_pp0_iter0_p_phi_reg_946;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_49)) begin
        if ((ap_phi_mux_do_init_phi_fu_703_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_p_what2_4_reg_870 <= p_Result_5_2_fu_1017_p4;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_p_what2_4_reg_870 <= ap_phi_reg_pp0_iter0_p_what2_4_reg_870;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_347)) begin
        if ((do_init_reg_699 == 1'd0)) begin
            bx_V7_phi_reg_958 <= ap_phi_mux_bx_V7_rewind_phi_fu_790_p6;
        end else if ((1'b1 == 1'b1)) begin
            bx_V7_phi_reg_958 <= ap_phi_reg_pp0_iter1_bx_V7_phi_reg_958;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (bx_o_V_1_vld_reg == 1'b0) & (bx_o_V_1_vld_in == 1'b1))) begin
        bx_o_V_1_vld_reg <= 1'b1;
    end else if (((bx_o_V_1_vld_in == 1'b0) & (1'b1 == 1'b1) & (bx_o_V_1_vld_reg == 1'b1))) begin
        bx_o_V_1_vld_reg <= 1'b0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln672_reg_2171 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        do_init_reg_699 <= 1'd0;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln672_reg_2171 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        do_init_reg_699 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_347)) begin
        if ((do_init_reg_699 == 1'd0)) begin
            nInputs_0_V_phi_reg_934 <= ap_phi_mux_nInputs_0_V_rewind_phi_fu_762_p6;
        end else if ((1'b1 == 1'b1)) begin
            nInputs_0_V_phi_reg_934 <= ap_phi_reg_pp0_iter1_nInputs_0_V_phi_reg_934;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_347)) begin
        if ((do_init_reg_699 == 1'd0)) begin
            nInputs_1_V_phi_reg_922 <= ap_phi_mux_nInputs_1_V_rewind_phi_fu_748_p6;
        end else if ((1'b1 == 1'b1)) begin
            nInputs_1_V_phi_reg_922 <= ap_phi_reg_pp0_iter1_nInputs_1_V_phi_reg_922;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_347)) begin
        if ((do_init_reg_699 == 1'd0)) begin
            nInputs_2_V_1_phi_reg_910 <= ap_phi_mux_nInputs_2_V_1_rewind_phi_fu_734_p6;
        end else if ((1'b1 == 1'b1)) begin
            nInputs_2_V_1_phi_reg_910 <= ap_phi_reg_pp0_iter1_nInputs_2_V_1_phi_reg_910;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln672_reg_2171_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_05_reg_856 <= read_addr_V_1_reg_2227;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln672_reg_2171_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        p_05_reg_856 <= 7'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_347)) begin
        if ((do_init_reg_699 == 1'd0)) begin
            p_phi_reg_946 <= ap_phi_mux_p_rewind_phi_fu_776_p6;
        end else if ((1'b1 == 1'b1)) begin
            p_phi_reg_946 <= ap_phi_reg_pp0_iter1_p_phi_reg_946;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        addr_index_assign6_reg_715_pp0_iter1_reg <= addr_index_assign6_reg_715;
        icmp_ln672_reg_2171 <= icmp_ln672_fu_1113_p2;
        icmp_ln672_reg_2171_pp0_iter1_reg <= icmp_ln672_reg_2171;
        icmp_ln687_reg_2181 <= icmp_ln687_fu_1137_p2;
        noStubsLeft_reg_2175 <= noStubsLeft_fu_1119_p2;
        trunc_ln42_reg_2202 <= trunc_ln42_fu_1158_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        addr_index_assign6_reg_715_pp0_iter2_reg <= addr_index_assign6_reg_715_pp0_iter1_reg;
        addr_index_assign6_reg_715_pp0_iter3_reg <= addr_index_assign6_reg_715_pp0_iter2_reg;
        addr_index_assign6_reg_715_pp0_iter4_reg <= addr_index_assign6_reg_715_pp0_iter3_reg;
        bend_V_reg_2242_pp0_iter4_reg <= bend_V_reg_2242;
        bx_V7_phi_reg_958_pp0_iter2_reg <= bx_V7_phi_reg_958;
        bx_V7_phi_reg_958_pp0_iter3_reg <= bx_V7_phi_reg_958_pp0_iter2_reg;
        bx_V7_phi_reg_958_pp0_iter4_reg <= bx_V7_phi_reg_958_pp0_iter3_reg;
        icmp_ln672_reg_2171_pp0_iter2_reg <= icmp_ln672_reg_2171_pp0_iter1_reg;
        icmp_ln672_reg_2171_pp0_iter3_reg <= icmp_ln672_reg_2171_pp0_iter2_reg;
        icmp_ln672_reg_2171_pp0_iter4_reg <= icmp_ln672_reg_2171_pp0_iter3_reg;
        icmp_ln687_reg_2181_pp0_iter2_reg <= icmp_ln687_reg_2181;
        noStubsLeft_reg_2175_pp0_iter2_reg <= noStubsLeft_reg_2175;
        noStubsLeft_reg_2175_pp0_iter3_reg <= noStubsLeft_reg_2175_pp0_iter2_reg;
        noStubsLeft_reg_2175_pp0_iter4_reg <= noStubsLeft_reg_2175_pp0_iter3_reg;
        or_ln675_1_reg_2238 <= or_ln675_1_fu_1327_p2;
        or_ln675_1_reg_2238_pp0_iter4_reg <= or_ln675_1_reg_2238;
        p_Val2_s_reg_2232 <= p_Val2_s_fu_1320_p3;
        p_Val2_s_reg_2232_pp0_iter4_reg <= p_Val2_s_reg_2232;
        p_phi_reg_946_pp0_iter2_reg <= p_phi_reg_946;
        p_phi_reg_946_pp0_iter3_reg <= p_phi_reg_946_pp0_iter2_reg;
        p_phi_reg_946_pp0_iter4_reg <= p_phi_reg_946_pp0_iter3_reg;
        trunc_ln42_reg_2202_pp0_iter2_reg <= trunc_ln42_reg_2202;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (noStubsLeft_reg_2175_pp0_iter2_reg == 1'd0) & (or_ln675_1_fu_1327_p2 == 1'd1))) begin
        bend_V_reg_2242 <= bend_V_fu_1341_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln672_reg_2171_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        bx_V7_rewind_reg_786 <= bx_V7_phi_reg_958;
        nInputs_0_V_rewind_reg_758 <= nInputs_0_V_phi_reg_934;
        nInputs_1_V_02_rewind_reg_828 <= nInputs_2_V_8_reg_2212;
        nInputs_1_V_rewind_reg_744 <= nInputs_1_V_phi_reg_922;
        nInputs_2_V3_rewind_reg_842 <= nInputs_2_V_10_reg_2217;
        nInputs_2_V_01_rewind_reg_814 <= nInputs_2_V_7_reg_2207;
        nInputs_2_V_1_rewind_reg_730 <= nInputs_2_V_1_phi_reg_910;
        p_rewind_reg_772 <= p_phi_reg_946;
        p_what2_4_rewind_reg_800 <= p_what2_s_reg_2222;
    end
end

always @ (posedge ap_clk) begin
    if (((~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (bx_o_V_1_vld_reg == 1'b0) & (bx_o_V_1_vld_in == 1'b1)) | (~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (1'b1 == 1'b1) & (bx_o_V_1_vld_in == 1'b1) & (bx_o_V_1_vld_reg == 1'b1)))) begin
        bx_o_V_1_data_reg <= bx_V7_phi_reg_958_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_reg_2166 <= i_fu_1107_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        nInputs_2_V_10_reg_2217 <= nInputs_2_V_10_fu_1260_p3;
        nInputs_2_V_7_reg_2207 <= nInputs_2_V_7_fu_1236_p3;
        nInputs_2_V_8_reg_2212 <= nInputs_2_V_8_fu_1252_p3;
        p_what2_s_reg_2222 <= p_what2_s_fu_1268_p3;
        read_addr_V_1_reg_2227 <= read_addr_V_1_fu_1294_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (noStubsLeft_reg_2175_pp0_iter3_reg == 1'd0) & (or_ln675_1_reg_2238 == 1'd1))) begin
        tmp_13_reg_2258 <= phiCorr_V_2_fu_1448_p3[32'd14];
        trunc_ln214_reg_2263 <= trunc_ln214_fu_1464_p1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln672_reg_2171_pp0_iter4_reg == 1'd1) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to4 = 1'b1;
    end else begin
        ap_idle_pp0_0to4 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_401)) begin
        if ((icmp_ln672_reg_2171 == 1'd1)) begin
            ap_phi_mux_addr_index_assign6_phi_fu_719_p6 = 7'd0;
        end else if ((icmp_ln672_reg_2171 == 1'd0)) begin
            ap_phi_mux_addr_index_assign6_phi_fu_719_p6 = i_reg_2166;
        end else begin
            ap_phi_mux_addr_index_assign6_phi_fu_719_p6 = addr_index_assign6_reg_715;
        end
    end else begin
        ap_phi_mux_addr_index_assign6_phi_fu_719_p6 = addr_index_assign6_reg_715;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln672_reg_2171_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_phi_mux_bx_V7_rewind_phi_fu_790_p6 = bx_V7_phi_reg_958;
    end else begin
        ap_phi_mux_bx_V7_rewind_phi_fu_790_p6 = bx_V7_rewind_reg_786;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_401)) begin
        if ((icmp_ln672_reg_2171 == 1'd1)) begin
            ap_phi_mux_do_init_phi_fu_703_p6 = 1'd1;
        end else if ((icmp_ln672_reg_2171 == 1'd0)) begin
            ap_phi_mux_do_init_phi_fu_703_p6 = 1'd0;
        end else begin
            ap_phi_mux_do_init_phi_fu_703_p6 = do_init_reg_699;
        end
    end else begin
        ap_phi_mux_do_init_phi_fu_703_p6 = do_init_reg_699;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln672_reg_2171_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_phi_mux_nInputs_0_V_rewind_phi_fu_762_p6 = nInputs_0_V_phi_reg_934;
    end else begin
        ap_phi_mux_nInputs_0_V_rewind_phi_fu_762_p6 = nInputs_0_V_rewind_reg_758;
    end
end

always @ (*) begin
    if ((do_init_reg_699 == 1'd0)) begin
        ap_phi_mux_nInputs_1_V_02_phi_fu_893_p4 = ap_phi_mux_nInputs_1_V_02_rewind_phi_fu_832_p6;
    end else begin
        ap_phi_mux_nInputs_1_V_02_phi_fu_893_p4 = ap_phi_reg_pp0_iter1_nInputs_1_V_02_reg_890;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln672_reg_2171_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_phi_mux_nInputs_1_V_02_rewind_phi_fu_832_p6 = nInputs_2_V_8_reg_2212;
    end else begin
        ap_phi_mux_nInputs_1_V_02_rewind_phi_fu_832_p6 = nInputs_1_V_02_rewind_reg_828;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln672_reg_2171_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_phi_mux_nInputs_1_V_rewind_phi_fu_748_p6 = nInputs_1_V_phi_reg_922;
    end else begin
        ap_phi_mux_nInputs_1_V_rewind_phi_fu_748_p6 = nInputs_1_V_rewind_reg_744;
    end
end

always @ (*) begin
    if ((do_init_reg_699 == 1'd0)) begin
        ap_phi_mux_nInputs_2_V3_phi_fu_883_p4 = ap_phi_mux_nInputs_2_V3_rewind_phi_fu_846_p6;
    end else begin
        ap_phi_mux_nInputs_2_V3_phi_fu_883_p4 = ap_phi_reg_pp0_iter1_nInputs_2_V3_reg_880;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln672_reg_2171_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_phi_mux_nInputs_2_V3_rewind_phi_fu_846_p6 = nInputs_2_V_10_reg_2217;
    end else begin
        ap_phi_mux_nInputs_2_V3_rewind_phi_fu_846_p6 = nInputs_2_V3_rewind_reg_842;
    end
end

always @ (*) begin
    if ((do_init_reg_699 == 1'd0)) begin
        ap_phi_mux_nInputs_2_V_01_phi_fu_903_p4 = ap_phi_mux_nInputs_2_V_01_rewind_phi_fu_818_p6;
    end else begin
        ap_phi_mux_nInputs_2_V_01_phi_fu_903_p4 = ap_phi_reg_pp0_iter1_nInputs_2_V_01_reg_900;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln672_reg_2171_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_phi_mux_nInputs_2_V_01_rewind_phi_fu_818_p6 = nInputs_2_V_7_reg_2207;
    end else begin
        ap_phi_mux_nInputs_2_V_01_rewind_phi_fu_818_p6 = nInputs_2_V_01_rewind_reg_814;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln672_reg_2171_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_phi_mux_nInputs_2_V_1_rewind_phi_fu_734_p6 = nInputs_2_V_1_phi_reg_910;
    end else begin
        ap_phi_mux_nInputs_2_V_1_rewind_phi_fu_734_p6 = nInputs_2_V_1_rewind_reg_730;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((icmp_ln672_reg_2171_pp0_iter1_reg == 1'd1)) begin
            ap_phi_mux_p_05_phi_fu_860_p6 = 7'd0;
        end else if ((icmp_ln672_reg_2171_pp0_iter1_reg == 1'd0)) begin
            ap_phi_mux_p_05_phi_fu_860_p6 = read_addr_V_1_reg_2227;
        end else begin
            ap_phi_mux_p_05_phi_fu_860_p6 = p_05_reg_856;
        end
    end else begin
        ap_phi_mux_p_05_phi_fu_860_p6 = p_05_reg_856;
    end
end

always @ (*) begin
    if ((do_init_reg_699 == 1'd0)) begin
        ap_phi_mux_p_phi_phi_fu_950_p4 = ap_phi_mux_p_rewind_phi_fu_776_p6;
    end else begin
        ap_phi_mux_p_phi_phi_fu_950_p4 = ap_phi_reg_pp0_iter1_p_phi_reg_946;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln672_reg_2171_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_phi_mux_p_rewind_phi_fu_776_p6 = p_phi_reg_946;
    end else begin
        ap_phi_mux_p_rewind_phi_fu_776_p6 = p_rewind_reg_772;
    end
end

always @ (*) begin
    if ((do_init_reg_699 == 1'd0)) begin
        ap_phi_mux_p_what2_4_phi_fu_873_p4 = ap_phi_mux_p_what2_4_rewind_phi_fu_804_p6;
    end else begin
        ap_phi_mux_p_what2_4_phi_fu_873_p4 = ap_phi_reg_pp0_iter1_p_what2_4_reg_870;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln672_reg_2171_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_phi_mux_p_what2_4_rewind_phi_fu_804_p6 = p_what2_s_reg_2222;
    end else begin
        ap_phi_mux_p_what2_4_rewind_phi_fu_804_p6 = p_what2_4_rewind_reg_800;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln672_fu_1113_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to4 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((bx_o_V_1_vld_reg == 1'b0) | ((1'b1 == 1'b1) & (bx_o_V_1_vld_reg == 1'b1)))) begin
        bx_o_V_1_ack_in = 1'b1;
    end else begin
        bx_o_V_1_ack_in = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln672_reg_2171_pp0_iter3_reg == 1'd1) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        bx_o_V_1_vld_in = 1'b1;
    end else begin
        bx_o_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        inputStubs_0_dataarray_data_V_ce0 = 1'b1;
    end else begin
        inputStubs_0_dataarray_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        inputStubs_1_dataarray_data_V_ce0 = 1'b1;
    end else begin
        inputStubs_1_dataarray_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        inputStubs_2_dataarray_data_V_ce0 = 1'b1;
    end else begin
        inputStubs_2_dataarray_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        lut_1_ce0 = 1'b1;
    end else begin
        lut_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1)))) begin
        lut_ce0 = 1'b1;
    end else begin
        lut_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        memoriesAS_0_dataarray_data_V_ce0 = 1'b1;
    end else begin
        memoriesAS_0_dataarray_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (noStubsLeft_reg_2175_pp0_iter4_reg == 1'd0) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        memoriesAS_0_dataarray_data_V_we0 = 1'b1;
    end else begin
        memoriesAS_0_dataarray_data_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        memoriesTEI_0_0_dataarray_data_V_ce0 = 1'b1;
    end else begin
        memoriesTEI_0_0_dataarray_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln_fu_1570_p4 == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln792_fu_1623_p2 == 1'd0) & (p_Result_s_fu_1564_p2 == 1'd0) & (icmp_ln807_fu_1542_p2 == 1'd0) & (noStubsLeft_reg_2175_pp0_iter4_reg == 1'd0) & (or_ln675_1_reg_2238_pp0_iter4_reg == 1'd1) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        memoriesTEI_0_0_dataarray_data_V_we0 = 1'b1;
    end else begin
        memoriesTEI_0_0_dataarray_data_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        memoriesTEI_0_1_dataarray_data_V_ce0 = 1'b1;
    end else begin
        memoriesTEI_0_1_dataarray_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln_fu_1570_p4 == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln792_1_fu_1733_p2 == 1'd0) & (p_Result_s_fu_1564_p2 == 1'd0) & (icmp_ln807_fu_1542_p2 == 1'd0) & (noStubsLeft_reg_2175_pp0_iter4_reg == 1'd0) & (or_ln675_1_reg_2238_pp0_iter4_reg == 1'd1) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        memoriesTEI_0_1_dataarray_data_V_we0 = 1'b1;
    end else begin
        memoriesTEI_0_1_dataarray_data_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        memoriesTEI_0_2_dataarray_data_V_ce0 = 1'b1;
    end else begin
        memoriesTEI_0_2_dataarray_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln_fu_1570_p4 == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln792_2_fu_1833_p2 == 1'd0) & (p_Result_s_fu_1564_p2 == 1'd0) & (icmp_ln807_fu_1542_p2 == 1'd0) & (noStubsLeft_reg_2175_pp0_iter4_reg == 1'd0) & (or_ln675_1_reg_2238_pp0_iter4_reg == 1'd1) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        memoriesTEI_0_2_dataarray_data_V_we0 = 1'b1;
    end else begin
        memoriesTEI_0_2_dataarray_data_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        memoriesTEI_0_3_dataarray_data_V_ce0 = 1'b1;
    end else begin
        memoriesTEI_0_3_dataarray_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln_fu_1570_p4 == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln792_4_fu_1939_p2 == 1'd0) & (p_Result_s_fu_1564_p2 == 1'd0) & (icmp_ln807_fu_1542_p2 == 1'd0) & (noStubsLeft_reg_2175_pp0_iter4_reg == 1'd0) & (or_ln675_1_reg_2238_pp0_iter4_reg == 1'd1) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        memoriesTEI_0_3_dataarray_data_V_we0 = 1'b1;
    end else begin
        memoriesTEI_0_3_dataarray_data_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        memoriesTEI_1_0_dataarray_data_V_ce0 = 1'b1;
    end else begin
        memoriesTEI_1_0_dataarray_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln_fu_1570_p4 == 2'd2) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln792_fu_1623_p2 == 1'd0) & (p_Result_s_fu_1564_p2 == 1'd0) & (icmp_ln807_fu_1542_p2 == 1'd0) & (noStubsLeft_reg_2175_pp0_iter4_reg == 1'd0) & (or_ln675_1_reg_2238_pp0_iter4_reg == 1'd1) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        memoriesTEI_1_0_dataarray_data_V_we0 = 1'b1;
    end else begin
        memoriesTEI_1_0_dataarray_data_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        memoriesTEI_1_1_dataarray_data_V_ce0 = 1'b1;
    end else begin
        memoriesTEI_1_1_dataarray_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln_fu_1570_p4 == 2'd2) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln792_1_fu_1733_p2 == 1'd0) & (p_Result_s_fu_1564_p2 == 1'd0) & (icmp_ln807_fu_1542_p2 == 1'd0) & (noStubsLeft_reg_2175_pp0_iter4_reg == 1'd0) & (or_ln675_1_reg_2238_pp0_iter4_reg == 1'd1) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        memoriesTEI_1_1_dataarray_data_V_we0 = 1'b1;
    end else begin
        memoriesTEI_1_1_dataarray_data_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        memoriesTEI_1_2_dataarray_data_V_ce0 = 1'b1;
    end else begin
        memoriesTEI_1_2_dataarray_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln_fu_1570_p4 == 2'd2) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln792_2_fu_1833_p2 == 1'd0) & (p_Result_s_fu_1564_p2 == 1'd0) & (icmp_ln807_fu_1542_p2 == 1'd0) & (noStubsLeft_reg_2175_pp0_iter4_reg == 1'd0) & (or_ln675_1_reg_2238_pp0_iter4_reg == 1'd1) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        memoriesTEI_1_2_dataarray_data_V_we0 = 1'b1;
    end else begin
        memoriesTEI_1_2_dataarray_data_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        memoriesTEI_1_3_dataarray_data_V_ce0 = 1'b1;
    end else begin
        memoriesTEI_1_3_dataarray_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln_fu_1570_p4 == 2'd2) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln792_4_fu_1939_p2 == 1'd0) & (p_Result_s_fu_1564_p2 == 1'd0) & (icmp_ln807_fu_1542_p2 == 1'd0) & (noStubsLeft_reg_2175_pp0_iter4_reg == 1'd0) & (or_ln675_1_reg_2238_pp0_iter4_reg == 1'd1) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        memoriesTEI_1_3_dataarray_data_V_we0 = 1'b1;
    end else begin
        memoriesTEI_1_3_dataarray_data_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        memoriesTEI_2_0_dataarray_data_V_ce0 = 1'b1;
    end else begin
        memoriesTEI_2_0_dataarray_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln_fu_1570_p4 == 2'd3) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln792_fu_1623_p2 == 1'd0) & (p_Result_s_fu_1564_p2 == 1'd0) & (icmp_ln807_fu_1542_p2 == 1'd0) & (noStubsLeft_reg_2175_pp0_iter4_reg == 1'd0) & (or_ln675_1_reg_2238_pp0_iter4_reg == 1'd1) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        memoriesTEI_2_0_dataarray_data_V_we0 = 1'b1;
    end else begin
        memoriesTEI_2_0_dataarray_data_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        memoriesTEI_2_1_dataarray_data_V_ce0 = 1'b1;
    end else begin
        memoriesTEI_2_1_dataarray_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln_fu_1570_p4 == 2'd3) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln792_1_fu_1733_p2 == 1'd0) & (p_Result_s_fu_1564_p2 == 1'd0) & (icmp_ln807_fu_1542_p2 == 1'd0) & (noStubsLeft_reg_2175_pp0_iter4_reg == 1'd0) & (or_ln675_1_reg_2238_pp0_iter4_reg == 1'd1) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        memoriesTEI_2_1_dataarray_data_V_we0 = 1'b1;
    end else begin
        memoriesTEI_2_1_dataarray_data_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        memoriesTEI_2_2_dataarray_data_V_ce0 = 1'b1;
    end else begin
        memoriesTEI_2_2_dataarray_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln_fu_1570_p4 == 2'd3) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln792_2_fu_1833_p2 == 1'd0) & (p_Result_s_fu_1564_p2 == 1'd0) & (icmp_ln807_fu_1542_p2 == 1'd0) & (noStubsLeft_reg_2175_pp0_iter4_reg == 1'd0) & (or_ln675_1_reg_2238_pp0_iter4_reg == 1'd1) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        memoriesTEI_2_2_dataarray_data_V_we0 = 1'b1;
    end else begin
        memoriesTEI_2_2_dataarray_data_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        memoriesTEI_2_3_dataarray_data_V_ce0 = 1'b1;
    end else begin
        memoriesTEI_2_3_dataarray_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln_fu_1570_p4 == 2'd3) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln792_4_fu_1939_p2 == 1'd0) & (p_Result_s_fu_1564_p2 == 1'd0) & (icmp_ln807_fu_1542_p2 == 1'd0) & (noStubsLeft_reg_2175_pp0_iter4_reg == 1'd0) & (or_ln675_1_reg_2238_pp0_iter4_reg == 1'd1) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        memoriesTEI_2_3_dataarray_data_V_we0 = 1'b1;
    end else begin
        memoriesTEI_2_3_dataarray_data_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        memoriesTEI_3_0_dataarray_data_V_ce0 = 1'b1;
    end else begin
        memoriesTEI_3_0_dataarray_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln_fu_1570_p4 == 2'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln792_fu_1623_p2 == 1'd0) & (p_Result_s_fu_1564_p2 == 1'd0) & (icmp_ln807_fu_1542_p2 == 1'd0) & (noStubsLeft_reg_2175_pp0_iter4_reg == 1'd0) & (or_ln675_1_reg_2238_pp0_iter4_reg == 1'd1) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        memoriesTEI_3_0_dataarray_data_V_we0 = 1'b1;
    end else begin
        memoriesTEI_3_0_dataarray_data_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        memoriesTEI_3_1_dataarray_data_V_ce0 = 1'b1;
    end else begin
        memoriesTEI_3_1_dataarray_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln_fu_1570_p4 == 2'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln792_1_fu_1733_p2 == 1'd0) & (p_Result_s_fu_1564_p2 == 1'd0) & (icmp_ln807_fu_1542_p2 == 1'd0) & (noStubsLeft_reg_2175_pp0_iter4_reg == 1'd0) & (or_ln675_1_reg_2238_pp0_iter4_reg == 1'd1) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        memoriesTEI_3_1_dataarray_data_V_we0 = 1'b1;
    end else begin
        memoriesTEI_3_1_dataarray_data_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        memoriesTEI_3_2_dataarray_data_V_ce0 = 1'b1;
    end else begin
        memoriesTEI_3_2_dataarray_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln_fu_1570_p4 == 2'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln792_2_fu_1833_p2 == 1'd0) & (p_Result_s_fu_1564_p2 == 1'd0) & (icmp_ln807_fu_1542_p2 == 1'd0) & (noStubsLeft_reg_2175_pp0_iter4_reg == 1'd0) & (or_ln675_1_reg_2238_pp0_iter4_reg == 1'd1) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        memoriesTEI_3_2_dataarray_data_V_we0 = 1'b1;
    end else begin
        memoriesTEI_3_2_dataarray_data_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        memoriesTEI_3_3_dataarray_data_V_ce0 = 1'b1;
    end else begin
        memoriesTEI_3_3_dataarray_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln_fu_1570_p4 == 2'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln792_4_fu_1939_p2 == 1'd0) & (p_Result_s_fu_1564_p2 == 1'd0) & (icmp_ln807_fu_1542_p2 == 1'd0) & (noStubsLeft_reg_2175_pp0_iter4_reg == 1'd0) & (or_ln675_1_reg_2238_pp0_iter4_reg == 1'd1) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        memoriesTEI_3_3_dataarray_data_V_we0 = 1'b1;
    end else begin
        memoriesTEI_3_3_dataarray_data_V_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((ap_reset_idle_pp0 == 1'b0)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_reset_idle_pp0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln792_fu_1588_p2 = ($signed(shl_ln_fu_1580_p3) + $signed(4'd12));

assign addrCountTEI_0_0_V_2_fu_1677_p2 = (tmp_1_fu_1647_p6 + 7'd1);

assign addrCountTEI_0_1_V_2_fu_1787_p2 = (tmp_4_fu_1757_p6 + 7'd1);

assign addrCountTEI_0_2_V_2_fu_1887_p2 = (tmp_5_fu_1857_p6 + 7'd1);

assign addrCountTEI_0_3_V_2_fu_1993_p2 = (tmp_7_fu_1963_p6 + 7'd1);

assign and_ln675_fu_1282_p2 = (xor_ln675_fu_1276_p2 & resetNext_fu_1174_p2);

assign and_ln792_1_fu_1727_p2 = (shl_ln792_1_fu_1611_p2 & phi_ln792_1_fu_1713_p6);

assign and_ln792_2_fu_1827_p2 = (shl_ln792_1_fu_1611_p2 & phi_ln792_2_fu_1813_p6);

assign and_ln792_3_fu_1933_p2 = (shl_ln792_1_fu_1611_p2 & select_ln792_1_fu_1925_p3);

assign and_ln792_fu_1617_p2 = (shl_ln792_1_fu_1611_p2 & select_ln792_fu_1600_p3);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((bx_o_V_1_ack_in == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((bx_o_V_1_ack_in == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((bx_o_V_1_ack_in == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b1));
end

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state7_pp0_stage0_iter5 = (bx_o_V_1_ack_in == 1'b0);
end

always @ (*) begin
    ap_condition_1174 = ((ap_phi_mux_do_init_phi_fu_703_p6 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_1182 = ((trunc_ln_fu_1570_p4 == 2'd1) & (icmp_ln792_fu_1623_p2 == 1'd0) & (p_Result_s_fu_1564_p2 == 1'd0) & (icmp_ln807_fu_1542_p2 == 1'd0) & (noStubsLeft_reg_2175_pp0_iter4_reg == 1'd0) & (or_ln675_1_reg_2238_pp0_iter4_reg == 1'd1) & (ap_enable_reg_pp0_iter5 == 1'b1));
end

always @ (*) begin
    ap_condition_1186 = ((trunc_ln_fu_1570_p4 == 2'd1) & (icmp_ln792_1_fu_1733_p2 == 1'd0) & (p_Result_s_fu_1564_p2 == 1'd0) & (icmp_ln807_fu_1542_p2 == 1'd0) & (noStubsLeft_reg_2175_pp0_iter4_reg == 1'd0) & (or_ln675_1_reg_2238_pp0_iter4_reg == 1'd1) & (ap_enable_reg_pp0_iter5 == 1'b1));
end

always @ (*) begin
    ap_condition_1190 = ((trunc_ln_fu_1570_p4 == 2'd1) & (icmp_ln792_2_fu_1833_p2 == 1'd0) & (p_Result_s_fu_1564_p2 == 1'd0) & (icmp_ln807_fu_1542_p2 == 1'd0) & (noStubsLeft_reg_2175_pp0_iter4_reg == 1'd0) & (or_ln675_1_reg_2238_pp0_iter4_reg == 1'd1) & (ap_enable_reg_pp0_iter5 == 1'b1));
end

always @ (*) begin
    ap_condition_1194 = ((trunc_ln_fu_1570_p4 == 2'd1) & (icmp_ln792_4_fu_1939_p2 == 1'd0) & (p_Result_s_fu_1564_p2 == 1'd0) & (icmp_ln807_fu_1542_p2 == 1'd0) & (noStubsLeft_reg_2175_pp0_iter4_reg == 1'd0) & (or_ln675_1_reg_2238_pp0_iter4_reg == 1'd1) & (ap_enable_reg_pp0_iter5 == 1'b1));
end

always @ (*) begin
    ap_condition_1197 = ((trunc_ln_fu_1570_p4 == 2'd2) & (icmp_ln792_fu_1623_p2 == 1'd0) & (p_Result_s_fu_1564_p2 == 1'd0) & (icmp_ln807_fu_1542_p2 == 1'd0) & (noStubsLeft_reg_2175_pp0_iter4_reg == 1'd0) & (or_ln675_1_reg_2238_pp0_iter4_reg == 1'd1) & (ap_enable_reg_pp0_iter5 == 1'b1));
end

always @ (*) begin
    ap_condition_1200 = ((trunc_ln_fu_1570_p4 == 2'd2) & (icmp_ln792_1_fu_1733_p2 == 1'd0) & (p_Result_s_fu_1564_p2 == 1'd0) & (icmp_ln807_fu_1542_p2 == 1'd0) & (noStubsLeft_reg_2175_pp0_iter4_reg == 1'd0) & (or_ln675_1_reg_2238_pp0_iter4_reg == 1'd1) & (ap_enable_reg_pp0_iter5 == 1'b1));
end

always @ (*) begin
    ap_condition_1203 = ((trunc_ln_fu_1570_p4 == 2'd2) & (icmp_ln792_2_fu_1833_p2 == 1'd0) & (p_Result_s_fu_1564_p2 == 1'd0) & (icmp_ln807_fu_1542_p2 == 1'd0) & (noStubsLeft_reg_2175_pp0_iter4_reg == 1'd0) & (or_ln675_1_reg_2238_pp0_iter4_reg == 1'd1) & (ap_enable_reg_pp0_iter5 == 1'b1));
end

always @ (*) begin
    ap_condition_1206 = ((trunc_ln_fu_1570_p4 == 2'd2) & (icmp_ln792_4_fu_1939_p2 == 1'd0) & (p_Result_s_fu_1564_p2 == 1'd0) & (icmp_ln807_fu_1542_p2 == 1'd0) & (noStubsLeft_reg_2175_pp0_iter4_reg == 1'd0) & (or_ln675_1_reg_2238_pp0_iter4_reg == 1'd1) & (ap_enable_reg_pp0_iter5 == 1'b1));
end

always @ (*) begin
    ap_condition_1209 = ((trunc_ln_fu_1570_p4 == 2'd3) & (icmp_ln792_fu_1623_p2 == 1'd0) & (p_Result_s_fu_1564_p2 == 1'd0) & (icmp_ln807_fu_1542_p2 == 1'd0) & (noStubsLeft_reg_2175_pp0_iter4_reg == 1'd0) & (or_ln675_1_reg_2238_pp0_iter4_reg == 1'd1) & (ap_enable_reg_pp0_iter5 == 1'b1));
end

always @ (*) begin
    ap_condition_1212 = ((trunc_ln_fu_1570_p4 == 2'd3) & (icmp_ln792_1_fu_1733_p2 == 1'd0) & (p_Result_s_fu_1564_p2 == 1'd0) & (icmp_ln807_fu_1542_p2 == 1'd0) & (noStubsLeft_reg_2175_pp0_iter4_reg == 1'd0) & (or_ln675_1_reg_2238_pp0_iter4_reg == 1'd1) & (ap_enable_reg_pp0_iter5 == 1'b1));
end

always @ (*) begin
    ap_condition_1215 = ((trunc_ln_fu_1570_p4 == 2'd3) & (icmp_ln792_2_fu_1833_p2 == 1'd0) & (p_Result_s_fu_1564_p2 == 1'd0) & (icmp_ln807_fu_1542_p2 == 1'd0) & (noStubsLeft_reg_2175_pp0_iter4_reg == 1'd0) & (or_ln675_1_reg_2238_pp0_iter4_reg == 1'd1) & (ap_enable_reg_pp0_iter5 == 1'b1));
end

always @ (*) begin
    ap_condition_1218 = ((trunc_ln_fu_1570_p4 == 2'd3) & (icmp_ln792_4_fu_1939_p2 == 1'd0) & (p_Result_s_fu_1564_p2 == 1'd0) & (icmp_ln807_fu_1542_p2 == 1'd0) & (noStubsLeft_reg_2175_pp0_iter4_reg == 1'd0) & (or_ln675_1_reg_2238_pp0_iter4_reg == 1'd1) & (ap_enable_reg_pp0_iter5 == 1'b1));
end

always @ (*) begin
    ap_condition_1221 = ((trunc_ln_fu_1570_p4 == 2'd0) & (icmp_ln792_fu_1623_p2 == 1'd0) & (p_Result_s_fu_1564_p2 == 1'd0) & (icmp_ln807_fu_1542_p2 == 1'd0) & (noStubsLeft_reg_2175_pp0_iter4_reg == 1'd0) & (or_ln675_1_reg_2238_pp0_iter4_reg == 1'd1) & (ap_enable_reg_pp0_iter5 == 1'b1));
end

always @ (*) begin
    ap_condition_1224 = ((trunc_ln_fu_1570_p4 == 2'd0) & (icmp_ln792_1_fu_1733_p2 == 1'd0) & (p_Result_s_fu_1564_p2 == 1'd0) & (icmp_ln807_fu_1542_p2 == 1'd0) & (noStubsLeft_reg_2175_pp0_iter4_reg == 1'd0) & (or_ln675_1_reg_2238_pp0_iter4_reg == 1'd1) & (ap_enable_reg_pp0_iter5 == 1'b1));
end

always @ (*) begin
    ap_condition_1227 = ((trunc_ln_fu_1570_p4 == 2'd0) & (icmp_ln792_2_fu_1833_p2 == 1'd0) & (p_Result_s_fu_1564_p2 == 1'd0) & (icmp_ln807_fu_1542_p2 == 1'd0) & (noStubsLeft_reg_2175_pp0_iter4_reg == 1'd0) & (or_ln675_1_reg_2238_pp0_iter4_reg == 1'd1) & (ap_enable_reg_pp0_iter5 == 1'b1));
end

always @ (*) begin
    ap_condition_1230 = ((trunc_ln_fu_1570_p4 == 2'd0) & (icmp_ln792_4_fu_1939_p2 == 1'd0) & (p_Result_s_fu_1564_p2 == 1'd0) & (icmp_ln807_fu_1542_p2 == 1'd0) & (noStubsLeft_reg_2175_pp0_iter4_reg == 1'd0) & (or_ln675_1_reg_2238_pp0_iter4_reg == 1'd1) & (ap_enable_reg_pp0_iter5 == 1'b1));
end

always @ (*) begin
    ap_condition_347 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_401 = ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_49 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_phi_reg_pp0_iter0_bx_V7_phi_reg_958 = 'bx;

assign ap_phi_reg_pp0_iter0_nInputs_0_V_phi_reg_934 = 'bx;

assign ap_phi_reg_pp0_iter0_nInputs_1_V_02_reg_890 = 'bx;

assign ap_phi_reg_pp0_iter0_nInputs_1_V_phi_reg_922 = 'bx;

assign ap_phi_reg_pp0_iter0_nInputs_2_V3_reg_880 = 'bx;

assign ap_phi_reg_pp0_iter0_nInputs_2_V_01_reg_900 = 'bx;

assign ap_phi_reg_pp0_iter0_nInputs_2_V_1_phi_reg_910 = 'bx;

assign ap_phi_reg_pp0_iter0_p_phi_reg_946 = 'bx;

assign ap_phi_reg_pp0_iter0_p_what2_4_reg_870 = 'bx;

assign bend_V_fu_1341_p1 = p_Val2_s_fu_1320_p3[2:0];

assign bx_o_V = bx_o_V_1_data_reg;

assign bx_o_V_ap_vld = bx_o_V_1_vld_reg;

assign i_fu_1107_p2 = (7'd1 + ap_phi_mux_addr_index_assign6_phi_fu_719_p6);

assign icmp_ln672_fu_1113_p2 = ((ap_phi_mux_addr_index_assign6_phi_fu_719_p6 == 7'd107) ? 1'b1 : 1'b0);

assign icmp_ln687_fu_1137_p2 = ((mem_index_fu_1129_p3 < 32'd3) ? 1'b1 : 1'b0);

assign icmp_ln701_1_fu_1208_p2 = ((trunc_ln42_fu_1158_p1 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln701_fu_1202_p2 = ((trunc_ln42_fu_1158_p1 == 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln792_1_fu_1733_p2 = ((and_ln792_1_fu_1727_p2 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln792_2_fu_1833_p2 = ((and_ln792_2_fu_1827_p2 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln792_3_fu_1919_p2 = ((or_ln792_fu_1913_p2 == 4'd7) ? 1'b1 : 1'b0);

assign icmp_ln792_4_fu_1939_p2 = ((and_ln792_3_fu_1933_p2 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln792_6_fu_1594_p2 = ((trunc_ln_fu_1570_p4 == 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln792_fu_1623_p2 = ((and_ln792_fu_1617_p2 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln807_fu_1542_p2 = ((lut_q0 == 11'd2047) ? 1'b1 : 1'b0);

assign icmp_ln841_1_fu_997_p2 = ((nInputs_1_V_fu_989_p3 != 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln841_2_fu_1011_p2 = ((nInputs_2_V_fu_1003_p3 != 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln841_fu_983_p2 = ((nInputs_0_V_fu_975_p3 != 7'd0) ? 1'b1 : 1'b0);

assign indexr_V_fu_1390_p4 = {{ret_V_fu_1345_p2[6:3]}};

assign indexz_V_fu_1384_p2 = (tmp_12_fu_1374_p4 ^ 7'd64);

assign inputStubs_0_dataarray_data_V_address0 = zext_ln42_fu_1151_p1;

assign inputStubs_1_dataarray_data_V_address0 = zext_ln42_fu_1151_p1;

assign inputStubs_2_dataarray_data_V_address0 = zext_ln42_fu_1151_p1;

assign iphivm_V_fu_1497_p4 = {{phiCorr_V_fu_1481_p3[13:9]}};

assign lut_1_address0 = zext_ln544_fu_1369_p1;

assign lut_address0 = zext_ln400_fu_1408_p1;


always @ (zext_ln684_fu_1125_p1) begin
    if (zext_ln684_fu_1125_p1[0] == 1'b1) begin
        mem_index_fu_1129_p3 = 32'd0;
    end else if (zext_ln684_fu_1125_p1[1] == 1'b1) begin
        mem_index_fu_1129_p3 = 32'd1;
    end else if (zext_ln684_fu_1125_p1[2] == 1'b1) begin
        mem_index_fu_1129_p3 = 32'd2;
    end else if (zext_ln684_fu_1125_p1[3] == 1'b1) begin
        mem_index_fu_1129_p3 = 32'd3;
    end else if (zext_ln684_fu_1125_p1[4] == 1'b1) begin
        mem_index_fu_1129_p3 = 32'd4;
    end else if (zext_ln684_fu_1125_p1[5] == 1'b1) begin
        mem_index_fu_1129_p3 = 32'd5;
    end else if (zext_ln684_fu_1125_p1[6] == 1'b1) begin
        mem_index_fu_1129_p3 = 32'd6;
    end else if (zext_ln684_fu_1125_p1[7] == 1'b1) begin
        mem_index_fu_1129_p3 = 32'd7;
    end else if (zext_ln684_fu_1125_p1[8] == 1'b1) begin
        mem_index_fu_1129_p3 = 32'd8;
    end else if (zext_ln684_fu_1125_p1[9] == 1'b1) begin
        mem_index_fu_1129_p3 = 32'd9;
    end else if (zext_ln684_fu_1125_p1[10] == 1'b1) begin
        mem_index_fu_1129_p3 = 32'd10;
    end else if (zext_ln684_fu_1125_p1[11] == 1'b1) begin
        mem_index_fu_1129_p3 = 32'd11;
    end else if (zext_ln684_fu_1125_p1[12] == 1'b1) begin
        mem_index_fu_1129_p3 = 32'd12;
    end else if (zext_ln684_fu_1125_p1[13] == 1'b1) begin
        mem_index_fu_1129_p3 = 32'd13;
    end else if (zext_ln684_fu_1125_p1[14] == 1'b1) begin
        mem_index_fu_1129_p3 = 32'd14;
    end else if (zext_ln684_fu_1125_p1[15] == 1'b1) begin
        mem_index_fu_1129_p3 = 32'd15;
    end else if (zext_ln684_fu_1125_p1[16] == 1'b1) begin
        mem_index_fu_1129_p3 = 32'd16;
    end else if (zext_ln684_fu_1125_p1[17] == 1'b1) begin
        mem_index_fu_1129_p3 = 32'd17;
    end else if (zext_ln684_fu_1125_p1[18] == 1'b1) begin
        mem_index_fu_1129_p3 = 32'd18;
    end else if (zext_ln684_fu_1125_p1[19] == 1'b1) begin
        mem_index_fu_1129_p3 = 32'd19;
    end else if (zext_ln684_fu_1125_p1[20] == 1'b1) begin
        mem_index_fu_1129_p3 = 32'd20;
    end else if (zext_ln684_fu_1125_p1[21] == 1'b1) begin
        mem_index_fu_1129_p3 = 32'd21;
    end else if (zext_ln684_fu_1125_p1[22] == 1'b1) begin
        mem_index_fu_1129_p3 = 32'd22;
    end else if (zext_ln684_fu_1125_p1[23] == 1'b1) begin
        mem_index_fu_1129_p3 = 32'd23;
    end else if (zext_ln684_fu_1125_p1[24] == 1'b1) begin
        mem_index_fu_1129_p3 = 32'd24;
    end else if (zext_ln684_fu_1125_p1[25] == 1'b1) begin
        mem_index_fu_1129_p3 = 32'd25;
    end else if (zext_ln684_fu_1125_p1[26] == 1'b1) begin
        mem_index_fu_1129_p3 = 32'd26;
    end else if (zext_ln684_fu_1125_p1[27] == 1'b1) begin
        mem_index_fu_1129_p3 = 32'd27;
    end else if (zext_ln684_fu_1125_p1[28] == 1'b1) begin
        mem_index_fu_1129_p3 = 32'd28;
    end else if (zext_ln684_fu_1125_p1[29] == 1'b1) begin
        mem_index_fu_1129_p3 = 32'd29;
    end else if (zext_ln684_fu_1125_p1[30] == 1'b1) begin
        mem_index_fu_1129_p3 = 32'd30;
    end else if (zext_ln684_fu_1125_p1[31] == 1'b1) begin
        mem_index_fu_1129_p3 = 32'd31;
    end else begin
        mem_index_fu_1129_p3 = 32'd32;
    end
end

assign memoriesAS_0_dataarray_data_V_address0 = zext_ln321_fu_1476_p1;

assign memoriesAS_0_dataarray_data_V_d0 = p_Val2_s_reg_2232_pp0_iter4_reg;

assign memoriesTEI_0_0_dataarray_data_V_address0 = zext_ln321_1_fu_1669_p1;

assign memoriesTEI_0_0_dataarray_data_V_d0 = p_Result_2_fu_1515_p5;

assign memoriesTEI_0_1_dataarray_data_V_address0 = zext_ln321_2_fu_1779_p1;

assign memoriesTEI_0_1_dataarray_data_V_d0 = p_Result_2_fu_1515_p5;

assign memoriesTEI_0_2_dataarray_data_V_address0 = zext_ln321_3_fu_1879_p1;

assign memoriesTEI_0_2_dataarray_data_V_d0 = p_Result_2_fu_1515_p5;

assign memoriesTEI_0_3_dataarray_data_V_address0 = zext_ln321_4_fu_1985_p1;

assign memoriesTEI_0_3_dataarray_data_V_d0 = p_Result_2_fu_1515_p5;

assign memoriesTEI_1_0_dataarray_data_V_address0 = zext_ln321_1_fu_1669_p1;

assign memoriesTEI_1_0_dataarray_data_V_d0 = p_Result_2_fu_1515_p5;

assign memoriesTEI_1_1_dataarray_data_V_address0 = zext_ln321_2_fu_1779_p1;

assign memoriesTEI_1_1_dataarray_data_V_d0 = p_Result_2_fu_1515_p5;

assign memoriesTEI_1_2_dataarray_data_V_address0 = zext_ln321_3_fu_1879_p1;

assign memoriesTEI_1_2_dataarray_data_V_d0 = p_Result_2_fu_1515_p5;

assign memoriesTEI_1_3_dataarray_data_V_address0 = zext_ln321_4_fu_1985_p1;

assign memoriesTEI_1_3_dataarray_data_V_d0 = p_Result_2_fu_1515_p5;

assign memoriesTEI_2_0_dataarray_data_V_address0 = zext_ln321_1_fu_1669_p1;

assign memoriesTEI_2_0_dataarray_data_V_d0 = p_Result_2_fu_1515_p5;

assign memoriesTEI_2_1_dataarray_data_V_address0 = zext_ln321_2_fu_1779_p1;

assign memoriesTEI_2_1_dataarray_data_V_d0 = p_Result_2_fu_1515_p5;

assign memoriesTEI_2_2_dataarray_data_V_address0 = zext_ln321_3_fu_1879_p1;

assign memoriesTEI_2_2_dataarray_data_V_d0 = p_Result_2_fu_1515_p5;

assign memoriesTEI_2_3_dataarray_data_V_address0 = zext_ln321_4_fu_1985_p1;

assign memoriesTEI_2_3_dataarray_data_V_d0 = p_Result_2_fu_1515_p5;

assign memoriesTEI_3_0_dataarray_data_V_address0 = zext_ln321_1_fu_1669_p1;

assign memoriesTEI_3_0_dataarray_data_V_d0 = p_Result_2_fu_1515_p5;

assign memoriesTEI_3_1_dataarray_data_V_address0 = zext_ln321_2_fu_1779_p1;

assign memoriesTEI_3_1_dataarray_data_V_d0 = p_Result_2_fu_1515_p5;

assign memoriesTEI_3_2_dataarray_data_V_address0 = zext_ln321_3_fu_1879_p1;

assign memoriesTEI_3_2_dataarray_data_V_d0 = p_Result_2_fu_1515_p5;

assign memoriesTEI_3_3_dataarray_data_V_address0 = zext_ln321_4_fu_1985_p1;

assign memoriesTEI_3_3_dataarray_data_V_d0 = p_Result_2_fu_1515_p5;

assign nInputs_0_V_fu_975_p3 = ((trunc_ln209_fu_971_p1[0:0] === 1'b1) ? inputStubs_0_nentries_1_V : inputStubs_0_nentries_0_V);

assign nInputs_1_V_fu_989_p3 = ((trunc_ln209_fu_971_p1[0:0] === 1'b1) ? inputStubs_1_nentries_1_V : inputStubs_1_nentries_0_V);

assign nInputs_2_V_10_fu_1260_p3 = ((noStubsLeft_fu_1119_p2[0:0] === 1'b1) ? ap_phi_mux_nInputs_2_V3_phi_fu_883_p4 : nInputs_2_V_6_fu_1214_p3);

assign nInputs_2_V_6_fu_1214_p3 = ((icmp_ln701_1_fu_1208_p2[0:0] === 1'b1) ? nInputs_2_V_9_fu_1196_p2 : ap_phi_mux_nInputs_2_V3_phi_fu_883_p4);

assign nInputs_2_V_7_fu_1236_p3 = ((or_ln675_fu_1222_p2[0:0] === 1'b1) ? ap_phi_mux_nInputs_2_V_01_phi_fu_903_p4 : select_ln675_fu_1228_p3);

assign nInputs_2_V_8_fu_1252_p3 = ((or_ln675_fu_1222_p2[0:0] === 1'b1) ? ap_phi_mux_nInputs_1_V_02_phi_fu_893_p4 : select_ln675_2_fu_1244_p3);

assign nInputs_2_V_9_fu_1196_p2 = ($signed(7'd127) + $signed(tmp_fu_1162_p5));

assign nInputs_2_V_fu_1003_p3 = ((trunc_ln209_fu_971_p1[0:0] === 1'b1) ? inputStubs_2_nentries_1_V : inputStubs_2_nentries_0_V);

assign noStubsLeft_fu_1119_p2 = ((ap_phi_mux_p_what2_4_phi_fu_873_p4 == 3'd0) ? 1'b1 : 1'b0);

assign or_ln675_1_fu_1327_p2 = (noStubsLeft_reg_2175_pp0_iter2_reg | icmp_ln687_reg_2181_pp0_iter2_reg);

assign or_ln675_fu_1222_p2 = (noStubsLeft_fu_1119_p2 | icmp_ln701_1_fu_1208_p2);

assign or_ln792_fu_1913_p2 = (4'd3 | add_ln792_fu_1588_p2);

assign p_Repl2_s_fu_1180_p2 = (resetNext_fu_1174_p2 ^ 1'd1);

always @ (*) begin
    p_Result_1_fu_1186_p4 = ap_phi_mux_p_what2_4_phi_fu_873_p4;
    p_Result_1_fu_1186_p4[mem_index_fu_1129_p3] = |(p_Repl2_s_fu_1180_p2);
end

assign p_Result_2_fu_1515_p5 = {{{{addr_index_assign6_reg_715_pp0_iter4_reg}, {bend_V_reg_2242_pp0_iter4_reg}}, {p_Result_i6_i_fu_1487_p4}}, {trunc_ln301_fu_1511_p1}};

assign p_Result_5_2_fu_1017_p4 = {{{icmp_ln841_2_fu_1011_p2}, {icmp_ln841_1_fu_997_p2}}, {icmp_ln841_fu_983_p2}};

assign p_Result_i6_i_fu_1487_p4 = {{phiCorr_V_fu_1481_p3[8:7]}};

assign p_Result_s_fu_1564_p2 = ((tmp_19_fu_1554_p4 == 3'd0) ? 1'b1 : 1'b0);

assign p_Val2_s_fu_1320_p3 = ((noStubsLeft_reg_2175_pp0_iter2_reg[0:0] === 1'b1) ? 36'd0 : select_ln687_fu_1313_p3);

assign p_what2_s_fu_1268_p3 = ((noStubsLeft_fu_1119_p2[0:0] === 1'b1) ? 3'd0 : p_Result_1_fu_1186_p4);

assign phiCorr_V_2_fu_1448_p3 = ((tmp_11_fu_1440_p3[0:0] === 1'b1) ? 15'd0 : trunc_ln1354_fu_1436_p1);

assign phiCorr_V_fu_1481_p3 = ((tmp_13_reg_2258[0:0] === 1'b1) ? 14'd16383 : trunc_ln214_reg_2263);

assign phi_V_fu_1413_p4 = {{p_Val2_s_reg_2232[16:3]}};

assign phi_ln792_1_fu_1713_p5 = {{add_ln792_fu_1588_p2[3:2]}};

assign phi_ln792_2_fu_1813_p5 = {{add_ln792_fu_1588_p2[3:2]}};

assign rBin_V_fu_1351_p4 = {{ret_V_fu_1345_p2[6:4]}};

assign r_V_fu_1331_p4 = {{p_Val2_s_fu_1320_p3[35:29]}};

assign read_addr_V_1_fu_1294_p3 = ((and_ln675_fu_1282_p2[0:0] === 1'b1) ? 7'd0 : read_addr_V_fu_1288_p2);

assign read_addr_V_fu_1288_p2 = (7'd1 + ap_phi_mux_p_05_phi_fu_860_p6);

assign resetNext_fu_1174_p2 = ((tmp_fu_1162_p5 == 7'd1) ? 1'b1 : 1'b0);

assign ret_V_2_fu_1430_p2 = ($signed(zext_ln215_fu_1422_p1) - $signed(sext_ln215_fu_1426_p1));

assign ret_V_fu_1345_p2 = (r_V_fu_1331_p4 ^ 7'd64);

assign select_ln675_2_fu_1244_p3 = ((icmp_ln701_fu_1202_p2[0:0] === 1'b1) ? nInputs_2_V_9_fu_1196_p2 : ap_phi_mux_nInputs_1_V_02_phi_fu_893_p4);

assign select_ln675_fu_1228_p3 = ((icmp_ln701_fu_1202_p2[0:0] === 1'b1) ? ap_phi_mux_nInputs_2_V_01_phi_fu_903_p4 : nInputs_2_V_9_fu_1196_p2);

assign select_ln687_fu_1313_p3 = ((icmp_ln687_reg_2181_pp0_iter2_reg[0:0] === 1'b1) ? stub_data_V_fu_1302_p5 : 36'd0);

assign select_ln792_1_fu_1925_p3 = ((icmp_ln792_3_fu_1919_p2[0:0] === 1'b1) ? 8'd247 : 8'd0);

assign select_ln792_fu_1600_p3 = ((icmp_ln792_6_fu_1594_p2[0:0] === 1'b1) ? 8'd247 : 8'd31);

assign sext_ln215_fu_1426_p1 = $signed(lut_1_q0);

assign shl_ln792_1_fu_1611_p2 = 8'd1 << zext_ln792_fu_1608_p1;

assign shl_ln792_fu_1548_p2 = 16'd1 << zext_ln215_1_fu_1507_p1;

assign shl_ln_fu_1580_p3 = {{trunc_ln_fu_1570_p4}, {2'd0}};

assign tmp_10_fu_1468_p3 = {{bx_V7_phi_reg_958_pp0_iter4_reg}, {addr_index_assign6_reg_715_pp0_iter4_reg}};

assign tmp_11_fu_1440_p3 = ret_V_2_fu_1430_p2[32'd15];

assign tmp_12_fu_1374_p4 = {{p_Val2_s_fu_1320_p3[28:22]}};

assign tmp_14_fu_1661_p3 = {{p_phi_reg_946_pp0_iter4_reg}, {tmp_1_fu_1647_p6}};

assign tmp_15_fu_1771_p3 = {{p_phi_reg_946_pp0_iter4_reg}, {tmp_4_fu_1757_p6}};

assign tmp_16_fu_1871_p3 = {{p_phi_reg_946_pp0_iter4_reg}, {tmp_5_fu_1857_p6}};

assign tmp_17_fu_1977_p3 = {{p_phi_reg_946_pp0_iter4_reg}, {tmp_7_fu_1963_p6}};

assign tmp_18_fu_1400_p3 = {{indexz_V_fu_1384_p2}, {indexr_V_fu_1390_p4}};

assign tmp_19_fu_1554_p4 = {{shl_ln792_fu_1548_p2[15:13]}};

assign tmp_1_fu_1647_p5 = (trunc_ln_fu_1570_p4 + 2'd3);

assign tmp_4_fu_1757_p5 = (trunc_ln_fu_1570_p4 + 2'd3);

assign tmp_5_fu_1857_p5 = (trunc_ln_fu_1570_p4 + 2'd3);

assign tmp_7_fu_1963_p5 = (trunc_ln_fu_1570_p4 + 2'd3);

assign tmp_9_fu_1143_p3 = {{ap_phi_mux_p_phi_phi_fu_950_p4}, {ap_phi_mux_p_05_phi_fu_860_p6}};

assign tmp_i_i_fu_1361_p3 = {{bend_V_fu_1341_p1}, {rBin_V_fu_1351_p4}};

assign trunc_ln1354_fu_1436_p1 = ret_V_2_fu_1430_p2[14:0];

assign trunc_ln209_fu_971_p1 = bx_V[0:0];

assign trunc_ln214_fu_1464_p1 = phiCorr_V_2_fu_1448_p3[13:0];

assign trunc_ln301_fu_1511_p1 = lut_q0[9:0];

assign trunc_ln42_fu_1158_p1 = mem_index_fu_1129_p3[1:0];

assign trunc_ln_fu_1570_p4 = {{phiCorr_V_fu_1481_p3[10:9]}};

assign xor_ln675_fu_1276_p2 = (noStubsLeft_fu_1119_p2 ^ 1'd1);

assign zext_ln215_1_fu_1507_p1 = iphivm_V_fu_1497_p4;

assign zext_ln215_fu_1422_p1 = phi_V_fu_1413_p4;

assign zext_ln321_1_fu_1669_p1 = tmp_14_fu_1661_p3;

assign zext_ln321_2_fu_1779_p1 = tmp_15_fu_1771_p3;

assign zext_ln321_3_fu_1879_p1 = tmp_16_fu_1871_p3;

assign zext_ln321_4_fu_1985_p1 = tmp_17_fu_1977_p3;

assign zext_ln321_fu_1476_p1 = tmp_10_fu_1468_p3;

assign zext_ln400_fu_1408_p1 = tmp_18_fu_1400_p3;

assign zext_ln42_fu_1151_p1 = tmp_9_fu_1143_p3;

assign zext_ln544_fu_1369_p1 = tmp_i_i_fu_1361_p3;

assign zext_ln684_fu_1125_p1 = ap_phi_mux_p_what2_4_phi_fu_873_p4;

assign zext_ln792_fu_1608_p1 = bend_V_reg_2242_pp0_iter4_reg;

endmodule //VMRouterTop_L1PHID
