// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="VMRouterTop_L1PHID,hls_ip_2020_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xcvu7p-flvb2104-1-e,HLS_INPUT_CLOCK=4.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.301500,HLS_SYN_LAT=112,HLS_SYN_TPT=none,HLS_SYN_MEM=2,HLS_SYN_DSP=0,HLS_SYN_FF=912,HLS_SYN_LUT=1696,HLS_VERSION=2020_1}" *)

module VMRouterTop_L1PHID (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        bx_V,
        bx_o_V,
        bx_o_V_ap_vld,
        inputStubs_0_dataarray_data_V_address0,
        inputStubs_0_dataarray_data_V_ce0,
        inputStubs_0_dataarray_data_V_q0,
        inputStubs_1_dataarray_data_V_address0,
        inputStubs_1_dataarray_data_V_ce0,
        inputStubs_1_dataarray_data_V_q0,
        inputStubs_2_dataarray_data_V_address0,
        inputStubs_2_dataarray_data_V_ce0,
        inputStubs_2_dataarray_data_V_q0,
        inputStubs_0_nentries_0_V,
        inputStubs_0_nentries_1_V,
        inputStubs_1_nentries_0_V,
        inputStubs_1_nentries_1_V,
        inputStubs_2_nentries_0_V,
        inputStubs_2_nentries_1_V,
        memoriesAS_0_dataarray_data_V_address0,
        memoriesAS_0_dataarray_data_V_ce0,
        memoriesAS_0_dataarray_data_V_we0,
        memoriesAS_0_dataarray_data_V_d0,
        memoriesTEI_0_0_dataarray_data_V_address0,
        memoriesTEI_0_0_dataarray_data_V_ce0,
        memoriesTEI_0_0_dataarray_data_V_we0,
        memoriesTEI_0_0_dataarray_data_V_d0,
        memoriesTEI_0_1_dataarray_data_V_address0,
        memoriesTEI_0_1_dataarray_data_V_ce0,
        memoriesTEI_0_1_dataarray_data_V_we0,
        memoriesTEI_0_1_dataarray_data_V_d0,
        memoriesTEI_0_2_dataarray_data_V_address0,
        memoriesTEI_0_2_dataarray_data_V_ce0,
        memoriesTEI_0_2_dataarray_data_V_we0,
        memoriesTEI_0_2_dataarray_data_V_d0,
        memoriesTEI_0_3_dataarray_data_V_address0,
        memoriesTEI_0_3_dataarray_data_V_ce0,
        memoriesTEI_0_3_dataarray_data_V_we0,
        memoriesTEI_0_3_dataarray_data_V_d0,
        memoriesTEI_1_0_dataarray_data_V_address0,
        memoriesTEI_1_0_dataarray_data_V_ce0,
        memoriesTEI_1_0_dataarray_data_V_we0,
        memoriesTEI_1_0_dataarray_data_V_d0,
        memoriesTEI_1_1_dataarray_data_V_address0,
        memoriesTEI_1_1_dataarray_data_V_ce0,
        memoriesTEI_1_1_dataarray_data_V_we0,
        memoriesTEI_1_1_dataarray_data_V_d0,
        memoriesTEI_1_2_dataarray_data_V_address0,
        memoriesTEI_1_2_dataarray_data_V_ce0,
        memoriesTEI_1_2_dataarray_data_V_we0,
        memoriesTEI_1_2_dataarray_data_V_d0,
        memoriesTEI_1_3_dataarray_data_V_address0,
        memoriesTEI_1_3_dataarray_data_V_ce0,
        memoriesTEI_1_3_dataarray_data_V_we0,
        memoriesTEI_1_3_dataarray_data_V_d0,
        memoriesTEI_2_0_dataarray_data_V_address0,
        memoriesTEI_2_0_dataarray_data_V_ce0,
        memoriesTEI_2_0_dataarray_data_V_we0,
        memoriesTEI_2_0_dataarray_data_V_d0,
        memoriesTEI_2_1_dataarray_data_V_address0,
        memoriesTEI_2_1_dataarray_data_V_ce0,
        memoriesTEI_2_1_dataarray_data_V_we0,
        memoriesTEI_2_1_dataarray_data_V_d0,
        memoriesTEI_2_2_dataarray_data_V_address0,
        memoriesTEI_2_2_dataarray_data_V_ce0,
        memoriesTEI_2_2_dataarray_data_V_we0,
        memoriesTEI_2_2_dataarray_data_V_d0,
        memoriesTEI_2_3_dataarray_data_V_address0,
        memoriesTEI_2_3_dataarray_data_V_ce0,
        memoriesTEI_2_3_dataarray_data_V_we0,
        memoriesTEI_2_3_dataarray_data_V_d0,
        memoriesTEI_3_0_dataarray_data_V_address0,
        memoriesTEI_3_0_dataarray_data_V_ce0,
        memoriesTEI_3_0_dataarray_data_V_we0,
        memoriesTEI_3_0_dataarray_data_V_d0,
        memoriesTEI_3_1_dataarray_data_V_address0,
        memoriesTEI_3_1_dataarray_data_V_ce0,
        memoriesTEI_3_1_dataarray_data_V_we0,
        memoriesTEI_3_1_dataarray_data_V_d0,
        memoriesTEI_3_2_dataarray_data_V_address0,
        memoriesTEI_3_2_dataarray_data_V_ce0,
        memoriesTEI_3_2_dataarray_data_V_we0,
        memoriesTEI_3_2_dataarray_data_V_d0,
        memoriesTEI_3_3_dataarray_data_V_address0,
        memoriesTEI_3_3_dataarray_data_V_ce0,
        memoriesTEI_3_3_dataarray_data_V_we0,
        memoriesTEI_3_3_dataarray_data_V_d0
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_pp0_stage0 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [2:0] bx_V;
output  [2:0] bx_o_V;
output   bx_o_V_ap_vld;
output  [7:0] inputStubs_0_dataarray_data_V_address0;
output   inputStubs_0_dataarray_data_V_ce0;
input  [35:0] inputStubs_0_dataarray_data_V_q0;
output  [7:0] inputStubs_1_dataarray_data_V_address0;
output   inputStubs_1_dataarray_data_V_ce0;
input  [35:0] inputStubs_1_dataarray_data_V_q0;
output  [7:0] inputStubs_2_dataarray_data_V_address0;
output   inputStubs_2_dataarray_data_V_ce0;
input  [35:0] inputStubs_2_dataarray_data_V_q0;
input  [6:0] inputStubs_0_nentries_0_V;
input  [6:0] inputStubs_0_nentries_1_V;
input  [6:0] inputStubs_1_nentries_0_V;
input  [6:0] inputStubs_1_nentries_1_V;
input  [6:0] inputStubs_2_nentries_0_V;
input  [6:0] inputStubs_2_nentries_1_V;
output  [9:0] memoriesAS_0_dataarray_data_V_address0;
output   memoriesAS_0_dataarray_data_V_ce0;
output   memoriesAS_0_dataarray_data_V_we0;
output  [35:0] memoriesAS_0_dataarray_data_V_d0;
output  [7:0] memoriesTEI_0_0_dataarray_data_V_address0;
output   memoriesTEI_0_0_dataarray_data_V_ce0;
output   memoriesTEI_0_0_dataarray_data_V_we0;
output  [21:0] memoriesTEI_0_0_dataarray_data_V_d0;
output  [7:0] memoriesTEI_0_1_dataarray_data_V_address0;
output   memoriesTEI_0_1_dataarray_data_V_ce0;
output   memoriesTEI_0_1_dataarray_data_V_we0;
output  [21:0] memoriesTEI_0_1_dataarray_data_V_d0;
output  [7:0] memoriesTEI_0_2_dataarray_data_V_address0;
output   memoriesTEI_0_2_dataarray_data_V_ce0;
output   memoriesTEI_0_2_dataarray_data_V_we0;
output  [21:0] memoriesTEI_0_2_dataarray_data_V_d0;
output  [7:0] memoriesTEI_0_3_dataarray_data_V_address0;
output   memoriesTEI_0_3_dataarray_data_V_ce0;
output   memoriesTEI_0_3_dataarray_data_V_we0;
output  [21:0] memoriesTEI_0_3_dataarray_data_V_d0;
output  [7:0] memoriesTEI_1_0_dataarray_data_V_address0;
output   memoriesTEI_1_0_dataarray_data_V_ce0;
output   memoriesTEI_1_0_dataarray_data_V_we0;
output  [21:0] memoriesTEI_1_0_dataarray_data_V_d0;
output  [7:0] memoriesTEI_1_1_dataarray_data_V_address0;
output   memoriesTEI_1_1_dataarray_data_V_ce0;
output   memoriesTEI_1_1_dataarray_data_V_we0;
output  [21:0] memoriesTEI_1_1_dataarray_data_V_d0;
output  [7:0] memoriesTEI_1_2_dataarray_data_V_address0;
output   memoriesTEI_1_2_dataarray_data_V_ce0;
output   memoriesTEI_1_2_dataarray_data_V_we0;
output  [21:0] memoriesTEI_1_2_dataarray_data_V_d0;
output  [7:0] memoriesTEI_1_3_dataarray_data_V_address0;
output   memoriesTEI_1_3_dataarray_data_V_ce0;
output   memoriesTEI_1_3_dataarray_data_V_we0;
output  [21:0] memoriesTEI_1_3_dataarray_data_V_d0;
output  [7:0] memoriesTEI_2_0_dataarray_data_V_address0;
output   memoriesTEI_2_0_dataarray_data_V_ce0;
output   memoriesTEI_2_0_dataarray_data_V_we0;
output  [21:0] memoriesTEI_2_0_dataarray_data_V_d0;
output  [7:0] memoriesTEI_2_1_dataarray_data_V_address0;
output   memoriesTEI_2_1_dataarray_data_V_ce0;
output   memoriesTEI_2_1_dataarray_data_V_we0;
output  [21:0] memoriesTEI_2_1_dataarray_data_V_d0;
output  [7:0] memoriesTEI_2_2_dataarray_data_V_address0;
output   memoriesTEI_2_2_dataarray_data_V_ce0;
output   memoriesTEI_2_2_dataarray_data_V_we0;
output  [21:0] memoriesTEI_2_2_dataarray_data_V_d0;
output  [7:0] memoriesTEI_2_3_dataarray_data_V_address0;
output   memoriesTEI_2_3_dataarray_data_V_ce0;
output   memoriesTEI_2_3_dataarray_data_V_we0;
output  [21:0] memoriesTEI_2_3_dataarray_data_V_d0;
output  [7:0] memoriesTEI_3_0_dataarray_data_V_address0;
output   memoriesTEI_3_0_dataarray_data_V_ce0;
output   memoriesTEI_3_0_dataarray_data_V_we0;
output  [21:0] memoriesTEI_3_0_dataarray_data_V_d0;
output  [7:0] memoriesTEI_3_1_dataarray_data_V_address0;
output   memoriesTEI_3_1_dataarray_data_V_ce0;
output   memoriesTEI_3_1_dataarray_data_V_we0;
output  [21:0] memoriesTEI_3_1_dataarray_data_V_d0;
output  [7:0] memoriesTEI_3_2_dataarray_data_V_address0;
output   memoriesTEI_3_2_dataarray_data_V_ce0;
output   memoriesTEI_3_2_dataarray_data_V_we0;
output  [21:0] memoriesTEI_3_2_dataarray_data_V_d0;
output  [7:0] memoriesTEI_3_3_dataarray_data_V_address0;
output   memoriesTEI_3_3_dataarray_data_V_ce0;
output   memoriesTEI_3_3_dataarray_data_V_we0;
output  [21:0] memoriesTEI_3_3_dataarray_data_V_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg inputStubs_0_dataarray_data_V_ce0;
reg inputStubs_1_dataarray_data_V_ce0;
reg inputStubs_2_dataarray_data_V_ce0;
reg memoriesAS_0_dataarray_data_V_ce0;
reg memoriesAS_0_dataarray_data_V_we0;
reg memoriesTEI_0_0_dataarray_data_V_ce0;
reg memoriesTEI_0_0_dataarray_data_V_we0;
reg memoriesTEI_0_1_dataarray_data_V_ce0;
reg memoriesTEI_0_1_dataarray_data_V_we0;
reg memoriesTEI_0_2_dataarray_data_V_ce0;
reg memoriesTEI_0_2_dataarray_data_V_we0;
reg memoriesTEI_0_3_dataarray_data_V_ce0;
reg memoriesTEI_0_3_dataarray_data_V_we0;
reg memoriesTEI_1_0_dataarray_data_V_ce0;
reg memoriesTEI_1_0_dataarray_data_V_we0;
reg memoriesTEI_1_1_dataarray_data_V_ce0;
reg memoriesTEI_1_1_dataarray_data_V_we0;
reg memoriesTEI_1_2_dataarray_data_V_ce0;
reg memoriesTEI_1_2_dataarray_data_V_we0;
reg memoriesTEI_1_3_dataarray_data_V_ce0;
reg memoriesTEI_1_3_dataarray_data_V_we0;
reg memoriesTEI_2_0_dataarray_data_V_ce0;
reg memoriesTEI_2_0_dataarray_data_V_we0;
reg memoriesTEI_2_1_dataarray_data_V_ce0;
reg memoriesTEI_2_1_dataarray_data_V_we0;
reg memoriesTEI_2_2_dataarray_data_V_ce0;
reg memoriesTEI_2_2_dataarray_data_V_we0;
reg memoriesTEI_2_3_dataarray_data_V_ce0;
reg memoriesTEI_2_3_dataarray_data_V_we0;
reg memoriesTEI_3_0_dataarray_data_V_ce0;
reg memoriesTEI_3_0_dataarray_data_V_we0;
reg memoriesTEI_3_1_dataarray_data_V_ce0;
reg memoriesTEI_3_1_dataarray_data_V_we0;
reg memoriesTEI_3_2_dataarray_data_V_ce0;
reg memoriesTEI_3_2_dataarray_data_V_we0;
reg memoriesTEI_3_3_dataarray_data_V_ce0;
reg memoriesTEI_3_3_dataarray_data_V_we0;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] icmp_ln609_fu_1122_p2;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
wire    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_state4_pp0_stage0_iter2;
wire    ap_block_state5_pp0_stage0_iter3;
wire    ap_block_state6_pp0_stage0_iter4;
reg    bx_o_V_1_ack_in;
reg    ap_block_state7_pp0_stage0_iter5;
reg    ap_enable_reg_pp0_iter5;
reg    ap_block_pp0_stage0_11001;
reg   [2:0] bx_o_V_1_data_reg;
reg    bx_o_V_1_vld_reg;
reg    bx_o_V_1_vld_in;
wire   [5:0] lut_1_address0;
reg    lut_1_ce0;
wire   [14:0] lut_1_q0;
wire   [10:0] lut_address0;
reg    lut_ce0;
wire   [10:0] lut_q0;
reg   [0:0] do_init_reg_701;
reg   [6:0] nInputs_2_V_1_rewind_reg_717;
reg   [6:0] nInputs_1_V_rewind_reg_731;
reg   [6:0] nInputs_0_V_rewind_reg_745;
reg   [0:0] p_rewind_reg_759;
reg   [2:0] bx_V8_rewind_reg_773;
reg   [2:0] p_what2_5_rewind_reg_787;
reg   [6:0] nInputs_2_V_01_rewind_reg_802;
reg   [6:0] nInputs_1_V_02_rewind_reg_817;
reg   [6:0] nInputs_2_V_63_rewind_reg_832;
reg   [7:0] val_assign7_reg_847;
reg   [6:0] nInputs_2_V_1_phi_reg_862;
reg   [6:0] nInputs_1_V_phi_reg_874;
reg   [6:0] nInputs_0_V_phi_reg_886;
reg   [0:0] p_phi_reg_898;
reg   [0:0] p_phi_reg_898_pp0_iter1_reg;
reg   [0:0] p_phi_reg_898_pp0_iter2_reg;
reg   [0:0] p_phi_reg_898_pp0_iter3_reg;
reg   [0:0] p_phi_reg_898_pp0_iter4_reg;
reg   [2:0] bx_V8_phi_reg_910;
reg   [2:0] bx_V8_phi_reg_910_pp0_iter1_reg;
reg   [2:0] bx_V8_phi_reg_910_pp0_iter2_reg;
reg   [2:0] bx_V8_phi_reg_910_pp0_iter3_reg;
reg   [2:0] bx_V8_phi_reg_910_pp0_iter4_reg;
reg   [6:0] p_06_reg_924;
reg   [6:0] p_050_2_i_reg_1034;
wire   [6:0] nInputs_0_V_fu_1057_p3;
reg   [0:0] ap_phi_mux_do_init_phi_fu_705_p6;
wire   [6:0] nInputs_1_V_fu_1072_p3;
wire   [6:0] nInputs_2_V_1_fu_1087_p3;
wire   [2:0] p_Result_5_2_fu_1102_p4;
wire   [7:0] i_fu_1112_p2;
reg   [7:0] i_reg_2282;
reg   [0:0] icmp_ln609_reg_2287;
reg   [0:0] icmp_ln609_reg_2287_pp0_iter1_reg;
reg   [0:0] icmp_ln609_reg_2287_pp0_iter2_reg;
reg   [0:0] icmp_ln609_reg_2287_pp0_iter3_reg;
reg   [0:0] icmp_ln609_reg_2287_pp0_iter4_reg;
wire   [0:0] icmp_ln615_fu_1128_p2;
reg   [0:0] icmp_ln615_reg_2291;
reg   [0:0] icmp_ln615_reg_2291_pp0_iter2_reg;
reg   [0:0] icmp_ln615_reg_2291_pp0_iter3_reg;
reg   [0:0] icmp_ln615_reg_2291_pp0_iter4_reg;
wire   [0:0] noStubsLeft_fu_1134_p2;
reg   [0:0] noStubsLeft_reg_2295;
reg   [0:0] noStubsLeft_reg_2295_pp0_iter2_reg;
reg   [0:0] noStubsLeft_reg_2295_pp0_iter3_reg;
reg   [0:0] noStubsLeft_reg_2295_pp0_iter4_reg;
wire   [0:0] icmp_ln643_fu_1152_p2;
reg   [0:0] icmp_ln643_reg_2300;
reg   [0:0] icmp_ln643_reg_2300_pp0_iter2_reg;
wire   [1:0] trunc_ln57_fu_1173_p1;
reg   [1:0] trunc_ln57_reg_2320;
reg   [1:0] trunc_ln57_reg_2320_pp0_iter2_reg;
wire   [0:0] or_ln631_fu_1321_p2;
reg   [0:0] or_ln631_reg_2325;
reg   [0:0] or_ln631_reg_2325_pp0_iter2_reg;
reg   [0:0] or_ln631_reg_2325_pp0_iter3_reg;
reg   [0:0] or_ln631_reg_2325_pp0_iter4_reg;
wire   [6:0] trunc_ln301_fu_1343_p1;
reg   [6:0] trunc_ln301_reg_2329;
reg   [6:0] trunc_ln301_reg_2329_pp0_iter2_reg;
reg   [6:0] trunc_ln301_reg_2329_pp0_iter3_reg;
reg   [6:0] trunc_ln301_reg_2329_pp0_iter4_reg;
wire   [35:0] stub_data_V_3_fu_1368_p3;
reg   [35:0] stub_data_V_3_reg_2335;
reg   [35:0] stub_data_V_3_reg_2335_pp0_iter4_reg;
wire   [2:0] bend_V_fu_1386_p1;
reg   [2:0] bend_V_reg_2341;
reg   [2:0] bend_V_reg_2341_pp0_iter4_reg;
reg   [0:0] tmp_13_reg_2357;
wire   [13:0] trunc_ln214_fu_1509_p1;
reg   [13:0] trunc_ln214_reg_2362;
reg    ap_enable_reg_pp0_iter1;
reg    ap_block_pp0_stage0_subdone;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
wire    ap_block_pp0_stage0;
reg   [6:0] ap_phi_mux_nInputs_2_V_1_rewind_phi_fu_721_p6;
reg   [6:0] ap_phi_mux_nInputs_1_V_rewind_phi_fu_735_p6;
reg   [6:0] ap_phi_mux_nInputs_0_V_rewind_phi_fu_749_p6;
reg   [0:0] ap_phi_mux_p_rewind_phi_fu_763_p6;
reg   [2:0] ap_phi_mux_bx_V8_rewind_phi_fu_777_p6;
reg   [2:0] ap_phi_mux_p_what2_s_phi_fu_1024_p6;
reg   [2:0] ap_phi_mux_p_what2_5_rewind_phi_fu_791_p6;
reg   [6:0] ap_phi_mux_nInputs_2_V_3_phi_fu_982_p6;
reg   [6:0] ap_phi_mux_nInputs_2_V_01_rewind_phi_fu_806_p6;
reg   [6:0] ap_phi_mux_nInputs_1_V_3_phi_fu_996_p6;
reg   [6:0] ap_phi_mux_nInputs_1_V_02_rewind_phi_fu_821_p6;
reg   [6:0] ap_phi_mux_nInputs_2_V_14_phi_fu_1010_p6;
reg   [6:0] ap_phi_mux_nInputs_2_V_63_rewind_phi_fu_836_p6;
reg   [7:0] ap_phi_mux_val_assign7_phi_fu_851_p6;
wire   [6:0] ap_phi_reg_pp0_iter0_nInputs_2_V_1_phi_reg_862;
wire   [6:0] ap_phi_reg_pp0_iter0_nInputs_1_V_phi_reg_874;
wire   [6:0] ap_phi_reg_pp0_iter0_nInputs_0_V_phi_reg_886;
wire   [0:0] trunc_ln209_fu_1052_p1;
wire   [0:0] ap_phi_reg_pp0_iter0_p_phi_reg_898;
wire   [2:0] ap_phi_reg_pp0_iter0_bx_V8_phi_reg_910;
reg   [6:0] ap_phi_mux_p_06_phi_fu_928_p6;
wire   [2:0] ap_phi_reg_pp0_iter0_p_what2_5_reg_938;
reg   [2:0] ap_phi_reg_pp0_iter1_p_what2_5_reg_938;
wire   [6:0] ap_phi_reg_pp0_iter0_nInputs_2_V_63_reg_948;
reg   [6:0] ap_phi_reg_pp0_iter1_nInputs_2_V_63_reg_948;
wire   [6:0] ap_phi_reg_pp0_iter0_nInputs_1_V_02_reg_958;
reg   [6:0] ap_phi_reg_pp0_iter1_nInputs_1_V_02_reg_958;
wire   [6:0] ap_phi_reg_pp0_iter0_nInputs_2_V_01_reg_968;
reg   [6:0] ap_phi_reg_pp0_iter1_nInputs_2_V_01_reg_968;
wire   [6:0] ap_phi_reg_pp0_iter1_nInputs_2_V_3_reg_978;
wire   [6:0] nInputs_2_V_16_fu_1269_p3;
wire   [6:0] ap_phi_reg_pp0_iter1_nInputs_1_V_3_reg_992;
wire   [6:0] nInputs_2_V_17_fu_1279_p3;
wire   [6:0] ap_phi_reg_pp0_iter1_nInputs_2_V_14_reg_1006;
wire   [6:0] nInputs_2_V_18_fu_1289_p3;
wire   [2:0] ap_phi_reg_pp0_iter1_p_what2_s_reg_1020;
wire   [2:0] hasStubs_V_1_fu_1299_p3;
wire   [6:0] ap_phi_reg_pp0_iter1_p_050_2_i_reg_1034;
wire   [6:0] read_addr_V_1_fu_1333_p3;
wire   [63:0] zext_ln57_fu_1166_p1;
wire   [63:0] zext_ln544_fu_1414_p1;
wire   [63:0] zext_ln357_fu_1453_p1;
wire   [63:0] zext_ln321_fu_1520_p1;
wire   [63:0] zext_ln321_1_fu_1712_p1;
wire   [0:0] icmp_ln756_fu_1585_p2;
wire   [0:0] p_Result_s_fu_1607_p2;
wire   [0:0] icmp_ln792_fu_1666_p2;
wire   [63:0] zext_ln321_2_fu_1822_p1;
wire   [0:0] icmp_ln792_1_fu_1776_p2;
wire   [63:0] zext_ln321_3_fu_1922_p1;
wire   [0:0] icmp_ln792_2_fu_1876_p2;
wire   [63:0] zext_ln321_4_fu_2028_p1;
wire   [0:0] icmp_ln792_4_fu_1982_p2;
reg   [35:0] p_Val2_s_fu_298;
reg   [6:0] addrCountTEI_0_0_V_fu_302;
wire   [6:0] addrCountTEI_0_0_V_2_fu_1720_p2;
wire   [1:0] trunc_ln_fu_1613_p4;
reg   [6:0] addrCountTEI_0_1_V_fu_306;
wire   [6:0] addrCountTEI_0_1_V_2_fu_1830_p2;
reg   [6:0] addrCountTEI_0_2_V_fu_310;
wire   [6:0] addrCountTEI_0_2_V_2_fu_1930_p2;
reg   [6:0] addrCountTEI_0_3_V_fu_314;
wire   [6:0] addrCountTEI_0_3_V_2_fu_2036_p2;
reg   [6:0] addrCountTEI_1_0_V_fu_318;
reg   [6:0] addrCountTEI_1_1_V_fu_322;
reg   [6:0] addrCountTEI_1_2_V_fu_326;
reg   [6:0] addrCountTEI_1_3_V_fu_330;
reg   [6:0] addrCountTEI_2_0_V_fu_334;
reg   [6:0] addrCountTEI_2_1_V_fu_338;
reg   [6:0] addrCountTEI_2_2_V_fu_342;
reg   [6:0] addrCountTEI_2_3_V_fu_346;
reg   [6:0] addrCountTEI_3_0_V_fu_350;
reg   [6:0] addrCountTEI_3_1_V_fu_354;
reg   [6:0] addrCountTEI_3_2_V_fu_358;
reg   [6:0] addrCountTEI_3_3_V_fu_362;
reg    ap_block_pp0_stage0_01001;
wire   [21:0] p_Result_2_fu_1559_p5;
wire   [0:0] icmp_ln841_2_fu_1096_p2;
wire   [0:0] icmp_ln841_1_fu_1081_p2;
wire   [0:0] icmp_ln841_fu_1066_p2;
wire   [6:0] trunc_ln609_fu_1118_p1;
wire   [31:0] zext_ln640_fu_1140_p1;
reg   [31:0] mem_index_fu_1144_p3;
wire   [7:0] tmp_9_fu_1158_p3;
wire   [6:0] tmp_fu_1177_p5;
wire   [0:0] resetNext_fu_1189_p2;
wire   [0:0] p_Repl2_s_fu_1195_p2;
wire   [0:0] icmp_ln701_fu_1217_p2;
wire   [6:0] nInputs_2_V_19_fu_1211_p2;
wire   [0:0] icmp_ln701_1_fu_1231_p2;
wire   [6:0] nInputs_2_V_fu_1223_p3;
wire   [6:0] nInputs_2_V_12_fu_1245_p3;
wire   [6:0] nInputs_2_V_11_fu_1237_p3;
wire   [6:0] nInputs_2_V_13_fu_1253_p3;
wire   [6:0] nInputs_2_V_15_fu_1261_p3;
reg   [2:0] p_Result_1_fu_1201_p4;
wire   [0:0] xor_ln631_fu_1309_p2;
wire   [0:0] and_ln631_fu_1315_p2;
wire   [6:0] read_addr_V_fu_1327_p2;
wire   [35:0] stub_data_V_fu_1350_p5;
wire   [35:0] stub_data_V_1_fu_1361_p3;
wire   [6:0] r_V_fu_1376_p4;
wire   [6:0] ret_V_fu_1390_p2;
wire   [2:0] rBin_V_fu_1396_p4;
wire   [5:0] tmp_i_i_fu_1406_p3;
wire   [6:0] tmp_12_fu_1419_p4;
wire   [6:0] indexz_V_fu_1429_p2;
wire   [3:0] indexr_V_fu_1435_p4;
wire   [10:0] tmp_18_fu_1445_p3;
wire   [13:0] phi_V_fu_1458_p4;
wire   [15:0] zext_ln215_fu_1467_p1;
wire  signed [15:0] sext_ln215_fu_1471_p1;
wire   [15:0] ret_V_2_fu_1475_p2;
wire   [0:0] tmp_11_fu_1485_p3;
wire   [14:0] trunc_ln1354_fu_1481_p1;
wire   [14:0] phiCorr_V_2_fu_1493_p3;
wire   [9:0] tmp_10_fu_1513_p3;
wire   [13:0] phiCorr_V_fu_1525_p3;
wire   [4:0] iphivm_V_fu_1541_p4;
wire   [1:0] p_Result_i6_i_fu_1531_p4;
wire   [9:0] trunc_ln301_1_fu_1555_p1;
wire   [15:0] zext_ln215_1_fu_1551_p1;
wire   [15:0] shl_ln792_fu_1591_p2;
wire   [2:0] tmp_19_fu_1597_p4;
wire   [3:0] shl_ln_fu_1623_p3;
wire   [0:0] icmp_ln792_6_fu_1637_p2;
wire   [7:0] zext_ln792_fu_1651_p1;
wire   [7:0] select_ln792_fu_1643_p3;
wire   [7:0] shl_ln792_1_fu_1654_p2;
wire   [7:0] and_ln792_fu_1660_p2;
wire   [1:0] tmp_1_fu_1690_p5;
wire   [6:0] tmp_1_fu_1690_p6;
wire   [7:0] tmp_14_fu_1704_p3;
wire   [3:0] add_ln792_fu_1631_p2;
wire   [1:0] phi_ln792_1_fu_1756_p5;
wire   [7:0] phi_ln792_1_fu_1756_p6;
wire   [7:0] and_ln792_1_fu_1770_p2;
wire   [1:0] tmp_4_fu_1800_p5;
wire   [6:0] tmp_4_fu_1800_p6;
wire   [7:0] tmp_15_fu_1814_p3;
wire   [1:0] phi_ln792_2_fu_1856_p5;
wire   [7:0] phi_ln792_2_fu_1856_p6;
wire   [7:0] and_ln792_2_fu_1870_p2;
wire   [1:0] tmp_5_fu_1900_p5;
wire   [6:0] tmp_5_fu_1900_p6;
wire   [7:0] tmp_16_fu_1914_p3;
wire   [3:0] or_ln792_fu_1956_p2;
wire   [0:0] icmp_ln792_3_fu_1962_p2;
wire   [7:0] select_ln792_1_fu_1968_p3;
wire   [7:0] and_ln792_3_fu_1976_p2;
wire   [1:0] tmp_7_fu_2006_p5;
wire   [6:0] tmp_7_fu_2006_p6;
wire   [7:0] tmp_17_fu_2020_p3;
reg   [1:0] ap_NS_fsm;
reg    ap_idle_pp0_0to4;
reg    ap_reset_idle_pp0;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_572;
reg    ap_condition_581;
reg    ap_condition_587;
reg    ap_condition_593;
reg    ap_condition_600;
reg    ap_condition_606;
reg    ap_condition_611;
reg    ap_condition_616;
reg    ap_condition_623;
reg    ap_condition_629;
reg    ap_condition_634;
reg    ap_condition_639;
reg    ap_condition_646;
reg    ap_condition_652;
reg    ap_condition_657;
reg    ap_condition_662;
reg    ap_condition_419;
reg    ap_condition_49;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 bx_o_V_1_data_reg = 3'd0;
#0 bx_o_V_1_vld_reg = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
end

VMRouterTop_L1PHID_lut_1 #(
    .DataWidth( 15 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
lut_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(lut_1_address0),
    .ce0(lut_1_ce0),
    .q0(lut_1_q0)
);

VMRouterTop_L1PHID_lut #(
    .DataWidth( 11 ),
    .AddressRange( 2048 ),
    .AddressWidth( 11 ))
lut_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(lut_address0),
    .ce0(lut_ce0),
    .q0(lut_q0)
);

VMRouterTop_L1PHID_mux_32_7_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 7 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 7 ))
VMRouterTop_L1PHID_mux_32_7_1_1_U1(
    .din0(ap_phi_reg_pp0_iter1_nInputs_2_V_63_reg_948),
    .din1(ap_phi_reg_pp0_iter1_nInputs_1_V_02_reg_958),
    .din2(ap_phi_reg_pp0_iter1_nInputs_2_V_01_reg_968),
    .din3(trunc_ln57_fu_1173_p1),
    .dout(tmp_fu_1177_p5)
);

VMRouterTop_L1PHID_mux_32_36_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 36 ),
    .din1_WIDTH( 36 ),
    .din2_WIDTH( 36 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 36 ))
VMRouterTop_L1PHID_mux_32_36_1_1_U2(
    .din0(inputStubs_0_dataarray_data_V_q0),
    .din1(inputStubs_1_dataarray_data_V_q0),
    .din2(inputStubs_2_dataarray_data_V_q0),
    .din3(trunc_ln57_reg_2320_pp0_iter2_reg),
    .dout(stub_data_V_fu_1350_p5)
);

VMRouterTop_L1PHID_mux_42_7_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 7 ),
    .din3_WIDTH( 7 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 7 ))
VMRouterTop_L1PHID_mux_42_7_1_1_U3(
    .din0(addrCountTEI_0_0_V_fu_302),
    .din1(addrCountTEI_1_0_V_fu_318),
    .din2(addrCountTEI_2_0_V_fu_334),
    .din3(addrCountTEI_3_0_V_fu_350),
    .din4(tmp_1_fu_1690_p5),
    .dout(tmp_1_fu_1690_p6)
);

VMRouterTop_L1PHID_mux_42_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
VMRouterTop_L1PHID_mux_42_8_1_1_U4(
    .din0(8'd241),
    .din1(8'd159),
    .din2(8'd159),
    .din3(8'd159),
    .din4(phi_ln792_1_fu_1756_p5),
    .dout(phi_ln792_1_fu_1756_p6)
);

VMRouterTop_L1PHID_mux_42_7_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 7 ),
    .din3_WIDTH( 7 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 7 ))
VMRouterTop_L1PHID_mux_42_7_1_1_U5(
    .din0(addrCountTEI_0_1_V_fu_306),
    .din1(addrCountTEI_1_1_V_fu_322),
    .din2(addrCountTEI_2_1_V_fu_338),
    .din3(addrCountTEI_3_1_V_fu_354),
    .din4(tmp_4_fu_1800_p5),
    .dout(tmp_4_fu_1800_p6)
);

VMRouterTop_L1PHID_mux_42_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
VMRouterTop_L1PHID_mux_42_8_1_1_U6(
    .din0(8'd0),
    .din1(8'd255),
    .din2(8'd255),
    .din3(8'd255),
    .din4(phi_ln792_2_fu_1856_p5),
    .dout(phi_ln792_2_fu_1856_p6)
);

VMRouterTop_L1PHID_mux_42_7_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 7 ),
    .din3_WIDTH( 7 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 7 ))
VMRouterTop_L1PHID_mux_42_7_1_1_U7(
    .din0(addrCountTEI_0_2_V_fu_310),
    .din1(addrCountTEI_1_2_V_fu_326),
    .din2(addrCountTEI_2_2_V_fu_342),
    .din3(addrCountTEI_3_2_V_fu_358),
    .din4(tmp_5_fu_1900_p5),
    .dout(tmp_5_fu_1900_p6)
);

VMRouterTop_L1PHID_mux_42_7_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 7 ),
    .din3_WIDTH( 7 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 7 ))
VMRouterTop_L1PHID_mux_42_7_1_1_U8(
    .din0(addrCountTEI_0_3_V_fu_314),
    .din1(addrCountTEI_1_3_V_fu_330),
    .din2(addrCountTEI_2_3_V_fu_346),
    .din3(addrCountTEI_3_3_V_fu_362),
    .din4(tmp_7_fu_2006_p5),
    .dout(tmp_7_fu_2006_p6)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter5 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        if ((icmp_ln615_reg_2291_pp0_iter4_reg == 1'd1)) begin
            addrCountTEI_0_0_V_fu_302 <= 7'd0;
        end else if ((1'b1 == ap_condition_572)) begin
            addrCountTEI_0_0_V_fu_302 <= addrCountTEI_0_0_V_2_fu_1720_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        if ((icmp_ln615_reg_2291_pp0_iter4_reg == 1'd1)) begin
            addrCountTEI_0_1_V_fu_306 <= 7'd0;
        end else if ((1'b1 == ap_condition_581)) begin
            addrCountTEI_0_1_V_fu_306 <= addrCountTEI_0_1_V_2_fu_1830_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        if ((icmp_ln615_reg_2291_pp0_iter4_reg == 1'd1)) begin
            addrCountTEI_0_2_V_fu_310 <= 7'd0;
        end else if ((1'b1 == ap_condition_587)) begin
            addrCountTEI_0_2_V_fu_310 <= addrCountTEI_0_2_V_2_fu_1930_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        if ((icmp_ln615_reg_2291_pp0_iter4_reg == 1'd1)) begin
            addrCountTEI_0_3_V_fu_314 <= 7'd0;
        end else if ((1'b1 == ap_condition_593)) begin
            addrCountTEI_0_3_V_fu_314 <= addrCountTEI_0_3_V_2_fu_2036_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        if ((icmp_ln615_reg_2291_pp0_iter4_reg == 1'd1)) begin
            addrCountTEI_1_0_V_fu_318 <= 7'd0;
        end else if ((1'b1 == ap_condition_600)) begin
            addrCountTEI_1_0_V_fu_318 <= addrCountTEI_0_0_V_2_fu_1720_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        if ((icmp_ln615_reg_2291_pp0_iter4_reg == 1'd1)) begin
            addrCountTEI_1_1_V_fu_322 <= 7'd0;
        end else if ((1'b1 == ap_condition_606)) begin
            addrCountTEI_1_1_V_fu_322 <= addrCountTEI_0_1_V_2_fu_1830_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        if ((icmp_ln615_reg_2291_pp0_iter4_reg == 1'd1)) begin
            addrCountTEI_1_2_V_fu_326 <= 7'd0;
        end else if ((1'b1 == ap_condition_611)) begin
            addrCountTEI_1_2_V_fu_326 <= addrCountTEI_0_2_V_2_fu_1930_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        if ((icmp_ln615_reg_2291_pp0_iter4_reg == 1'd1)) begin
            addrCountTEI_1_3_V_fu_330 <= 7'd0;
        end else if ((1'b1 == ap_condition_616)) begin
            addrCountTEI_1_3_V_fu_330 <= addrCountTEI_0_3_V_2_fu_2036_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        if ((icmp_ln615_reg_2291_pp0_iter4_reg == 1'd1)) begin
            addrCountTEI_2_0_V_fu_334 <= 7'd0;
        end else if ((1'b1 == ap_condition_623)) begin
            addrCountTEI_2_0_V_fu_334 <= addrCountTEI_0_0_V_2_fu_1720_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        if ((icmp_ln615_reg_2291_pp0_iter4_reg == 1'd1)) begin
            addrCountTEI_2_1_V_fu_338 <= 7'd0;
        end else if ((1'b1 == ap_condition_629)) begin
            addrCountTEI_2_1_V_fu_338 <= addrCountTEI_0_1_V_2_fu_1830_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        if ((icmp_ln615_reg_2291_pp0_iter4_reg == 1'd1)) begin
            addrCountTEI_2_2_V_fu_342 <= 7'd0;
        end else if ((1'b1 == ap_condition_634)) begin
            addrCountTEI_2_2_V_fu_342 <= addrCountTEI_0_2_V_2_fu_1930_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        if ((icmp_ln615_reg_2291_pp0_iter4_reg == 1'd1)) begin
            addrCountTEI_2_3_V_fu_346 <= 7'd0;
        end else if ((1'b1 == ap_condition_639)) begin
            addrCountTEI_2_3_V_fu_346 <= addrCountTEI_0_3_V_2_fu_2036_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        if ((icmp_ln615_reg_2291_pp0_iter4_reg == 1'd1)) begin
            addrCountTEI_3_0_V_fu_350 <= 7'd0;
        end else if ((1'b1 == ap_condition_646)) begin
            addrCountTEI_3_0_V_fu_350 <= addrCountTEI_0_0_V_2_fu_1720_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        if ((icmp_ln615_reg_2291_pp0_iter4_reg == 1'd1)) begin
            addrCountTEI_3_1_V_fu_354 <= 7'd0;
        end else if ((1'b1 == ap_condition_652)) begin
            addrCountTEI_3_1_V_fu_354 <= addrCountTEI_0_1_V_2_fu_1830_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        if ((icmp_ln615_reg_2291_pp0_iter4_reg == 1'd1)) begin
            addrCountTEI_3_2_V_fu_358 <= 7'd0;
        end else if ((1'b1 == ap_condition_657)) begin
            addrCountTEI_3_2_V_fu_358 <= addrCountTEI_0_2_V_2_fu_1930_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        if ((icmp_ln615_reg_2291_pp0_iter4_reg == 1'd1)) begin
            addrCountTEI_3_3_V_fu_362 <= 7'd0;
        end else if ((1'b1 == ap_condition_662)) begin
            addrCountTEI_3_3_V_fu_362 <= addrCountTEI_0_3_V_2_fu_2036_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_49)) begin
        if ((ap_phi_mux_do_init_phi_fu_705_p6 == 1'd0)) begin
            ap_phi_reg_pp0_iter1_nInputs_1_V_02_reg_958 <= ap_phi_mux_nInputs_1_V_02_rewind_phi_fu_821_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_705_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_nInputs_1_V_02_reg_958 <= nInputs_1_V_fu_1072_p3;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_nInputs_1_V_02_reg_958 <= ap_phi_reg_pp0_iter0_nInputs_1_V_02_reg_958;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_49)) begin
        if ((ap_phi_mux_do_init_phi_fu_705_p6 == 1'd0)) begin
            ap_phi_reg_pp0_iter1_nInputs_2_V_01_reg_968 <= ap_phi_mux_nInputs_2_V_01_rewind_phi_fu_806_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_705_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_nInputs_2_V_01_reg_968 <= nInputs_2_V_1_fu_1087_p3;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_nInputs_2_V_01_reg_968 <= ap_phi_reg_pp0_iter0_nInputs_2_V_01_reg_968;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_49)) begin
        if ((ap_phi_mux_do_init_phi_fu_705_p6 == 1'd0)) begin
            ap_phi_reg_pp0_iter1_nInputs_2_V_63_reg_948 <= ap_phi_mux_nInputs_2_V_63_rewind_phi_fu_836_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_705_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_nInputs_2_V_63_reg_948 <= nInputs_0_V_fu_1057_p3;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_nInputs_2_V_63_reg_948 <= ap_phi_reg_pp0_iter0_nInputs_2_V_63_reg_948;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_49)) begin
        if ((ap_phi_mux_do_init_phi_fu_705_p6 == 1'd0)) begin
            ap_phi_reg_pp0_iter1_p_what2_5_reg_938 <= ap_phi_mux_p_what2_5_rewind_phi_fu_791_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_705_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_p_what2_5_reg_938 <= p_Result_5_2_fu_1102_p4;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_p_what2_5_reg_938 <= ap_phi_reg_pp0_iter0_p_what2_5_reg_938;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_49)) begin
        if ((ap_phi_mux_do_init_phi_fu_705_p6 == 1'd0)) begin
            bx_V8_phi_reg_910 <= ap_phi_mux_bx_V8_rewind_phi_fu_777_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_705_p6 == 1'd1)) begin
            bx_V8_phi_reg_910 <= bx_V;
        end else if ((1'b1 == 1'b1)) begin
            bx_V8_phi_reg_910 <= ap_phi_reg_pp0_iter0_bx_V8_phi_reg_910;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (bx_o_V_1_vld_reg == 1'b0) & (bx_o_V_1_vld_in == 1'b1))) begin
        bx_o_V_1_vld_reg <= 1'b1;
    end else if (((bx_o_V_1_vld_in == 1'b0) & (1'b1 == 1'b1) & (bx_o_V_1_vld_reg == 1'b1))) begin
        bx_o_V_1_vld_reg <= 1'b0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln609_reg_2287 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        do_init_reg_701 <= 1'd0;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln609_reg_2287 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        do_init_reg_701 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_49)) begin
        if ((ap_phi_mux_do_init_phi_fu_705_p6 == 1'd0)) begin
            nInputs_0_V_phi_reg_886 <= ap_phi_mux_nInputs_0_V_rewind_phi_fu_749_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_705_p6 == 1'd1)) begin
            nInputs_0_V_phi_reg_886 <= nInputs_0_V_fu_1057_p3;
        end else if ((1'b1 == 1'b1)) begin
            nInputs_0_V_phi_reg_886 <= ap_phi_reg_pp0_iter0_nInputs_0_V_phi_reg_886;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_49)) begin
        if ((ap_phi_mux_do_init_phi_fu_705_p6 == 1'd0)) begin
            nInputs_1_V_phi_reg_874 <= ap_phi_mux_nInputs_1_V_rewind_phi_fu_735_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_705_p6 == 1'd1)) begin
            nInputs_1_V_phi_reg_874 <= nInputs_1_V_fu_1072_p3;
        end else if ((1'b1 == 1'b1)) begin
            nInputs_1_V_phi_reg_874 <= ap_phi_reg_pp0_iter0_nInputs_1_V_phi_reg_874;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_49)) begin
        if ((ap_phi_mux_do_init_phi_fu_705_p6 == 1'd0)) begin
            nInputs_2_V_1_phi_reg_862 <= ap_phi_mux_nInputs_2_V_1_rewind_phi_fu_721_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_705_p6 == 1'd1)) begin
            nInputs_2_V_1_phi_reg_862 <= nInputs_2_V_1_fu_1087_p3;
        end else if ((1'b1 == 1'b1)) begin
            nInputs_2_V_1_phi_reg_862 <= ap_phi_reg_pp0_iter0_nInputs_2_V_1_phi_reg_862;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln615_fu_1128_p2 == 1'd0) & (noStubsLeft_fu_1134_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (noStubsLeft_fu_1134_p2 == 1'd0) & (icmp_ln615_fu_1128_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_050_2_i_reg_1034 <= read_addr_V_1_fu_1333_p3;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln615_fu_1128_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_050_2_i_reg_1034 <= ap_phi_mux_p_06_phi_fu_928_p6;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_050_2_i_reg_1034 <= ap_phi_reg_pp0_iter1_p_050_2_i_reg_1034;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln609_reg_2287_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_06_reg_924 <= p_050_2_i_reg_1034;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln609_reg_2287_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        p_06_reg_924 <= 7'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_49)) begin
        if ((ap_phi_mux_do_init_phi_fu_705_p6 == 1'd0)) begin
            p_phi_reg_898 <= ap_phi_mux_p_rewind_phi_fu_763_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_705_p6 == 1'd1)) begin
            p_phi_reg_898 <= trunc_ln209_fu_1052_p1;
        end else if ((1'b1 == 1'b1)) begin
            p_phi_reg_898 <= ap_phi_reg_pp0_iter0_p_phi_reg_898;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln609_reg_2287 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        val_assign7_reg_847 <= i_reg_2282;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln609_reg_2287 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        val_assign7_reg_847 <= 8'd255;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (noStubsLeft_reg_2295_pp0_iter2_reg == 1'd0) & (icmp_ln615_reg_2291_pp0_iter2_reg == 1'd0) & (or_ln631_reg_2325_pp0_iter2_reg == 1'd1))) begin
        bend_V_reg_2341 <= bend_V_fu_1386_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        bend_V_reg_2341_pp0_iter4_reg <= bend_V_reg_2341;
        bx_V8_phi_reg_910_pp0_iter2_reg <= bx_V8_phi_reg_910_pp0_iter1_reg;
        bx_V8_phi_reg_910_pp0_iter3_reg <= bx_V8_phi_reg_910_pp0_iter2_reg;
        bx_V8_phi_reg_910_pp0_iter4_reg <= bx_V8_phi_reg_910_pp0_iter3_reg;
        icmp_ln609_reg_2287_pp0_iter2_reg <= icmp_ln609_reg_2287_pp0_iter1_reg;
        icmp_ln609_reg_2287_pp0_iter3_reg <= icmp_ln609_reg_2287_pp0_iter2_reg;
        icmp_ln609_reg_2287_pp0_iter4_reg <= icmp_ln609_reg_2287_pp0_iter3_reg;
        icmp_ln615_reg_2291_pp0_iter2_reg <= icmp_ln615_reg_2291;
        icmp_ln615_reg_2291_pp0_iter3_reg <= icmp_ln615_reg_2291_pp0_iter2_reg;
        icmp_ln615_reg_2291_pp0_iter4_reg <= icmp_ln615_reg_2291_pp0_iter3_reg;
        icmp_ln643_reg_2300_pp0_iter2_reg <= icmp_ln643_reg_2300;
        noStubsLeft_reg_2295_pp0_iter2_reg <= noStubsLeft_reg_2295;
        noStubsLeft_reg_2295_pp0_iter3_reg <= noStubsLeft_reg_2295_pp0_iter2_reg;
        noStubsLeft_reg_2295_pp0_iter4_reg <= noStubsLeft_reg_2295_pp0_iter3_reg;
        or_ln631_reg_2325_pp0_iter2_reg <= or_ln631_reg_2325;
        or_ln631_reg_2325_pp0_iter3_reg <= or_ln631_reg_2325_pp0_iter2_reg;
        or_ln631_reg_2325_pp0_iter4_reg <= or_ln631_reg_2325_pp0_iter3_reg;
        p_phi_reg_898_pp0_iter2_reg <= p_phi_reg_898_pp0_iter1_reg;
        p_phi_reg_898_pp0_iter3_reg <= p_phi_reg_898_pp0_iter2_reg;
        p_phi_reg_898_pp0_iter4_reg <= p_phi_reg_898_pp0_iter3_reg;
        stub_data_V_3_reg_2335_pp0_iter4_reg <= stub_data_V_3_reg_2335;
        trunc_ln301_reg_2329_pp0_iter2_reg <= trunc_ln301_reg_2329;
        trunc_ln301_reg_2329_pp0_iter3_reg <= trunc_ln301_reg_2329_pp0_iter2_reg;
        trunc_ln301_reg_2329_pp0_iter4_reg <= trunc_ln301_reg_2329_pp0_iter3_reg;
        trunc_ln57_reg_2320_pp0_iter2_reg <= trunc_ln57_reg_2320;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bx_V8_phi_reg_910_pp0_iter1_reg <= bx_V8_phi_reg_910;
        icmp_ln609_reg_2287 <= icmp_ln609_fu_1122_p2;
        icmp_ln609_reg_2287_pp0_iter1_reg <= icmp_ln609_reg_2287;
        icmp_ln615_reg_2291 <= icmp_ln615_fu_1128_p2;
        p_phi_reg_898_pp0_iter1_reg <= p_phi_reg_898;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln609_reg_2287 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bx_V8_rewind_reg_773 <= bx_V8_phi_reg_910;
        nInputs_0_V_rewind_reg_745 <= nInputs_0_V_phi_reg_886;
        nInputs_1_V_02_rewind_reg_817 <= ap_phi_mux_nInputs_1_V_3_phi_fu_996_p6;
        nInputs_1_V_rewind_reg_731 <= nInputs_1_V_phi_reg_874;
        nInputs_2_V_01_rewind_reg_802 <= ap_phi_mux_nInputs_2_V_3_phi_fu_982_p6;
        nInputs_2_V_1_rewind_reg_717 <= nInputs_2_V_1_phi_reg_862;
        nInputs_2_V_63_rewind_reg_832 <= ap_phi_mux_nInputs_2_V_14_phi_fu_1010_p6;
        p_rewind_reg_759 <= p_phi_reg_898;
        p_what2_5_rewind_reg_787 <= ap_phi_mux_p_what2_s_phi_fu_1024_p6;
    end
end

always @ (posedge ap_clk) begin
    if (((~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (bx_o_V_1_vld_reg == 1'b0) & (bx_o_V_1_vld_in == 1'b1)) | (~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (1'b1 == 1'b1) & (bx_o_V_1_vld_in == 1'b1) & (bx_o_V_1_vld_reg == 1'b1)))) begin
        bx_o_V_1_data_reg <= bx_V8_phi_reg_910_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_reg_2282 <= i_fu_1112_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln615_fu_1128_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln643_reg_2300 <= icmp_ln643_fu_1152_p2;
        noStubsLeft_reg_2295 <= noStubsLeft_fu_1134_p2;
        or_ln631_reg_2325 <= or_ln631_fu_1321_p2;
        trunc_ln57_reg_2320 <= trunc_ln57_fu_1173_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln615_reg_2291_pp0_iter2_reg == 1'd0) & (noStubsLeft_reg_2295_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (noStubsLeft_reg_2295_pp0_iter2_reg == 1'd0) & (icmp_ln615_reg_2291_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1)))) begin
        p_Val2_s_fu_298 <= stub_data_V_3_fu_1368_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln615_reg_2291_pp0_iter2_reg == 1'd0))) begin
        stub_data_V_3_reg_2335 <= stub_data_V_3_fu_1368_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (noStubsLeft_reg_2295_pp0_iter3_reg == 1'd0) & (icmp_ln615_reg_2291_pp0_iter3_reg == 1'd0) & (or_ln631_reg_2325_pp0_iter3_reg == 1'd1))) begin
        tmp_13_reg_2357 <= phiCorr_V_2_fu_1493_p3[32'd14];
        trunc_ln214_reg_2362 <= trunc_ln214_fu_1509_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (noStubsLeft_fu_1134_p2 == 1'd0) & (icmp_ln615_fu_1128_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trunc_ln301_reg_2329 <= trunc_ln301_fu_1343_p1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln609_reg_2287_pp0_iter4_reg == 1'd1) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to4 = 1'b1;
    end else begin
        ap_idle_pp0_0to4 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln609_reg_2287 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_bx_V8_rewind_phi_fu_777_p6 = bx_V8_phi_reg_910;
    end else begin
        ap_phi_mux_bx_V8_rewind_phi_fu_777_p6 = bx_V8_rewind_reg_773;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_419)) begin
        if ((icmp_ln609_reg_2287 == 1'd1)) begin
            ap_phi_mux_do_init_phi_fu_705_p6 = 1'd1;
        end else if ((icmp_ln609_reg_2287 == 1'd0)) begin
            ap_phi_mux_do_init_phi_fu_705_p6 = 1'd0;
        end else begin
            ap_phi_mux_do_init_phi_fu_705_p6 = do_init_reg_701;
        end
    end else begin
        ap_phi_mux_do_init_phi_fu_705_p6 = do_init_reg_701;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln609_reg_2287 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_nInputs_0_V_rewind_phi_fu_749_p6 = nInputs_0_V_phi_reg_886;
    end else begin
        ap_phi_mux_nInputs_0_V_rewind_phi_fu_749_p6 = nInputs_0_V_rewind_reg_745;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln609_reg_2287 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_nInputs_1_V_02_rewind_phi_fu_821_p6 = ap_phi_mux_nInputs_1_V_3_phi_fu_996_p6;
    end else begin
        ap_phi_mux_nInputs_1_V_02_rewind_phi_fu_821_p6 = nInputs_1_V_02_rewind_reg_817;
    end
end

always @ (*) begin
    if ((((icmp_ln615_fu_1128_p2 == 1'd0) & (noStubsLeft_fu_1134_p2 == 1'd1)) | ((noStubsLeft_fu_1134_p2 == 1'd0) & (icmp_ln615_fu_1128_p2 == 1'd0)))) begin
        ap_phi_mux_nInputs_1_V_3_phi_fu_996_p6 = nInputs_2_V_17_fu_1279_p3;
    end else if ((icmp_ln615_fu_1128_p2 == 1'd1)) begin
        ap_phi_mux_nInputs_1_V_3_phi_fu_996_p6 = ap_phi_reg_pp0_iter1_nInputs_1_V_02_reg_958;
    end else begin
        ap_phi_mux_nInputs_1_V_3_phi_fu_996_p6 = ap_phi_reg_pp0_iter1_nInputs_1_V_3_reg_992;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln609_reg_2287 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_nInputs_1_V_rewind_phi_fu_735_p6 = nInputs_1_V_phi_reg_874;
    end else begin
        ap_phi_mux_nInputs_1_V_rewind_phi_fu_735_p6 = nInputs_1_V_rewind_reg_731;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln609_reg_2287 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_nInputs_2_V_01_rewind_phi_fu_806_p6 = ap_phi_mux_nInputs_2_V_3_phi_fu_982_p6;
    end else begin
        ap_phi_mux_nInputs_2_V_01_rewind_phi_fu_806_p6 = nInputs_2_V_01_rewind_reg_802;
    end
end

always @ (*) begin
    if ((((icmp_ln615_fu_1128_p2 == 1'd0) & (noStubsLeft_fu_1134_p2 == 1'd1)) | ((noStubsLeft_fu_1134_p2 == 1'd0) & (icmp_ln615_fu_1128_p2 == 1'd0)))) begin
        ap_phi_mux_nInputs_2_V_14_phi_fu_1010_p6 = nInputs_2_V_18_fu_1289_p3;
    end else if ((icmp_ln615_fu_1128_p2 == 1'd1)) begin
        ap_phi_mux_nInputs_2_V_14_phi_fu_1010_p6 = ap_phi_reg_pp0_iter1_nInputs_2_V_63_reg_948;
    end else begin
        ap_phi_mux_nInputs_2_V_14_phi_fu_1010_p6 = ap_phi_reg_pp0_iter1_nInputs_2_V_14_reg_1006;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln609_reg_2287 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_nInputs_2_V_1_rewind_phi_fu_721_p6 = nInputs_2_V_1_phi_reg_862;
    end else begin
        ap_phi_mux_nInputs_2_V_1_rewind_phi_fu_721_p6 = nInputs_2_V_1_rewind_reg_717;
    end
end

always @ (*) begin
    if ((((icmp_ln615_fu_1128_p2 == 1'd0) & (noStubsLeft_fu_1134_p2 == 1'd1)) | ((noStubsLeft_fu_1134_p2 == 1'd0) & (icmp_ln615_fu_1128_p2 == 1'd0)))) begin
        ap_phi_mux_nInputs_2_V_3_phi_fu_982_p6 = nInputs_2_V_16_fu_1269_p3;
    end else if ((icmp_ln615_fu_1128_p2 == 1'd1)) begin
        ap_phi_mux_nInputs_2_V_3_phi_fu_982_p6 = ap_phi_reg_pp0_iter1_nInputs_2_V_01_reg_968;
    end else begin
        ap_phi_mux_nInputs_2_V_3_phi_fu_982_p6 = ap_phi_reg_pp0_iter1_nInputs_2_V_3_reg_978;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln609_reg_2287 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_nInputs_2_V_63_rewind_phi_fu_836_p6 = ap_phi_mux_nInputs_2_V_14_phi_fu_1010_p6;
    end else begin
        ap_phi_mux_nInputs_2_V_63_rewind_phi_fu_836_p6 = nInputs_2_V_63_rewind_reg_832;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((icmp_ln609_reg_2287_pp0_iter1_reg == 1'd1)) begin
            ap_phi_mux_p_06_phi_fu_928_p6 = 7'd0;
        end else if ((icmp_ln609_reg_2287_pp0_iter1_reg == 1'd0)) begin
            ap_phi_mux_p_06_phi_fu_928_p6 = p_050_2_i_reg_1034;
        end else begin
            ap_phi_mux_p_06_phi_fu_928_p6 = p_06_reg_924;
        end
    end else begin
        ap_phi_mux_p_06_phi_fu_928_p6 = p_06_reg_924;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln609_reg_2287 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_p_rewind_phi_fu_763_p6 = p_phi_reg_898;
    end else begin
        ap_phi_mux_p_rewind_phi_fu_763_p6 = p_rewind_reg_759;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln609_reg_2287 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_p_what2_5_rewind_phi_fu_791_p6 = ap_phi_mux_p_what2_s_phi_fu_1024_p6;
    end else begin
        ap_phi_mux_p_what2_5_rewind_phi_fu_791_p6 = p_what2_5_rewind_reg_787;
    end
end

always @ (*) begin
    if ((((icmp_ln615_fu_1128_p2 == 1'd0) & (noStubsLeft_fu_1134_p2 == 1'd1)) | ((noStubsLeft_fu_1134_p2 == 1'd0) & (icmp_ln615_fu_1128_p2 == 1'd0)))) begin
        ap_phi_mux_p_what2_s_phi_fu_1024_p6 = hasStubs_V_1_fu_1299_p3;
    end else if ((icmp_ln615_fu_1128_p2 == 1'd1)) begin
        ap_phi_mux_p_what2_s_phi_fu_1024_p6 = ap_phi_reg_pp0_iter1_p_what2_5_reg_938;
    end else begin
        ap_phi_mux_p_what2_s_phi_fu_1024_p6 = ap_phi_reg_pp0_iter1_p_what2_s_reg_1020;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_419)) begin
        if ((icmp_ln609_reg_2287 == 1'd1)) begin
            ap_phi_mux_val_assign7_phi_fu_851_p6 = 8'd255;
        end else if ((icmp_ln609_reg_2287 == 1'd0)) begin
            ap_phi_mux_val_assign7_phi_fu_851_p6 = i_reg_2282;
        end else begin
            ap_phi_mux_val_assign7_phi_fu_851_p6 = val_assign7_reg_847;
        end
    end else begin
        ap_phi_mux_val_assign7_phi_fu_851_p6 = val_assign7_reg_847;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln609_fu_1122_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to4 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((bx_o_V_1_vld_reg == 1'b0) | ((1'b1 == 1'b1) & (bx_o_V_1_vld_reg == 1'b1)))) begin
        bx_o_V_1_ack_in = 1'b1;
    end else begin
        bx_o_V_1_ack_in = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln609_reg_2287_pp0_iter3_reg == 1'd1) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        bx_o_V_1_vld_in = 1'b1;
    end else begin
        bx_o_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        inputStubs_0_dataarray_data_V_ce0 = 1'b1;
    end else begin
        inputStubs_0_dataarray_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        inputStubs_1_dataarray_data_V_ce0 = 1'b1;
    end else begin
        inputStubs_1_dataarray_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        inputStubs_2_dataarray_data_V_ce0 = 1'b1;
    end else begin
        inputStubs_2_dataarray_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        lut_1_ce0 = 1'b1;
    end else begin
        lut_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1)))) begin
        lut_ce0 = 1'b1;
    end else begin
        lut_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        memoriesAS_0_dataarray_data_V_ce0 = 1'b1;
    end else begin
        memoriesAS_0_dataarray_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (noStubsLeft_reg_2295_pp0_iter4_reg == 1'd0) & (icmp_ln615_reg_2291_pp0_iter4_reg == 1'd0) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        memoriesAS_0_dataarray_data_V_we0 = 1'b1;
    end else begin
        memoriesAS_0_dataarray_data_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        memoriesTEI_0_0_dataarray_data_V_ce0 = 1'b1;
    end else begin
        memoriesTEI_0_0_dataarray_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln_fu_1613_p4 == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln792_fu_1666_p2 == 1'd0) & (p_Result_s_fu_1607_p2 == 1'd0) & (icmp_ln756_fu_1585_p2 == 1'd0) & (noStubsLeft_reg_2295_pp0_iter4_reg == 1'd0) & (icmp_ln615_reg_2291_pp0_iter4_reg == 1'd0) & (or_ln631_reg_2325_pp0_iter4_reg == 1'd1) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        memoriesTEI_0_0_dataarray_data_V_we0 = 1'b1;
    end else begin
        memoriesTEI_0_0_dataarray_data_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        memoriesTEI_0_1_dataarray_data_V_ce0 = 1'b1;
    end else begin
        memoriesTEI_0_1_dataarray_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln_fu_1613_p4 == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln792_1_fu_1776_p2 == 1'd0) & (p_Result_s_fu_1607_p2 == 1'd0) & (icmp_ln756_fu_1585_p2 == 1'd0) & (noStubsLeft_reg_2295_pp0_iter4_reg == 1'd0) & (icmp_ln615_reg_2291_pp0_iter4_reg == 1'd0) & (or_ln631_reg_2325_pp0_iter4_reg == 1'd1) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        memoriesTEI_0_1_dataarray_data_V_we0 = 1'b1;
    end else begin
        memoriesTEI_0_1_dataarray_data_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        memoriesTEI_0_2_dataarray_data_V_ce0 = 1'b1;
    end else begin
        memoriesTEI_0_2_dataarray_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln_fu_1613_p4 == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln792_2_fu_1876_p2 == 1'd0) & (p_Result_s_fu_1607_p2 == 1'd0) & (icmp_ln756_fu_1585_p2 == 1'd0) & (noStubsLeft_reg_2295_pp0_iter4_reg == 1'd0) & (icmp_ln615_reg_2291_pp0_iter4_reg == 1'd0) & (or_ln631_reg_2325_pp0_iter4_reg == 1'd1) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        memoriesTEI_0_2_dataarray_data_V_we0 = 1'b1;
    end else begin
        memoriesTEI_0_2_dataarray_data_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        memoriesTEI_0_3_dataarray_data_V_ce0 = 1'b1;
    end else begin
        memoriesTEI_0_3_dataarray_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln_fu_1613_p4 == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln792_4_fu_1982_p2 == 1'd0) & (p_Result_s_fu_1607_p2 == 1'd0) & (icmp_ln756_fu_1585_p2 == 1'd0) & (noStubsLeft_reg_2295_pp0_iter4_reg == 1'd0) & (icmp_ln615_reg_2291_pp0_iter4_reg == 1'd0) & (or_ln631_reg_2325_pp0_iter4_reg == 1'd1) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        memoriesTEI_0_3_dataarray_data_V_we0 = 1'b1;
    end else begin
        memoriesTEI_0_3_dataarray_data_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        memoriesTEI_1_0_dataarray_data_V_ce0 = 1'b1;
    end else begin
        memoriesTEI_1_0_dataarray_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln_fu_1613_p4 == 2'd2) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln792_fu_1666_p2 == 1'd0) & (p_Result_s_fu_1607_p2 == 1'd0) & (icmp_ln756_fu_1585_p2 == 1'd0) & (noStubsLeft_reg_2295_pp0_iter4_reg == 1'd0) & (icmp_ln615_reg_2291_pp0_iter4_reg == 1'd0) & (or_ln631_reg_2325_pp0_iter4_reg == 1'd1) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        memoriesTEI_1_0_dataarray_data_V_we0 = 1'b1;
    end else begin
        memoriesTEI_1_0_dataarray_data_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        memoriesTEI_1_1_dataarray_data_V_ce0 = 1'b1;
    end else begin
        memoriesTEI_1_1_dataarray_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln_fu_1613_p4 == 2'd2) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln792_1_fu_1776_p2 == 1'd0) & (p_Result_s_fu_1607_p2 == 1'd0) & (icmp_ln756_fu_1585_p2 == 1'd0) & (noStubsLeft_reg_2295_pp0_iter4_reg == 1'd0) & (icmp_ln615_reg_2291_pp0_iter4_reg == 1'd0) & (or_ln631_reg_2325_pp0_iter4_reg == 1'd1) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        memoriesTEI_1_1_dataarray_data_V_we0 = 1'b1;
    end else begin
        memoriesTEI_1_1_dataarray_data_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        memoriesTEI_1_2_dataarray_data_V_ce0 = 1'b1;
    end else begin
        memoriesTEI_1_2_dataarray_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln_fu_1613_p4 == 2'd2) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln792_2_fu_1876_p2 == 1'd0) & (p_Result_s_fu_1607_p2 == 1'd0) & (icmp_ln756_fu_1585_p2 == 1'd0) & (noStubsLeft_reg_2295_pp0_iter4_reg == 1'd0) & (icmp_ln615_reg_2291_pp0_iter4_reg == 1'd0) & (or_ln631_reg_2325_pp0_iter4_reg == 1'd1) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        memoriesTEI_1_2_dataarray_data_V_we0 = 1'b1;
    end else begin
        memoriesTEI_1_2_dataarray_data_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        memoriesTEI_1_3_dataarray_data_V_ce0 = 1'b1;
    end else begin
        memoriesTEI_1_3_dataarray_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln_fu_1613_p4 == 2'd2) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln792_4_fu_1982_p2 == 1'd0) & (p_Result_s_fu_1607_p2 == 1'd0) & (icmp_ln756_fu_1585_p2 == 1'd0) & (noStubsLeft_reg_2295_pp0_iter4_reg == 1'd0) & (icmp_ln615_reg_2291_pp0_iter4_reg == 1'd0) & (or_ln631_reg_2325_pp0_iter4_reg == 1'd1) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        memoriesTEI_1_3_dataarray_data_V_we0 = 1'b1;
    end else begin
        memoriesTEI_1_3_dataarray_data_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        memoriesTEI_2_0_dataarray_data_V_ce0 = 1'b1;
    end else begin
        memoriesTEI_2_0_dataarray_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln_fu_1613_p4 == 2'd3) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln792_fu_1666_p2 == 1'd0) & (p_Result_s_fu_1607_p2 == 1'd0) & (icmp_ln756_fu_1585_p2 == 1'd0) & (noStubsLeft_reg_2295_pp0_iter4_reg == 1'd0) & (icmp_ln615_reg_2291_pp0_iter4_reg == 1'd0) & (or_ln631_reg_2325_pp0_iter4_reg == 1'd1) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        memoriesTEI_2_0_dataarray_data_V_we0 = 1'b1;
    end else begin
        memoriesTEI_2_0_dataarray_data_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        memoriesTEI_2_1_dataarray_data_V_ce0 = 1'b1;
    end else begin
        memoriesTEI_2_1_dataarray_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln_fu_1613_p4 == 2'd3) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln792_1_fu_1776_p2 == 1'd0) & (p_Result_s_fu_1607_p2 == 1'd0) & (icmp_ln756_fu_1585_p2 == 1'd0) & (noStubsLeft_reg_2295_pp0_iter4_reg == 1'd0) & (icmp_ln615_reg_2291_pp0_iter4_reg == 1'd0) & (or_ln631_reg_2325_pp0_iter4_reg == 1'd1) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        memoriesTEI_2_1_dataarray_data_V_we0 = 1'b1;
    end else begin
        memoriesTEI_2_1_dataarray_data_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        memoriesTEI_2_2_dataarray_data_V_ce0 = 1'b1;
    end else begin
        memoriesTEI_2_2_dataarray_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln_fu_1613_p4 == 2'd3) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln792_2_fu_1876_p2 == 1'd0) & (p_Result_s_fu_1607_p2 == 1'd0) & (icmp_ln756_fu_1585_p2 == 1'd0) & (noStubsLeft_reg_2295_pp0_iter4_reg == 1'd0) & (icmp_ln615_reg_2291_pp0_iter4_reg == 1'd0) & (or_ln631_reg_2325_pp0_iter4_reg == 1'd1) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        memoriesTEI_2_2_dataarray_data_V_we0 = 1'b1;
    end else begin
        memoriesTEI_2_2_dataarray_data_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        memoriesTEI_2_3_dataarray_data_V_ce0 = 1'b1;
    end else begin
        memoriesTEI_2_3_dataarray_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln_fu_1613_p4 == 2'd3) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln792_4_fu_1982_p2 == 1'd0) & (p_Result_s_fu_1607_p2 == 1'd0) & (icmp_ln756_fu_1585_p2 == 1'd0) & (noStubsLeft_reg_2295_pp0_iter4_reg == 1'd0) & (icmp_ln615_reg_2291_pp0_iter4_reg == 1'd0) & (or_ln631_reg_2325_pp0_iter4_reg == 1'd1) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        memoriesTEI_2_3_dataarray_data_V_we0 = 1'b1;
    end else begin
        memoriesTEI_2_3_dataarray_data_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        memoriesTEI_3_0_dataarray_data_V_ce0 = 1'b1;
    end else begin
        memoriesTEI_3_0_dataarray_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln_fu_1613_p4 == 2'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln792_fu_1666_p2 == 1'd0) & (p_Result_s_fu_1607_p2 == 1'd0) & (icmp_ln756_fu_1585_p2 == 1'd0) & (noStubsLeft_reg_2295_pp0_iter4_reg == 1'd0) & (icmp_ln615_reg_2291_pp0_iter4_reg == 1'd0) & (or_ln631_reg_2325_pp0_iter4_reg == 1'd1) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        memoriesTEI_3_0_dataarray_data_V_we0 = 1'b1;
    end else begin
        memoriesTEI_3_0_dataarray_data_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        memoriesTEI_3_1_dataarray_data_V_ce0 = 1'b1;
    end else begin
        memoriesTEI_3_1_dataarray_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln_fu_1613_p4 == 2'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln792_1_fu_1776_p2 == 1'd0) & (p_Result_s_fu_1607_p2 == 1'd0) & (icmp_ln756_fu_1585_p2 == 1'd0) & (noStubsLeft_reg_2295_pp0_iter4_reg == 1'd0) & (icmp_ln615_reg_2291_pp0_iter4_reg == 1'd0) & (or_ln631_reg_2325_pp0_iter4_reg == 1'd1) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        memoriesTEI_3_1_dataarray_data_V_we0 = 1'b1;
    end else begin
        memoriesTEI_3_1_dataarray_data_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        memoriesTEI_3_2_dataarray_data_V_ce0 = 1'b1;
    end else begin
        memoriesTEI_3_2_dataarray_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln_fu_1613_p4 == 2'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln792_2_fu_1876_p2 == 1'd0) & (p_Result_s_fu_1607_p2 == 1'd0) & (icmp_ln756_fu_1585_p2 == 1'd0) & (noStubsLeft_reg_2295_pp0_iter4_reg == 1'd0) & (icmp_ln615_reg_2291_pp0_iter4_reg == 1'd0) & (or_ln631_reg_2325_pp0_iter4_reg == 1'd1) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        memoriesTEI_3_2_dataarray_data_V_we0 = 1'b1;
    end else begin
        memoriesTEI_3_2_dataarray_data_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        memoriesTEI_3_3_dataarray_data_V_ce0 = 1'b1;
    end else begin
        memoriesTEI_3_3_dataarray_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln_fu_1613_p4 == 2'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln792_4_fu_1982_p2 == 1'd0) & (p_Result_s_fu_1607_p2 == 1'd0) & (icmp_ln756_fu_1585_p2 == 1'd0) & (noStubsLeft_reg_2295_pp0_iter4_reg == 1'd0) & (icmp_ln615_reg_2291_pp0_iter4_reg == 1'd0) & (or_ln631_reg_2325_pp0_iter4_reg == 1'd1) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        memoriesTEI_3_3_dataarray_data_V_we0 = 1'b1;
    end else begin
        memoriesTEI_3_3_dataarray_data_V_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((ap_reset_idle_pp0 == 1'b0)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_reset_idle_pp0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln792_fu_1631_p2 = ($signed(shl_ln_fu_1623_p3) + $signed(4'd12));

assign addrCountTEI_0_0_V_2_fu_1720_p2 = (tmp_1_fu_1690_p6 + 7'd1);

assign addrCountTEI_0_1_V_2_fu_1830_p2 = (tmp_4_fu_1800_p6 + 7'd1);

assign addrCountTEI_0_2_V_2_fu_1930_p2 = (tmp_5_fu_1900_p6 + 7'd1);

assign addrCountTEI_0_3_V_2_fu_2036_p2 = (tmp_7_fu_2006_p6 + 7'd1);

assign and_ln631_fu_1315_p2 = (xor_ln631_fu_1309_p2 & resetNext_fu_1189_p2);

assign and_ln792_1_fu_1770_p2 = (shl_ln792_1_fu_1654_p2 & phi_ln792_1_fu_1756_p6);

assign and_ln792_2_fu_1870_p2 = (shl_ln792_1_fu_1654_p2 & phi_ln792_2_fu_1856_p6);

assign and_ln792_3_fu_1976_p2 = (shl_ln792_1_fu_1654_p2 & select_ln792_1_fu_1968_p3);

assign and_ln792_fu_1660_p2 = (shl_ln792_1_fu_1654_p2 & select_ln792_fu_1643_p3);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((bx_o_V_1_ack_in == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((bx_o_V_1_ack_in == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((bx_o_V_1_ack_in == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b1));
end

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state7_pp0_stage0_iter5 = (bx_o_V_1_ack_in == 1'b0);
end

always @ (*) begin
    ap_condition_419 = ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_49 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_572 = ((trunc_ln_fu_1613_p4 == 2'd1) & (icmp_ln792_fu_1666_p2 == 1'd0) & (p_Result_s_fu_1607_p2 == 1'd0) & (icmp_ln756_fu_1585_p2 == 1'd0) & (noStubsLeft_reg_2295_pp0_iter4_reg == 1'd0) & (icmp_ln615_reg_2291_pp0_iter4_reg == 1'd0) & (or_ln631_reg_2325_pp0_iter4_reg == 1'd1));
end

always @ (*) begin
    ap_condition_581 = ((trunc_ln_fu_1613_p4 == 2'd1) & (icmp_ln792_1_fu_1776_p2 == 1'd0) & (p_Result_s_fu_1607_p2 == 1'd0) & (icmp_ln756_fu_1585_p2 == 1'd0) & (noStubsLeft_reg_2295_pp0_iter4_reg == 1'd0) & (icmp_ln615_reg_2291_pp0_iter4_reg == 1'd0) & (or_ln631_reg_2325_pp0_iter4_reg == 1'd1));
end

always @ (*) begin
    ap_condition_587 = ((trunc_ln_fu_1613_p4 == 2'd1) & (icmp_ln792_2_fu_1876_p2 == 1'd0) & (p_Result_s_fu_1607_p2 == 1'd0) & (icmp_ln756_fu_1585_p2 == 1'd0) & (noStubsLeft_reg_2295_pp0_iter4_reg == 1'd0) & (icmp_ln615_reg_2291_pp0_iter4_reg == 1'd0) & (or_ln631_reg_2325_pp0_iter4_reg == 1'd1));
end

always @ (*) begin
    ap_condition_593 = ((trunc_ln_fu_1613_p4 == 2'd1) & (icmp_ln792_4_fu_1982_p2 == 1'd0) & (p_Result_s_fu_1607_p2 == 1'd0) & (icmp_ln756_fu_1585_p2 == 1'd0) & (noStubsLeft_reg_2295_pp0_iter4_reg == 1'd0) & (icmp_ln615_reg_2291_pp0_iter4_reg == 1'd0) & (or_ln631_reg_2325_pp0_iter4_reg == 1'd1));
end

always @ (*) begin
    ap_condition_600 = ((trunc_ln_fu_1613_p4 == 2'd2) & (icmp_ln792_fu_1666_p2 == 1'd0) & (p_Result_s_fu_1607_p2 == 1'd0) & (icmp_ln756_fu_1585_p2 == 1'd0) & (noStubsLeft_reg_2295_pp0_iter4_reg == 1'd0) & (icmp_ln615_reg_2291_pp0_iter4_reg == 1'd0) & (or_ln631_reg_2325_pp0_iter4_reg == 1'd1));
end

always @ (*) begin
    ap_condition_606 = ((trunc_ln_fu_1613_p4 == 2'd2) & (icmp_ln792_1_fu_1776_p2 == 1'd0) & (p_Result_s_fu_1607_p2 == 1'd0) & (icmp_ln756_fu_1585_p2 == 1'd0) & (noStubsLeft_reg_2295_pp0_iter4_reg == 1'd0) & (icmp_ln615_reg_2291_pp0_iter4_reg == 1'd0) & (or_ln631_reg_2325_pp0_iter4_reg == 1'd1));
end

always @ (*) begin
    ap_condition_611 = ((trunc_ln_fu_1613_p4 == 2'd2) & (icmp_ln792_2_fu_1876_p2 == 1'd0) & (p_Result_s_fu_1607_p2 == 1'd0) & (icmp_ln756_fu_1585_p2 == 1'd0) & (noStubsLeft_reg_2295_pp0_iter4_reg == 1'd0) & (icmp_ln615_reg_2291_pp0_iter4_reg == 1'd0) & (or_ln631_reg_2325_pp0_iter4_reg == 1'd1));
end

always @ (*) begin
    ap_condition_616 = ((trunc_ln_fu_1613_p4 == 2'd2) & (icmp_ln792_4_fu_1982_p2 == 1'd0) & (p_Result_s_fu_1607_p2 == 1'd0) & (icmp_ln756_fu_1585_p2 == 1'd0) & (noStubsLeft_reg_2295_pp0_iter4_reg == 1'd0) & (icmp_ln615_reg_2291_pp0_iter4_reg == 1'd0) & (or_ln631_reg_2325_pp0_iter4_reg == 1'd1));
end

always @ (*) begin
    ap_condition_623 = ((trunc_ln_fu_1613_p4 == 2'd3) & (icmp_ln792_fu_1666_p2 == 1'd0) & (p_Result_s_fu_1607_p2 == 1'd0) & (icmp_ln756_fu_1585_p2 == 1'd0) & (noStubsLeft_reg_2295_pp0_iter4_reg == 1'd0) & (icmp_ln615_reg_2291_pp0_iter4_reg == 1'd0) & (or_ln631_reg_2325_pp0_iter4_reg == 1'd1));
end

always @ (*) begin
    ap_condition_629 = ((trunc_ln_fu_1613_p4 == 2'd3) & (icmp_ln792_1_fu_1776_p2 == 1'd0) & (p_Result_s_fu_1607_p2 == 1'd0) & (icmp_ln756_fu_1585_p2 == 1'd0) & (noStubsLeft_reg_2295_pp0_iter4_reg == 1'd0) & (icmp_ln615_reg_2291_pp0_iter4_reg == 1'd0) & (or_ln631_reg_2325_pp0_iter4_reg == 1'd1));
end

always @ (*) begin
    ap_condition_634 = ((trunc_ln_fu_1613_p4 == 2'd3) & (icmp_ln792_2_fu_1876_p2 == 1'd0) & (p_Result_s_fu_1607_p2 == 1'd0) & (icmp_ln756_fu_1585_p2 == 1'd0) & (noStubsLeft_reg_2295_pp0_iter4_reg == 1'd0) & (icmp_ln615_reg_2291_pp0_iter4_reg == 1'd0) & (or_ln631_reg_2325_pp0_iter4_reg == 1'd1));
end

always @ (*) begin
    ap_condition_639 = ((trunc_ln_fu_1613_p4 == 2'd3) & (icmp_ln792_4_fu_1982_p2 == 1'd0) & (p_Result_s_fu_1607_p2 == 1'd0) & (icmp_ln756_fu_1585_p2 == 1'd0) & (noStubsLeft_reg_2295_pp0_iter4_reg == 1'd0) & (icmp_ln615_reg_2291_pp0_iter4_reg == 1'd0) & (or_ln631_reg_2325_pp0_iter4_reg == 1'd1));
end

always @ (*) begin
    ap_condition_646 = ((trunc_ln_fu_1613_p4 == 2'd0) & (icmp_ln792_fu_1666_p2 == 1'd0) & (p_Result_s_fu_1607_p2 == 1'd0) & (icmp_ln756_fu_1585_p2 == 1'd0) & (noStubsLeft_reg_2295_pp0_iter4_reg == 1'd0) & (icmp_ln615_reg_2291_pp0_iter4_reg == 1'd0) & (or_ln631_reg_2325_pp0_iter4_reg == 1'd1));
end

always @ (*) begin
    ap_condition_652 = ((trunc_ln_fu_1613_p4 == 2'd0) & (icmp_ln792_1_fu_1776_p2 == 1'd0) & (p_Result_s_fu_1607_p2 == 1'd0) & (icmp_ln756_fu_1585_p2 == 1'd0) & (noStubsLeft_reg_2295_pp0_iter4_reg == 1'd0) & (icmp_ln615_reg_2291_pp0_iter4_reg == 1'd0) & (or_ln631_reg_2325_pp0_iter4_reg == 1'd1));
end

always @ (*) begin
    ap_condition_657 = ((trunc_ln_fu_1613_p4 == 2'd0) & (icmp_ln792_2_fu_1876_p2 == 1'd0) & (p_Result_s_fu_1607_p2 == 1'd0) & (icmp_ln756_fu_1585_p2 == 1'd0) & (noStubsLeft_reg_2295_pp0_iter4_reg == 1'd0) & (icmp_ln615_reg_2291_pp0_iter4_reg == 1'd0) & (or_ln631_reg_2325_pp0_iter4_reg == 1'd1));
end

always @ (*) begin
    ap_condition_662 = ((trunc_ln_fu_1613_p4 == 2'd0) & (icmp_ln792_4_fu_1982_p2 == 1'd0) & (p_Result_s_fu_1607_p2 == 1'd0) & (icmp_ln756_fu_1585_p2 == 1'd0) & (noStubsLeft_reg_2295_pp0_iter4_reg == 1'd0) & (icmp_ln615_reg_2291_pp0_iter4_reg == 1'd0) & (or_ln631_reg_2325_pp0_iter4_reg == 1'd1));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_phi_reg_pp0_iter0_bx_V8_phi_reg_910 = 'bx;

assign ap_phi_reg_pp0_iter0_nInputs_0_V_phi_reg_886 = 'bx;

assign ap_phi_reg_pp0_iter0_nInputs_1_V_02_reg_958 = 'bx;

assign ap_phi_reg_pp0_iter0_nInputs_1_V_phi_reg_874 = 'bx;

assign ap_phi_reg_pp0_iter0_nInputs_2_V_01_reg_968 = 'bx;

assign ap_phi_reg_pp0_iter0_nInputs_2_V_1_phi_reg_862 = 'bx;

assign ap_phi_reg_pp0_iter0_nInputs_2_V_63_reg_948 = 'bx;

assign ap_phi_reg_pp0_iter0_p_phi_reg_898 = 'bx;

assign ap_phi_reg_pp0_iter0_p_what2_5_reg_938 = 'bx;

assign ap_phi_reg_pp0_iter1_nInputs_1_V_3_reg_992 = 'bx;

assign ap_phi_reg_pp0_iter1_nInputs_2_V_14_reg_1006 = 'bx;

assign ap_phi_reg_pp0_iter1_nInputs_2_V_3_reg_978 = 'bx;

assign ap_phi_reg_pp0_iter1_p_050_2_i_reg_1034 = 'bx;

assign ap_phi_reg_pp0_iter1_p_what2_s_reg_1020 = 'bx;

assign bend_V_fu_1386_p1 = stub_data_V_3_fu_1368_p3[2:0];

assign bx_o_V = bx_o_V_1_data_reg;

assign bx_o_V_ap_vld = bx_o_V_1_vld_reg;

assign hasStubs_V_1_fu_1299_p3 = ((noStubsLeft_fu_1134_p2[0:0] === 1'b1) ? 3'd0 : p_Result_1_fu_1201_p4);

assign i_fu_1112_p2 = (8'd1 + ap_phi_mux_val_assign7_phi_fu_851_p6);

assign icmp_ln609_fu_1122_p2 = ((trunc_ln609_fu_1118_p1 == 7'd107) ? 1'b1 : 1'b0);

assign icmp_ln615_fu_1128_p2 = ((val_assign7_reg_847 == 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln643_fu_1152_p2 = ((mem_index_fu_1144_p3 < 32'd3) ? 1'b1 : 1'b0);

assign icmp_ln701_1_fu_1231_p2 = ((trunc_ln57_fu_1173_p1 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln701_fu_1217_p2 = ((trunc_ln57_fu_1173_p1 == 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln756_fu_1585_p2 = ((lut_q0 == 11'd2047) ? 1'b1 : 1'b0);

assign icmp_ln792_1_fu_1776_p2 = ((and_ln792_1_fu_1770_p2 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln792_2_fu_1876_p2 = ((and_ln792_2_fu_1870_p2 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln792_3_fu_1962_p2 = ((or_ln792_fu_1956_p2 == 4'd7) ? 1'b1 : 1'b0);

assign icmp_ln792_4_fu_1982_p2 = ((and_ln792_3_fu_1976_p2 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln792_6_fu_1637_p2 = ((trunc_ln_fu_1613_p4 == 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln792_fu_1666_p2 = ((and_ln792_fu_1660_p2 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln841_1_fu_1081_p2 = ((nInputs_1_V_fu_1072_p3 != 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln841_2_fu_1096_p2 = ((nInputs_2_V_1_fu_1087_p3 != 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln841_fu_1066_p2 = ((nInputs_0_V_fu_1057_p3 != 7'd0) ? 1'b1 : 1'b0);

assign indexr_V_fu_1435_p4 = {{ret_V_fu_1390_p2[6:3]}};

assign indexz_V_fu_1429_p2 = (tmp_12_fu_1419_p4 ^ 7'd64);

assign inputStubs_0_dataarray_data_V_address0 = zext_ln57_fu_1166_p1;

assign inputStubs_1_dataarray_data_V_address0 = zext_ln57_fu_1166_p1;

assign inputStubs_2_dataarray_data_V_address0 = zext_ln57_fu_1166_p1;

assign iphivm_V_fu_1541_p4 = {{phiCorr_V_fu_1525_p3[13:9]}};

assign lut_1_address0 = zext_ln544_fu_1414_p1;

assign lut_address0 = zext_ln357_fu_1453_p1;


always @ (zext_ln640_fu_1140_p1) begin
    if (zext_ln640_fu_1140_p1[0] == 1'b1) begin
        mem_index_fu_1144_p3 = 32'd0;
    end else if (zext_ln640_fu_1140_p1[1] == 1'b1) begin
        mem_index_fu_1144_p3 = 32'd1;
    end else if (zext_ln640_fu_1140_p1[2] == 1'b1) begin
        mem_index_fu_1144_p3 = 32'd2;
    end else if (zext_ln640_fu_1140_p1[3] == 1'b1) begin
        mem_index_fu_1144_p3 = 32'd3;
    end else if (zext_ln640_fu_1140_p1[4] == 1'b1) begin
        mem_index_fu_1144_p3 = 32'd4;
    end else if (zext_ln640_fu_1140_p1[5] == 1'b1) begin
        mem_index_fu_1144_p3 = 32'd5;
    end else if (zext_ln640_fu_1140_p1[6] == 1'b1) begin
        mem_index_fu_1144_p3 = 32'd6;
    end else if (zext_ln640_fu_1140_p1[7] == 1'b1) begin
        mem_index_fu_1144_p3 = 32'd7;
    end else if (zext_ln640_fu_1140_p1[8] == 1'b1) begin
        mem_index_fu_1144_p3 = 32'd8;
    end else if (zext_ln640_fu_1140_p1[9] == 1'b1) begin
        mem_index_fu_1144_p3 = 32'd9;
    end else if (zext_ln640_fu_1140_p1[10] == 1'b1) begin
        mem_index_fu_1144_p3 = 32'd10;
    end else if (zext_ln640_fu_1140_p1[11] == 1'b1) begin
        mem_index_fu_1144_p3 = 32'd11;
    end else if (zext_ln640_fu_1140_p1[12] == 1'b1) begin
        mem_index_fu_1144_p3 = 32'd12;
    end else if (zext_ln640_fu_1140_p1[13] == 1'b1) begin
        mem_index_fu_1144_p3 = 32'd13;
    end else if (zext_ln640_fu_1140_p1[14] == 1'b1) begin
        mem_index_fu_1144_p3 = 32'd14;
    end else if (zext_ln640_fu_1140_p1[15] == 1'b1) begin
        mem_index_fu_1144_p3 = 32'd15;
    end else if (zext_ln640_fu_1140_p1[16] == 1'b1) begin
        mem_index_fu_1144_p3 = 32'd16;
    end else if (zext_ln640_fu_1140_p1[17] == 1'b1) begin
        mem_index_fu_1144_p3 = 32'd17;
    end else if (zext_ln640_fu_1140_p1[18] == 1'b1) begin
        mem_index_fu_1144_p3 = 32'd18;
    end else if (zext_ln640_fu_1140_p1[19] == 1'b1) begin
        mem_index_fu_1144_p3 = 32'd19;
    end else if (zext_ln640_fu_1140_p1[20] == 1'b1) begin
        mem_index_fu_1144_p3 = 32'd20;
    end else if (zext_ln640_fu_1140_p1[21] == 1'b1) begin
        mem_index_fu_1144_p3 = 32'd21;
    end else if (zext_ln640_fu_1140_p1[22] == 1'b1) begin
        mem_index_fu_1144_p3 = 32'd22;
    end else if (zext_ln640_fu_1140_p1[23] == 1'b1) begin
        mem_index_fu_1144_p3 = 32'd23;
    end else if (zext_ln640_fu_1140_p1[24] == 1'b1) begin
        mem_index_fu_1144_p3 = 32'd24;
    end else if (zext_ln640_fu_1140_p1[25] == 1'b1) begin
        mem_index_fu_1144_p3 = 32'd25;
    end else if (zext_ln640_fu_1140_p1[26] == 1'b1) begin
        mem_index_fu_1144_p3 = 32'd26;
    end else if (zext_ln640_fu_1140_p1[27] == 1'b1) begin
        mem_index_fu_1144_p3 = 32'd27;
    end else if (zext_ln640_fu_1140_p1[28] == 1'b1) begin
        mem_index_fu_1144_p3 = 32'd28;
    end else if (zext_ln640_fu_1140_p1[29] == 1'b1) begin
        mem_index_fu_1144_p3 = 32'd29;
    end else if (zext_ln640_fu_1140_p1[30] == 1'b1) begin
        mem_index_fu_1144_p3 = 32'd30;
    end else if (zext_ln640_fu_1140_p1[31] == 1'b1) begin
        mem_index_fu_1144_p3 = 32'd31;
    end else begin
        mem_index_fu_1144_p3 = 32'd32;
    end
end

assign memoriesAS_0_dataarray_data_V_address0 = zext_ln321_fu_1520_p1;

assign memoriesAS_0_dataarray_data_V_d0 = stub_data_V_3_reg_2335_pp0_iter4_reg;

assign memoriesTEI_0_0_dataarray_data_V_address0 = zext_ln321_1_fu_1712_p1;

assign memoriesTEI_0_0_dataarray_data_V_d0 = p_Result_2_fu_1559_p5;

assign memoriesTEI_0_1_dataarray_data_V_address0 = zext_ln321_2_fu_1822_p1;

assign memoriesTEI_0_1_dataarray_data_V_d0 = p_Result_2_fu_1559_p5;

assign memoriesTEI_0_2_dataarray_data_V_address0 = zext_ln321_3_fu_1922_p1;

assign memoriesTEI_0_2_dataarray_data_V_d0 = p_Result_2_fu_1559_p5;

assign memoriesTEI_0_3_dataarray_data_V_address0 = zext_ln321_4_fu_2028_p1;

assign memoriesTEI_0_3_dataarray_data_V_d0 = p_Result_2_fu_1559_p5;

assign memoriesTEI_1_0_dataarray_data_V_address0 = zext_ln321_1_fu_1712_p1;

assign memoriesTEI_1_0_dataarray_data_V_d0 = p_Result_2_fu_1559_p5;

assign memoriesTEI_1_1_dataarray_data_V_address0 = zext_ln321_2_fu_1822_p1;

assign memoriesTEI_1_1_dataarray_data_V_d0 = p_Result_2_fu_1559_p5;

assign memoriesTEI_1_2_dataarray_data_V_address0 = zext_ln321_3_fu_1922_p1;

assign memoriesTEI_1_2_dataarray_data_V_d0 = p_Result_2_fu_1559_p5;

assign memoriesTEI_1_3_dataarray_data_V_address0 = zext_ln321_4_fu_2028_p1;

assign memoriesTEI_1_3_dataarray_data_V_d0 = p_Result_2_fu_1559_p5;

assign memoriesTEI_2_0_dataarray_data_V_address0 = zext_ln321_1_fu_1712_p1;

assign memoriesTEI_2_0_dataarray_data_V_d0 = p_Result_2_fu_1559_p5;

assign memoriesTEI_2_1_dataarray_data_V_address0 = zext_ln321_2_fu_1822_p1;

assign memoriesTEI_2_1_dataarray_data_V_d0 = p_Result_2_fu_1559_p5;

assign memoriesTEI_2_2_dataarray_data_V_address0 = zext_ln321_3_fu_1922_p1;

assign memoriesTEI_2_2_dataarray_data_V_d0 = p_Result_2_fu_1559_p5;

assign memoriesTEI_2_3_dataarray_data_V_address0 = zext_ln321_4_fu_2028_p1;

assign memoriesTEI_2_3_dataarray_data_V_d0 = p_Result_2_fu_1559_p5;

assign memoriesTEI_3_0_dataarray_data_V_address0 = zext_ln321_1_fu_1712_p1;

assign memoriesTEI_3_0_dataarray_data_V_d0 = p_Result_2_fu_1559_p5;

assign memoriesTEI_3_1_dataarray_data_V_address0 = zext_ln321_2_fu_1822_p1;

assign memoriesTEI_3_1_dataarray_data_V_d0 = p_Result_2_fu_1559_p5;

assign memoriesTEI_3_2_dataarray_data_V_address0 = zext_ln321_3_fu_1922_p1;

assign memoriesTEI_3_2_dataarray_data_V_d0 = p_Result_2_fu_1559_p5;

assign memoriesTEI_3_3_dataarray_data_V_address0 = zext_ln321_4_fu_2028_p1;

assign memoriesTEI_3_3_dataarray_data_V_d0 = p_Result_2_fu_1559_p5;

assign nInputs_0_V_fu_1057_p3 = ((trunc_ln209_fu_1052_p1[0:0] === 1'b1) ? inputStubs_0_nentries_1_V : inputStubs_0_nentries_0_V);

assign nInputs_1_V_fu_1072_p3 = ((trunc_ln209_fu_1052_p1[0:0] === 1'b1) ? inputStubs_1_nentries_1_V : inputStubs_1_nentries_0_V);

assign nInputs_2_V_11_fu_1237_p3 = ((icmp_ln701_1_fu_1231_p2[0:0] === 1'b1) ? ap_phi_reg_pp0_iter1_nInputs_2_V_01_reg_968 : nInputs_2_V_fu_1223_p3);

assign nInputs_2_V_12_fu_1245_p3 = ((icmp_ln701_fu_1217_p2[0:0] === 1'b1) ? nInputs_2_V_19_fu_1211_p2 : ap_phi_reg_pp0_iter1_nInputs_1_V_02_reg_958);

assign nInputs_2_V_13_fu_1253_p3 = ((icmp_ln701_1_fu_1231_p2[0:0] === 1'b1) ? ap_phi_reg_pp0_iter1_nInputs_1_V_02_reg_958 : nInputs_2_V_12_fu_1245_p3);

assign nInputs_2_V_15_fu_1261_p3 = ((icmp_ln701_1_fu_1231_p2[0:0] === 1'b1) ? nInputs_2_V_19_fu_1211_p2 : ap_phi_reg_pp0_iter1_nInputs_2_V_63_reg_948);

assign nInputs_2_V_16_fu_1269_p3 = ((noStubsLeft_fu_1134_p2[0:0] === 1'b1) ? ap_phi_reg_pp0_iter1_nInputs_2_V_01_reg_968 : nInputs_2_V_11_fu_1237_p3);

assign nInputs_2_V_17_fu_1279_p3 = ((noStubsLeft_fu_1134_p2[0:0] === 1'b1) ? ap_phi_reg_pp0_iter1_nInputs_1_V_02_reg_958 : nInputs_2_V_13_fu_1253_p3);

assign nInputs_2_V_18_fu_1289_p3 = ((noStubsLeft_fu_1134_p2[0:0] === 1'b1) ? ap_phi_reg_pp0_iter1_nInputs_2_V_63_reg_948 : nInputs_2_V_15_fu_1261_p3);

assign nInputs_2_V_19_fu_1211_p2 = ($signed(7'd127) + $signed(tmp_fu_1177_p5));

assign nInputs_2_V_1_fu_1087_p3 = ((trunc_ln209_fu_1052_p1[0:0] === 1'b1) ? inputStubs_2_nentries_1_V : inputStubs_2_nentries_0_V);

assign nInputs_2_V_fu_1223_p3 = ((icmp_ln701_fu_1217_p2[0:0] === 1'b1) ? ap_phi_reg_pp0_iter1_nInputs_2_V_01_reg_968 : nInputs_2_V_19_fu_1211_p2);

assign noStubsLeft_fu_1134_p2 = ((ap_phi_reg_pp0_iter1_p_what2_5_reg_938 == 3'd0) ? 1'b1 : 1'b0);

assign or_ln631_fu_1321_p2 = (noStubsLeft_fu_1134_p2 | icmp_ln643_fu_1152_p2);

assign or_ln792_fu_1956_p2 = (4'd3 | add_ln792_fu_1631_p2);

assign p_Repl2_s_fu_1195_p2 = (resetNext_fu_1189_p2 ^ 1'd1);

always @ (*) begin
    p_Result_1_fu_1201_p4 = ap_phi_reg_pp0_iter1_p_what2_5_reg_938;
    p_Result_1_fu_1201_p4[mem_index_fu_1144_p3] = |(p_Repl2_s_fu_1195_p2);
end

assign p_Result_2_fu_1559_p5 = {{{{trunc_ln301_reg_2329_pp0_iter4_reg}, {bend_V_reg_2341_pp0_iter4_reg}}, {p_Result_i6_i_fu_1531_p4}}, {trunc_ln301_1_fu_1555_p1}};

assign p_Result_5_2_fu_1102_p4 = {{{icmp_ln841_2_fu_1096_p2}, {icmp_ln841_1_fu_1081_p2}}, {icmp_ln841_fu_1066_p2}};

assign p_Result_i6_i_fu_1531_p4 = {{phiCorr_V_fu_1525_p3[8:7]}};

assign p_Result_s_fu_1607_p2 = ((tmp_19_fu_1597_p4 == 3'd0) ? 1'b1 : 1'b0);

assign phiCorr_V_2_fu_1493_p3 = ((tmp_11_fu_1485_p3[0:0] === 1'b1) ? 15'd0 : trunc_ln1354_fu_1481_p1);

assign phiCorr_V_fu_1525_p3 = ((tmp_13_reg_2357[0:0] === 1'b1) ? 14'd16383 : trunc_ln214_reg_2362);

assign phi_V_fu_1458_p4 = {{stub_data_V_3_reg_2335[16:3]}};

assign phi_ln792_1_fu_1756_p5 = {{add_ln792_fu_1631_p2[3:2]}};

assign phi_ln792_2_fu_1856_p5 = {{add_ln792_fu_1631_p2[3:2]}};

assign rBin_V_fu_1396_p4 = {{ret_V_fu_1390_p2[6:4]}};

assign r_V_fu_1376_p4 = {{stub_data_V_3_fu_1368_p3[35:29]}};

assign read_addr_V_1_fu_1333_p3 = ((and_ln631_fu_1315_p2[0:0] === 1'b1) ? 7'd0 : read_addr_V_fu_1327_p2);

assign read_addr_V_fu_1327_p2 = (7'd1 + ap_phi_mux_p_06_phi_fu_928_p6);

assign resetNext_fu_1189_p2 = ((tmp_fu_1177_p5 == 7'd1) ? 1'b1 : 1'b0);

assign ret_V_2_fu_1475_p2 = ($signed(zext_ln215_fu_1467_p1) - $signed(sext_ln215_fu_1471_p1));

assign ret_V_fu_1390_p2 = (r_V_fu_1376_p4 ^ 7'd64);

assign select_ln792_1_fu_1968_p3 = ((icmp_ln792_3_fu_1962_p2[0:0] === 1'b1) ? 8'd247 : 8'd0);

assign select_ln792_fu_1643_p3 = ((icmp_ln792_6_fu_1637_p2[0:0] === 1'b1) ? 8'd247 : 8'd31);

assign sext_ln215_fu_1471_p1 = $signed(lut_1_q0);

assign shl_ln792_1_fu_1654_p2 = 8'd1 << zext_ln792_fu_1651_p1;

assign shl_ln792_fu_1591_p2 = 16'd1 << zext_ln215_1_fu_1551_p1;

assign shl_ln_fu_1623_p3 = {{trunc_ln_fu_1613_p4}, {2'd0}};

assign stub_data_V_1_fu_1361_p3 = ((icmp_ln643_reg_2300_pp0_iter2_reg[0:0] === 1'b1) ? stub_data_V_fu_1350_p5 : p_Val2_s_fu_298);

assign stub_data_V_3_fu_1368_p3 = ((noStubsLeft_reg_2295_pp0_iter2_reg[0:0] === 1'b1) ? p_Val2_s_fu_298 : stub_data_V_1_fu_1361_p3);

assign tmp_10_fu_1513_p3 = {{bx_V8_phi_reg_910_pp0_iter4_reg}, {trunc_ln301_reg_2329_pp0_iter4_reg}};

assign tmp_11_fu_1485_p3 = ret_V_2_fu_1475_p2[32'd15];

assign tmp_12_fu_1419_p4 = {{stub_data_V_3_fu_1368_p3[28:22]}};

assign tmp_14_fu_1704_p3 = {{p_phi_reg_898_pp0_iter4_reg}, {tmp_1_fu_1690_p6}};

assign tmp_15_fu_1814_p3 = {{p_phi_reg_898_pp0_iter4_reg}, {tmp_4_fu_1800_p6}};

assign tmp_16_fu_1914_p3 = {{p_phi_reg_898_pp0_iter4_reg}, {tmp_5_fu_1900_p6}};

assign tmp_17_fu_2020_p3 = {{p_phi_reg_898_pp0_iter4_reg}, {tmp_7_fu_2006_p6}};

assign tmp_18_fu_1445_p3 = {{indexz_V_fu_1429_p2}, {indexr_V_fu_1435_p4}};

assign tmp_19_fu_1597_p4 = {{shl_ln792_fu_1591_p2[15:13]}};

assign tmp_1_fu_1690_p5 = (trunc_ln_fu_1613_p4 + 2'd3);

assign tmp_4_fu_1800_p5 = (trunc_ln_fu_1613_p4 + 2'd3);

assign tmp_5_fu_1900_p5 = (trunc_ln_fu_1613_p4 + 2'd3);

assign tmp_7_fu_2006_p5 = (trunc_ln_fu_1613_p4 + 2'd3);

assign tmp_9_fu_1158_p3 = {{p_phi_reg_898}, {ap_phi_mux_p_06_phi_fu_928_p6}};

assign tmp_i_i_fu_1406_p3 = {{bend_V_fu_1386_p1}, {rBin_V_fu_1396_p4}};

assign trunc_ln1354_fu_1481_p1 = ret_V_2_fu_1475_p2[14:0];

assign trunc_ln209_fu_1052_p1 = bx_V[0:0];

assign trunc_ln214_fu_1509_p1 = phiCorr_V_2_fu_1493_p3[13:0];

assign trunc_ln301_1_fu_1555_p1 = lut_q0[9:0];

assign trunc_ln301_fu_1343_p1 = val_assign7_reg_847[6:0];

assign trunc_ln57_fu_1173_p1 = mem_index_fu_1144_p3[1:0];

assign trunc_ln609_fu_1118_p1 = i_fu_1112_p2[6:0];

assign trunc_ln_fu_1613_p4 = {{phiCorr_V_fu_1525_p3[10:9]}};

assign xor_ln631_fu_1309_p2 = (noStubsLeft_fu_1134_p2 ^ 1'd1);

assign zext_ln215_1_fu_1551_p1 = iphivm_V_fu_1541_p4;

assign zext_ln215_fu_1467_p1 = phi_V_fu_1458_p4;

assign zext_ln321_1_fu_1712_p1 = tmp_14_fu_1704_p3;

assign zext_ln321_2_fu_1822_p1 = tmp_15_fu_1814_p3;

assign zext_ln321_3_fu_1922_p1 = tmp_16_fu_1914_p3;

assign zext_ln321_4_fu_2028_p1 = tmp_17_fu_2020_p3;

assign zext_ln321_fu_1520_p1 = tmp_10_fu_1513_p3;

assign zext_ln357_fu_1453_p1 = tmp_18_fu_1445_p3;

assign zext_ln544_fu_1414_p1 = tmp_i_i_fu_1406_p3;

assign zext_ln57_fu_1166_p1 = tmp_9_fu_1158_p3;

assign zext_ln640_fu_1140_p1 = ap_phi_reg_pp0_iter1_p_what2_5_reg_938;

assign zext_ln792_fu_1651_p1 = bend_V_reg_2341_pp0_iter4_reg;

endmodule //VMRouterTop_L1PHID
