// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="ProjectionRouterTop_L3PHIB,hls_ip_2020_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xcvu7p-flvb2104-1-e,HLS_INPUT_CLOCK=4.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.458500,HLS_SYN_LAT=111,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=530,HLS_SYN_LUT=750,HLS_VERSION=2020_1}" *)

module ProjectionRouterTop_L3PHIB (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        bx_V,
        projin_0_dataarray_data_V_address0,
        projin_0_dataarray_data_V_ce0,
        projin_0_dataarray_data_V_q0,
        projin_0_nentries_0_V,
        projin_0_nentries_1_V,
        bx_o_V,
        bx_o_V_ap_vld,
        allprojout_dataarray_data_V_address0,
        allprojout_dataarray_data_V_ce0,
        allprojout_dataarray_data_V_we0,
        allprojout_dataarray_data_V_d0,
        vmprojout_0_dataarray_data_V_address0,
        vmprojout_0_dataarray_data_V_ce0,
        vmprojout_0_dataarray_data_V_we0,
        vmprojout_0_dataarray_data_V_d0,
        vmprojout_1_dataarray_data_V_address0,
        vmprojout_1_dataarray_data_V_ce0,
        vmprojout_1_dataarray_data_V_we0,
        vmprojout_1_dataarray_data_V_d0,
        vmprojout_2_dataarray_data_V_address0,
        vmprojout_2_dataarray_data_V_ce0,
        vmprojout_2_dataarray_data_V_we0,
        vmprojout_2_dataarray_data_V_d0,
        vmprojout_3_dataarray_data_V_address0,
        vmprojout_3_dataarray_data_V_ce0,
        vmprojout_3_dataarray_data_V_we0,
        vmprojout_3_dataarray_data_V_d0,
        vmprojout_4_dataarray_data_V_address0,
        vmprojout_4_dataarray_data_V_ce0,
        vmprojout_4_dataarray_data_V_we0,
        vmprojout_4_dataarray_data_V_d0,
        vmprojout_5_dataarray_data_V_address0,
        vmprojout_5_dataarray_data_V_ce0,
        vmprojout_5_dataarray_data_V_we0,
        vmprojout_5_dataarray_data_V_d0,
        vmprojout_6_dataarray_data_V_address0,
        vmprojout_6_dataarray_data_V_ce0,
        vmprojout_6_dataarray_data_V_we0,
        vmprojout_6_dataarray_data_V_d0,
        vmprojout_7_dataarray_data_V_address0,
        vmprojout_7_dataarray_data_V_ce0,
        vmprojout_7_dataarray_data_V_we0,
        vmprojout_7_dataarray_data_V_d0
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_pp0_stage0 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [2:0] bx_V;
output  [7:0] projin_0_dataarray_data_V_address0;
output   projin_0_dataarray_data_V_ce0;
input  [59:0] projin_0_dataarray_data_V_q0;
input  [6:0] projin_0_nentries_0_V;
input  [6:0] projin_0_nentries_1_V;
output  [2:0] bx_o_V;
output   bx_o_V_ap_vld;
output  [9:0] allprojout_dataarray_data_V_address0;
output   allprojout_dataarray_data_V_ce0;
output   allprojout_dataarray_data_V_we0;
output  [59:0] allprojout_dataarray_data_V_d0;
output  [7:0] vmprojout_0_dataarray_data_V_address0;
output   vmprojout_0_dataarray_data_V_ce0;
output   vmprojout_0_dataarray_data_V_we0;
output  [23:0] vmprojout_0_dataarray_data_V_d0;
output  [7:0] vmprojout_1_dataarray_data_V_address0;
output   vmprojout_1_dataarray_data_V_ce0;
output   vmprojout_1_dataarray_data_V_we0;
output  [23:0] vmprojout_1_dataarray_data_V_d0;
output  [7:0] vmprojout_2_dataarray_data_V_address0;
output   vmprojout_2_dataarray_data_V_ce0;
output   vmprojout_2_dataarray_data_V_we0;
output  [23:0] vmprojout_2_dataarray_data_V_d0;
output  [7:0] vmprojout_3_dataarray_data_V_address0;
output   vmprojout_3_dataarray_data_V_ce0;
output   vmprojout_3_dataarray_data_V_we0;
output  [23:0] vmprojout_3_dataarray_data_V_d0;
output  [7:0] vmprojout_4_dataarray_data_V_address0;
output   vmprojout_4_dataarray_data_V_ce0;
output   vmprojout_4_dataarray_data_V_we0;
output  [23:0] vmprojout_4_dataarray_data_V_d0;
output  [7:0] vmprojout_5_dataarray_data_V_address0;
output   vmprojout_5_dataarray_data_V_ce0;
output   vmprojout_5_dataarray_data_V_we0;
output  [23:0] vmprojout_5_dataarray_data_V_d0;
output  [7:0] vmprojout_6_dataarray_data_V_address0;
output   vmprojout_6_dataarray_data_V_ce0;
output   vmprojout_6_dataarray_data_V_we0;
output  [23:0] vmprojout_6_dataarray_data_V_d0;
output  [7:0] vmprojout_7_dataarray_data_V_address0;
output   vmprojout_7_dataarray_data_V_ce0;
output   vmprojout_7_dataarray_data_V_we0;
output  [23:0] vmprojout_7_dataarray_data_V_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg projin_0_dataarray_data_V_ce0;
reg allprojout_dataarray_data_V_ce0;
reg allprojout_dataarray_data_V_we0;
reg vmprojout_0_dataarray_data_V_ce0;
reg vmprojout_0_dataarray_data_V_we0;
reg vmprojout_1_dataarray_data_V_ce0;
reg vmprojout_1_dataarray_data_V_we0;
reg vmprojout_2_dataarray_data_V_ce0;
reg vmprojout_2_dataarray_data_V_we0;
reg vmprojout_3_dataarray_data_V_ce0;
reg vmprojout_3_dataarray_data_V_we0;
reg vmprojout_4_dataarray_data_V_ce0;
reg vmprojout_4_dataarray_data_V_we0;
reg vmprojout_5_dataarray_data_V_ce0;
reg vmprojout_5_dataarray_data_V_we0;
reg vmprojout_6_dataarray_data_V_ce0;
reg vmprojout_6_dataarray_data_V_we0;
reg vmprojout_7_dataarray_data_V_ce0;
reg vmprojout_7_dataarray_data_V_we0;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] icmp_ln79_fu_490_p2;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
wire    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_state4_pp0_stage0_iter2;
wire    ap_block_state5_pp0_stage0_iter3;
reg    bx_o_V_1_ack_in;
reg    ap_block_state6_pp0_stage0_iter4;
reg    ap_enable_reg_pp0_iter4;
reg    ap_block_pp0_stage0_11001;
reg   [2:0] bx_o_V_1_data_reg;
reg    bx_o_V_1_vld_reg;
reg    bx_o_V_1_vld_in;
reg   [0:0] do_init_reg_389;
reg   [6:0] istep_0_i13_reg_405;
reg   [2:0] bx_V14_rewind_reg_419;
reg   [2:0] bx_V14_phi_reg_433;
reg   [2:0] bx_V14_phi_reg_433_pp0_iter2_reg;
reg   [2:0] bx_V14_phi_reg_433_pp0_iter3_reg;
reg   [0:0] ap_phi_mux_do_init_phi_fu_393_p6;
wire   [0:0] icmp_ln81_fu_478_p2;
reg   [0:0] icmp_ln81_reg_1147;
reg   [0:0] icmp_ln81_reg_1147_pp0_iter1_reg;
reg   [0:0] icmp_ln81_reg_1147_pp0_iter2_reg;
reg   [0:0] icmp_ln81_reg_1147_pp0_iter3_reg;
reg   [6:0] projin_0_nentries_0_V_read_reg_1163;
reg   [6:0] projin_0_nentries_1_V_read_reg_1168;
wire   [6:0] istep_fu_484_p2;
reg   [6:0] istep_reg_1173;
reg   [0:0] icmp_ln79_reg_1178;
reg   [0:0] icmp_ln79_reg_1178_pp0_iter1_reg;
reg   [0:0] icmp_ln79_reg_1178_pp0_iter2_reg;
reg   [0:0] icmp_ln79_reg_1178_pp0_iter3_reg;
wire   [0:0] trunc_ln209_fu_505_p1;
reg   [0:0] trunc_ln209_reg_1182;
reg   [0:0] trunc_ln209_reg_1182_pp0_iter2_reg;
reg   [0:0] trunc_ln209_reg_1182_pp0_iter3_reg;
wire   [0:0] p_Val2_s_fu_535_p3;
reg   [0:0] p_Val2_s_reg_1187;
reg   [0:0] p_Val2_s_reg_1187_pp0_iter2_reg;
reg   [0:0] p_Val2_s_reg_1187_pp0_iter3_reg;
reg   [59:0] tproj_data_V_reg_1196;
wire   [0:0] psseed_fu_632_p2;
reg   [0:0] psseed_reg_1201;
wire   [2:0] zbin1_V_fu_684_p3;
reg   [2:0] zbin1_V_reg_1206;
wire   [0:0] icmp_ln883_fu_730_p2;
reg   [0:0] icmp_ln883_reg_1211;
wire   [3:0] finez_V_fu_758_p2;
reg   [3:0] finez_V_reg_1216;
reg   [4:0] p_Result_1_reg_1221;
reg   [2:0] v2_V_reg_1226;
reg   [2:0] p_Result_s_53_reg_1231;
reg    ap_enable_reg_pp0_iter1;
reg    ap_block_pp0_stage0_subdone;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
wire    ap_block_pp0_stage0;
reg   [6:0] ap_phi_mux_istep_0_i13_phi_fu_409_p6;
reg   [2:0] ap_phi_mux_bx_V14_rewind_phi_fu_423_p6;
reg   [2:0] ap_phi_mux_bx_V14_phi_phi_fu_438_p4;
wire   [2:0] ap_phi_reg_pp0_iter0_bx_V14_phi_reg_433;
reg   [2:0] ap_phi_reg_pp0_iter1_bx_V14_phi_reg_433;
wire   [63:0] zext_ln42_fu_565_p1;
wire   [63:0] zext_ln321_fu_975_p1;
wire   [63:0] zext_ln321_1_fu_1041_p1;
reg   [6:0] numbersin_0_V_2_fu_186;
wire   [6:0] numbersin_0_V_3_fu_521_p3;
reg   [6:0] nvmprojout_7_V_fu_190;
wire   [6:0] select_ln81_fu_845_p3;
wire   [6:0] nvmprojout_0_V_fu_987_p2;
reg   [6:0] nvmprojout_7_V_1_fu_194;
wire   [6:0] select_ln81_1_fu_853_p3;
reg   [6:0] nvmprojout_7_V_2_fu_198;
wire   [6:0] select_ln81_2_fu_861_p3;
reg   [6:0] nvmprojout_7_V_3_fu_202;
wire   [6:0] select_ln81_3_fu_869_p3;
reg   [6:0] nvmprojout_7_V_4_fu_206;
wire   [6:0] select_ln81_4_fu_877_p3;
reg   [6:0] nvmprojout_7_V_5_fu_210;
wire   [6:0] select_ln81_5_fu_885_p3;
reg   [6:0] nvmprojout_7_V_6_fu_214;
wire   [6:0] select_ln81_6_fu_893_p3;
reg   [6:0] nvmprojout_7_V_7_fu_218;
wire   [6:0] select_ln81_7_fu_901_p3;
reg   [6:0] mem_rea_010_fu_222;
wire   [6:0] select_ln81_9_fu_528_p3;
wire   [6:0] select_ln29_fu_582_p3;
reg   [0:0] p_Val2_1_fu_226;
wire   [0:0] icmp_ln891_fu_576_p2;
reg   [6:0] nallproj_V_1_fu_230;
wire   [6:0] index_V_fu_909_p3;
wire   [6:0] nallproj_V_fu_1046_p2;
reg    ap_block_pp0_stage0_01001;
wire   [23:0] ret_V_fu_926_p8;
wire   [6:0] numbersin_0_V_fu_509_p3;
wire   [0:0] icmp_ln98_fu_515_p2;
wire   [7:0] tmp_2_fu_557_p3;
wire   [6:0] mem_read_addr_V_fu_570_p2;
wire   [2:0] iseed_V_fu_610_p4;
wire   [0:0] icmp_ln133_fu_620_p2;
wire   [0:0] icmp_ln133_1_fu_626_p2;
wire   [11:0] izproj_V_fu_600_p4;
wire   [11:0] ret_V_2_fu_638_p2;
wire   [5:0] p_Result_s_fu_652_p4;
wire   [5:0] select_ln147_fu_644_p3;
wire   [5:0] zbinlower_V_fu_668_p2;
wire   [0:0] icmp_ln887_fu_662_p2;
wire   [2:0] trunc_ln1_fu_674_p4;
wire   [5:0] select_ln895_fu_692_p3;
wire   [5:0] zbinupper_V_fu_706_p2;
wire   [0:0] icmp_ln895_fu_700_p2;
wire   [2:0] trunc_ln2_fu_712_p4;
wire   [2:0] zbin2_V_fu_722_p3;
wire   [0:0] trunc_ln312_fu_736_p1;
wire   [3:0] trunc_ln214_2_fu_740_p4;
wire   [3:0] trunc_ln214_3_fu_750_p3;
wire   [9:0] tmp_3_fu_764_p4;
wire   [10:0] shl_ln_fu_774_p3;
wire   [10:0] irinv_tmp_V_fu_782_p2;
wire   [4:0] rinv_V_fu_921_p2;
wire   [6:0] t_V_fu_947_p1;
wire   [6:0] t_V_fu_947_p2;
wire   [6:0] t_V_fu_947_p3;
wire   [6:0] t_V_fu_947_p4;
wire   [6:0] t_V_fu_947_p5;
wire   [6:0] t_V_fu_947_p6;
wire   [6:0] t_V_fu_947_p7;
wire   [6:0] t_V_fu_947_p8;
wire   [6:0] t_V_fu_947_p10;
wire   [7:0] tmp_4_fu_968_p3;
wire   [9:0] tmp_5_fu_1033_p3;
reg   [1:0] ap_NS_fsm;
reg    ap_idle_pp0_0to3;
reg    ap_reset_idle_pp0;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_236;
reg    ap_condition_48;
reg    ap_condition_230;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 bx_o_V_1_data_reg = 3'd0;
#0 bx_o_V_1_vld_reg = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
end

ProjectionRouterTop_L3PHIB_mux_83_7_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 7 ),
    .din2_WIDTH( 7 ),
    .din3_WIDTH( 7 ),
    .din4_WIDTH( 7 ),
    .din5_WIDTH( 7 ),
    .din6_WIDTH( 7 ),
    .din7_WIDTH( 7 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 7 ))
ProjectionRouterTop_L3PHIB_mux_83_7_1_1_U1(
    .din0(t_V_fu_947_p1),
    .din1(t_V_fu_947_p2),
    .din2(t_V_fu_947_p3),
    .din3(t_V_fu_947_p4),
    .din4(t_V_fu_947_p5),
    .din5(t_V_fu_947_p6),
    .din6(t_V_fu_947_p7),
    .din7(t_V_fu_947_p8),
    .din8(p_Result_s_53_reg_1231),
    .dout(t_V_fu_947_p10)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter4 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_48)) begin
        if ((ap_phi_mux_do_init_phi_fu_393_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_bx_V14_phi_reg_433 <= bx_V;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_bx_V14_phi_reg_433 <= ap_phi_reg_pp0_iter0_bx_V14_phi_reg_433;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_230)) begin
        if ((do_init_reg_389 == 1'd0)) begin
            bx_V14_phi_reg_433 <= ap_phi_mux_bx_V14_rewind_phi_fu_423_p6;
        end else if ((1'b1 == 1'b1)) begin
            bx_V14_phi_reg_433 <= ap_phi_reg_pp0_iter1_bx_V14_phi_reg_433;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (bx_o_V_1_vld_reg == 1'b0) & (bx_o_V_1_vld_in == 1'b1))) begin
        bx_o_V_1_vld_reg <= 1'b1;
    end else if (((bx_o_V_1_vld_in == 1'b0) & (1'b1 == 1'b1) & (bx_o_V_1_vld_reg == 1'b1))) begin
        bx_o_V_1_vld_reg <= 1'b0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln79_reg_1178 == 1'd0))) begin
        do_init_reg_389 <= 1'd0;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln79_reg_1178 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        do_init_reg_389 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln79_reg_1178 == 1'd0))) begin
        istep_0_i13_reg_405 <= istep_reg_1173;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln79_reg_1178 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        istep_0_i13_reg_405 <= 7'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_230)) begin
        if ((p_Val2_s_fu_535_p3 == 1'd1)) begin
            mem_rea_010_fu_222 <= select_ln29_fu_582_p3;
        end else if ((p_Val2_s_fu_535_p3 == 1'd0)) begin
            mem_rea_010_fu_222 <= select_ln81_9_fu_528_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        if ((p_Val2_s_reg_1187_pp0_iter3_reg == 1'd1)) begin
            nallproj_V_1_fu_230 <= nallproj_V_fu_1046_p2;
        end else if ((p_Val2_s_reg_1187_pp0_iter3_reg == 1'd0)) begin
            nallproj_V_1_fu_230 <= index_V_fu_909_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (p_Val2_s_reg_1187_pp0_iter3_reg == 1'd1) & (p_Result_s_53_reg_1231 == 3'd6) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        nvmprojout_7_V_1_fu_194 <= nvmprojout_0_V_fu_987_p2;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (p_Val2_s_reg_1187_pp0_iter3_reg == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (p_Val2_s_reg_1187_pp0_iter3_reg == 1'd1) & (p_Result_s_53_reg_1231 == 3'd7) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((p_Result_s_53_reg_1231 == 3'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (p_Val2_s_reg_1187_pp0_iter3_reg == 1'd1) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (p_Val2_s_reg_1187_pp0_iter3_reg == 1'd1) & (p_Result_s_53_reg_1231 == 3'd1) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (p_Val2_s_reg_1187_pp0_iter3_reg == 1'd1) & (p_Result_s_53_reg_1231 == 3'd2) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (p_Val2_s_reg_1187_pp0_iter3_reg == 1'd1) & (p_Result_s_53_reg_1231 == 3'd3) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (p_Val2_s_reg_1187_pp0_iter3_reg == 1'd1) & (p_Result_s_53_reg_1231 == 3'd4) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (p_Val2_s_reg_1187_pp0_iter3_reg == 1'd1) & (p_Result_s_53_reg_1231 == 3'd5) & (ap_enable_reg_pp0_iter4 == 1'b1)))) begin
        nvmprojout_7_V_1_fu_194 <= select_ln81_1_fu_853_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (p_Val2_s_reg_1187_pp0_iter3_reg == 1'd1) & (p_Result_s_53_reg_1231 == 3'd5) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        nvmprojout_7_V_2_fu_198 <= nvmprojout_0_V_fu_987_p2;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (p_Val2_s_reg_1187_pp0_iter3_reg == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (p_Val2_s_reg_1187_pp0_iter3_reg == 1'd1) & (p_Result_s_53_reg_1231 == 3'd7) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((p_Result_s_53_reg_1231 == 3'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (p_Val2_s_reg_1187_pp0_iter3_reg == 1'd1) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (p_Val2_s_reg_1187_pp0_iter3_reg == 1'd1) & (p_Result_s_53_reg_1231 == 3'd1) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (p_Val2_s_reg_1187_pp0_iter3_reg == 1'd1) & (p_Result_s_53_reg_1231 == 3'd2) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (p_Val2_s_reg_1187_pp0_iter3_reg == 1'd1) & (p_Result_s_53_reg_1231 == 3'd3) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (p_Val2_s_reg_1187_pp0_iter3_reg == 1'd1) & (p_Result_s_53_reg_1231 == 3'd4) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (p_Val2_s_reg_1187_pp0_iter3_reg == 1'd1) & (p_Result_s_53_reg_1231 == 3'd6) & (ap_enable_reg_pp0_iter4 == 1'b1)))) begin
        nvmprojout_7_V_2_fu_198 <= select_ln81_2_fu_861_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (p_Val2_s_reg_1187_pp0_iter3_reg == 1'd1) & (p_Result_s_53_reg_1231 == 3'd4) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        nvmprojout_7_V_3_fu_202 <= nvmprojout_0_V_fu_987_p2;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (p_Val2_s_reg_1187_pp0_iter3_reg == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (p_Val2_s_reg_1187_pp0_iter3_reg == 1'd1) & (p_Result_s_53_reg_1231 == 3'd7) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((p_Result_s_53_reg_1231 == 3'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (p_Val2_s_reg_1187_pp0_iter3_reg == 1'd1) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (p_Val2_s_reg_1187_pp0_iter3_reg == 1'd1) & (p_Result_s_53_reg_1231 == 3'd1) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (p_Val2_s_reg_1187_pp0_iter3_reg == 1'd1) & (p_Result_s_53_reg_1231 == 3'd2) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (p_Val2_s_reg_1187_pp0_iter3_reg == 1'd1) & (p_Result_s_53_reg_1231 == 3'd3) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (p_Val2_s_reg_1187_pp0_iter3_reg == 1'd1) & (p_Result_s_53_reg_1231 == 3'd5) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (p_Val2_s_reg_1187_pp0_iter3_reg == 1'd1) & (p_Result_s_53_reg_1231 == 3'd6) & (ap_enable_reg_pp0_iter4 == 1'b1)))) begin
        nvmprojout_7_V_3_fu_202 <= select_ln81_3_fu_869_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (p_Val2_s_reg_1187_pp0_iter3_reg == 1'd1) & (p_Result_s_53_reg_1231 == 3'd3) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        nvmprojout_7_V_4_fu_206 <= nvmprojout_0_V_fu_987_p2;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (p_Val2_s_reg_1187_pp0_iter3_reg == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (p_Val2_s_reg_1187_pp0_iter3_reg == 1'd1) & (p_Result_s_53_reg_1231 == 3'd7) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((p_Result_s_53_reg_1231 == 3'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (p_Val2_s_reg_1187_pp0_iter3_reg == 1'd1) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (p_Val2_s_reg_1187_pp0_iter3_reg == 1'd1) & (p_Result_s_53_reg_1231 == 3'd1) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (p_Val2_s_reg_1187_pp0_iter3_reg == 1'd1) & (p_Result_s_53_reg_1231 == 3'd2) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (p_Val2_s_reg_1187_pp0_iter3_reg == 1'd1) & (p_Result_s_53_reg_1231 == 3'd4) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (p_Val2_s_reg_1187_pp0_iter3_reg == 1'd1) & (p_Result_s_53_reg_1231 == 3'd5) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (p_Val2_s_reg_1187_pp0_iter3_reg == 1'd1) & (p_Result_s_53_reg_1231 == 3'd6) & (ap_enable_reg_pp0_iter4 == 1'b1)))) begin
        nvmprojout_7_V_4_fu_206 <= select_ln81_4_fu_877_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (p_Val2_s_reg_1187_pp0_iter3_reg == 1'd1) & (p_Result_s_53_reg_1231 == 3'd2) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        nvmprojout_7_V_5_fu_210 <= nvmprojout_0_V_fu_987_p2;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (p_Val2_s_reg_1187_pp0_iter3_reg == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (p_Val2_s_reg_1187_pp0_iter3_reg == 1'd1) & (p_Result_s_53_reg_1231 == 3'd7) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((p_Result_s_53_reg_1231 == 3'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (p_Val2_s_reg_1187_pp0_iter3_reg == 1'd1) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (p_Val2_s_reg_1187_pp0_iter3_reg == 1'd1) & (p_Result_s_53_reg_1231 == 3'd1) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (p_Val2_s_reg_1187_pp0_iter3_reg == 1'd1) & (p_Result_s_53_reg_1231 == 3'd3) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (p_Val2_s_reg_1187_pp0_iter3_reg == 1'd1) & (p_Result_s_53_reg_1231 == 3'd4) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (p_Val2_s_reg_1187_pp0_iter3_reg == 1'd1) & (p_Result_s_53_reg_1231 == 3'd5) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (p_Val2_s_reg_1187_pp0_iter3_reg == 1'd1) & (p_Result_s_53_reg_1231 == 3'd6) & (ap_enable_reg_pp0_iter4 == 1'b1)))) begin
        nvmprojout_7_V_5_fu_210 <= select_ln81_5_fu_885_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (p_Val2_s_reg_1187_pp0_iter3_reg == 1'd1) & (p_Result_s_53_reg_1231 == 3'd1) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        nvmprojout_7_V_6_fu_214 <= nvmprojout_0_V_fu_987_p2;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (p_Val2_s_reg_1187_pp0_iter3_reg == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (p_Val2_s_reg_1187_pp0_iter3_reg == 1'd1) & (p_Result_s_53_reg_1231 == 3'd7) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((p_Result_s_53_reg_1231 == 3'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (p_Val2_s_reg_1187_pp0_iter3_reg == 1'd1) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (p_Val2_s_reg_1187_pp0_iter3_reg == 1'd1) & (p_Result_s_53_reg_1231 == 3'd2) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (p_Val2_s_reg_1187_pp0_iter3_reg == 1'd1) & (p_Result_s_53_reg_1231 == 3'd3) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (p_Val2_s_reg_1187_pp0_iter3_reg == 1'd1) & (p_Result_s_53_reg_1231 == 3'd4) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (p_Val2_s_reg_1187_pp0_iter3_reg == 1'd1) & (p_Result_s_53_reg_1231 == 3'd5) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (p_Val2_s_reg_1187_pp0_iter3_reg == 1'd1) & (p_Result_s_53_reg_1231 == 3'd6) & (ap_enable_reg_pp0_iter4 == 1'b1)))) begin
        nvmprojout_7_V_6_fu_214 <= select_ln81_6_fu_893_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((p_Result_s_53_reg_1231 == 3'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (p_Val2_s_reg_1187_pp0_iter3_reg == 1'd1) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        nvmprojout_7_V_7_fu_218 <= nvmprojout_0_V_fu_987_p2;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (p_Val2_s_reg_1187_pp0_iter3_reg == 1'd0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (p_Val2_s_reg_1187_pp0_iter3_reg == 1'd1) & (p_Result_s_53_reg_1231 == 3'd7) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (p_Val2_s_reg_1187_pp0_iter3_reg == 1'd1) & (p_Result_s_53_reg_1231 == 3'd1) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (p_Val2_s_reg_1187_pp0_iter3_reg == 1'd1) & (p_Result_s_53_reg_1231 == 3'd2) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (p_Val2_s_reg_1187_pp0_iter3_reg == 1'd1) & (p_Result_s_53_reg_1231 == 3'd3) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (p_Val2_s_reg_1187_pp0_iter3_reg == 1'd1) & (p_Result_s_53_reg_1231 == 3'd4) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (p_Val2_s_reg_1187_pp0_iter3_reg == 1'd1) & (p_Result_s_53_reg_1231 == 3'd5) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (p_Val2_s_reg_1187_pp0_iter3_reg == 1'd1) & (p_Result_s_53_reg_1231 == 3'd6) & (ap_enable_reg_pp0_iter4 == 1'b1)))) begin
        nvmprojout_7_V_7_fu_218 <= select_ln81_7_fu_901_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (p_Val2_s_reg_1187_pp0_iter3_reg == 1'd1) & (p_Result_s_53_reg_1231 == 3'd7) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        nvmprojout_7_V_fu_190 <= nvmprojout_0_V_fu_987_p2;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (p_Val2_s_reg_1187_pp0_iter3_reg == 1'd0)) | ((p_Result_s_53_reg_1231 == 3'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (p_Val2_s_reg_1187_pp0_iter3_reg == 1'd1) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (p_Val2_s_reg_1187_pp0_iter3_reg == 1'd1) & (p_Result_s_53_reg_1231 == 3'd1) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (p_Val2_s_reg_1187_pp0_iter3_reg == 1'd1) & (p_Result_s_53_reg_1231 == 3'd2) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (p_Val2_s_reg_1187_pp0_iter3_reg == 1'd1) & (p_Result_s_53_reg_1231 == 3'd3) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (p_Val2_s_reg_1187_pp0_iter3_reg == 1'd1) & (p_Result_s_53_reg_1231 == 3'd4) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (p_Val2_s_reg_1187_pp0_iter3_reg == 1'd1) & (p_Result_s_53_reg_1231 == 3'd5) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (p_Val2_s_reg_1187_pp0_iter3_reg == 1'd1) & (p_Result_s_53_reg_1231 == 3'd6) & (ap_enable_reg_pp0_iter4 == 1'b1)))) begin
        nvmprojout_7_V_fu_190 <= select_ln81_fu_845_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_230)) begin
        if ((p_Val2_s_fu_535_p3 == 1'd1)) begin
            p_Val2_1_fu_226 <= icmp_ln891_fu_576_p2;
        end else if ((p_Val2_s_fu_535_p3 == 1'd0)) begin
            p_Val2_1_fu_226 <= p_Val2_s_fu_535_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        bx_V14_phi_reg_433_pp0_iter2_reg <= bx_V14_phi_reg_433;
        bx_V14_phi_reg_433_pp0_iter3_reg <= bx_V14_phi_reg_433_pp0_iter2_reg;
        icmp_ln79_reg_1178_pp0_iter2_reg <= icmp_ln79_reg_1178_pp0_iter1_reg;
        icmp_ln79_reg_1178_pp0_iter3_reg <= icmp_ln79_reg_1178_pp0_iter2_reg;
        icmp_ln81_reg_1147_pp0_iter2_reg <= icmp_ln81_reg_1147_pp0_iter1_reg;
        icmp_ln81_reg_1147_pp0_iter3_reg <= icmp_ln81_reg_1147_pp0_iter2_reg;
        p_Val2_s_reg_1187_pp0_iter2_reg <= p_Val2_s_reg_1187;
        p_Val2_s_reg_1187_pp0_iter3_reg <= p_Val2_s_reg_1187_pp0_iter2_reg;
        trunc_ln209_reg_1182_pp0_iter2_reg <= trunc_ln209_reg_1182;
        trunc_ln209_reg_1182_pp0_iter3_reg <= trunc_ln209_reg_1182_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln79_reg_1178_pp0_iter1_reg == 1'd0))) begin
        bx_V14_rewind_reg_419 <= bx_V14_phi_reg_433;
    end
end

always @ (posedge ap_clk) begin
    if (((~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (bx_o_V_1_vld_reg == 1'b0) & (bx_o_V_1_vld_in == 1'b1)) | (~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (1'b1 == 1'b1) & (bx_o_V_1_vld_in == 1'b1) & (bx_o_V_1_vld_reg == 1'b1)))) begin
        bx_o_V_1_data_reg <= bx_V14_phi_reg_433_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (p_Val2_s_reg_1187_pp0_iter2_reg == 1'd1))) begin
        finez_V_reg_1216 <= finez_V_fu_758_p2;
        icmp_ln883_reg_1211 <= icmp_ln883_fu_730_p2;
        p_Result_1_reg_1221 <= {{irinv_tmp_V_fu_782_p2[10:6]}};
        p_Result_s_53_reg_1231 <= {{projin_0_dataarray_data_V_q0[43:41]}};
        psseed_reg_1201 <= psseed_fu_632_p2;
        tproj_data_V_reg_1196 <= projin_0_dataarray_data_V_q0;
        v2_V_reg_1226 <= {{projin_0_dataarray_data_V_q0[40:38]}};
        zbin1_V_reg_1206 <= zbin1_V_fu_684_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln79_reg_1178 <= icmp_ln79_fu_490_p2;
        icmp_ln79_reg_1178_pp0_iter1_reg <= icmp_ln79_reg_1178;
        icmp_ln81_reg_1147 <= icmp_ln81_fu_478_p2;
        icmp_ln81_reg_1147_pp0_iter1_reg <= icmp_ln81_reg_1147;
        p_Val2_s_reg_1187 <= p_Val2_s_fu_535_p3;
        projin_0_nentries_0_V_read_reg_1163 <= projin_0_nentries_0_V;
        projin_0_nentries_1_V_read_reg_1168 <= projin_0_nentries_1_V;
        trunc_ln209_reg_1182 <= trunc_ln209_fu_505_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        istep_reg_1173 <= istep_fu_484_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        numbersin_0_V_2_fu_186 <= numbersin_0_V_3_fu_521_p3;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        allprojout_dataarray_data_V_ce0 = 1'b1;
    end else begin
        allprojout_dataarray_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (p_Val2_s_reg_1187_pp0_iter3_reg == 1'd1) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        allprojout_dataarray_data_V_we0 = 1'b1;
    end else begin
        allprojout_dataarray_data_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln79_reg_1178_pp0_iter3_reg == 1'd1) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_0to3 = 1'b1;
    end else begin
        ap_idle_pp0_0to3 = 1'b0;
    end
end

always @ (*) begin
    if ((do_init_reg_389 == 1'd0)) begin
        ap_phi_mux_bx_V14_phi_phi_fu_438_p4 = ap_phi_mux_bx_V14_rewind_phi_fu_423_p6;
    end else begin
        ap_phi_mux_bx_V14_phi_phi_fu_438_p4 = ap_phi_reg_pp0_iter1_bx_V14_phi_reg_433;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln79_reg_1178_pp0_iter1_reg == 1'd0))) begin
        ap_phi_mux_bx_V14_rewind_phi_fu_423_p6 = bx_V14_phi_reg_433;
    end else begin
        ap_phi_mux_bx_V14_rewind_phi_fu_423_p6 = bx_V14_rewind_reg_419;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_236)) begin
        if ((icmp_ln79_reg_1178 == 1'd1)) begin
            ap_phi_mux_do_init_phi_fu_393_p6 = 1'd1;
        end else if ((icmp_ln79_reg_1178 == 1'd0)) begin
            ap_phi_mux_do_init_phi_fu_393_p6 = 1'd0;
        end else begin
            ap_phi_mux_do_init_phi_fu_393_p6 = do_init_reg_389;
        end
    end else begin
        ap_phi_mux_do_init_phi_fu_393_p6 = do_init_reg_389;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_236)) begin
        if ((icmp_ln79_reg_1178 == 1'd1)) begin
            ap_phi_mux_istep_0_i13_phi_fu_409_p6 = 7'd0;
        end else if ((icmp_ln79_reg_1178 == 1'd0)) begin
            ap_phi_mux_istep_0_i13_phi_fu_409_p6 = istep_reg_1173;
        end else begin
            ap_phi_mux_istep_0_i13_phi_fu_409_p6 = istep_0_i13_reg_405;
        end
    end else begin
        ap_phi_mux_istep_0_i13_phi_fu_409_p6 = istep_0_i13_reg_405;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln79_fu_490_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to3 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((bx_o_V_1_vld_reg == 1'b0) | ((1'b1 == 1'b1) & (bx_o_V_1_vld_reg == 1'b1)))) begin
        bx_o_V_1_ack_in = 1'b1;
    end else begin
        bx_o_V_1_ack_in = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln79_reg_1178_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        bx_o_V_1_vld_in = 1'b1;
    end else begin
        bx_o_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1)))) begin
        projin_0_dataarray_data_V_ce0 = 1'b1;
    end else begin
        projin_0_dataarray_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        vmprojout_0_dataarray_data_V_ce0 = 1'b1;
    end else begin
        vmprojout_0_dataarray_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((p_Result_s_53_reg_1231 == 3'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (p_Val2_s_reg_1187_pp0_iter3_reg == 1'd1) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        vmprojout_0_dataarray_data_V_we0 = 1'b1;
    end else begin
        vmprojout_0_dataarray_data_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        vmprojout_1_dataarray_data_V_ce0 = 1'b1;
    end else begin
        vmprojout_1_dataarray_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (p_Val2_s_reg_1187_pp0_iter3_reg == 1'd1) & (p_Result_s_53_reg_1231 == 3'd1) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        vmprojout_1_dataarray_data_V_we0 = 1'b1;
    end else begin
        vmprojout_1_dataarray_data_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        vmprojout_2_dataarray_data_V_ce0 = 1'b1;
    end else begin
        vmprojout_2_dataarray_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (p_Val2_s_reg_1187_pp0_iter3_reg == 1'd1) & (p_Result_s_53_reg_1231 == 3'd2) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        vmprojout_2_dataarray_data_V_we0 = 1'b1;
    end else begin
        vmprojout_2_dataarray_data_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        vmprojout_3_dataarray_data_V_ce0 = 1'b1;
    end else begin
        vmprojout_3_dataarray_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (p_Val2_s_reg_1187_pp0_iter3_reg == 1'd1) & (p_Result_s_53_reg_1231 == 3'd3) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        vmprojout_3_dataarray_data_V_we0 = 1'b1;
    end else begin
        vmprojout_3_dataarray_data_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        vmprojout_4_dataarray_data_V_ce0 = 1'b1;
    end else begin
        vmprojout_4_dataarray_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (p_Val2_s_reg_1187_pp0_iter3_reg == 1'd1) & (p_Result_s_53_reg_1231 == 3'd4) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        vmprojout_4_dataarray_data_V_we0 = 1'b1;
    end else begin
        vmprojout_4_dataarray_data_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        vmprojout_5_dataarray_data_V_ce0 = 1'b1;
    end else begin
        vmprojout_5_dataarray_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (p_Val2_s_reg_1187_pp0_iter3_reg == 1'd1) & (p_Result_s_53_reg_1231 == 3'd5) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        vmprojout_5_dataarray_data_V_we0 = 1'b1;
    end else begin
        vmprojout_5_dataarray_data_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        vmprojout_6_dataarray_data_V_ce0 = 1'b1;
    end else begin
        vmprojout_6_dataarray_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (p_Val2_s_reg_1187_pp0_iter3_reg == 1'd1) & (p_Result_s_53_reg_1231 == 3'd6) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        vmprojout_6_dataarray_data_V_we0 = 1'b1;
    end else begin
        vmprojout_6_dataarray_data_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        vmprojout_7_dataarray_data_V_ce0 = 1'b1;
    end else begin
        vmprojout_7_dataarray_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (p_Val2_s_reg_1187_pp0_iter3_reg == 1'd1) & (p_Result_s_53_reg_1231 == 3'd7) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        vmprojout_7_dataarray_data_V_we0 = 1'b1;
    end else begin
        vmprojout_7_dataarray_data_V_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((ap_reset_idle_pp0 == 1'b0)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_reset_idle_pp0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign allprojout_dataarray_data_V_address0 = zext_ln321_1_fu_1041_p1;

assign allprojout_dataarray_data_V_d0 = tproj_data_V_reg_1196;

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((bx_o_V_1_ack_in == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((bx_o_V_1_ack_in == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((bx_o_V_1_ack_in == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1));
end

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state6_pp0_stage0_iter4 = (bx_o_V_1_ack_in == 1'b0);
end

always @ (*) begin
    ap_condition_230 = ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_236 = ((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_48 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_phi_reg_pp0_iter0_bx_V14_phi_reg_433 = 'bx;

assign bx_o_V = bx_o_V_1_data_reg;

assign bx_o_V_ap_vld = bx_o_V_1_vld_reg;

assign finez_V_fu_758_p2 = (trunc_ln214_2_fu_740_p4 - trunc_ln214_3_fu_750_p3);

assign icmp_ln133_1_fu_626_p2 = ((iseed_V_fu_610_p4 != 3'd2) ? 1'b1 : 1'b0);

assign icmp_ln133_fu_620_p2 = ((iseed_V_fu_610_p4 != 3'd3) ? 1'b1 : 1'b0);

assign icmp_ln79_fu_490_p2 = ((ap_phi_mux_istep_0_i13_phi_fu_409_p6 == 7'd107) ? 1'b1 : 1'b0);

assign icmp_ln81_fu_478_p2 = ((ap_phi_mux_istep_0_i13_phi_fu_409_p6 == 7'd0) ? 1'b1 : 1'b0);

assign icmp_ln883_fu_730_p2 = ((zbin2_V_fu_722_p3 != zbin1_V_fu_684_p3) ? 1'b1 : 1'b0);

assign icmp_ln887_fu_662_p2 = ((p_Result_s_fu_652_p4 < select_ln147_fu_644_p3) ? 1'b1 : 1'b0);

assign icmp_ln891_fu_576_p2 = ((mem_read_addr_V_fu_570_p2 < numbersin_0_V_3_fu_521_p3) ? 1'b1 : 1'b0);

assign icmp_ln895_fu_700_p2 = ((p_Result_s_fu_652_p4 > select_ln895_fu_692_p3) ? 1'b1 : 1'b0);

assign icmp_ln98_fu_515_p2 = ((numbersin_0_V_fu_509_p3 != 7'd0) ? 1'b1 : 1'b0);

assign index_V_fu_909_p3 = ((icmp_ln81_reg_1147_pp0_iter3_reg[0:0] === 1'b1) ? 7'd0 : nallproj_V_1_fu_230);

assign irinv_tmp_V_fu_782_p2 = (11'd0 - shl_ln_fu_774_p3);

assign iseed_V_fu_610_p4 = {{projin_0_dataarray_data_V_q0[59:57]}};

assign istep_fu_484_p2 = (7'd1 + ap_phi_mux_istep_0_i13_phi_fu_409_p6);

assign izproj_V_fu_600_p4 = {{projin_0_dataarray_data_V_q0[31:20]}};

assign mem_read_addr_V_fu_570_p2 = (7'd1 + select_ln81_9_fu_528_p3);

assign nallproj_V_fu_1046_p2 = (index_V_fu_909_p3 + 7'd1);

assign numbersin_0_V_3_fu_521_p3 = ((icmp_ln81_reg_1147[0:0] === 1'b1) ? numbersin_0_V_fu_509_p3 : numbersin_0_V_2_fu_186);

assign numbersin_0_V_fu_509_p3 = ((trunc_ln209_fu_505_p1[0:0] === 1'b1) ? projin_0_nentries_1_V_read_reg_1168 : projin_0_nentries_0_V_read_reg_1163);

assign nvmprojout_0_V_fu_987_p2 = (7'd1 + t_V_fu_947_p10);

assign p_Result_s_fu_652_p4 = {{ret_V_2_fu_638_p2[11:6]}};

assign p_Val2_s_fu_535_p3 = ((icmp_ln81_reg_1147[0:0] === 1'b1) ? icmp_ln98_fu_515_p2 : p_Val2_1_fu_226);

assign projin_0_dataarray_data_V_address0 = zext_ln42_fu_565_p1;

assign psseed_fu_632_p2 = (icmp_ln133_fu_620_p2 & icmp_ln133_1_fu_626_p2);

assign ret_V_2_fu_638_p2 = (izproj_V_fu_600_p4 ^ 12'd2048);

assign ret_V_fu_926_p8 = {{{{{{{index_V_fu_909_p3}, {zbin1_V_reg_1206}}, {icmp_ln883_reg_1211}}, {finez_V_reg_1216}}, {v2_V_reg_1226}}, {rinv_V_fu_921_p2}}, {psseed_reg_1201}};

assign rinv_V_fu_921_p2 = (p_Result_1_reg_1221 ^ 5'd16);

assign select_ln147_fu_644_p3 = ((psseed_fu_632_p2[0:0] === 1'b1) ? 6'd1 : 6'd4);

assign select_ln29_fu_582_p3 = ((icmp_ln891_fu_576_p2[0:0] === 1'b1) ? mem_read_addr_V_fu_570_p2 : 7'd0);

assign select_ln81_1_fu_853_p3 = ((icmp_ln81_reg_1147_pp0_iter3_reg[0:0] === 1'b1) ? 7'd0 : nvmprojout_7_V_1_fu_194);

assign select_ln81_2_fu_861_p3 = ((icmp_ln81_reg_1147_pp0_iter3_reg[0:0] === 1'b1) ? 7'd0 : nvmprojout_7_V_2_fu_198);

assign select_ln81_3_fu_869_p3 = ((icmp_ln81_reg_1147_pp0_iter3_reg[0:0] === 1'b1) ? 7'd0 : nvmprojout_7_V_3_fu_202);

assign select_ln81_4_fu_877_p3 = ((icmp_ln81_reg_1147_pp0_iter3_reg[0:0] === 1'b1) ? 7'd0 : nvmprojout_7_V_4_fu_206);

assign select_ln81_5_fu_885_p3 = ((icmp_ln81_reg_1147_pp0_iter3_reg[0:0] === 1'b1) ? 7'd0 : nvmprojout_7_V_5_fu_210);

assign select_ln81_6_fu_893_p3 = ((icmp_ln81_reg_1147_pp0_iter3_reg[0:0] === 1'b1) ? 7'd0 : nvmprojout_7_V_6_fu_214);

assign select_ln81_7_fu_901_p3 = ((icmp_ln81_reg_1147_pp0_iter3_reg[0:0] === 1'b1) ? 7'd0 : nvmprojout_7_V_7_fu_218);

assign select_ln81_9_fu_528_p3 = ((icmp_ln81_reg_1147[0:0] === 1'b1) ? 7'd0 : mem_rea_010_fu_222);

assign select_ln81_fu_845_p3 = ((icmp_ln81_reg_1147_pp0_iter3_reg[0:0] === 1'b1) ? 7'd0 : nvmprojout_7_V_fu_190);

assign select_ln895_fu_692_p3 = ((psseed_fu_632_p2[0:0] === 1'b1) ? 6'd62 : 6'd59);

assign shl_ln_fu_774_p3 = {{tmp_3_fu_764_p4}, {1'd0}};

assign t_V_fu_947_p1 = ((icmp_ln81_reg_1147_pp0_iter3_reg[0:0] === 1'b1) ? 7'd0 : nvmprojout_7_V_7_fu_218);

assign t_V_fu_947_p2 = ((icmp_ln81_reg_1147_pp0_iter3_reg[0:0] === 1'b1) ? 7'd0 : nvmprojout_7_V_6_fu_214);

assign t_V_fu_947_p3 = ((icmp_ln81_reg_1147_pp0_iter3_reg[0:0] === 1'b1) ? 7'd0 : nvmprojout_7_V_5_fu_210);

assign t_V_fu_947_p4 = ((icmp_ln81_reg_1147_pp0_iter3_reg[0:0] === 1'b1) ? 7'd0 : nvmprojout_7_V_4_fu_206);

assign t_V_fu_947_p5 = ((icmp_ln81_reg_1147_pp0_iter3_reg[0:0] === 1'b1) ? 7'd0 : nvmprojout_7_V_3_fu_202);

assign t_V_fu_947_p6 = ((icmp_ln81_reg_1147_pp0_iter3_reg[0:0] === 1'b1) ? 7'd0 : nvmprojout_7_V_2_fu_198);

assign t_V_fu_947_p7 = ((icmp_ln81_reg_1147_pp0_iter3_reg[0:0] === 1'b1) ? 7'd0 : nvmprojout_7_V_1_fu_194);

assign t_V_fu_947_p8 = ((icmp_ln81_reg_1147_pp0_iter3_reg[0:0] === 1'b1) ? 7'd0 : nvmprojout_7_V_fu_190);

assign tmp_2_fu_557_p3 = {{trunc_ln209_fu_505_p1}, {select_ln81_9_fu_528_p3}};

assign tmp_3_fu_764_p4 = {{projin_0_dataarray_data_V_q0[19:10]}};

assign tmp_4_fu_968_p3 = {{trunc_ln209_reg_1182_pp0_iter3_reg}, {t_V_fu_947_p10}};

assign tmp_5_fu_1033_p3 = {{bx_V14_phi_reg_433_pp0_iter3_reg}, {index_V_fu_909_p3}};

assign trunc_ln1_fu_674_p4 = {{zbinlower_V_fu_668_p2[5:3]}};

assign trunc_ln209_fu_505_p1 = ap_phi_mux_bx_V14_phi_phi_fu_438_p4[0:0];

assign trunc_ln214_2_fu_740_p4 = {{projin_0_dataarray_data_V_q0[29:26]}};

assign trunc_ln214_3_fu_750_p3 = {{trunc_ln312_fu_736_p1}, {3'd0}};

assign trunc_ln2_fu_712_p4 = {{zbinupper_V_fu_706_p2[5:3]}};

assign trunc_ln312_fu_736_p1 = zbin1_V_fu_684_p3[0:0];

assign vmprojout_0_dataarray_data_V_address0 = zext_ln321_fu_975_p1;

assign vmprojout_0_dataarray_data_V_d0 = ret_V_fu_926_p8;

assign vmprojout_1_dataarray_data_V_address0 = zext_ln321_fu_975_p1;

assign vmprojout_1_dataarray_data_V_d0 = ret_V_fu_926_p8;

assign vmprojout_2_dataarray_data_V_address0 = zext_ln321_fu_975_p1;

assign vmprojout_2_dataarray_data_V_d0 = ret_V_fu_926_p8;

assign vmprojout_3_dataarray_data_V_address0 = zext_ln321_fu_975_p1;

assign vmprojout_3_dataarray_data_V_d0 = ret_V_fu_926_p8;

assign vmprojout_4_dataarray_data_V_address0 = zext_ln321_fu_975_p1;

assign vmprojout_4_dataarray_data_V_d0 = ret_V_fu_926_p8;

assign vmprojout_5_dataarray_data_V_address0 = zext_ln321_fu_975_p1;

assign vmprojout_5_dataarray_data_V_d0 = ret_V_fu_926_p8;

assign vmprojout_6_dataarray_data_V_address0 = zext_ln321_fu_975_p1;

assign vmprojout_6_dataarray_data_V_d0 = ret_V_fu_926_p8;

assign vmprojout_7_dataarray_data_V_address0 = zext_ln321_fu_975_p1;

assign vmprojout_7_dataarray_data_V_d0 = ret_V_fu_926_p8;

assign zbin1_V_fu_684_p3 = ((icmp_ln887_fu_662_p2[0:0] === 1'b1) ? 3'd0 : trunc_ln1_fu_674_p4);

assign zbin2_V_fu_722_p3 = ((icmp_ln895_fu_700_p2[0:0] === 1'b1) ? 3'd7 : trunc_ln2_fu_712_p4);

assign zbinlower_V_fu_668_p2 = (p_Result_s_fu_652_p4 - select_ln147_fu_644_p3);

assign zbinupper_V_fu_706_p2 = (select_ln147_fu_644_p3 + p_Result_s_fu_652_p4);

assign zext_ln321_1_fu_1041_p1 = tmp_5_fu_1033_p3;

assign zext_ln321_fu_975_p1 = tmp_4_fu_968_p3;

assign zext_ln42_fu_565_p1 = tmp_2_fu_557_p3;

endmodule //ProjectionRouterTop_L3PHIB
