// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="InputRouterTop_IR_DTC_2S_3_A,hls_ip_2020_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xcvu7p-flvb2104-1-e,HLS_INPUT_CLOCK=4.167000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.527708,HLS_SYN_LAT=110,HLS_SYN_TPT=none,HLS_SYN_MEM=5,HLS_SYN_DSP=0,HLS_SYN_FF=1007,HLS_SYN_LUT=2133,HLS_VERSION=2020_1}" *)

module InputRouterTop_IR_DTC_2S_3_A (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        hInputStubs_V_dout,
        hInputStubs_V_empty_n,
        hInputStubs_V_read,
        bx_V,
        hLinkWord_V,
        hPhBnWord_V,
        bx_o_V,
        bx_o_V_ap_vld,
        hOutputStubs_0_dataarray_data_V_address0,
        hOutputStubs_0_dataarray_data_V_ce0,
        hOutputStubs_0_dataarray_data_V_we0,
        hOutputStubs_0_dataarray_data_V_d0
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_pp0_stage0 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [38:0] hInputStubs_V_dout;
input   hInputStubs_V_empty_n;
output   hInputStubs_V_read;
input  [2:0] bx_V;
input  [19:0] hLinkWord_V;
input  [31:0] hPhBnWord_V;
output  [2:0] bx_o_V;
output   bx_o_V_ap_vld;
output  [7:0] hOutputStubs_0_dataarray_data_V_address0;
output   hOutputStubs_0_dataarray_data_V_ce0;
output   hOutputStubs_0_dataarray_data_V_we0;
output  [35:0] hOutputStubs_0_dataarray_data_V_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg hInputStubs_V_read;
reg hOutputStubs_0_dataarray_data_V_ce0;
reg hOutputStubs_0_dataarray_data_V_we0;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] icmp_ln315_fu_777_p2;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_state4_pp0_stage0_iter2;
reg    bx_o_V_1_ack_in;
reg    ap_block_state5_pp0_stage0_iter3;
reg    ap_enable_reg_pp0_iter3;
reg    ap_block_pp0_stage0_11001;
reg   [2:0] bx_o_V_1_data_reg;
reg    bx_o_V_1_vld_reg;
reg    bx_o_V_1_vld_in;
wire   [5:0] kPhiCorrtable_L1_address0;
reg    kPhiCorrtable_L1_ce0;
wire   [14:0] kPhiCorrtable_L1_q0;
wire   [5:0] kPhiCorrtable_L1_address1;
reg    kPhiCorrtable_L1_ce1;
wire   [14:0] kPhiCorrtable_L1_q1;
wire   [5:0] kPhiCorrtable_L2_address0;
reg    kPhiCorrtable_L2_ce0;
wire   [13:0] kPhiCorrtable_L2_q0;
wire   [5:0] kPhiCorrtable_L2_address1;
reg    kPhiCorrtable_L2_ce1;
wire   [13:0] kPhiCorrtable_L2_q1;
wire   [5:0] kPhiCorrtable_L3_address0;
reg    kPhiCorrtable_L3_ce0;
wire   [13:0] kPhiCorrtable_L3_q0;
wire   [5:0] kPhiCorrtable_L3_address1;
reg    kPhiCorrtable_L3_ce1;
wire   [13:0] kPhiCorrtable_L3_q1;
wire   [6:0] kPhiCorrtable_L4_address0;
reg    kPhiCorrtable_L4_ce0;
wire   [15:0] kPhiCorrtable_L4_q0;
wire   [6:0] kPhiCorrtable_L4_address1;
reg    kPhiCorrtable_L4_ce1;
wire   [15:0] kPhiCorrtable_L4_q1;
wire   [6:0] kPhiCorrtable_L5_address0;
reg    kPhiCorrtable_L5_ce0;
wire   [15:0] kPhiCorrtable_L5_q0;
wire   [6:0] kPhiCorrtable_L5_address1;
reg    kPhiCorrtable_L5_ce1;
wire   [15:0] kPhiCorrtable_L5_q1;
wire   [6:0] kPhiCorrtable_L6_address0;
reg    kPhiCorrtable_L6_ce0;
wire   [15:0] kPhiCorrtable_L6_q0;
wire   [6:0] kPhiCorrtable_L6_address1;
reg    kPhiCorrtable_L6_ce1;
wire   [15:0] kPhiCorrtable_L6_q1;
reg    hInputStubs_V_blk_n;
wire    ap_block_pp0_stage0;
reg   [0:0] do_init_reg_434;
reg   [0:0] p_rewind_reg_450;
reg   [2:0] bx_V3_rewind_reg_464;
reg   [19:0] hLinkWord_V4_rewind_reg_478;
reg   [31:0] hPhBnWord_V5_rewind_reg_492;
reg   [6:0] cStubCounter_0_i2_reg_506;
reg   [0:0] p_phi_reg_520;
reg   [0:0] p_phi_reg_520_pp0_iter1_reg;
reg   [0:0] p_phi_reg_520_pp0_iter2_reg;
reg   [2:0] bx_V3_phi_reg_532;
reg   [2:0] bx_V3_phi_reg_532_pp0_iter1_reg;
reg   [2:0] bx_V3_phi_reg_532_pp0_iter2_reg;
reg   [19:0] hLinkWord_V4_phi_reg_546;
reg   [19:0] hLinkWord_V4_phi_reg_546_pp0_iter1_reg;
reg   [19:0] hLinkWord_V4_phi_reg_546_pp0_iter2_reg;
reg   [31:0] hPhBnWord_V5_phi_reg_559;
reg   [31:0] hPhBnWord_V5_phi_reg_559_pp0_iter1_reg;
reg   [31:0] hPhBnWord_V5_phi_reg_559_pp0_iter2_reg;
reg   [6:0] hEntries_V1_reg_572;
reg   [38:0] hStub_V_reg_1520;
reg   [38:0] hStub_V_reg_1520_pp0_iter1_reg;
reg   [38:0] hStub_V_reg_1520_pp0_iter2_reg;
wire   [0:0] icmp_ln879_fu_613_p2;
reg   [0:0] icmp_ln879_reg_1529;
reg   [0:0] icmp_ln879_reg_1529_pp0_iter1_reg;
reg   [0:0] icmp_ln879_reg_1529_pp0_iter2_reg;
wire   [6:0] cStubCounter_fu_619_p2;
reg   [6:0] cStubCounter_reg_1533;
wire   [0:0] trunc_ln647_fu_625_p1;
reg   [0:0] trunc_ln647_reg_1538;
reg   [0:0] trunc_ln647_reg_1538_pp0_iter1_reg;
reg   [0:0] trunc_ln647_reg_1538_pp0_iter2_reg;
wire   [1:0] tmp_fu_629_p4;
reg   [1:0] tmp_reg_1542;
reg   [1:0] tmp_reg_1542_pp0_iter1_reg;
reg   [1:0] tmp_reg_1542_pp0_iter2_reg;
wire   [3:0] Hi_fu_639_p3;
reg   [3:0] Hi_reg_1547;
reg   [3:0] Hi_reg_1547_pp0_iter1_reg;
reg   [3:0] Hi_reg_1547_pp0_iter2_reg;
wire   [0:0] icmp_ln681_fu_659_p2;
reg   [0:0] icmp_ln681_reg_1552;
wire   [4:0] zext_ln681_fu_665_p1;
reg   [4:0] zext_ln681_reg_1558;
wire   [4:0] sub_ln681_1_fu_679_p2;
reg   [4:0] sub_ln681_1_reg_1563;
wire   [4:0] sub_ln681_3_fu_699_p2;
reg   [4:0] sub_ln681_3_reg_1568;
reg   [0:0] icmp_ln315_reg_1633;
reg   [0:0] icmp_ln315_reg_1633_pp0_iter1_reg;
reg   [0:0] icmp_ln315_reg_1633_pp0_iter2_reg;
wire   [0:0] icmp_ln136_5_fu_876_p2;
reg   [0:0] icmp_ln136_5_reg_1637;
wire   [0:0] or_ln136_fu_894_p2;
reg   [0:0] or_ln136_reg_1643;
wire   [0:0] or_ln136_2_fu_922_p2;
reg   [0:0] or_ln136_2_reg_1649;
wire   [15:0] select_ln136_3_fu_928_p3;
reg   [15:0] select_ln136_3_reg_1655;
wire   [0:0] or_ln136_3_fu_936_p2;
reg   [0:0] or_ln136_3_reg_1660;
wire   [15:0] select_ln136_4_fu_942_p3;
reg   [15:0] select_ln136_4_reg_1668;
wire   [15:0] select_ln136_9_fu_978_p3;
reg   [15:0] select_ln136_9_reg_1673;
wire   [15:0] select_ln136_10_fu_986_p3;
reg   [15:0] select_ln136_10_reg_1678;
wire   [5:0] sub_ln681_6_fu_1173_p2;
reg   [5:0] sub_ln681_6_reg_1683;
wire   [32:0] lshr_ln681_2_fu_1183_p2;
reg   [32:0] lshr_ln681_2_reg_1688;
wire   [5:0] sub_ln681_9_fu_1350_p2;
reg   [5:0] sub_ln681_9_reg_1693;
wire   [32:0] lshr_ln681_4_fu_1360_p2;
reg   [32:0] lshr_ln681_4_reg_1698;
reg    ap_enable_reg_pp0_iter1;
reg    ap_block_pp0_stage0_subdone;
reg    ap_enable_reg_pp0_iter2;
reg   [0:0] ap_phi_mux_do_init_phi_fu_438_p6;
reg   [0:0] ap_phi_mux_p_rewind_phi_fu_454_p6;
reg   [2:0] ap_phi_mux_bx_V3_rewind_phi_fu_468_p6;
reg   [19:0] ap_phi_mux_hLinkWord_V4_rewind_phi_fu_482_p6;
reg   [31:0] ap_phi_mux_hPhBnWord_V5_rewind_phi_fu_496_p6;
reg   [6:0] ap_phi_mux_cStubCounter_0_i2_phi_fu_510_p6;
wire   [0:0] ap_phi_reg_pp0_iter0_p_phi_reg_520;
wire   [2:0] ap_phi_reg_pp0_iter0_bx_V3_phi_reg_532;
wire   [19:0] ap_phi_reg_pp0_iter0_hLinkWord_V4_phi_reg_546;
wire   [31:0] ap_phi_reg_pp0_iter0_hPhBnWord_V5_phi_reg_559;
reg   [6:0] ap_phi_mux_hEntries_V_phi_fu_590_p8;
wire   [6:0] ap_phi_reg_pp0_iter3_hEntries_V_reg_586;
wire   [0:0] tmp_14_fu_1486_p3;
wire   [6:0] hNStubs_0_V_fu_1494_p2;
wire   [63:0] zext_ln544_fu_757_p1;
wire   [63:0] zext_ln544_1_fu_767_p1;
wire   [63:0] zext_ln321_fu_1513_p1;
reg    ap_block_pp0_stage0_01001;
wire   [3:0] Lo_1_fu_653_p2;
wire   [3:0] Hi_1_fu_647_p2;
wire   [4:0] zext_ln681_1_fu_669_p1;
wire   [4:0] sub_ln681_fu_673_p2;
wire   [4:0] sub_ln681_2_fu_685_p2;
wire   [4:0] select_ln681_fu_691_p3;
wire   [2:0] trunc_ln1_fu_715_p4;
wire   [3:0] hBend_V_fu_705_p4;
wire   [2:0] rbin_V_fu_725_p2;
wire   [2:0] hBend_V_1_fu_739_p4;
wire   [6:0] tmp_5_fu_731_p3;
wire   [5:0] tmp_6_fu_749_p3;
reg   [19:0] tmp_3_fu_783_p4;
wire   [4:0] select_ln681_2_fu_800_p3;
wire   [19:0] select_ln681_1_fu_793_p3;
wire   [19:0] zext_ln681_2_fu_805_p1;
wire   [19:0] zext_ln681_3_fu_809_p1;
wire   [19:0] lshr_ln681_fu_812_p2;
wire   [19:0] lshr_ln681_1_fu_818_p2;
wire   [19:0] p_Result_s_fu_824_p2;
wire  signed [14:0] sext_ln143_fu_830_p1;
wire   [14:0] select_ln136_fu_882_p3;
wire   [0:0] icmp_ln136_4_fu_870_p2;
wire   [0:0] icmp_ln136_3_fu_864_p2;
wire  signed [15:0] sext_ln147_fu_834_p1;
wire   [0:0] icmp_ln136_2_fu_858_p2;
wire   [0:0] icmp_ln136_1_fu_852_p2;
wire   [0:0] icmp_ln136_fu_846_p2;
wire  signed [15:0] sext_ln136_fu_890_p1;
wire   [15:0] select_ln136_1_fu_900_p3;
wire   [0:0] or_ln136_1_fu_908_p2;
wire   [15:0] select_ln136_2_fu_914_p3;
wire  signed [14:0] sext_ln143_1_fu_838_p1;
wire   [14:0] select_ln136_6_fu_950_p3;
wire  signed [15:0] sext_ln147_1_fu_842_p1;
wire  signed [15:0] sext_ln136_1_fu_958_p1;
wire   [15:0] select_ln136_7_fu_962_p3;
wire   [15:0] select_ln136_8_fu_970_p3;
wire   [16:0] hPhi_V_fu_994_p4;
wire   [15:0] corrval_12_fu_1012_p3;
wire   [18:0] zext_ln215_fu_1017_p1;
wire  signed [18:0] sext_ln215_fu_1021_p1;
wire   [18:0] ret_V_fu_1025_p2;
wire   [0:0] tmp_7_fu_1035_p3;
wire   [17:0] trunc_ln1354_fu_1031_p1;
wire   [17:0] select_ln166_fu_1043_p3;
wire   [0:0] tmp_9_fu_1055_p3;
wire   [16:0] trunc_ln166_fu_1051_p1;
wire   [16:0] p_Val2_5_fu_1063_p3;
wire   [1:0] select_ln171_fu_1075_p3;
wire   [1:0] select_ln171_1_fu_1082_p3;
wire  signed [3:0] sext_ln171_fu_1089_p1;
wire   [4:0] zext_ln171_fu_1093_p1;
wire   [4:0] select_ln171_2_fu_1097_p3;
wire   [4:0] cBn_l_index_fu_1104_p3;
wire   [32:0] zext_ln168_fu_1071_p1;
wire   [5:0] zext_ln681_4_fu_1117_p1;
wire   [0:0] icmp_ln681_1_fu_1111_p2;
wire   [5:0] add_ln681_fu_1131_p2;
wire   [5:0] sub_ln681_5_fu_1143_p2;
reg   [32:0] tmp_10_fu_1121_p4;
wire   [5:0] sub_ln681_4_fu_1137_p2;
wire   [5:0] select_ln681_3_fu_1149_p3;
wire   [5:0] select_ln681_5_fu_1165_p3;
wire   [32:0] select_ln681_4_fu_1157_p3;
wire   [32:0] zext_ln681_5_fu_1179_p1;
wire   [13:0] hPhi_V_1_fu_1003_p4;
wire   [15:0] corrval_13_fu_1189_p3;
wire   [16:0] zext_ln215_1_fu_1194_p1;
wire  signed [16:0] sext_ln215_1_fu_1198_p1;
wire   [16:0] ret_V_1_fu_1202_p2;
wire   [0:0] tmp_11_fu_1212_p3;
wire   [15:0] trunc_ln1354_1_fu_1208_p1;
wire   [15:0] select_ln166_1_fu_1220_p3;
wire   [1:0] tmp_12_fu_1232_p4;
wire   [0:0] icmp_ln891_fu_1242_p2;
wire   [13:0] trunc_ln166_1_fu_1228_p1;
wire   [13:0] p_Val2_6_fu_1248_p3;
wire   [3:0] select_ln171_4_fu_1260_p3;
wire   [3:0] select_ln171_5_fu_1267_p3;
wire   [3:0] select_ln171_6_fu_1274_p3;
wire   [3:0] cBn_l_index_1_fu_1281_p3;
wire   [32:0] zext_ln168_1_fu_1256_p1;
wire   [5:0] zext_ln681_7_fu_1294_p1;
wire   [0:0] icmp_ln681_2_fu_1288_p2;
wire   [5:0] add_ln681_1_fu_1308_p2;
wire   [5:0] sub_ln681_8_fu_1320_p2;
reg   [32:0] tmp_13_fu_1298_p4;
wire   [5:0] sub_ln681_7_fu_1314_p2;
wire   [5:0] select_ln681_6_fu_1326_p3;
wire   [5:0] select_ln681_8_fu_1342_p3;
wire   [32:0] select_ln681_7_fu_1334_p3;
wire   [32:0] zext_ln681_8_fu_1356_p1;
wire   [31:0] zext_ln555_fu_1376_p1;
wire   [1:0] p_Result_4_fu_1387_p4;
wire   [1:0] p_Result_5_fu_1396_p4;
wire   [1:0] select_ln647_fu_1405_p3;
wire   [32:0] zext_ln681_6_fu_1417_p1;
wire   [32:0] lshr_ln681_3_fu_1420_p2;
wire   [32:0] zext_ln681_9_fu_1431_p1;
wire   [32:0] lshr_ln681_5_fu_1434_p2;
wire   [32:0] p_Result_1_fu_1426_p2;
wire   [32:0] p_Result_2_fu_1440_p2;
wire   [31:0] trunc_ln647_1_fu_1445_p1;
wire   [31:0] trunc_ln647_2_fu_1449_p1;
wire   [0:0] tmp_2_fu_1379_p3;
wire   [31:0] cIndxThisBn_1_fu_1453_p3;
wire   [31:0] cIndxThisBn_fu_1413_p1;
wire   [4:0] shl_ln_fu_1469_p3;
wire   [31:0] cIndxThisBn_2_fu_1461_p3;
wire   [31:0] zext_ln555_1_fu_1476_p1;
wire   [31:0] Hi_2_fu_1480_p2;
wire   [0:0] trunc_ln321_fu_1501_p1;
wire   [7:0] tmp_8_fu_1505_p3;
reg   [1:0] ap_NS_fsm;
reg    ap_idle_pp0_0to2;
reg    ap_reset_idle_pp0;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_314;
reg    ap_condition_54;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 bx_o_V_1_data_reg = 3'd0;
#0 bx_o_V_1_vld_reg = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
end

InputRouterTop_IR_DTC_2S_3_A_kPhiCorrtable_L1 #(
    .DataWidth( 15 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
kPhiCorrtable_L1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(kPhiCorrtable_L1_address0),
    .ce0(kPhiCorrtable_L1_ce0),
    .q0(kPhiCorrtable_L1_q0),
    .address1(kPhiCorrtable_L1_address1),
    .ce1(kPhiCorrtable_L1_ce1),
    .q1(kPhiCorrtable_L1_q1)
);

InputRouterTop_IR_DTC_2S_3_A_kPhiCorrtable_L2 #(
    .DataWidth( 14 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
kPhiCorrtable_L2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(kPhiCorrtable_L2_address0),
    .ce0(kPhiCorrtable_L2_ce0),
    .q0(kPhiCorrtable_L2_q0),
    .address1(kPhiCorrtable_L2_address1),
    .ce1(kPhiCorrtable_L2_ce1),
    .q1(kPhiCorrtable_L2_q1)
);

InputRouterTop_IR_DTC_2S_3_A_kPhiCorrtable_L3 #(
    .DataWidth( 14 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
kPhiCorrtable_L3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(kPhiCorrtable_L3_address0),
    .ce0(kPhiCorrtable_L3_ce0),
    .q0(kPhiCorrtable_L3_q0),
    .address1(kPhiCorrtable_L3_address1),
    .ce1(kPhiCorrtable_L3_ce1),
    .q1(kPhiCorrtable_L3_q1)
);

InputRouterTop_IR_DTC_2S_3_A_kPhiCorrtable_L4 #(
    .DataWidth( 16 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
kPhiCorrtable_L4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(kPhiCorrtable_L4_address0),
    .ce0(kPhiCorrtable_L4_ce0),
    .q0(kPhiCorrtable_L4_q0),
    .address1(kPhiCorrtable_L4_address1),
    .ce1(kPhiCorrtable_L4_ce1),
    .q1(kPhiCorrtable_L4_q1)
);

InputRouterTop_IR_DTC_2S_3_A_kPhiCorrtable_L5 #(
    .DataWidth( 16 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
kPhiCorrtable_L5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(kPhiCorrtable_L5_address0),
    .ce0(kPhiCorrtable_L5_ce0),
    .q0(kPhiCorrtable_L5_q0),
    .address1(kPhiCorrtable_L5_address1),
    .ce1(kPhiCorrtable_L5_ce1),
    .q1(kPhiCorrtable_L5_q1)
);

InputRouterTop_IR_DTC_2S_3_A_kPhiCorrtable_L6 #(
    .DataWidth( 16 ),
    .AddressRange( 128 ),
    .AddressWidth( 7 ))
kPhiCorrtable_L6_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(kPhiCorrtable_L6_address0),
    .ce0(kPhiCorrtable_L6_ce0),
    .q0(kPhiCorrtable_L6_q0),
    .address1(kPhiCorrtable_L6_address1),
    .ce1(kPhiCorrtable_L6_ce1),
    .q1(kPhiCorrtable_L6_q1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter3 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_54)) begin
        if ((ap_phi_mux_do_init_phi_fu_438_p6 == 1'd0)) begin
            bx_V3_phi_reg_532 <= ap_phi_mux_bx_V3_rewind_phi_fu_468_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_438_p6 == 1'd1)) begin
            bx_V3_phi_reg_532 <= bx_V;
        end else if ((1'b1 == 1'b1)) begin
            bx_V3_phi_reg_532 <= ap_phi_reg_pp0_iter0_bx_V3_phi_reg_532;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (bx_o_V_1_vld_reg == 1'b0) & (bx_o_V_1_vld_in == 1'b1))) begin
        bx_o_V_1_vld_reg <= 1'b1;
    end else if (((bx_o_V_1_vld_in == 1'b0) & (1'b1 == 1'b1) & (bx_o_V_1_vld_reg == 1'b1))) begin
        bx_o_V_1_vld_reg <= 1'b0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln315_reg_1633 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        cStubCounter_0_i2_reg_506 <= cStubCounter_reg_1533;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln315_reg_1633 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        cStubCounter_0_i2_reg_506 <= 7'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln315_reg_1633 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        do_init_reg_434 <= 1'd0;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln315_reg_1633 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        do_init_reg_434 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln315_reg_1633_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        hEntries_V1_reg_572 <= ap_phi_mux_hEntries_V_phi_fu_590_p8;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln315_reg_1633_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        hEntries_V1_reg_572 <= 7'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_54)) begin
        if ((ap_phi_mux_do_init_phi_fu_438_p6 == 1'd0)) begin
            hLinkWord_V4_phi_reg_546 <= ap_phi_mux_hLinkWord_V4_rewind_phi_fu_482_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_438_p6 == 1'd1)) begin
            hLinkWord_V4_phi_reg_546 <= hLinkWord_V;
        end else if ((1'b1 == 1'b1)) begin
            hLinkWord_V4_phi_reg_546 <= ap_phi_reg_pp0_iter0_hLinkWord_V4_phi_reg_546;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_54)) begin
        if ((ap_phi_mux_do_init_phi_fu_438_p6 == 1'd0)) begin
            hPhBnWord_V5_phi_reg_559 <= ap_phi_mux_hPhBnWord_V5_rewind_phi_fu_496_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_438_p6 == 1'd1)) begin
            hPhBnWord_V5_phi_reg_559 <= hPhBnWord_V;
        end else if ((1'b1 == 1'b1)) begin
            hPhBnWord_V5_phi_reg_559 <= ap_phi_reg_pp0_iter0_hPhBnWord_V5_phi_reg_559;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_54)) begin
        if ((ap_phi_mux_do_init_phi_fu_438_p6 == 1'd0)) begin
            p_phi_reg_520 <= ap_phi_mux_p_rewind_phi_fu_454_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_438_p6 == 1'd1)) begin
            p_phi_reg_520 <= hLinkWord_V[32'd16];
        end else if ((1'b1 == 1'b1)) begin
            p_phi_reg_520 <= ap_phi_reg_pp0_iter0_p_phi_reg_520;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln647_fu_625_p1 == 1'd1) & (icmp_ln879_fu_613_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Hi_reg_1547[3 : 2] <= Hi_fu_639_p3[3 : 2];
        icmp_ln681_reg_1552 <= icmp_ln681_fu_659_p2;
        sub_ln681_1_reg_1563[4 : 2] <= sub_ln681_1_fu_679_p2[4 : 2];
        sub_ln681_3_reg_1568[4 : 2] <= sub_ln681_3_fu_699_p2[4 : 2];
        tmp_reg_1542 <= {{hInputStubs_V_dout[2:1]}};
        zext_ln681_reg_1558[3 : 2] <= zext_ln681_fu_665_p1[3 : 2];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Hi_reg_1547_pp0_iter1_reg[3 : 2] <= Hi_reg_1547[3 : 2];
        bx_V3_phi_reg_532_pp0_iter1_reg <= bx_V3_phi_reg_532;
        hLinkWord_V4_phi_reg_546_pp0_iter1_reg <= hLinkWord_V4_phi_reg_546;
        hPhBnWord_V5_phi_reg_559_pp0_iter1_reg <= hPhBnWord_V5_phi_reg_559;
        hStub_V_reg_1520 <= hInputStubs_V_dout;
        hStub_V_reg_1520_pp0_iter1_reg <= hStub_V_reg_1520;
        icmp_ln315_reg_1633 <= icmp_ln315_fu_777_p2;
        icmp_ln315_reg_1633_pp0_iter1_reg <= icmp_ln315_reg_1633;
        icmp_ln879_reg_1529 <= icmp_ln879_fu_613_p2;
        icmp_ln879_reg_1529_pp0_iter1_reg <= icmp_ln879_reg_1529;
        p_phi_reg_520_pp0_iter1_reg <= p_phi_reg_520;
        tmp_reg_1542_pp0_iter1_reg <= tmp_reg_1542;
        trunc_ln647_reg_1538_pp0_iter1_reg <= trunc_ln647_reg_1538;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        Hi_reg_1547_pp0_iter2_reg[3 : 2] <= Hi_reg_1547_pp0_iter1_reg[3 : 2];
        bx_V3_phi_reg_532_pp0_iter2_reg <= bx_V3_phi_reg_532_pp0_iter1_reg;
        hLinkWord_V4_phi_reg_546_pp0_iter2_reg <= hLinkWord_V4_phi_reg_546_pp0_iter1_reg;
        hPhBnWord_V5_phi_reg_559_pp0_iter2_reg <= hPhBnWord_V5_phi_reg_559_pp0_iter1_reg;
        hStub_V_reg_1520_pp0_iter2_reg <= hStub_V_reg_1520_pp0_iter1_reg;
        icmp_ln315_reg_1633_pp0_iter2_reg <= icmp_ln315_reg_1633_pp0_iter1_reg;
        icmp_ln879_reg_1529_pp0_iter2_reg <= icmp_ln879_reg_1529_pp0_iter1_reg;
        p_phi_reg_520_pp0_iter2_reg <= p_phi_reg_520_pp0_iter1_reg;
        tmp_reg_1542_pp0_iter2_reg <= tmp_reg_1542_pp0_iter1_reg;
        trunc_ln647_reg_1538_pp0_iter2_reg <= trunc_ln647_reg_1538_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln315_reg_1633 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bx_V3_rewind_reg_464 <= bx_V3_phi_reg_532;
        hLinkWord_V4_rewind_reg_478 <= hLinkWord_V4_phi_reg_546;
        hPhBnWord_V5_rewind_reg_492 <= hPhBnWord_V5_phi_reg_559;
        p_rewind_reg_450 <= p_phi_reg_520;
    end
end

always @ (posedge ap_clk) begin
    if (((~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (bx_o_V_1_vld_reg == 1'b0) & (bx_o_V_1_vld_in == 1'b1)) | (~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (1'b1 == 1'b1) & (bx_o_V_1_vld_in == 1'b1) & (bx_o_V_1_vld_reg == 1'b1)))) begin
        bx_o_V_1_data_reg <= bx_V3_phi_reg_532_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        cStubCounter_reg_1533 <= cStubCounter_fu_619_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln647_reg_1538 == 1'd1) & (icmp_ln879_reg_1529 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln136_5_reg_1637 <= icmp_ln136_5_fu_876_p2;
        or_ln136_2_reg_1649 <= or_ln136_2_fu_922_p2;
        or_ln136_3_reg_1660 <= or_ln136_3_fu_936_p2;
        or_ln136_reg_1643 <= or_ln136_fu_894_p2;
        select_ln136_10_reg_1678 <= select_ln136_10_fu_986_p3;
        select_ln136_3_reg_1655 <= select_ln136_3_fu_928_p3;
        select_ln136_4_reg_1668 <= select_ln136_4_fu_942_p3;
        select_ln136_9_reg_1673 <= select_ln136_9_fu_978_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln647_reg_1538_pp0_iter1_reg == 1'd1) & (icmp_ln879_reg_1529_pp0_iter1_reg == 1'd0))) begin
        lshr_ln681_2_reg_1688 <= lshr_ln681_2_fu_1183_p2;
        lshr_ln681_4_reg_1698 <= lshr_ln681_4_fu_1360_p2;
        sub_ln681_6_reg_1683 <= sub_ln681_6_fu_1173_p2;
        sub_ln681_9_reg_1693 <= sub_ln681_9_fu_1350_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln879_fu_613_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trunc_ln647_reg_1538 <= trunc_ln647_fu_625_p1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln315_reg_1633_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to2 = 1'b1;
    end else begin
        ap_idle_pp0_0to2 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln315_reg_1633 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_bx_V3_rewind_phi_fu_468_p6 = bx_V3_phi_reg_532;
    end else begin
        ap_phi_mux_bx_V3_rewind_phi_fu_468_p6 = bx_V3_rewind_reg_464;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_314)) begin
        if ((icmp_ln315_reg_1633 == 1'd1)) begin
            ap_phi_mux_cStubCounter_0_i2_phi_fu_510_p6 = 7'd0;
        end else if ((icmp_ln315_reg_1633 == 1'd0)) begin
            ap_phi_mux_cStubCounter_0_i2_phi_fu_510_p6 = cStubCounter_reg_1533;
        end else begin
            ap_phi_mux_cStubCounter_0_i2_phi_fu_510_p6 = cStubCounter_0_i2_reg_506;
        end
    end else begin
        ap_phi_mux_cStubCounter_0_i2_phi_fu_510_p6 = cStubCounter_0_i2_reg_506;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_314)) begin
        if ((icmp_ln315_reg_1633 == 1'd1)) begin
            ap_phi_mux_do_init_phi_fu_438_p6 = 1'd1;
        end else if ((icmp_ln315_reg_1633 == 1'd0)) begin
            ap_phi_mux_do_init_phi_fu_438_p6 = 1'd0;
        end else begin
            ap_phi_mux_do_init_phi_fu_438_p6 = do_init_reg_434;
        end
    end else begin
        ap_phi_mux_do_init_phi_fu_438_p6 = do_init_reg_434;
    end
end

always @ (*) begin
    if (((tmp_14_fu_1486_p3 == 1'd1) & (trunc_ln647_reg_1538_pp0_iter2_reg == 1'd1) & (icmp_ln879_reg_1529_pp0_iter2_reg == 1'd0))) begin
        ap_phi_mux_hEntries_V_phi_fu_590_p8 = hNStubs_0_V_fu_1494_p2;
    end else if (((icmp_ln879_reg_1529_pp0_iter2_reg == 1'd1) | ((trunc_ln647_reg_1538_pp0_iter2_reg == 1'd0) & (icmp_ln879_reg_1529_pp0_iter2_reg == 1'd0)) | ((trunc_ln647_reg_1538_pp0_iter2_reg == 1'd1) & (tmp_14_fu_1486_p3 == 1'd0) & (icmp_ln879_reg_1529_pp0_iter2_reg == 1'd0)))) begin
        ap_phi_mux_hEntries_V_phi_fu_590_p8 = hEntries_V1_reg_572;
    end else begin
        ap_phi_mux_hEntries_V_phi_fu_590_p8 = ap_phi_reg_pp0_iter3_hEntries_V_reg_586;
    end
end

always @ (*) begin
    if (((icmp_ln315_reg_1633 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_hLinkWord_V4_rewind_phi_fu_482_p6 = hLinkWord_V4_phi_reg_546;
    end else begin
        ap_phi_mux_hLinkWord_V4_rewind_phi_fu_482_p6 = hLinkWord_V4_rewind_reg_478;
    end
end

always @ (*) begin
    if (((icmp_ln315_reg_1633 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_hPhBnWord_V5_rewind_phi_fu_496_p6 = hPhBnWord_V5_phi_reg_559;
    end else begin
        ap_phi_mux_hPhBnWord_V5_rewind_phi_fu_496_p6 = hPhBnWord_V5_rewind_reg_492;
    end
end

always @ (*) begin
    if (((icmp_ln315_reg_1633 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_phi_mux_p_rewind_phi_fu_454_p6 = p_phi_reg_520;
    end else begin
        ap_phi_mux_p_rewind_phi_fu_454_p6 = p_rewind_reg_450;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln315_fu_777_p2 == 1'd1) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to2 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((bx_o_V_1_vld_reg == 1'b0) | ((1'b1 == 1'b1) & (bx_o_V_1_vld_reg == 1'b1)))) begin
        bx_o_V_1_ack_in = 1'b1;
    end else begin
        bx_o_V_1_ack_in = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln315_reg_1633_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        bx_o_V_1_vld_in = 1'b1;
    end else begin
        bx_o_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        hInputStubs_V_blk_n = hInputStubs_V_empty_n;
    end else begin
        hInputStubs_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        hInputStubs_V_read = 1'b1;
    end else begin
        hInputStubs_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        hOutputStubs_0_dataarray_data_V_ce0 = 1'b1;
    end else begin
        hOutputStubs_0_dataarray_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_14_fu_1486_p3 == 1'd1) & (trunc_ln647_reg_1538_pp0_iter2_reg == 1'd1) & (icmp_ln879_reg_1529_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        hOutputStubs_0_dataarray_data_V_we0 = 1'b1;
    end else begin
        hOutputStubs_0_dataarray_data_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        kPhiCorrtable_L1_ce0 = 1'b1;
    end else begin
        kPhiCorrtable_L1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        kPhiCorrtable_L1_ce1 = 1'b1;
    end else begin
        kPhiCorrtable_L1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        kPhiCorrtable_L2_ce0 = 1'b1;
    end else begin
        kPhiCorrtable_L2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        kPhiCorrtable_L2_ce1 = 1'b1;
    end else begin
        kPhiCorrtable_L2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        kPhiCorrtable_L3_ce0 = 1'b1;
    end else begin
        kPhiCorrtable_L3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        kPhiCorrtable_L3_ce1 = 1'b1;
    end else begin
        kPhiCorrtable_L3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        kPhiCorrtable_L4_ce0 = 1'b1;
    end else begin
        kPhiCorrtable_L4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        kPhiCorrtable_L4_ce1 = 1'b1;
    end else begin
        kPhiCorrtable_L4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        kPhiCorrtable_L5_ce0 = 1'b1;
    end else begin
        kPhiCorrtable_L5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        kPhiCorrtable_L5_ce1 = 1'b1;
    end else begin
        kPhiCorrtable_L5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        kPhiCorrtable_L6_ce0 = 1'b1;
    end else begin
        kPhiCorrtable_L6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        kPhiCorrtable_L6_ce1 = 1'b1;
    end else begin
        kPhiCorrtable_L6_ce1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((ap_reset_idle_pp0 == 1'b0)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_reset_idle_pp0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign Hi_1_fu_647_p2 = (4'd3 | Hi_fu_639_p3);

assign Hi_2_fu_1480_p2 = (cIndxThisBn_2_fu_1461_p3 + zext_ln555_1_fu_1476_p1);

assign Hi_fu_639_p3 = {{tmp_fu_629_p4}, {2'd0}};

assign Lo_1_fu_653_p2 = (4'd1 | Hi_fu_639_p3);

assign add_ln681_1_fu_1308_p2 = ($signed(6'd51) + $signed(zext_ln681_7_fu_1294_p1));

assign add_ln681_fu_1131_p2 = ($signed(6'd48) + $signed(zext_ln681_4_fu_1117_p1));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((bx_o_V_1_ack_in == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((hInputStubs_V_empty_n == 1'b0) & (ap_start == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((bx_o_V_1_ack_in == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((hInputStubs_V_empty_n == 1'b0) & (ap_start == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((bx_o_V_1_ack_in == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((hInputStubs_V_empty_n == 1'b0) & (ap_start == 1'b1)));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter0 = (hInputStubs_V_empty_n == 1'b0);
end

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state5_pp0_stage0_iter3 = (bx_o_V_1_ack_in == 1'b0);
end

always @ (*) begin
    ap_condition_314 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0));
end

always @ (*) begin
    ap_condition_54 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_phi_reg_pp0_iter0_bx_V3_phi_reg_532 = 'bx;

assign ap_phi_reg_pp0_iter0_hLinkWord_V4_phi_reg_546 = 'bx;

assign ap_phi_reg_pp0_iter0_hPhBnWord_V5_phi_reg_559 = 'bx;

assign ap_phi_reg_pp0_iter0_p_phi_reg_520 = 'bx;

assign ap_phi_reg_pp0_iter3_hEntries_V_reg_586 = 'bx;

assign bx_o_V = bx_o_V_1_data_reg;

assign bx_o_V_ap_vld = bx_o_V_1_vld_reg;

assign cBn_l_index_1_fu_1281_p3 = ((or_ln136_3_reg_1660[0:0] === 1'b1) ? select_ln171_5_fu_1267_p3 : select_ln171_6_fu_1274_p3);

assign cBn_l_index_fu_1104_p3 = ((or_ln136_3_reg_1660[0:0] === 1'b1) ? zext_ln171_fu_1093_p1 : select_ln171_2_fu_1097_p3);

assign cIndxThisBn_1_fu_1453_p3 = ((p_phi_reg_520_pp0_iter2_reg[0:0] === 1'b1) ? trunc_ln647_1_fu_1445_p1 : trunc_ln647_2_fu_1449_p1);

assign cIndxThisBn_2_fu_1461_p3 = ((tmp_2_fu_1379_p3[0:0] === 1'b1) ? cIndxThisBn_1_fu_1453_p3 : cIndxThisBn_fu_1413_p1);

assign cIndxThisBn_fu_1413_p1 = select_ln647_fu_1405_p3;

assign cStubCounter_fu_619_p2 = (ap_phi_mux_cStubCounter_0_i2_phi_fu_510_p6 + 7'd1);

assign corrval_12_fu_1012_p3 = ((or_ln136_3_reg_1660[0:0] === 1'b1) ? select_ln136_3_reg_1655 : select_ln136_4_reg_1668);

assign corrval_13_fu_1189_p3 = ((or_ln136_3_reg_1660[0:0] === 1'b1) ? select_ln136_9_reg_1673 : select_ln136_10_reg_1678);

assign hBend_V_1_fu_739_p4 = {{hInputStubs_V_dout[5:3]}};

assign hBend_V_fu_705_p4 = {{hInputStubs_V_dout[6:3]}};

assign hNStubs_0_V_fu_1494_p2 = (7'd1 + hEntries_V1_reg_572);

assign hOutputStubs_0_dataarray_data_V_address0 = zext_ln321_fu_1513_p1;

assign hOutputStubs_0_dataarray_data_V_d0 = {{hStub_V_reg_1520_pp0_iter2_reg[38:3]}};

assign hPhi_V_1_fu_1003_p4 = {{hStub_V_reg_1520_pp0_iter1_reg[19:6]}};

assign hPhi_V_fu_994_p4 = {{hStub_V_reg_1520_pp0_iter1_reg[23:7]}};

assign icmp_ln136_1_fu_852_p2 = ((p_Result_s_fu_824_p2 == 20'd5) ? 1'b1 : 1'b0);

assign icmp_ln136_2_fu_858_p2 = ((p_Result_s_fu_824_p2 == 20'd4) ? 1'b1 : 1'b0);

assign icmp_ln136_3_fu_864_p2 = ((p_Result_s_fu_824_p2 == 20'd3) ? 1'b1 : 1'b0);

assign icmp_ln136_4_fu_870_p2 = ((p_Result_s_fu_824_p2 == 20'd2) ? 1'b1 : 1'b0);

assign icmp_ln136_5_fu_876_p2 = ((p_Result_s_fu_824_p2 == 20'd1) ? 1'b1 : 1'b0);

assign icmp_ln136_fu_846_p2 = ((p_Result_s_fu_824_p2 == 20'd6) ? 1'b1 : 1'b0);

assign icmp_ln315_fu_777_p2 = ((ap_phi_mux_cStubCounter_0_i2_phi_fu_510_p6 == 7'd107) ? 1'b1 : 1'b0);

assign icmp_ln681_1_fu_1111_p2 = ((cBn_l_index_fu_1104_p3 > 5'd16) ? 1'b1 : 1'b0);

assign icmp_ln681_2_fu_1288_p2 = ((cBn_l_index_1_fu_1281_p3 > 4'd13) ? 1'b1 : 1'b0);

assign icmp_ln681_fu_659_p2 = ((Lo_1_fu_653_p2 > Hi_1_fu_647_p2) ? 1'b1 : 1'b0);

assign icmp_ln879_fu_613_p2 = ((hInputStubs_V_dout == 39'd0) ? 1'b1 : 1'b0);

assign icmp_ln891_fu_1242_p2 = ((tmp_12_fu_1232_p4 != 2'd0) ? 1'b1 : 1'b0);

assign kPhiCorrtable_L1_address0 = zext_ln544_fu_757_p1;

assign kPhiCorrtable_L1_address1 = zext_ln544_1_fu_767_p1;

assign kPhiCorrtable_L2_address0 = zext_ln544_fu_757_p1;

assign kPhiCorrtable_L2_address1 = zext_ln544_1_fu_767_p1;

assign kPhiCorrtable_L3_address0 = zext_ln544_fu_757_p1;

assign kPhiCorrtable_L3_address1 = zext_ln544_1_fu_767_p1;

assign kPhiCorrtable_L4_address0 = zext_ln544_fu_757_p1;

assign kPhiCorrtable_L4_address1 = zext_ln544_1_fu_767_p1;

assign kPhiCorrtable_L5_address0 = zext_ln544_fu_757_p1;

assign kPhiCorrtable_L5_address1 = zext_ln544_1_fu_767_p1;

assign kPhiCorrtable_L6_address0 = zext_ln544_fu_757_p1;

assign kPhiCorrtable_L6_address1 = zext_ln544_1_fu_767_p1;

assign lshr_ln681_1_fu_818_p2 = 20'd1048575 >> zext_ln681_3_fu_809_p1;

assign lshr_ln681_2_fu_1183_p2 = select_ln681_4_fu_1157_p3 >> zext_ln681_5_fu_1179_p1;

assign lshr_ln681_3_fu_1420_p2 = 33'd8589934591 >> zext_ln681_6_fu_1417_p1;

assign lshr_ln681_4_fu_1360_p2 = select_ln681_7_fu_1334_p3 >> zext_ln681_8_fu_1356_p1;

assign lshr_ln681_5_fu_1434_p2 = 33'd8589934591 >> zext_ln681_9_fu_1431_p1;

assign lshr_ln681_fu_812_p2 = select_ln681_1_fu_793_p3 >> zext_ln681_2_fu_805_p1;

assign or_ln136_1_fu_908_p2 = (icmp_ln136_3_fu_864_p2 | icmp_ln136_2_fu_858_p2);

assign or_ln136_2_fu_922_p2 = (icmp_ln136_fu_846_p2 | icmp_ln136_1_fu_852_p2);

assign or_ln136_3_fu_936_p2 = (or_ln136_fu_894_p2 | or_ln136_1_fu_908_p2);

assign or_ln136_fu_894_p2 = (icmp_ln136_5_fu_876_p2 | icmp_ln136_4_fu_870_p2);

assign p_Result_1_fu_1426_p2 = (lshr_ln681_3_fu_1420_p2 & lshr_ln681_2_reg_1688);

assign p_Result_2_fu_1440_p2 = (lshr_ln681_5_fu_1434_p2 & lshr_ln681_4_reg_1698);

assign p_Result_4_fu_1387_p4 = {{hStub_V_reg_1520_pp0_iter2_reg[24:23]}};

assign p_Result_5_fu_1396_p4 = {{hStub_V_reg_1520_pp0_iter2_reg[19:18]}};

assign p_Result_s_fu_824_p2 = (lshr_ln681_fu_812_p2 & lshr_ln681_1_fu_818_p2);

assign p_Val2_5_fu_1063_p3 = ((tmp_9_fu_1055_p3[0:0] === 1'b1) ? 17'd131071 : trunc_ln166_fu_1051_p1);

assign p_Val2_6_fu_1248_p3 = ((icmp_ln891_fu_1242_p2[0:0] === 1'b1) ? 14'd16383 : trunc_ln166_1_fu_1228_p1);

assign rbin_V_fu_725_p2 = (trunc_ln1_fu_715_p4 ^ 3'd4);

assign ret_V_1_fu_1202_p2 = ($signed(zext_ln215_1_fu_1194_p1) - $signed(sext_ln215_1_fu_1198_p1));

assign ret_V_fu_1025_p2 = ($signed(zext_ln215_fu_1017_p1) - $signed(sext_ln215_fu_1021_p1));

assign select_ln136_10_fu_986_p3 = ((or_ln136_2_fu_922_p2[0:0] === 1'b1) ? select_ln136_8_fu_970_p3 : 16'd0);

assign select_ln136_1_fu_900_p3 = ((icmp_ln136_3_fu_864_p2[0:0] === 1'b1) ? sext_ln147_fu_834_p1 : kPhiCorrtable_L4_q0);

assign select_ln136_2_fu_914_p3 = ((icmp_ln136_1_fu_852_p2[0:0] === 1'b1) ? kPhiCorrtable_L5_q0 : kPhiCorrtable_L6_q0);

assign select_ln136_3_fu_928_p3 = ((or_ln136_fu_894_p2[0:0] === 1'b1) ? sext_ln136_fu_890_p1 : select_ln136_1_fu_900_p3);

assign select_ln136_4_fu_942_p3 = ((or_ln136_2_fu_922_p2[0:0] === 1'b1) ? select_ln136_2_fu_914_p3 : 16'd0);

assign select_ln136_6_fu_950_p3 = ((icmp_ln136_5_fu_876_p2[0:0] === 1'b1) ? kPhiCorrtable_L1_q1 : sext_ln143_1_fu_838_p1);

assign select_ln136_7_fu_962_p3 = ((icmp_ln136_3_fu_864_p2[0:0] === 1'b1) ? sext_ln147_1_fu_842_p1 : kPhiCorrtable_L4_q1);

assign select_ln136_8_fu_970_p3 = ((icmp_ln136_1_fu_852_p2[0:0] === 1'b1) ? kPhiCorrtable_L5_q1 : kPhiCorrtable_L6_q1);

assign select_ln136_9_fu_978_p3 = ((or_ln136_fu_894_p2[0:0] === 1'b1) ? sext_ln136_1_fu_958_p1 : select_ln136_7_fu_962_p3);

assign select_ln136_fu_882_p3 = ((icmp_ln136_5_fu_876_p2[0:0] === 1'b1) ? kPhiCorrtable_L1_q0 : sext_ln143_fu_830_p1);

assign select_ln166_1_fu_1220_p3 = ((tmp_11_fu_1212_p3[0:0] === 1'b1) ? 16'd0 : trunc_ln1354_1_fu_1208_p1);

assign select_ln166_fu_1043_p3 = ((tmp_7_fu_1035_p3[0:0] === 1'b1) ? 18'd0 : trunc_ln1354_fu_1031_p1);

assign select_ln171_1_fu_1082_p3 = ((or_ln136_reg_1643[0:0] === 1'b1) ? select_ln171_fu_1075_p3 : 2'd3);

assign select_ln171_2_fu_1097_p3 = ((or_ln136_2_reg_1649[0:0] === 1'b1) ? 5'd15 : 5'd17);

assign select_ln171_4_fu_1260_p3 = ((icmp_ln136_5_reg_1637[0:0] === 1'b1) ? 4'd11 : 4'd12);

assign select_ln171_5_fu_1267_p3 = ((or_ln136_reg_1643[0:0] === 1'b1) ? select_ln171_4_fu_1260_p3 : 4'd12);

assign select_ln171_6_fu_1274_p3 = ((or_ln136_2_reg_1649[0:0] === 1'b1) ? 4'd12 : 4'd14);

assign select_ln171_fu_1075_p3 = ((icmp_ln136_5_reg_1637[0:0] === 1'b1) ? 2'd2 : 2'd3);

assign select_ln647_fu_1405_p3 = ((p_phi_reg_520_pp0_iter2_reg[0:0] === 1'b1) ? p_Result_4_fu_1387_p4 : p_Result_5_fu_1396_p4);

assign select_ln681_1_fu_793_p3 = ((icmp_ln681_reg_1552[0:0] === 1'b1) ? tmp_3_fu_783_p4 : hLinkWord_V4_phi_reg_546);

assign select_ln681_2_fu_800_p3 = ((icmp_ln681_reg_1552[0:0] === 1'b1) ? sub_ln681_1_reg_1563 : zext_ln681_reg_1558);

assign select_ln681_3_fu_1149_p3 = ((icmp_ln681_1_fu_1111_p2[0:0] === 1'b1) ? add_ln681_fu_1131_p2 : sub_ln681_5_fu_1143_p2);

assign select_ln681_4_fu_1157_p3 = ((icmp_ln681_1_fu_1111_p2[0:0] === 1'b1) ? tmp_10_fu_1121_p4 : zext_ln168_fu_1071_p1);

assign select_ln681_5_fu_1165_p3 = ((icmp_ln681_1_fu_1111_p2[0:0] === 1'b1) ? sub_ln681_4_fu_1137_p2 : zext_ln681_4_fu_1117_p1);

assign select_ln681_6_fu_1326_p3 = ((icmp_ln681_2_fu_1288_p2[0:0] === 1'b1) ? add_ln681_1_fu_1308_p2 : sub_ln681_8_fu_1320_p2);

assign select_ln681_7_fu_1334_p3 = ((icmp_ln681_2_fu_1288_p2[0:0] === 1'b1) ? tmp_13_fu_1298_p4 : zext_ln168_1_fu_1256_p1);

assign select_ln681_8_fu_1342_p3 = ((icmp_ln681_2_fu_1288_p2[0:0] === 1'b1) ? sub_ln681_7_fu_1314_p2 : zext_ln681_7_fu_1294_p1);

assign select_ln681_fu_691_p3 = ((icmp_ln681_fu_659_p2[0:0] === 1'b1) ? sub_ln681_fu_673_p2 : sub_ln681_2_fu_685_p2);

assign sext_ln136_1_fu_958_p1 = $signed(select_ln136_6_fu_950_p3);

assign sext_ln136_fu_890_p1 = $signed(select_ln136_fu_882_p3);

assign sext_ln143_1_fu_838_p1 = $signed(kPhiCorrtable_L2_q1);

assign sext_ln143_fu_830_p1 = $signed(kPhiCorrtable_L2_q0);

assign sext_ln147_1_fu_842_p1 = $signed(kPhiCorrtable_L3_q1);

assign sext_ln147_fu_834_p1 = $signed(kPhiCorrtable_L3_q0);

assign sext_ln171_fu_1089_p1 = $signed(select_ln171_1_fu_1082_p3);

assign sext_ln215_1_fu_1198_p1 = $signed(corrval_13_fu_1189_p3);

assign sext_ln215_fu_1021_p1 = $signed(corrval_12_fu_1012_p3);

assign shl_ln_fu_1469_p3 = {{tmp_reg_1542_pp0_iter2_reg}, {3'd0}};

assign sub_ln681_1_fu_679_p2 = ($signed(5'd19) - $signed(zext_ln681_fu_665_p1));

assign sub_ln681_2_fu_685_p2 = (zext_ln681_1_fu_669_p1 - zext_ln681_fu_665_p1);

assign sub_ln681_3_fu_699_p2 = ($signed(5'd19) - $signed(select_ln681_fu_691_p3));

assign sub_ln681_4_fu_1137_p2 = ($signed(6'd32) - $signed(zext_ln681_4_fu_1117_p1));

assign sub_ln681_5_fu_1143_p2 = (6'd16 - zext_ln681_4_fu_1117_p1);

assign sub_ln681_6_fu_1173_p2 = ($signed(6'd32) - $signed(select_ln681_3_fu_1149_p3));

assign sub_ln681_7_fu_1314_p2 = ($signed(6'd32) - $signed(zext_ln681_7_fu_1294_p1));

assign sub_ln681_8_fu_1320_p2 = (6'd13 - zext_ln681_7_fu_1294_p1);

assign sub_ln681_9_fu_1350_p2 = ($signed(6'd32) - $signed(select_ln681_6_fu_1326_p3));

assign sub_ln681_fu_673_p2 = (zext_ln681_fu_665_p1 - zext_ln681_1_fu_669_p1);

integer ap_tvar_int_0;

always @ (zext_ln168_fu_1071_p1) begin
    for (ap_tvar_int_0 = 33 - 1; ap_tvar_int_0 >= 0; ap_tvar_int_0 = ap_tvar_int_0 - 1) begin
        if (ap_tvar_int_0 > 32 - 0) begin
            tmp_10_fu_1121_p4[ap_tvar_int_0] = 1'b0;
        end else begin
            tmp_10_fu_1121_p4[ap_tvar_int_0] = zext_ln168_fu_1071_p1[32 - ap_tvar_int_0];
        end
    end
end

assign tmp_11_fu_1212_p3 = ret_V_1_fu_1202_p2[32'd16];

assign tmp_12_fu_1232_p4 = {{select_ln166_1_fu_1220_p3[15:14]}};

integer ap_tvar_int_1;

always @ (zext_ln168_1_fu_1256_p1) begin
    for (ap_tvar_int_1 = 33 - 1; ap_tvar_int_1 >= 0; ap_tvar_int_1 = ap_tvar_int_1 - 1) begin
        if (ap_tvar_int_1 > 32 - 0) begin
            tmp_13_fu_1298_p4[ap_tvar_int_1] = 1'b0;
        end else begin
            tmp_13_fu_1298_p4[ap_tvar_int_1] = zext_ln168_1_fu_1256_p1[32 - ap_tvar_int_1];
        end
    end
end

assign tmp_14_fu_1486_p3 = hPhBnWord_V5_phi_reg_559_pp0_iter2_reg[Hi_2_fu_1480_p2];

assign tmp_2_fu_1379_p3 = hLinkWord_V4_phi_reg_546_pp0_iter2_reg[zext_ln555_fu_1376_p1];

integer ap_tvar_int_2;

always @ (hLinkWord_V4_phi_reg_546) begin
    for (ap_tvar_int_2 = 20 - 1; ap_tvar_int_2 >= 0; ap_tvar_int_2 = ap_tvar_int_2 - 1) begin
        if (ap_tvar_int_2 > 19 - 0) begin
            tmp_3_fu_783_p4[ap_tvar_int_2] = 1'b0;
        end else begin
            tmp_3_fu_783_p4[ap_tvar_int_2] = hLinkWord_V4_phi_reg_546[19 - ap_tvar_int_2];
        end
    end
end

assign tmp_5_fu_731_p3 = {{hBend_V_fu_705_p4}, {rbin_V_fu_725_p2}};

assign tmp_6_fu_749_p3 = {{hBend_V_1_fu_739_p4}, {rbin_V_fu_725_p2}};

assign tmp_7_fu_1035_p3 = ret_V_fu_1025_p2[32'd18];

assign tmp_8_fu_1505_p3 = {{trunc_ln321_fu_1501_p1}, {hEntries_V1_reg_572}};

assign tmp_9_fu_1055_p3 = select_ln166_fu_1043_p3[32'd17];

assign tmp_fu_629_p4 = {{hInputStubs_V_dout[2:1]}};

assign trunc_ln1354_1_fu_1208_p1 = ret_V_1_fu_1202_p2[15:0];

assign trunc_ln1354_fu_1031_p1 = ret_V_fu_1025_p2[17:0];

assign trunc_ln166_1_fu_1228_p1 = select_ln166_1_fu_1220_p3[13:0];

assign trunc_ln166_fu_1051_p1 = select_ln166_fu_1043_p3[16:0];

assign trunc_ln1_fu_715_p4 = {{hInputStubs_V_dout[38:36]}};

assign trunc_ln321_fu_1501_p1 = bx_V3_phi_reg_532_pp0_iter2_reg[0:0];

assign trunc_ln647_1_fu_1445_p1 = p_Result_1_fu_1426_p2[31:0];

assign trunc_ln647_2_fu_1449_p1 = p_Result_2_fu_1440_p2[31:0];

assign trunc_ln647_fu_625_p1 = hInputStubs_V_dout[0:0];

assign zext_ln168_1_fu_1256_p1 = p_Val2_6_fu_1248_p3;

assign zext_ln168_fu_1071_p1 = p_Val2_5_fu_1063_p3;

assign zext_ln171_fu_1093_p1 = $unsigned(sext_ln171_fu_1089_p1);

assign zext_ln215_1_fu_1194_p1 = hPhi_V_1_fu_1003_p4;

assign zext_ln215_fu_1017_p1 = hPhi_V_fu_994_p4;

assign zext_ln321_fu_1513_p1 = tmp_8_fu_1505_p3;

assign zext_ln544_1_fu_767_p1 = tmp_6_fu_749_p3;

assign zext_ln544_fu_757_p1 = tmp_5_fu_731_p3;

assign zext_ln555_1_fu_1476_p1 = shl_ln_fu_1469_p3;

assign zext_ln555_fu_1376_p1 = Hi_reg_1547_pp0_iter2_reg;

assign zext_ln681_1_fu_669_p1 = Hi_1_fu_647_p2;

assign zext_ln681_2_fu_805_p1 = select_ln681_2_fu_800_p3;

assign zext_ln681_3_fu_809_p1 = sub_ln681_3_reg_1568;

assign zext_ln681_4_fu_1117_p1 = cBn_l_index_fu_1104_p3;

assign zext_ln681_5_fu_1179_p1 = select_ln681_5_fu_1165_p3;

assign zext_ln681_6_fu_1417_p1 = sub_ln681_6_reg_1683;

assign zext_ln681_7_fu_1294_p1 = cBn_l_index_1_fu_1281_p3;

assign zext_ln681_8_fu_1356_p1 = select_ln681_8_fu_1342_p3;

assign zext_ln681_9_fu_1431_p1 = sub_ln681_9_reg_1693;

assign zext_ln681_fu_665_p1 = Lo_1_fu_653_p2;

always @ (posedge ap_clk) begin
    Hi_reg_1547[1:0] <= 2'b00;
    Hi_reg_1547_pp0_iter1_reg[1:0] <= 2'b00;
    Hi_reg_1547_pp0_iter2_reg[1:0] <= 2'b00;
    zext_ln681_reg_1558[1:0] <= 2'b01;
    zext_ln681_reg_1558[4] <= 1'b0;
    sub_ln681_1_reg_1563[1:0] <= 2'b10;
    sub_ln681_3_reg_1568[1:0] <= 2'b01;
end

endmodule //InputRouterTop_IR_DTC_2S_3_A
