// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="TrackletEngineTop,hls_ip_2020_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xcvu7p-flvb2104-1-e,HLS_INPUT_CLOCK=4.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.067750,HLS_SYN_LAT=113,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=1177,HLS_SYN_LUT=5644,HLS_VERSION=2020_1}" *)

module TrackletEngineTop (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        bx_V,
        instubinnerdata_dataarray_data_V_address0,
        instubinnerdata_dataarray_data_V_ce0,
        instubinnerdata_dataarray_data_V_q0,
        instubinnerdata_nentries_0_V,
        instubinnerdata_nentries_1_V,
        instubouterdata_dataarray_data_V_address0,
        instubouterdata_dataarray_data_V_ce0,
        instubouterdata_dataarray_data_V_q0,
        instubouterdata_nentries_0_V_0,
        instubouterdata_nentries_0_V_1,
        instubouterdata_nentries_0_V_2,
        instubouterdata_nentries_0_V_3,
        instubouterdata_nentries_0_V_4,
        instubouterdata_nentries_0_V_5,
        instubouterdata_nentries_0_V_6,
        instubouterdata_nentries_0_V_7,
        instubouterdata_nentries_1_V_0,
        instubouterdata_nentries_1_V_1,
        instubouterdata_nentries_1_V_2,
        instubouterdata_nentries_1_V_3,
        instubouterdata_nentries_1_V_4,
        instubouterdata_nentries_1_V_5,
        instubouterdata_nentries_1_V_6,
        instubouterdata_nentries_1_V_7,
        bendinnertable_V_address0,
        bendinnertable_V_ce0,
        bendinnertable_V_q0,
        bendoutertable_V_address0,
        bendoutertable_V_ce0,
        bendoutertable_V_q0,
        bx_o_V,
        bx_o_V_ap_vld,
        outstubpair_dataarray_data_V_address0,
        outstubpair_dataarray_data_V_ce0,
        outstubpair_dataarray_data_V_we0,
        outstubpair_dataarray_data_V_d0
);

parameter    ap_ST_fsm_state1 = 2'd1;
parameter    ap_ST_fsm_pp0_stage0 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [2:0] bx_V;
output  [7:0] instubinnerdata_dataarray_data_V_address0;
output   instubinnerdata_dataarray_data_V_ce0;
input  [21:0] instubinnerdata_dataarray_data_V_q0;
input  [6:0] instubinnerdata_nentries_0_V;
input  [6:0] instubinnerdata_nentries_1_V;
output  [7:0] instubouterdata_dataarray_data_V_address0;
output   instubouterdata_dataarray_data_V_ce0;
input  [15:0] instubouterdata_dataarray_data_V_q0;
input  [4:0] instubouterdata_nentries_0_V_0;
input  [4:0] instubouterdata_nentries_0_V_1;
input  [4:0] instubouterdata_nentries_0_V_2;
input  [4:0] instubouterdata_nentries_0_V_3;
input  [4:0] instubouterdata_nentries_0_V_4;
input  [4:0] instubouterdata_nentries_0_V_5;
input  [4:0] instubouterdata_nentries_0_V_6;
input  [4:0] instubouterdata_nentries_0_V_7;
input  [4:0] instubouterdata_nentries_1_V_0;
input  [4:0] instubouterdata_nentries_1_V_1;
input  [4:0] instubouterdata_nentries_1_V_2;
input  [4:0] instubouterdata_nentries_1_V_3;
input  [4:0] instubouterdata_nentries_1_V_4;
input  [4:0] instubouterdata_nentries_1_V_5;
input  [4:0] instubouterdata_nentries_1_V_6;
input  [4:0] instubouterdata_nentries_1_V_7;
output  [7:0] bendinnertable_V_address0;
output   bendinnertable_V_ce0;
input  [0:0] bendinnertable_V_q0;
output  [7:0] bendoutertable_V_address0;
output   bendoutertable_V_ce0;
input  [0:0] bendoutertable_V_q0;
output  [2:0] bx_o_V;
output   bx_o_V_ap_vld;
output  [7:0] outstubpair_dataarray_data_V_address0;
output   outstubpair_dataarray_data_V_ce0;
output   outstubpair_dataarray_data_V_we0;
output  [13:0] outstubpair_dataarray_data_V_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg instubinnerdata_dataarray_data_V_ce0;
reg instubouterdata_dataarray_data_V_ce0;
reg bendinnertable_V_ce0;
reg bendoutertable_V_ce0;
reg outstubpair_dataarray_data_V_ce0;
reg outstubpair_dataarray_data_V_we0;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] icmp_ln108_fu_734_p2;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
wire    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_state4_pp0_stage0_iter2;
wire    ap_block_state5_pp0_stage0_iter3;
wire    ap_block_state6_pp0_stage0_iter4;
wire    ap_block_state7_pp0_stage0_iter5;
reg    bx_o_V_1_ack_in;
reg    ap_block_state8_pp0_stage0_iter6;
reg    ap_enable_reg_pp0_iter6;
reg    ap_block_pp0_stage0_11001;
reg   [2:0] bx_o_V_1_data_reg;
reg    bx_o_V_1_vld_reg;
reg    bx_o_V_1_vld_in;
reg   [0:0] do_init_reg_456;
reg   [6:0] nstubinner_V_rewind_reg_472;
reg   [0:0] p_rewind_reg_486;
reg   [2:0] bx_V30_rewind_reg_500;
reg   [0:0] p_0725_0_i15_rewind_reg_514;
reg   [6:0] istep_0_i21_reg_529;
reg   [6:0] t_V14_reg_543;
reg   [6:0] nstubinner_V_phi_reg_558;
reg   [0:0] p_phi_reg_570;
reg   [0:0] p_phi_reg_570_pp0_iter1_reg;
reg   [0:0] p_phi_reg_570_pp0_iter2_reg;
reg   [0:0] p_phi_reg_570_pp0_iter3_reg;
reg   [0:0] p_phi_reg_570_pp0_iter4_reg;
reg   [0:0] p_phi_reg_570_pp0_iter5_reg;
reg   [2:0] bx_V30_phi_reg_582;
reg   [2:0] bx_V30_phi_reg_582_pp0_iter1_reg;
reg   [2:0] bx_V30_phi_reg_582_pp0_iter2_reg;
reg   [2:0] bx_V30_phi_reg_582_pp0_iter3_reg;
reg   [2:0] bx_V30_phi_reg_582_pp0_iter4_reg;
reg   [2:0] t_V_213_reg_596;
reg   [2:0] t_V_213_reg_596_pp0_iter2_reg;
reg   [2:0] writeindextmp_V12_reg_611;
reg   [2:0] writeindextmp_V12_reg_611_pp0_iter2_reg;
reg   [3:0] p_0594_0_i19_reg_636;
reg   [3:0] p_0594_2_i_reg_673;
wire   [0:0] morestubinner_V_fu_704_p2;
reg   [0:0] ap_phi_mux_do_init_phi_fu_460_p6;
reg   [4:0] instubouterdata_nentries_0_V_0_read_reg_2775;
reg   [4:0] instubouterdata_nentries_0_V_0_read_reg_2775_pp0_iter1_reg;
reg   [4:0] instubouterdata_nentries_0_V_1_read_reg_2781;
reg   [4:0] instubouterdata_nentries_0_V_1_read_reg_2781_pp0_iter1_reg;
reg   [4:0] instubouterdata_nentries_0_V_2_read_reg_2787;
reg   [4:0] instubouterdata_nentries_0_V_2_read_reg_2787_pp0_iter1_reg;
reg   [4:0] instubouterdata_nentries_0_V_3_read_reg_2793;
reg   [4:0] instubouterdata_nentries_0_V_3_read_reg_2793_pp0_iter1_reg;
reg   [4:0] instubouterdata_nentries_0_V_4_read_reg_2799;
reg   [4:0] instubouterdata_nentries_0_V_4_read_reg_2799_pp0_iter1_reg;
reg   [4:0] instubouterdata_nentries_0_V_5_read_reg_2805;
reg   [4:0] instubouterdata_nentries_0_V_5_read_reg_2805_pp0_iter1_reg;
reg   [4:0] instubouterdata_nentries_0_V_6_read_reg_2811;
reg   [4:0] instubouterdata_nentries_0_V_6_read_reg_2811_pp0_iter1_reg;
reg   [4:0] instubouterdata_nentries_0_V_7_read_reg_2817;
reg   [4:0] instubouterdata_nentries_0_V_7_read_reg_2817_pp0_iter1_reg;
reg   [4:0] instubouterdata_nentries_1_V_0_read_reg_2823;
reg   [4:0] instubouterdata_nentries_1_V_0_read_reg_2823_pp0_iter1_reg;
reg   [4:0] instubouterdata_nentries_1_V_1_read_reg_2829;
reg   [4:0] instubouterdata_nentries_1_V_1_read_reg_2829_pp0_iter1_reg;
reg   [4:0] instubouterdata_nentries_1_V_2_read_reg_2835;
reg   [4:0] instubouterdata_nentries_1_V_2_read_reg_2835_pp0_iter1_reg;
reg   [4:0] instubouterdata_nentries_1_V_3_read_reg_2841;
reg   [4:0] instubouterdata_nentries_1_V_3_read_reg_2841_pp0_iter1_reg;
reg   [4:0] instubouterdata_nentries_1_V_4_read_reg_2847;
reg   [4:0] instubouterdata_nentries_1_V_4_read_reg_2847_pp0_iter1_reg;
reg   [4:0] instubouterdata_nentries_1_V_5_read_reg_2853;
reg   [4:0] instubouterdata_nentries_1_V_5_read_reg_2853_pp0_iter1_reg;
reg   [4:0] instubouterdata_nentries_1_V_6_read_reg_2859;
reg   [4:0] instubouterdata_nentries_1_V_6_read_reg_2859_pp0_iter1_reg;
reg   [4:0] instubouterdata_nentries_1_V_7_read_reg_2865;
reg   [4:0] instubouterdata_nentries_1_V_7_read_reg_2865_pp0_iter1_reg;
wire   [6:0] istep_fu_728_p2;
reg   [6:0] istep_reg_2871;
reg   [0:0] icmp_ln108_reg_2876;
reg   [0:0] icmp_ln108_reg_2876_pp0_iter1_reg;
reg   [0:0] icmp_ln108_reg_2876_pp0_iter2_reg;
reg   [0:0] icmp_ln108_reg_2876_pp0_iter3_reg;
reg   [0:0] icmp_ln108_reg_2876_pp0_iter4_reg;
reg   [0:0] icmp_ln108_reg_2876_pp0_iter5_reg;
wire   [2:0] writeindexplus_V_fu_740_p2;
reg   [2:0] writeindexplus_V_reg_2880;
wire   [2:0] writeindex_V_fu_746_p2;
reg   [2:0] writeindex_V_reg_2885;
wire   [0:0] or_ln123_1_fu_776_p2;
reg   [0:0] or_ln123_1_reg_2890;
reg   [0:0] or_ln123_1_reg_2890_pp0_iter2_reg;
wire   [6:0] t_V_3_fu_794_p3;
reg    ap_enable_reg_pp0_iter1;
wire   [0:0] morestubinner_V_2_fu_802_p3;
reg   [30:0] teBuffer_7_V_1_load_reg_2914;
reg   [30:0] teBuffer_7_V_15_load_reg_2933;
reg   [30:0] teBuffer_7_V_22_load_reg_2952;
reg   [30:0] teBuffer_7_V_28_load_reg_2970;
reg   [30:0] teBuffer_7_V_33_load_reg_2987;
reg   [30:0] teBuffer_7_V_37_load_reg_3003;
reg   [30:0] teBuffer_7_V_40_load_reg_3018;
reg   [30:0] teBuffer_7_V_50_load_reg_3032;
wire   [0:0] buffernotempty_V_fu_834_p2;
reg   [0:0] buffernotempty_V_reg_3045;
reg   [0:0] buffernotempty_V_reg_3045_pp0_iter3_reg;
reg   [0:0] buffernotempty_V_reg_3045_pp0_iter4_reg;
reg   [0:0] buffernotempty_V_reg_3045_pp0_iter5_reg;
reg   [21:0] innerstubdatatmp_data_V_reg_3049;
wire   [2:0] zbinstart_V_fu_840_p4;
reg   [2:0] zbinstart_V_reg_3055;
wire   [2:0] zbinlast_V_fu_862_p2;
reg   [2:0] zbinlast_V_reg_3060;
wire   [4:0] nstubsstart_V_fu_896_p3;
reg   [4:0] nstubsstart_V_reg_3065;
wire   [4:0] nstubslast_V_fu_932_p3;
reg   [4:0] nstubslast_V_reg_3070;
wire   [0:0] savestart_V_fu_940_p2;
reg   [0:0] savestart_V_reg_3075;
wire   [0:0] savelast_V_fu_952_p2;
reg   [0:0] savelast_V_reg_3095;
wire   [0:0] icmp_ln321_fu_970_p2;
reg   [0:0] icmp_ln321_reg_3107;
wire   [0:0] icmp_ln321_1_fu_976_p2;
reg   [0:0] icmp_ln321_1_reg_3115;
wire   [2:0] writeindextmp_V_fu_1000_p3;
reg    ap_enable_reg_pp0_iter2;
wire   [0:0] icmp_ln879_fu_1014_p2;
reg   [0:0] icmp_ln879_reg_3132;
wire   [0:0] icmp_ln891_fu_1115_p2;
wire   [1:0] innerstubfinephi_V_2_fu_2413_p3;
reg   [1:0] innerstubfinephi_V_2_reg_3151;
wire   [2:0] innerstubbend_V_2_fu_2420_p3;
reg   [2:0] innerstubbend_V_2_reg_3157;
wire   [6:0] innerstubindex_V_2_fu_2427_p3;
reg   [6:0] innerstubindex_V_2_reg_3162;
reg   [6:0] innerstubindex_V_2_reg_3162_pp0_iter4_reg;
reg   [6:0] innerstubindex_V_2_reg_3162_pp0_iter5_reg;
wire   [2:0] zdiffmax_V_3_fu_2434_p3;
reg   [2:0] zdiffmax_V_3_reg_3167;
wire   [2:0] zbinfirst_V_3_fu_2441_p3;
reg   [2:0] zbinfirst_V_3_reg_3172;
wire   [0:0] second_V_3_fu_2448_p3;
reg   [0:0] second_V_3_reg_3178;
reg   [6:0] outerstubindex_V_reg_3183;
reg   [6:0] outerstubindex_V_reg_3183_pp0_iter5_reg;
wire   [0:0] icmp_ln899_fu_2557_p2;
reg   [0:0] icmp_ln899_reg_3188;
reg   [0:0] icmp_ln899_reg_3188_pp0_iter5_reg;
wire   [0:0] icmp_ln891_1_fu_2563_p2;
reg   [0:0] icmp_ln891_1_reg_3193;
reg   [0:0] icmp_ln891_1_reg_3193_pp0_iter5_reg;
reg    ap_block_pp0_stage0_subdone;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
wire    ap_block_pp0_stage0;
reg   [6:0] ap_phi_mux_nstubinner_V_rewind_phi_fu_476_p6;
reg   [0:0] ap_phi_mux_p_rewind_phi_fu_490_p6;
reg   [2:0] ap_phi_mux_bx_V30_rewind_phi_fu_504_p6;
reg   [0:0] ap_phi_mux_p_0725_0_i15_rewind_phi_fu_518_p6;
reg   [6:0] ap_phi_mux_istep_0_i21_phi_fu_533_p6;
reg   [6:0] ap_phi_mux_t_V14_phi_fu_547_p6;
wire   [6:0] nstubinner_V_fu_695_p3;
wire   [6:0] ap_phi_reg_pp0_iter0_nstubinner_V_phi_reg_558;
reg   [0:0] ap_phi_mux_p_phi_phi_fu_574_p4;
wire   [0:0] trunc_ln209_fu_690_p1;
wire   [0:0] ap_phi_reg_pp0_iter0_p_phi_reg_570;
wire   [2:0] ap_phi_reg_pp0_iter0_bx_V30_phi_reg_582;
reg   [2:0] ap_phi_mux_t_V_213_phi_fu_600_p6;
reg   [2:0] ap_phi_mux_t_V_1_phi_fu_664_p4;
reg   [2:0] ap_phi_mux_writeindextmp_V12_phi_fu_615_p6;
wire   [0:0] ap_phi_reg_pp0_iter0_p_0725_0_i15_reg_626;
reg   [0:0] ap_phi_reg_pp0_iter1_p_0725_0_i15_reg_626;
reg   [3:0] ap_phi_mux_p_0594_0_i19_phi_fu_640_p6;
reg   [2:0] ap_phi_mux_p_0709_1_i_phi_fu_653_p4;
wire   [2:0] readindex_V_fu_1126_p2;
wire   [2:0] ap_phi_reg_pp0_iter2_p_0709_1_i_reg_650;
wire   [2:0] ap_phi_reg_pp0_iter2_t_V_1_reg_660;
wire   [3:0] nstubs_V_1_fu_1084_p3;
wire   [3:0] ap_phi_reg_pp0_iter2_p_0594_2_i_reg_673;
wire   [63:0] zext_ln42_fu_723_p1;
wire   [63:0] tmp_7_fu_1144_p5;
wire   [63:0] zext_ln544_fu_2577_p1;
wire   [63:0] zext_ln544_1_fu_2591_p1;
wire   [63:0] zext_ln321_fu_2653_p1;
wire   [0:0] and_ln216_fu_2618_p2;
reg   [30:0] teBuffer_7_V_1_fu_202;
wire   [30:0] teBuffer_7_V_275_fu_2169_p3;
reg   [30:0] ap_sig_allocacmp_teBuffer_7_V_1_load;
reg   [30:0] teBuffer_7_V_15_fu_206;
wire   [30:0] teBuffer_7_V_276_fu_2175_p3;
reg   [30:0] ap_sig_allocacmp_teBuffer_7_V_15_load;
reg   [30:0] teBuffer_7_V_22_fu_210;
wire   [30:0] teBuffer_7_V_277_fu_2181_p3;
reg   [30:0] ap_sig_allocacmp_teBuffer_7_V_22_load;
reg   [30:0] teBuffer_7_V_28_fu_214;
wire   [30:0] teBuffer_7_V_278_fu_2187_p3;
reg   [30:0] ap_sig_allocacmp_teBuffer_7_V_28_load;
reg   [30:0] teBuffer_7_V_33_fu_218;
wire   [30:0] teBuffer_7_V_279_fu_2193_p3;
reg   [30:0] ap_sig_allocacmp_teBuffer_7_V_33_load;
reg   [30:0] teBuffer_7_V_37_fu_222;
wire   [30:0] teBuffer_7_V_280_fu_2199_p3;
reg   [30:0] ap_sig_allocacmp_teBuffer_7_V_37_load;
reg   [30:0] teBuffer_7_V_40_fu_226;
wire   [30:0] teBuffer_7_V_281_fu_2205_p3;
reg   [30:0] ap_sig_allocacmp_teBuffer_7_V_40_load;
reg   [30:0] teBuffer_7_V_50_fu_230;
wire   [30:0] teBuffer_7_V_282_fu_2211_p3;
reg   [30:0] ap_sig_allocacmp_teBuffer_7_V_50_load;
reg   [1:0] p_Repl2_s_fu_234;
reg   [2:0] p_Repl2_1_fu_238;
reg   [6:0] p_Repl2_2_fu_242;
reg   [2:0] zdiffmax_V_2_fu_246;
reg   [2:0] zbinfirst_V_2_fu_250;
reg   [0:0] second_V_fu_254;
reg   [2:0] ibin_V_2_fu_258;
wire   [2:0] ibin_V_3_fu_1093_p3;
reg   [6:0] nstubpairs_V_fu_262;
wire   [6:0] nstubpairs_V_1_fu_2634_p2;
reg   [3:0] istubouter_V_fu_266;
wire   [3:0] istubouter_V_1_fu_1133_p2;
reg    ap_block_pp0_stage0_01001;
wire   [7:0] tmp_6_fu_715_p3;
wire   [0:0] icmp_ln123_fu_758_p2;
wire   [0:0] xor_ln123_fu_752_p2;
wire   [0:0] or_ln123_fu_770_p2;
wire   [0:0] icmp_ln123_1_fu_764_p2;
wire   [6:0] istubinner_V_fu_782_p2;
wire   [0:0] morestubinner_V_1_fu_788_p2;
wire   [0:0] tmp_1_fu_850_p3;
wire   [2:0] zext_ln209_fu_858_p1;
wire   [2:0] tmp_2_fu_868_p9;
wire   [2:0] tmp_3_fu_882_p9;
wire   [4:0] tmp_2_fu_868_p10;
wire   [4:0] tmp_3_fu_882_p10;
wire   [4:0] tmp_4_fu_904_p10;
wire   [4:0] tmp_5_fu_918_p10;
wire   [0:0] icmp_ln134_fu_946_p2;
wire   [0:0] and_ln137_fu_958_p2;
wire   [0:0] or_ln139_fu_964_p2;
wire   [0:0] or_ln123_2_fu_988_p2;
wire   [2:0] select_ln123_fu_982_p3;
wire   [2:0] select_ln123_1_fu_993_p3;
wire   [30:0] bufdata_V_fu_1020_p10;
wire   [30:0] bufdata_V1_fu_1052_p10;
wire   [3:0] nstubs_V_fu_1042_p4;
wire   [2:0] ibin_V_fu_1074_p4;
wire   [4:0] zext_ln215_fu_1101_p1;
wire   [4:0] ret_V_fu_1105_p2;
wire   [4:0] zext_ln891_fu_1111_p1;
wire   [30:0] p_Result_s_fu_1162_p5;
wire   [30:0] teBuffer_7_V_fu_1171_p3;
wire   [0:0] icmp_ln321_2_fu_1183_p2;
wire   [30:0] teBuffer_7_V_146_fu_1177_p3;
wire   [0:0] icmp_ln321_3_fu_1196_p2;
wire   [30:0] teBuffer_7_V_147_fu_1189_p3;
wire   [0:0] icmp_ln321_4_fu_1209_p2;
wire   [30:0] teBuffer_7_V_148_fu_1202_p3;
wire   [0:0] icmp_ln321_5_fu_1222_p2;
wire   [30:0] teBuffer_7_V_149_fu_1215_p3;
wire   [0:0] icmp_ln321_6_fu_1235_p2;
wire   [30:0] teBuffer_7_V_150_fu_1228_p3;
wire   [30:0] teBuffer_7_V_152_fu_1248_p3;
wire   [30:0] teBuffer_7_V_153_fu_1254_p3;
wire   [30:0] teBuffer_7_V_154_fu_1260_p3;
wire   [30:0] teBuffer_7_V_155_fu_1267_p3;
wire   [30:0] teBuffer_7_V_156_fu_1274_p3;
wire   [30:0] teBuffer_7_V_157_fu_1281_p3;
wire   [30:0] teBuffer_7_V_159_fu_1295_p3;
wire   [30:0] teBuffer_7_V_160_fu_1301_p3;
wire   [30:0] teBuffer_7_V_161_fu_1308_p3;
wire   [30:0] teBuffer_7_V_162_fu_1315_p3;
wire   [30:0] teBuffer_7_V_163_fu_1322_p3;
wire   [30:0] teBuffer_7_V_165_fu_1336_p3;
wire   [30:0] teBuffer_7_V_166_fu_1343_p3;
wire   [30:0] teBuffer_7_V_167_fu_1350_p3;
wire   [30:0] teBuffer_7_V_168_fu_1357_p3;
wire   [30:0] teBuffer_7_V_170_fu_1371_p3;
wire   [30:0] teBuffer_7_V_171_fu_1378_p3;
wire   [30:0] teBuffer_7_V_172_fu_1385_p3;
wire   [30:0] teBuffer_7_V_174_fu_1399_p3;
wire   [30:0] teBuffer_7_V_175_fu_1406_p3;
wire   [30:0] teBuffer_7_V_177_fu_1420_p3;
wire   [30:0] teBuffer_7_V_151_fu_1241_p3;
wire   [30:0] teBuffer_7_V_158_fu_1288_p3;
wire   [30:0] teBuffer_7_V_164_fu_1329_p3;
wire   [30:0] teBuffer_7_V_169_fu_1364_p3;
wire   [30:0] teBuffer_7_V_173_fu_1392_p3;
wire   [30:0] teBuffer_7_V_176_fu_1413_p3;
wire   [30:0] teBuffer_7_V_178_fu_1427_p3;
wire   [30:0] teBuffer_7_V_179_fu_1434_p3;
wire   [30:0] teBuffer_7_V_180_fu_1441_p3;
wire   [30:0] p_Result_1_fu_1489_p5;
wire   [30:0] teBuffer_7_V_189_fu_1498_p3;
wire   [30:0] teBuffer_7_V_190_fu_1505_p3;
wire   [30:0] teBuffer_7_V_191_fu_1513_p3;
wire   [30:0] teBuffer_7_V_192_fu_1521_p3;
wire   [30:0] teBuffer_7_V_193_fu_1529_p3;
wire   [0:0] icmp_ln321_7_fu_1545_p2;
wire   [30:0] teBuffer_7_V_194_fu_1537_p3;
wire   [30:0] teBuffer_7_V_181_fu_1447_p3;
wire   [30:0] teBuffer_7_V_196_fu_1559_p3;
wire   [30:0] teBuffer_7_V_197_fu_1566_p3;
wire   [30:0] teBuffer_7_V_198_fu_1574_p3;
wire   [30:0] teBuffer_7_V_199_fu_1582_p3;
wire   [30:0] teBuffer_7_V_200_fu_1590_p3;
wire   [30:0] teBuffer_7_V_201_fu_1598_p3;
wire   [30:0] teBuffer_7_V_182_fu_1453_p3;
wire   [30:0] teBuffer_7_V_203_fu_1614_p3;
wire   [30:0] teBuffer_7_V_204_fu_1622_p3;
wire   [30:0] teBuffer_7_V_205_fu_1630_p3;
wire   [30:0] teBuffer_7_V_206_fu_1638_p3;
wire   [30:0] teBuffer_7_V_207_fu_1646_p3;
wire   [30:0] teBuffer_7_V_183_fu_1459_p3;
wire   [30:0] teBuffer_7_V_209_fu_1662_p3;
wire   [30:0] teBuffer_7_V_210_fu_1670_p3;
wire   [30:0] teBuffer_7_V_211_fu_1678_p3;
wire   [30:0] teBuffer_7_V_212_fu_1686_p3;
wire   [30:0] teBuffer_7_V_184_fu_1465_p3;
wire   [30:0] teBuffer_7_V_214_fu_1702_p3;
wire   [30:0] teBuffer_7_V_215_fu_1710_p3;
wire   [30:0] teBuffer_7_V_216_fu_1718_p3;
wire   [30:0] teBuffer_7_V_185_fu_1471_p3;
wire   [30:0] teBuffer_7_V_218_fu_1734_p3;
wire   [30:0] teBuffer_7_V_219_fu_1742_p3;
wire   [30:0] teBuffer_7_V_186_fu_1477_p3;
wire   [30:0] teBuffer_7_V_221_fu_1758_p3;
wire   [30:0] teBuffer_7_V_187_fu_1483_p3;
wire   [30:0] teBuffer_7_V_224_fu_1782_p3;
wire   [30:0] teBuffer_7_V_225_fu_1789_p3;
wire   [30:0] teBuffer_7_V_226_fu_1796_p3;
wire   [30:0] teBuffer_7_V_227_fu_1804_p3;
wire   [30:0] teBuffer_7_V_228_fu_1812_p3;
wire   [30:0] teBuffer_7_V_229_fu_1820_p3;
wire   [30:0] teBuffer_7_V_231_fu_1836_p3;
wire   [30:0] teBuffer_7_V_232_fu_1843_p3;
wire   [30:0] teBuffer_7_V_233_fu_1850_p3;
wire   [30:0] teBuffer_7_V_234_fu_1858_p3;
wire   [30:0] teBuffer_7_V_235_fu_1866_p3;
wire   [30:0] teBuffer_7_V_236_fu_1874_p3;
wire   [30:0] teBuffer_7_V_238_fu_1890_p3;
wire   [30:0] teBuffer_7_V_239_fu_1897_p3;
wire   [30:0] teBuffer_7_V_240_fu_1905_p3;
wire   [30:0] teBuffer_7_V_241_fu_1913_p3;
wire   [30:0] teBuffer_7_V_242_fu_1921_p3;
wire   [30:0] teBuffer_7_V_244_fu_1937_p3;
wire   [30:0] teBuffer_7_V_245_fu_1945_p3;
wire   [30:0] teBuffer_7_V_246_fu_1953_p3;
wire   [30:0] teBuffer_7_V_247_fu_1961_p3;
wire   [30:0] teBuffer_7_V_249_fu_1977_p3;
wire   [30:0] teBuffer_7_V_250_fu_1985_p3;
wire   [30:0] teBuffer_7_V_251_fu_1993_p3;
wire   [30:0] teBuffer_7_V_253_fu_2009_p3;
wire   [30:0] teBuffer_7_V_254_fu_2017_p3;
wire   [30:0] teBuffer_7_V_256_fu_2033_p3;
wire   [30:0] teBuffer_7_V_195_fu_1551_p3;
wire   [30:0] teBuffer_7_V_230_fu_1828_p3;
wire   [30:0] teBuffer_7_V_202_fu_1606_p3;
wire   [30:0] teBuffer_7_V_237_fu_1882_p3;
wire   [30:0] teBuffer_7_V_208_fu_1654_p3;
wire   [30:0] teBuffer_7_V_243_fu_1929_p3;
wire   [30:0] teBuffer_7_V_213_fu_1694_p3;
wire   [30:0] teBuffer_7_V_248_fu_1969_p3;
wire   [30:0] teBuffer_7_V_217_fu_1726_p3;
wire   [30:0] teBuffer_7_V_252_fu_2001_p3;
wire   [30:0] teBuffer_7_V_220_fu_1750_p3;
wire   [30:0] teBuffer_7_V_255_fu_2025_p3;
wire   [30:0] teBuffer_7_V_222_fu_1766_p3;
wire   [30:0] teBuffer_7_V_257_fu_2041_p3;
wire   [30:0] teBuffer_7_V_223_fu_1774_p3;
wire   [30:0] teBuffer_7_V_258_fu_2049_p3;
wire   [30:0] teBuffer_7_V_259_fu_2057_p3;
wire   [30:0] teBuffer_7_V_260_fu_2064_p3;
wire   [30:0] teBuffer_7_V_261_fu_2071_p3;
wire   [30:0] teBuffer_7_V_262_fu_2078_p3;
wire   [30:0] teBuffer_7_V_263_fu_2085_p3;
wire   [30:0] teBuffer_7_V_264_fu_2092_p3;
wire   [30:0] teBuffer_7_V_265_fu_2099_p3;
wire   [30:0] teBuffer_7_V_266_fu_2106_p3;
wire   [30:0] teBuffer_7_V_267_fu_2113_p3;
wire   [30:0] teBuffer_7_V_268_fu_2120_p3;
wire   [30:0] teBuffer_7_V_269_fu_2127_p3;
wire   [30:0] teBuffer_7_V_270_fu_2134_p3;
wire   [30:0] teBuffer_7_V_271_fu_2141_p3;
wire   [30:0] teBuffer_7_V_272_fu_2148_p3;
wire   [30:0] teBuffer_7_V_273_fu_2155_p3;
wire   [30:0] teBuffer_7_V_274_fu_2162_p3;
wire   [30:0] bufdata_V2_fu_2275_p10;
wire   [30:0] bufdata_V3_fu_2299_p10;
wire   [30:0] bufdata_V4_fu_2323_p10;
wire   [30:0] bufdata_V5_fu_2347_p10;
wire   [30:0] bufdata_V6_fu_2371_p10;
wire   [30:0] bufdata_V7_fu_2395_p10;
wire   [1:0] innerstubfinephi_V_fu_2337_p4;
wire   [2:0] innerstubbend_V_fu_2313_p4;
wire   [6:0] innerstubindex_V_fu_2289_p4;
wire   [2:0] zdiffmax_V_fu_2361_p4;
wire   [2:0] zbinfirst_V_fu_2385_p4;
wire   [0:0] second_V_2_fu_2409_p1;
wire   [2:0] outerstubfinez_V_fu_2515_p1;
wire   [3:0] or_ln_fu_2523_p3;
wire   [3:0] zext_ln200_fu_2519_p1;
wire   [3:0] tmpz_fu_2531_p3;
wire   [4:0] zext_ln215_1_fu_2541_p1;
wire   [4:0] zext_ln215_2_fu_2545_p1;
wire   [4:0] zext_ln899_fu_2554_p1;
wire   [4:0] ret_V_1_fu_2548_p2;
wire   [3:0] zext_ln1467_fu_2538_p1;
wire   [2:0] outerstubfinephi_V_fu_2495_p4;
wire   [7:0] p_Result_2_fu_2569_p4;
wire   [2:0] outerstubbend_V_fu_2505_p4;
wire   [7:0] p_Result_3_fu_2582_p4;
wire   [0:0] xor_ln899_fu_2596_p2;
wire   [0:0] xor_ln891_fu_2601_p2;
wire   [0:0] and_ln216_2_fu_2612_p2;
wire   [0:0] and_ln216_1_fu_2606_p2;
wire   [7:0] tmp_8_fu_2645_p3;
reg   [1:0] ap_NS_fsm;
reg    ap_idle_pp0_0to5;
reg    ap_reset_idle_pp0;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_391;
reg    ap_condition_50;
reg    ap_condition_1815;
reg    ap_condition_1819;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 bx_o_V_1_data_reg = 3'd0;
#0 bx_o_V_1_vld_reg = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
end

TrackletEngineTop_mux_83_5_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 5 ),
    .din2_WIDTH( 5 ),
    .din3_WIDTH( 5 ),
    .din4_WIDTH( 5 ),
    .din5_WIDTH( 5 ),
    .din6_WIDTH( 5 ),
    .din7_WIDTH( 5 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 5 ))
TrackletEngineTop_mux_83_5_1_1_U1(
    .din0(instubouterdata_nentries_1_V_0_read_reg_2823_pp0_iter1_reg),
    .din1(instubouterdata_nentries_1_V_1_read_reg_2829_pp0_iter1_reg),
    .din2(instubouterdata_nentries_1_V_2_read_reg_2835_pp0_iter1_reg),
    .din3(instubouterdata_nentries_1_V_3_read_reg_2841_pp0_iter1_reg),
    .din4(instubouterdata_nentries_1_V_4_read_reg_2847_pp0_iter1_reg),
    .din5(instubouterdata_nentries_1_V_5_read_reg_2853_pp0_iter1_reg),
    .din6(instubouterdata_nentries_1_V_6_read_reg_2859_pp0_iter1_reg),
    .din7(instubouterdata_nentries_1_V_7_read_reg_2865_pp0_iter1_reg),
    .din8(tmp_2_fu_868_p9),
    .dout(tmp_2_fu_868_p10)
);

TrackletEngineTop_mux_83_5_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 5 ),
    .din2_WIDTH( 5 ),
    .din3_WIDTH( 5 ),
    .din4_WIDTH( 5 ),
    .din5_WIDTH( 5 ),
    .din6_WIDTH( 5 ),
    .din7_WIDTH( 5 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 5 ))
TrackletEngineTop_mux_83_5_1_1_U2(
    .din0(instubouterdata_nentries_0_V_0_read_reg_2775_pp0_iter1_reg),
    .din1(instubouterdata_nentries_0_V_1_read_reg_2781_pp0_iter1_reg),
    .din2(instubouterdata_nentries_0_V_2_read_reg_2787_pp0_iter1_reg),
    .din3(instubouterdata_nentries_0_V_3_read_reg_2793_pp0_iter1_reg),
    .din4(instubouterdata_nentries_0_V_4_read_reg_2799_pp0_iter1_reg),
    .din5(instubouterdata_nentries_0_V_5_read_reg_2805_pp0_iter1_reg),
    .din6(instubouterdata_nentries_0_V_6_read_reg_2811_pp0_iter1_reg),
    .din7(instubouterdata_nentries_0_V_7_read_reg_2817_pp0_iter1_reg),
    .din8(tmp_3_fu_882_p9),
    .dout(tmp_3_fu_882_p10)
);

TrackletEngineTop_mux_83_5_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 5 ),
    .din2_WIDTH( 5 ),
    .din3_WIDTH( 5 ),
    .din4_WIDTH( 5 ),
    .din5_WIDTH( 5 ),
    .din6_WIDTH( 5 ),
    .din7_WIDTH( 5 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 5 ))
TrackletEngineTop_mux_83_5_1_1_U3(
    .din0(instubouterdata_nentries_1_V_0_read_reg_2823_pp0_iter1_reg),
    .din1(instubouterdata_nentries_1_V_1_read_reg_2829_pp0_iter1_reg),
    .din2(instubouterdata_nentries_1_V_2_read_reg_2835_pp0_iter1_reg),
    .din3(instubouterdata_nentries_1_V_3_read_reg_2841_pp0_iter1_reg),
    .din4(instubouterdata_nentries_1_V_4_read_reg_2847_pp0_iter1_reg),
    .din5(instubouterdata_nentries_1_V_5_read_reg_2853_pp0_iter1_reg),
    .din6(instubouterdata_nentries_1_V_6_read_reg_2859_pp0_iter1_reg),
    .din7(instubouterdata_nentries_1_V_7_read_reg_2865_pp0_iter1_reg),
    .din8(zbinlast_V_fu_862_p2),
    .dout(tmp_4_fu_904_p10)
);

TrackletEngineTop_mux_83_5_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 5 ),
    .din2_WIDTH( 5 ),
    .din3_WIDTH( 5 ),
    .din4_WIDTH( 5 ),
    .din5_WIDTH( 5 ),
    .din6_WIDTH( 5 ),
    .din7_WIDTH( 5 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 5 ))
TrackletEngineTop_mux_83_5_1_1_U4(
    .din0(instubouterdata_nentries_0_V_0_read_reg_2775_pp0_iter1_reg),
    .din1(instubouterdata_nentries_0_V_1_read_reg_2781_pp0_iter1_reg),
    .din2(instubouterdata_nentries_0_V_2_read_reg_2787_pp0_iter1_reg),
    .din3(instubouterdata_nentries_0_V_3_read_reg_2793_pp0_iter1_reg),
    .din4(instubouterdata_nentries_0_V_4_read_reg_2799_pp0_iter1_reg),
    .din5(instubouterdata_nentries_0_V_5_read_reg_2805_pp0_iter1_reg),
    .din6(instubouterdata_nentries_0_V_6_read_reg_2811_pp0_iter1_reg),
    .din7(instubouterdata_nentries_0_V_7_read_reg_2817_pp0_iter1_reg),
    .din8(zbinlast_V_fu_862_p2),
    .dout(tmp_5_fu_918_p10)
);

TrackletEngineTop_mux_83_31_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 31 ),
    .din2_WIDTH( 31 ),
    .din3_WIDTH( 31 ),
    .din4_WIDTH( 31 ),
    .din5_WIDTH( 31 ),
    .din6_WIDTH( 31 ),
    .din7_WIDTH( 31 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 31 ))
TrackletEngineTop_mux_83_31_1_1_U5(
    .din0(ap_sig_allocacmp_teBuffer_7_V_50_load),
    .din1(ap_sig_allocacmp_teBuffer_7_V_40_load),
    .din2(ap_sig_allocacmp_teBuffer_7_V_37_load),
    .din3(ap_sig_allocacmp_teBuffer_7_V_33_load),
    .din4(ap_sig_allocacmp_teBuffer_7_V_28_load),
    .din5(ap_sig_allocacmp_teBuffer_7_V_22_load),
    .din6(ap_sig_allocacmp_teBuffer_7_V_15_load),
    .din7(ap_sig_allocacmp_teBuffer_7_V_1_load),
    .din8(t_V_213_reg_596),
    .dout(bufdata_V_fu_1020_p10)
);

TrackletEngineTop_mux_83_31_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 31 ),
    .din2_WIDTH( 31 ),
    .din3_WIDTH( 31 ),
    .din4_WIDTH( 31 ),
    .din5_WIDTH( 31 ),
    .din6_WIDTH( 31 ),
    .din7_WIDTH( 31 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 31 ))
TrackletEngineTop_mux_83_31_1_1_U6(
    .din0(ap_sig_allocacmp_teBuffer_7_V_50_load),
    .din1(ap_sig_allocacmp_teBuffer_7_V_40_load),
    .din2(ap_sig_allocacmp_teBuffer_7_V_37_load),
    .din3(ap_sig_allocacmp_teBuffer_7_V_33_load),
    .din4(ap_sig_allocacmp_teBuffer_7_V_28_load),
    .din5(ap_sig_allocacmp_teBuffer_7_V_22_load),
    .din6(ap_sig_allocacmp_teBuffer_7_V_15_load),
    .din7(ap_sig_allocacmp_teBuffer_7_V_1_load),
    .din8(t_V_213_reg_596),
    .dout(bufdata_V1_fu_1052_p10)
);

TrackletEngineTop_mux_83_31_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 31 ),
    .din2_WIDTH( 31 ),
    .din3_WIDTH( 31 ),
    .din4_WIDTH( 31 ),
    .din5_WIDTH( 31 ),
    .din6_WIDTH( 31 ),
    .din7_WIDTH( 31 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 31 ))
TrackletEngineTop_mux_83_31_1_1_U7(
    .din0(teBuffer_7_V_50_load_reg_3032),
    .din1(teBuffer_7_V_40_load_reg_3018),
    .din2(teBuffer_7_V_37_load_reg_3003),
    .din3(teBuffer_7_V_33_load_reg_2987),
    .din4(teBuffer_7_V_28_load_reg_2970),
    .din5(teBuffer_7_V_22_load_reg_2952),
    .din6(teBuffer_7_V_15_load_reg_2933),
    .din7(teBuffer_7_V_1_load_reg_2914),
    .din8(t_V_213_reg_596_pp0_iter2_reg),
    .dout(bufdata_V2_fu_2275_p10)
);

TrackletEngineTop_mux_83_31_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 31 ),
    .din2_WIDTH( 31 ),
    .din3_WIDTH( 31 ),
    .din4_WIDTH( 31 ),
    .din5_WIDTH( 31 ),
    .din6_WIDTH( 31 ),
    .din7_WIDTH( 31 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 31 ))
TrackletEngineTop_mux_83_31_1_1_U8(
    .din0(teBuffer_7_V_50_load_reg_3032),
    .din1(teBuffer_7_V_40_load_reg_3018),
    .din2(teBuffer_7_V_37_load_reg_3003),
    .din3(teBuffer_7_V_33_load_reg_2987),
    .din4(teBuffer_7_V_28_load_reg_2970),
    .din5(teBuffer_7_V_22_load_reg_2952),
    .din6(teBuffer_7_V_15_load_reg_2933),
    .din7(teBuffer_7_V_1_load_reg_2914),
    .din8(t_V_213_reg_596_pp0_iter2_reg),
    .dout(bufdata_V3_fu_2299_p10)
);

TrackletEngineTop_mux_83_31_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 31 ),
    .din2_WIDTH( 31 ),
    .din3_WIDTH( 31 ),
    .din4_WIDTH( 31 ),
    .din5_WIDTH( 31 ),
    .din6_WIDTH( 31 ),
    .din7_WIDTH( 31 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 31 ))
TrackletEngineTop_mux_83_31_1_1_U9(
    .din0(teBuffer_7_V_50_load_reg_3032),
    .din1(teBuffer_7_V_40_load_reg_3018),
    .din2(teBuffer_7_V_37_load_reg_3003),
    .din3(teBuffer_7_V_33_load_reg_2987),
    .din4(teBuffer_7_V_28_load_reg_2970),
    .din5(teBuffer_7_V_22_load_reg_2952),
    .din6(teBuffer_7_V_15_load_reg_2933),
    .din7(teBuffer_7_V_1_load_reg_2914),
    .din8(t_V_213_reg_596_pp0_iter2_reg),
    .dout(bufdata_V4_fu_2323_p10)
);

TrackletEngineTop_mux_83_31_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 31 ),
    .din2_WIDTH( 31 ),
    .din3_WIDTH( 31 ),
    .din4_WIDTH( 31 ),
    .din5_WIDTH( 31 ),
    .din6_WIDTH( 31 ),
    .din7_WIDTH( 31 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 31 ))
TrackletEngineTop_mux_83_31_1_1_U10(
    .din0(teBuffer_7_V_50_load_reg_3032),
    .din1(teBuffer_7_V_40_load_reg_3018),
    .din2(teBuffer_7_V_37_load_reg_3003),
    .din3(teBuffer_7_V_33_load_reg_2987),
    .din4(teBuffer_7_V_28_load_reg_2970),
    .din5(teBuffer_7_V_22_load_reg_2952),
    .din6(teBuffer_7_V_15_load_reg_2933),
    .din7(teBuffer_7_V_1_load_reg_2914),
    .din8(t_V_213_reg_596_pp0_iter2_reg),
    .dout(bufdata_V5_fu_2347_p10)
);

TrackletEngineTop_mux_83_31_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 31 ),
    .din2_WIDTH( 31 ),
    .din3_WIDTH( 31 ),
    .din4_WIDTH( 31 ),
    .din5_WIDTH( 31 ),
    .din6_WIDTH( 31 ),
    .din7_WIDTH( 31 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 31 ))
TrackletEngineTop_mux_83_31_1_1_U11(
    .din0(teBuffer_7_V_50_load_reg_3032),
    .din1(teBuffer_7_V_40_load_reg_3018),
    .din2(teBuffer_7_V_37_load_reg_3003),
    .din3(teBuffer_7_V_33_load_reg_2987),
    .din4(teBuffer_7_V_28_load_reg_2970),
    .din5(teBuffer_7_V_22_load_reg_2952),
    .din6(teBuffer_7_V_15_load_reg_2933),
    .din7(teBuffer_7_V_1_load_reg_2914),
    .din8(t_V_213_reg_596_pp0_iter2_reg),
    .dout(bufdata_V6_fu_2371_p10)
);

TrackletEngineTop_mux_83_31_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 31 ),
    .din1_WIDTH( 31 ),
    .din2_WIDTH( 31 ),
    .din3_WIDTH( 31 ),
    .din4_WIDTH( 31 ),
    .din5_WIDTH( 31 ),
    .din6_WIDTH( 31 ),
    .din7_WIDTH( 31 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 31 ))
TrackletEngineTop_mux_83_31_1_1_U12(
    .din0(teBuffer_7_V_50_load_reg_3032),
    .din1(teBuffer_7_V_40_load_reg_3018),
    .din2(teBuffer_7_V_37_load_reg_3003),
    .din3(teBuffer_7_V_33_load_reg_2987),
    .din4(teBuffer_7_V_28_load_reg_2970),
    .din5(teBuffer_7_V_22_load_reg_2952),
    .din6(teBuffer_7_V_15_load_reg_2933),
    .din7(teBuffer_7_V_1_load_reg_2914),
    .din8(t_V_213_reg_596_pp0_iter2_reg),
    .dout(bufdata_V7_fu_2395_p10)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter6 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_50)) begin
        if ((ap_phi_mux_do_init_phi_fu_460_p6 == 1'd0)) begin
            ap_phi_reg_pp0_iter1_p_0725_0_i15_reg_626 <= ap_phi_mux_p_0725_0_i15_rewind_phi_fu_518_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_460_p6 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_p_0725_0_i15_reg_626 <= morestubinner_V_fu_704_p2;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_p_0725_0_i15_reg_626 <= ap_phi_reg_pp0_iter0_p_0725_0_i15_reg_626;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_50)) begin
        if ((ap_phi_mux_do_init_phi_fu_460_p6 == 1'd0)) begin
            bx_V30_phi_reg_582 <= ap_phi_mux_bx_V30_rewind_phi_fu_504_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_460_p6 == 1'd1)) begin
            bx_V30_phi_reg_582 <= bx_V;
        end else if ((1'b1 == 1'b1)) begin
            bx_V30_phi_reg_582 <= ap_phi_reg_pp0_iter0_bx_V30_phi_reg_582;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (bx_o_V_1_vld_reg == 1'b0) & (bx_o_V_1_vld_in == 1'b1))) begin
        bx_o_V_1_vld_reg <= 1'b1;
    end else if (((bx_o_V_1_vld_in == 1'b0) & (1'b1 == 1'b1) & (bx_o_V_1_vld_reg == 1'b1))) begin
        bx_o_V_1_vld_reg <= 1'b0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln108_reg_2876 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        do_init_reg_456 <= 1'd0;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln108_reg_2876 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        do_init_reg_456 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln108_reg_2876 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        istep_0_i21_reg_529 <= istep_reg_2871;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln108_reg_2876 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        istep_0_i21_reg_529 <= 7'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (buffernotempty_V_fu_834_p2 == 1'd0) & (icmp_ln891_fu_1115_p2 == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        istubouter_V_fu_266 <= istubouter_V_1_fu_1133_p2;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln891_fu_1115_p2 == 1'd0) & (buffernotempty_V_fu_834_p2 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_phi_mux_do_init_phi_fu_460_p6 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        istubouter_V_fu_266 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_50)) begin
        if ((ap_phi_mux_do_init_phi_fu_460_p6 == 1'd0)) begin
            nstubinner_V_phi_reg_558 <= ap_phi_mux_nstubinner_V_rewind_phi_fu_476_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_460_p6 == 1'd1)) begin
            nstubinner_V_phi_reg_558 <= nstubinner_V_fu_695_p3;
        end else if ((1'b1 == 1'b1)) begin
            nstubinner_V_phi_reg_558 <= ap_phi_reg_pp0_iter0_nstubinner_V_phi_reg_558;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if ((1'b1 == ap_condition_1819)) begin
            nstubpairs_V_fu_262 <= nstubpairs_V_1_fu_2634_p2;
        end else if ((1'b1 == ap_condition_1815)) begin
            nstubpairs_V_fu_262 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln108_reg_2876_pp0_iter2_reg == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        p_0594_0_i19_reg_636 <= p_0594_2_i_reg_673;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln108_reg_2876_pp0_iter2_reg == 1'd1) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        p_0594_0_i19_reg_636 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((buffernotempty_V_fu_834_p2 == 1'd1)) begin
            p_0594_2_i_reg_673 <= ap_phi_mux_p_0594_0_i19_phi_fu_640_p6;
        end else if ((buffernotempty_V_fu_834_p2 == 1'd0)) begin
            p_0594_2_i_reg_673 <= nstubs_V_1_fu_1084_p3;
        end else if ((1'b1 == 1'b1)) begin
            p_0594_2_i_reg_673 <= ap_phi_reg_pp0_iter2_p_0594_2_i_reg_673;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_50)) begin
        if ((ap_phi_mux_do_init_phi_fu_460_p6 == 1'd0)) begin
            p_phi_reg_570 <= ap_phi_mux_p_rewind_phi_fu_490_p6;
        end else if ((ap_phi_mux_do_init_phi_fu_460_p6 == 1'd1)) begin
            p_phi_reg_570 <= trunc_ln209_fu_690_p1;
        end else if ((1'b1 == 1'b1)) begin
            p_phi_reg_570 <= ap_phi_reg_pp0_iter0_p_phi_reg_570;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln108_reg_2876 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        t_V14_reg_543 <= t_V_3_fu_794_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln108_reg_2876 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        t_V14_reg_543 <= 7'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln108_reg_2876_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        t_V_213_reg_596 <= ap_phi_mux_t_V_1_phi_fu_664_p4;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln108_reg_2876_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        t_V_213_reg_596 <= 3'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln108_reg_2876_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        writeindextmp_V12_reg_611 <= writeindextmp_V_fu_1000_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln108_reg_2876_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1)))) begin
        writeindextmp_V12_reg_611 <= 3'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        buffernotempty_V_reg_3045 <= buffernotempty_V_fu_834_p2;
        buffernotempty_V_reg_3045_pp0_iter3_reg <= buffernotempty_V_reg_3045;
        buffernotempty_V_reg_3045_pp0_iter4_reg <= buffernotempty_V_reg_3045_pp0_iter3_reg;
        buffernotempty_V_reg_3045_pp0_iter5_reg <= buffernotempty_V_reg_3045_pp0_iter4_reg;
        bx_V30_phi_reg_582_pp0_iter2_reg <= bx_V30_phi_reg_582_pp0_iter1_reg;
        bx_V30_phi_reg_582_pp0_iter3_reg <= bx_V30_phi_reg_582_pp0_iter2_reg;
        bx_V30_phi_reg_582_pp0_iter4_reg <= bx_V30_phi_reg_582_pp0_iter3_reg;
        icmp_ln108_reg_2876_pp0_iter2_reg <= icmp_ln108_reg_2876_pp0_iter1_reg;
        icmp_ln108_reg_2876_pp0_iter3_reg <= icmp_ln108_reg_2876_pp0_iter2_reg;
        icmp_ln108_reg_2876_pp0_iter4_reg <= icmp_ln108_reg_2876_pp0_iter3_reg;
        icmp_ln108_reg_2876_pp0_iter5_reg <= icmp_ln108_reg_2876_pp0_iter4_reg;
        icmp_ln321_1_reg_3115 <= icmp_ln321_1_fu_976_p2;
        icmp_ln321_reg_3107 <= icmp_ln321_fu_970_p2;
        icmp_ln891_1_reg_3193_pp0_iter5_reg <= icmp_ln891_1_reg_3193;
        icmp_ln899_reg_3188_pp0_iter5_reg <= icmp_ln899_reg_3188;
        innerstubdatatmp_data_V_reg_3049 <= instubinnerdata_dataarray_data_V_q0;
        innerstubindex_V_2_reg_3162_pp0_iter4_reg <= innerstubindex_V_2_reg_3162;
        innerstubindex_V_2_reg_3162_pp0_iter5_reg <= innerstubindex_V_2_reg_3162_pp0_iter4_reg;
        nstubslast_V_reg_3070 <= nstubslast_V_fu_932_p3;
        nstubsstart_V_reg_3065 <= nstubsstart_V_fu_896_p3;
        or_ln123_1_reg_2890_pp0_iter2_reg <= or_ln123_1_reg_2890;
        outerstubindex_V_reg_3183_pp0_iter5_reg <= outerstubindex_V_reg_3183;
        p_phi_reg_570_pp0_iter2_reg <= p_phi_reg_570_pp0_iter1_reg;
        p_phi_reg_570_pp0_iter3_reg <= p_phi_reg_570_pp0_iter2_reg;
        p_phi_reg_570_pp0_iter4_reg <= p_phi_reg_570_pp0_iter3_reg;
        p_phi_reg_570_pp0_iter5_reg <= p_phi_reg_570_pp0_iter4_reg;
        savelast_V_reg_3095 <= savelast_V_fu_952_p2;
        savestart_V_reg_3075 <= savestart_V_fu_940_p2;
        t_V_213_reg_596_pp0_iter2_reg <= t_V_213_reg_596;
        teBuffer_7_V_15_load_reg_2933 <= ap_sig_allocacmp_teBuffer_7_V_15_load;
        teBuffer_7_V_1_load_reg_2914 <= ap_sig_allocacmp_teBuffer_7_V_1_load;
        teBuffer_7_V_22_load_reg_2952 <= ap_sig_allocacmp_teBuffer_7_V_22_load;
        teBuffer_7_V_28_load_reg_2970 <= ap_sig_allocacmp_teBuffer_7_V_28_load;
        teBuffer_7_V_33_load_reg_2987 <= ap_sig_allocacmp_teBuffer_7_V_33_load;
        teBuffer_7_V_37_load_reg_3003 <= ap_sig_allocacmp_teBuffer_7_V_37_load;
        teBuffer_7_V_40_load_reg_3018 <= ap_sig_allocacmp_teBuffer_7_V_40_load;
        teBuffer_7_V_50_load_reg_3032 <= ap_sig_allocacmp_teBuffer_7_V_50_load;
        writeindextmp_V12_reg_611_pp0_iter2_reg <= writeindextmp_V12_reg_611;
        zbinlast_V_reg_3060 <= zbinlast_V_fu_862_p2;
        zbinstart_V_reg_3055 <= {{instubinnerdata_dataarray_data_V_q0[6:4]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bx_V30_phi_reg_582_pp0_iter1_reg <= bx_V30_phi_reg_582;
        icmp_ln108_reg_2876 <= icmp_ln108_fu_734_p2;
        icmp_ln108_reg_2876_pp0_iter1_reg <= icmp_ln108_reg_2876;
        instubouterdata_nentries_0_V_0_read_reg_2775 <= instubouterdata_nentries_0_V_0;
        instubouterdata_nentries_0_V_0_read_reg_2775_pp0_iter1_reg <= instubouterdata_nentries_0_V_0_read_reg_2775;
        instubouterdata_nentries_0_V_1_read_reg_2781 <= instubouterdata_nentries_0_V_1;
        instubouterdata_nentries_0_V_1_read_reg_2781_pp0_iter1_reg <= instubouterdata_nentries_0_V_1_read_reg_2781;
        instubouterdata_nentries_0_V_2_read_reg_2787 <= instubouterdata_nentries_0_V_2;
        instubouterdata_nentries_0_V_2_read_reg_2787_pp0_iter1_reg <= instubouterdata_nentries_0_V_2_read_reg_2787;
        instubouterdata_nentries_0_V_3_read_reg_2793 <= instubouterdata_nentries_0_V_3;
        instubouterdata_nentries_0_V_3_read_reg_2793_pp0_iter1_reg <= instubouterdata_nentries_0_V_3_read_reg_2793;
        instubouterdata_nentries_0_V_4_read_reg_2799 <= instubouterdata_nentries_0_V_4;
        instubouterdata_nentries_0_V_4_read_reg_2799_pp0_iter1_reg <= instubouterdata_nentries_0_V_4_read_reg_2799;
        instubouterdata_nentries_0_V_5_read_reg_2805 <= instubouterdata_nentries_0_V_5;
        instubouterdata_nentries_0_V_5_read_reg_2805_pp0_iter1_reg <= instubouterdata_nentries_0_V_5_read_reg_2805;
        instubouterdata_nentries_0_V_6_read_reg_2811 <= instubouterdata_nentries_0_V_6;
        instubouterdata_nentries_0_V_6_read_reg_2811_pp0_iter1_reg <= instubouterdata_nentries_0_V_6_read_reg_2811;
        instubouterdata_nentries_0_V_7_read_reg_2817 <= instubouterdata_nentries_0_V_7;
        instubouterdata_nentries_0_V_7_read_reg_2817_pp0_iter1_reg <= instubouterdata_nentries_0_V_7_read_reg_2817;
        instubouterdata_nentries_1_V_0_read_reg_2823 <= instubouterdata_nentries_1_V_0;
        instubouterdata_nentries_1_V_0_read_reg_2823_pp0_iter1_reg <= instubouterdata_nentries_1_V_0_read_reg_2823;
        instubouterdata_nentries_1_V_1_read_reg_2829 <= instubouterdata_nentries_1_V_1;
        instubouterdata_nentries_1_V_1_read_reg_2829_pp0_iter1_reg <= instubouterdata_nentries_1_V_1_read_reg_2829;
        instubouterdata_nentries_1_V_2_read_reg_2835 <= instubouterdata_nentries_1_V_2;
        instubouterdata_nentries_1_V_2_read_reg_2835_pp0_iter1_reg <= instubouterdata_nentries_1_V_2_read_reg_2835;
        instubouterdata_nentries_1_V_3_read_reg_2841 <= instubouterdata_nentries_1_V_3;
        instubouterdata_nentries_1_V_3_read_reg_2841_pp0_iter1_reg <= instubouterdata_nentries_1_V_3_read_reg_2841;
        instubouterdata_nentries_1_V_4_read_reg_2847 <= instubouterdata_nentries_1_V_4;
        instubouterdata_nentries_1_V_4_read_reg_2847_pp0_iter1_reg <= instubouterdata_nentries_1_V_4_read_reg_2847;
        instubouterdata_nentries_1_V_5_read_reg_2853 <= instubouterdata_nentries_1_V_5;
        instubouterdata_nentries_1_V_5_read_reg_2853_pp0_iter1_reg <= instubouterdata_nentries_1_V_5_read_reg_2853;
        instubouterdata_nentries_1_V_6_read_reg_2859 <= instubouterdata_nentries_1_V_6;
        instubouterdata_nentries_1_V_6_read_reg_2859_pp0_iter1_reg <= instubouterdata_nentries_1_V_6_read_reg_2859;
        instubouterdata_nentries_1_V_7_read_reg_2865 <= instubouterdata_nentries_1_V_7;
        instubouterdata_nentries_1_V_7_read_reg_2865_pp0_iter1_reg <= instubouterdata_nentries_1_V_7_read_reg_2865;
        or_ln123_1_reg_2890 <= or_ln123_1_fu_776_p2;
        p_phi_reg_570_pp0_iter1_reg <= p_phi_reg_570;
        writeindex_V_reg_2885 <= writeindex_V_fu_746_p2;
        writeindexplus_V_reg_2880 <= writeindexplus_V_fu_740_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln108_reg_2876 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        bx_V30_rewind_reg_500 <= bx_V30_phi_reg_582;
        nstubinner_V_rewind_reg_472 <= nstubinner_V_phi_reg_558;
        p_0725_0_i15_rewind_reg_514 <= morestubinner_V_2_fu_802_p3;
        p_rewind_reg_486 <= p_phi_reg_570;
    end
end

always @ (posedge ap_clk) begin
    if (((~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (bx_o_V_1_vld_reg == 1'b0) & (bx_o_V_1_vld_in == 1'b1)) | (~((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) & (1'b1 == 1'b1) & (bx_o_V_1_vld_in == 1'b1) & (bx_o_V_1_vld_reg == 1'b1)))) begin
        bx_o_V_1_data_reg <= bx_V30_phi_reg_582_pp0_iter4_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (buffernotempty_V_fu_834_p2 == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ibin_V_2_fu_258 <= ibin_V_3_fu_1093_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (buffernotempty_V_fu_834_p2 == 1'd0))) begin
        icmp_ln879_reg_3132 <= icmp_ln879_fu_1014_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (buffernotempty_V_reg_3045_pp0_iter3_reg == 1'd0))) begin
        icmp_ln891_1_reg_3193 <= icmp_ln891_1_fu_2563_p2;
        icmp_ln899_reg_3188 <= icmp_ln899_fu_2557_p2;
        outerstubindex_V_reg_3183 <= {{instubouterdata_dataarray_data_V_q0[15:9]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (buffernotempty_V_reg_3045 == 1'd0))) begin
        innerstubbend_V_2_reg_3157 <= innerstubbend_V_2_fu_2420_p3;
        innerstubfinephi_V_2_reg_3151 <= innerstubfinephi_V_2_fu_2413_p3;
        innerstubindex_V_2_reg_3162 <= innerstubindex_V_2_fu_2427_p3;
        second_V_3_reg_3178 <= second_V_3_fu_2448_p3;
        zbinfirst_V_3_reg_3172 <= zbinfirst_V_3_fu_2441_p3;
        zdiffmax_V_3_reg_3167 <= zdiffmax_V_3_fu_2434_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        istep_reg_2871 <= istep_fu_728_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (buffernotempty_V_reg_3045 == 1'd0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        p_Repl2_1_fu_238 <= innerstubbend_V_2_fu_2420_p3;
        p_Repl2_2_fu_242 <= innerstubindex_V_2_fu_2427_p3;
        p_Repl2_s_fu_234 <= innerstubfinephi_V_2_fu_2413_p3;
        second_V_fu_254 <= second_V_3_fu_2448_p3;
        zbinfirst_V_2_fu_250 <= zbinfirst_V_3_fu_2441_p3;
        zdiffmax_V_2_fu_246 <= zdiffmax_V_3_fu_2434_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        teBuffer_7_V_15_fu_206 <= teBuffer_7_V_276_fu_2175_p3;
        teBuffer_7_V_1_fu_202 <= teBuffer_7_V_275_fu_2169_p3;
        teBuffer_7_V_22_fu_210 <= teBuffer_7_V_277_fu_2181_p3;
        teBuffer_7_V_28_fu_214 <= teBuffer_7_V_278_fu_2187_p3;
        teBuffer_7_V_33_fu_218 <= teBuffer_7_V_279_fu_2193_p3;
        teBuffer_7_V_37_fu_222 <= teBuffer_7_V_280_fu_2199_p3;
        teBuffer_7_V_40_fu_226 <= teBuffer_7_V_281_fu_2205_p3;
        teBuffer_7_V_50_fu_230 <= teBuffer_7_V_282_fu_2211_p3;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln108_reg_2876_pp0_iter5_reg == 1'd1) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_0to5 = 1'b1;
    end else begin
        ap_idle_pp0_0to5 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln108_reg_2876 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        ap_phi_mux_bx_V30_rewind_phi_fu_504_p6 = bx_V30_phi_reg_582;
    end else begin
        ap_phi_mux_bx_V30_rewind_phi_fu_504_p6 = bx_V30_rewind_reg_500;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_391)) begin
        if ((icmp_ln108_reg_2876 == 1'd1)) begin
            ap_phi_mux_do_init_phi_fu_460_p6 = 1'd1;
        end else if ((icmp_ln108_reg_2876 == 1'd0)) begin
            ap_phi_mux_do_init_phi_fu_460_p6 = 1'd0;
        end else begin
            ap_phi_mux_do_init_phi_fu_460_p6 = do_init_reg_456;
        end
    end else begin
        ap_phi_mux_do_init_phi_fu_460_p6 = do_init_reg_456;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_391)) begin
        if ((icmp_ln108_reg_2876 == 1'd1)) begin
            ap_phi_mux_istep_0_i21_phi_fu_533_p6 = 7'd0;
        end else if ((icmp_ln108_reg_2876 == 1'd0)) begin
            ap_phi_mux_istep_0_i21_phi_fu_533_p6 = istep_reg_2871;
        end else begin
            ap_phi_mux_istep_0_i21_phi_fu_533_p6 = istep_0_i21_reg_529;
        end
    end else begin
        ap_phi_mux_istep_0_i21_phi_fu_533_p6 = istep_0_i21_reg_529;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln108_reg_2876 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        ap_phi_mux_nstubinner_V_rewind_phi_fu_476_p6 = nstubinner_V_phi_reg_558;
    end else begin
        ap_phi_mux_nstubinner_V_rewind_phi_fu_476_p6 = nstubinner_V_rewind_reg_472;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        if ((icmp_ln108_reg_2876_pp0_iter2_reg == 1'd1)) begin
            ap_phi_mux_p_0594_0_i19_phi_fu_640_p6 = 4'd0;
        end else if ((icmp_ln108_reg_2876_pp0_iter2_reg == 1'd0)) begin
            ap_phi_mux_p_0594_0_i19_phi_fu_640_p6 = p_0594_2_i_reg_673;
        end else begin
            ap_phi_mux_p_0594_0_i19_phi_fu_640_p6 = p_0594_0_i19_reg_636;
        end
    end else begin
        ap_phi_mux_p_0594_0_i19_phi_fu_640_p6 = p_0594_0_i19_reg_636;
    end
end

always @ (*) begin
    if ((buffernotempty_V_fu_834_p2 == 1'd0)) begin
        if ((icmp_ln891_fu_1115_p2 == 1'd1)) begin
            ap_phi_mux_p_0709_1_i_phi_fu_653_p4 = t_V_213_reg_596;
        end else if ((icmp_ln891_fu_1115_p2 == 1'd0)) begin
            ap_phi_mux_p_0709_1_i_phi_fu_653_p4 = readindex_V_fu_1126_p2;
        end else begin
            ap_phi_mux_p_0709_1_i_phi_fu_653_p4 = ap_phi_reg_pp0_iter2_p_0709_1_i_reg_650;
        end
    end else begin
        ap_phi_mux_p_0709_1_i_phi_fu_653_p4 = ap_phi_reg_pp0_iter2_p_0709_1_i_reg_650;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln108_reg_2876 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        ap_phi_mux_p_0725_0_i15_rewind_phi_fu_518_p6 = morestubinner_V_2_fu_802_p3;
    end else begin
        ap_phi_mux_p_0725_0_i15_rewind_phi_fu_518_p6 = p_0725_0_i15_rewind_reg_514;
    end
end

always @ (*) begin
    if ((ap_phi_mux_do_init_phi_fu_460_p6 == 1'd0)) begin
        ap_phi_mux_p_phi_phi_fu_574_p4 = ap_phi_mux_p_rewind_phi_fu_490_p6;
    end else if ((ap_phi_mux_do_init_phi_fu_460_p6 == 1'd1)) begin
        ap_phi_mux_p_phi_phi_fu_574_p4 = trunc_ln209_fu_690_p1;
    end else begin
        ap_phi_mux_p_phi_phi_fu_574_p4 = ap_phi_reg_pp0_iter0_p_phi_reg_570;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln108_reg_2876 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        ap_phi_mux_p_rewind_phi_fu_490_p6 = p_phi_reg_570;
    end else begin
        ap_phi_mux_p_rewind_phi_fu_490_p6 = p_rewind_reg_486;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_391)) begin
        if ((icmp_ln108_reg_2876 == 1'd1)) begin
            ap_phi_mux_t_V14_phi_fu_547_p6 = 7'd0;
        end else if ((icmp_ln108_reg_2876 == 1'd0)) begin
            ap_phi_mux_t_V14_phi_fu_547_p6 = t_V_3_fu_794_p3;
        end else begin
            ap_phi_mux_t_V14_phi_fu_547_p6 = t_V14_reg_543;
        end
    end else begin
        ap_phi_mux_t_V14_phi_fu_547_p6 = t_V14_reg_543;
    end
end

always @ (*) begin
    if ((buffernotempty_V_fu_834_p2 == 1'd1)) begin
        ap_phi_mux_t_V_1_phi_fu_664_p4 = t_V_213_reg_596;
    end else if ((buffernotempty_V_fu_834_p2 == 1'd0)) begin
        ap_phi_mux_t_V_1_phi_fu_664_p4 = ap_phi_mux_p_0709_1_i_phi_fu_653_p4;
    end else begin
        ap_phi_mux_t_V_1_phi_fu_664_p4 = ap_phi_reg_pp0_iter2_t_V_1_reg_660;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((icmp_ln108_reg_2876_pp0_iter1_reg == 1'd1)) begin
            ap_phi_mux_t_V_213_phi_fu_600_p6 = 3'd0;
        end else if ((icmp_ln108_reg_2876_pp0_iter1_reg == 1'd0)) begin
            ap_phi_mux_t_V_213_phi_fu_600_p6 = ap_phi_mux_t_V_1_phi_fu_664_p4;
        end else begin
            ap_phi_mux_t_V_213_phi_fu_600_p6 = t_V_213_reg_596;
        end
    end else begin
        ap_phi_mux_t_V_213_phi_fu_600_p6 = t_V_213_reg_596;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        if ((icmp_ln108_reg_2876_pp0_iter1_reg == 1'd1)) begin
            ap_phi_mux_writeindextmp_V12_phi_fu_615_p6 = 3'd0;
        end else if ((icmp_ln108_reg_2876_pp0_iter1_reg == 1'd0)) begin
            ap_phi_mux_writeindextmp_V12_phi_fu_615_p6 = writeindextmp_V_fu_1000_p3;
        end else begin
            ap_phi_mux_writeindextmp_V12_phi_fu_615_p6 = writeindextmp_V12_reg_611;
        end
    end else begin
        ap_phi_mux_writeindextmp_V12_phi_fu_615_p6 = writeindextmp_V12_reg_611;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln108_fu_734_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to5 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_sig_allocacmp_teBuffer_7_V_15_load = teBuffer_7_V_276_fu_2175_p3;
    end else begin
        ap_sig_allocacmp_teBuffer_7_V_15_load = teBuffer_7_V_15_fu_206;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_sig_allocacmp_teBuffer_7_V_1_load = teBuffer_7_V_275_fu_2169_p3;
    end else begin
        ap_sig_allocacmp_teBuffer_7_V_1_load = teBuffer_7_V_1_fu_202;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_sig_allocacmp_teBuffer_7_V_22_load = teBuffer_7_V_277_fu_2181_p3;
    end else begin
        ap_sig_allocacmp_teBuffer_7_V_22_load = teBuffer_7_V_22_fu_210;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_sig_allocacmp_teBuffer_7_V_28_load = teBuffer_7_V_278_fu_2187_p3;
    end else begin
        ap_sig_allocacmp_teBuffer_7_V_28_load = teBuffer_7_V_28_fu_214;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_sig_allocacmp_teBuffer_7_V_33_load = teBuffer_7_V_279_fu_2193_p3;
    end else begin
        ap_sig_allocacmp_teBuffer_7_V_33_load = teBuffer_7_V_33_fu_218;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_sig_allocacmp_teBuffer_7_V_37_load = teBuffer_7_V_280_fu_2199_p3;
    end else begin
        ap_sig_allocacmp_teBuffer_7_V_37_load = teBuffer_7_V_37_fu_222;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_sig_allocacmp_teBuffer_7_V_40_load = teBuffer_7_V_281_fu_2205_p3;
    end else begin
        ap_sig_allocacmp_teBuffer_7_V_40_load = teBuffer_7_V_40_fu_226;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_sig_allocacmp_teBuffer_7_V_50_load = teBuffer_7_V_282_fu_2211_p3;
    end else begin
        ap_sig_allocacmp_teBuffer_7_V_50_load = teBuffer_7_V_50_fu_230;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1)))) begin
        bendinnertable_V_ce0 = 1'b1;
    end else begin
        bendinnertable_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1)))) begin
        bendoutertable_V_ce0 = 1'b1;
    end else begin
        bendoutertable_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((bx_o_V_1_vld_reg == 1'b0) | ((1'b1 == 1'b1) & (bx_o_V_1_vld_reg == 1'b1)))) begin
        bx_o_V_1_ack_in = 1'b1;
    end else begin
        bx_o_V_1_ack_in = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln108_reg_2876_pp0_iter4_reg == 1'd1) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        bx_o_V_1_vld_in = 1'b1;
    end else begin
        bx_o_V_1_vld_in = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        instubinnerdata_dataarray_data_V_ce0 = 1'b1;
    end else begin
        instubinnerdata_dataarray_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
        instubouterdata_dataarray_data_V_ce0 = 1'b1;
    end else begin
        instubouterdata_dataarray_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        outstubpair_dataarray_data_V_ce0 = 1'b1;
    end else begin
        outstubpair_dataarray_data_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (buffernotempty_V_reg_3045_pp0_iter5_reg == 1'd0) & (1'd1 == and_ln216_fu_2618_p2) & (ap_enable_reg_pp0_iter6 == 1'b1))) begin
        outstubpair_dataarray_data_V_we0 = 1'b1;
    end else begin
        outstubpair_dataarray_data_V_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((ap_reset_idle_pp0 == 1'b0)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_reset_idle_pp0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign and_ln137_fu_958_p2 = (savestart_V_fu_940_p2 & savelast_V_fu_952_p2);

assign and_ln216_1_fu_2606_p2 = (bendoutertable_V_q0 & bendinnertable_V_q0);

assign and_ln216_2_fu_2612_p2 = (xor_ln899_fu_2596_p2 & xor_ln891_fu_2601_p2);

assign and_ln216_fu_2618_p2 = (and_ln216_2_fu_2612_p2 & and_ln216_1_fu_2606_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((bx_o_V_1_ack_in == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((bx_o_V_1_ack_in == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((bx_o_V_1_ack_in == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b1));
end

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state8_pp0_stage0_iter6 = (bx_o_V_1_ack_in == 1'b0);
end

always @ (*) begin
    ap_condition_1815 = ((ap_phi_mux_do_init_phi_fu_460_p6 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_1819 = ((buffernotempty_V_reg_3045_pp0_iter5_reg == 1'd0) & (1'd1 == and_ln216_fu_2618_p2) & (ap_enable_reg_pp0_iter6 == 1'b1));
end

always @ (*) begin
    ap_condition_391 = ((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_50 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_phi_reg_pp0_iter0_bx_V30_phi_reg_582 = 'bx;

assign ap_phi_reg_pp0_iter0_nstubinner_V_phi_reg_558 = 'bx;

assign ap_phi_reg_pp0_iter0_p_0725_0_i15_reg_626 = 'bx;

assign ap_phi_reg_pp0_iter0_p_phi_reg_570 = 'bx;

assign ap_phi_reg_pp0_iter2_p_0594_2_i_reg_673 = 'bx;

assign ap_phi_reg_pp0_iter2_p_0709_1_i_reg_650 = 'bx;

assign ap_phi_reg_pp0_iter2_t_V_1_reg_660 = 'bx;

assign bendinnertable_V_address0 = zext_ln544_fu_2577_p1;

assign bendoutertable_V_address0 = zext_ln544_1_fu_2591_p1;

assign buffernotempty_V_fu_834_p2 = ((writeindextmp_V12_reg_611 == t_V_213_reg_596) ? 1'b1 : 1'b0);

assign bx_o_V = bx_o_V_1_data_reg;

assign bx_o_V_ap_vld = bx_o_V_1_vld_reg;

assign ibin_V_3_fu_1093_p3 = ((icmp_ln879_fu_1014_p2[0:0] === 1'b1) ? ibin_V_fu_1074_p4 : ibin_V_2_fu_258);

assign ibin_V_fu_1074_p4 = {{bufdata_V1_fu_1052_p10[3:1]}};

assign icmp_ln108_fu_734_p2 = ((ap_phi_mux_istep_0_i21_phi_fu_533_p6 == 7'd107) ? 1'b1 : 1'b0);

assign icmp_ln123_1_fu_764_p2 = ((writeindexplus_V_fu_740_p2 == ap_phi_mux_t_V_213_phi_fu_600_p6) ? 1'b1 : 1'b0);

assign icmp_ln123_fu_758_p2 = ((writeindex_V_fu_746_p2 == ap_phi_mux_t_V_213_phi_fu_600_p6) ? 1'b1 : 1'b0);

assign icmp_ln134_fu_946_p2 = ((nstubslast_V_fu_932_p3 != 5'd0) ? 1'b1 : 1'b0);

assign icmp_ln321_1_fu_976_p2 = ((writeindextmp_V12_reg_611 == 3'd5) ? 1'b1 : 1'b0);

assign icmp_ln321_2_fu_1183_p2 = ((writeindextmp_V12_reg_611_pp0_iter2_reg == 3'd4) ? 1'b1 : 1'b0);

assign icmp_ln321_3_fu_1196_p2 = ((writeindextmp_V12_reg_611_pp0_iter2_reg == 3'd3) ? 1'b1 : 1'b0);

assign icmp_ln321_4_fu_1209_p2 = ((writeindextmp_V12_reg_611_pp0_iter2_reg == 3'd2) ? 1'b1 : 1'b0);

assign icmp_ln321_5_fu_1222_p2 = ((writeindextmp_V12_reg_611_pp0_iter2_reg == 3'd1) ? 1'b1 : 1'b0);

assign icmp_ln321_6_fu_1235_p2 = ((writeindextmp_V12_reg_611_pp0_iter2_reg == 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln321_7_fu_1545_p2 = ((writeindextmp_V12_reg_611_pp0_iter2_reg == 3'd7) ? 1'b1 : 1'b0);

assign icmp_ln321_fu_970_p2 = ((writeindextmp_V12_reg_611 == 3'd6) ? 1'b1 : 1'b0);

assign icmp_ln879_fu_1014_p2 = ((istubouter_V_fu_266 == 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln891_1_fu_2563_p2 = ((tmpz_fu_2531_p3 < zext_ln1467_fu_2538_p1) ? 1'b1 : 1'b0);

assign icmp_ln891_fu_1115_p2 = ((ret_V_fu_1105_p2 < zext_ln891_fu_1111_p1) ? 1'b1 : 1'b0);

assign icmp_ln899_fu_2557_p2 = (($signed(zext_ln899_fu_2554_p1) < $signed(ret_V_1_fu_2548_p2)) ? 1'b1 : 1'b0);

assign innerstubbend_V_2_fu_2420_p3 = ((icmp_ln879_reg_3132[0:0] === 1'b1) ? innerstubbend_V_fu_2313_p4 : p_Repl2_1_fu_238);

assign innerstubbend_V_fu_2313_p4 = {{bufdata_V3_fu_2299_p10[18:16]}};

assign innerstubfinephi_V_2_fu_2413_p3 = ((icmp_ln879_reg_3132[0:0] === 1'b1) ? innerstubfinephi_V_fu_2337_p4 : p_Repl2_s_fu_234);

assign innerstubfinephi_V_fu_2337_p4 = {{bufdata_V4_fu_2323_p10[15:14]}};

assign innerstubindex_V_2_fu_2427_p3 = ((icmp_ln879_reg_3132[0:0] === 1'b1) ? innerstubindex_V_fu_2289_p4 : p_Repl2_2_fu_242);

assign innerstubindex_V_fu_2289_p4 = {{bufdata_V2_fu_2275_p10[25:19]}};

assign instubinnerdata_dataarray_data_V_address0 = zext_ln42_fu_723_p1;

assign instubouterdata_dataarray_data_V_address0 = tmp_7_fu_1144_p5;

assign istep_fu_728_p2 = (ap_phi_mux_istep_0_i21_phi_fu_533_p6 + 7'd1);

assign istubinner_V_fu_782_p2 = (t_V14_reg_543 + 7'd1);

assign istubouter_V_1_fu_1133_p2 = (istubouter_V_fu_266 + 4'd1);

assign morestubinner_V_1_fu_788_p2 = ((istubinner_V_fu_782_p2 < nstubinner_V_phi_reg_558) ? 1'b1 : 1'b0);

assign morestubinner_V_2_fu_802_p3 = ((or_ln123_1_fu_776_p2[0:0] === 1'b1) ? ap_phi_reg_pp0_iter1_p_0725_0_i15_reg_626 : morestubinner_V_1_fu_788_p2);

assign morestubinner_V_fu_704_p2 = ((nstubinner_V_fu_695_p3 != 7'd0) ? 1'b1 : 1'b0);

assign nstubinner_V_fu_695_p3 = ((trunc_ln209_fu_690_p1[0:0] === 1'b1) ? instubinnerdata_nentries_1_V : instubinnerdata_nentries_0_V);

assign nstubpairs_V_1_fu_2634_p2 = (nstubpairs_V_fu_262 + 7'd1);

assign nstubs_V_1_fu_1084_p3 = ((icmp_ln879_fu_1014_p2[0:0] === 1'b1) ? nstubs_V_fu_1042_p4 : ap_phi_mux_p_0594_0_i19_phi_fu_640_p6);

assign nstubs_V_fu_1042_p4 = {{bufdata_V_fu_1020_p10[29:26]}};

assign nstubslast_V_fu_932_p3 = ((p_phi_reg_570_pp0_iter1_reg[0:0] === 1'b1) ? tmp_4_fu_904_p10 : tmp_5_fu_918_p10);

assign nstubsstart_V_fu_896_p3 = ((p_phi_reg_570_pp0_iter1_reg[0:0] === 1'b1) ? tmp_2_fu_868_p10 : tmp_3_fu_882_p10);

assign or_ln123_1_fu_776_p2 = (or_ln123_fu_770_p2 | icmp_ln123_1_fu_764_p2);

assign or_ln123_2_fu_988_p2 = (or_ln123_1_reg_2890 | and_ln137_fu_958_p2);

assign or_ln123_fu_770_p2 = (xor_ln123_fu_752_p2 | icmp_ln123_fu_758_p2);

assign or_ln139_fu_964_p2 = (savestart_V_fu_940_p2 | savelast_V_fu_952_p2);

assign or_ln_fu_2523_p3 = {{1'd1}, {outerstubfinez_V_fu_2515_p1}};

assign outerstubbend_V_fu_2505_p4 = {{instubouterdata_dataarray_data_V_q0[8:6]}};

assign outerstubfinephi_V_fu_2495_p4 = {{instubouterdata_dataarray_data_V_q0[5:3]}};

assign outerstubfinez_V_fu_2515_p1 = instubouterdata_dataarray_data_V_q0[2:0];

assign outstubpair_dataarray_data_V_address0 = zext_ln321_fu_2653_p1;

assign outstubpair_dataarray_data_V_d0 = {{innerstubindex_V_2_reg_3162_pp0_iter5_reg}, {outerstubindex_V_reg_3183_pp0_iter5_reg}};

assign p_Result_1_fu_1489_p5 = {{{{nstubslast_V_reg_3070}, {innerstubdatatmp_data_V_reg_3049}}, {zbinlast_V_reg_3060}}, {1'd1}};

assign p_Result_2_fu_2569_p4 = {{{innerstubfinephi_V_2_reg_3151}, {outerstubfinephi_V_fu_2495_p4}}, {innerstubbend_V_2_reg_3157}};

assign p_Result_3_fu_2582_p4 = {{{innerstubfinephi_V_2_reg_3151}, {outerstubfinephi_V_fu_2495_p4}}, {outerstubbend_V_fu_2505_p4}};

assign p_Result_s_fu_1162_p5 = {{{{nstubsstart_V_reg_3065}, {innerstubdatatmp_data_V_reg_3049}}, {zbinstart_V_reg_3055}}, {1'd0}};

assign readindex_V_fu_1126_p2 = (t_V_213_reg_596 + 3'd1);

assign ret_V_1_fu_2548_p2 = (zext_ln215_1_fu_2541_p1 - zext_ln215_2_fu_2545_p1);

assign ret_V_fu_1105_p2 = (5'd1 + zext_ln215_fu_1101_p1);

assign savelast_V_fu_952_p2 = (tmp_1_fu_850_p3 & icmp_ln134_fu_946_p2);

assign savestart_V_fu_940_p2 = ((nstubsstart_V_fu_896_p3 != 5'd0) ? 1'b1 : 1'b0);

assign second_V_2_fu_2409_p1 = bufdata_V7_fu_2395_p10[0:0];

assign second_V_3_fu_2448_p3 = ((icmp_ln879_reg_3132[0:0] === 1'b1) ? second_V_2_fu_2409_p1 : second_V_fu_254);

assign select_ln123_1_fu_993_p3 = ((or_ln139_fu_964_p2[0:0] === 1'b1) ? writeindexplus_V_reg_2880 : writeindextmp_V12_reg_611);

assign select_ln123_fu_982_p3 = ((or_ln123_1_reg_2890[0:0] === 1'b1) ? writeindextmp_V12_reg_611 : writeindex_V_reg_2885);

assign t_V_3_fu_794_p3 = ((or_ln123_1_fu_776_p2[0:0] === 1'b1) ? t_V14_reg_543 : istubinner_V_fu_782_p2);

assign teBuffer_7_V_146_fu_1177_p3 = ((icmp_ln321_1_reg_3115[0:0] === 1'b1) ? teBuffer_7_V_1_load_reg_2914 : teBuffer_7_V_fu_1171_p3);

assign teBuffer_7_V_147_fu_1189_p3 = ((icmp_ln321_2_fu_1183_p2[0:0] === 1'b1) ? teBuffer_7_V_1_load_reg_2914 : teBuffer_7_V_146_fu_1177_p3);

assign teBuffer_7_V_148_fu_1202_p3 = ((icmp_ln321_3_fu_1196_p2[0:0] === 1'b1) ? teBuffer_7_V_1_load_reg_2914 : teBuffer_7_V_147_fu_1189_p3);

assign teBuffer_7_V_149_fu_1215_p3 = ((icmp_ln321_4_fu_1209_p2[0:0] === 1'b1) ? teBuffer_7_V_1_load_reg_2914 : teBuffer_7_V_148_fu_1202_p3);

assign teBuffer_7_V_150_fu_1228_p3 = ((icmp_ln321_5_fu_1222_p2[0:0] === 1'b1) ? teBuffer_7_V_1_load_reg_2914 : teBuffer_7_V_149_fu_1215_p3);

assign teBuffer_7_V_151_fu_1241_p3 = ((icmp_ln321_6_fu_1235_p2[0:0] === 1'b1) ? teBuffer_7_V_1_load_reg_2914 : teBuffer_7_V_150_fu_1228_p3);

assign teBuffer_7_V_152_fu_1248_p3 = ((icmp_ln321_reg_3107[0:0] === 1'b1) ? p_Result_s_fu_1162_p5 : teBuffer_7_V_15_load_reg_2933);

assign teBuffer_7_V_153_fu_1254_p3 = ((icmp_ln321_1_reg_3115[0:0] === 1'b1) ? teBuffer_7_V_15_load_reg_2933 : teBuffer_7_V_152_fu_1248_p3);

assign teBuffer_7_V_154_fu_1260_p3 = ((icmp_ln321_2_fu_1183_p2[0:0] === 1'b1) ? teBuffer_7_V_15_load_reg_2933 : teBuffer_7_V_153_fu_1254_p3);

assign teBuffer_7_V_155_fu_1267_p3 = ((icmp_ln321_3_fu_1196_p2[0:0] === 1'b1) ? teBuffer_7_V_15_load_reg_2933 : teBuffer_7_V_154_fu_1260_p3);

assign teBuffer_7_V_156_fu_1274_p3 = ((icmp_ln321_4_fu_1209_p2[0:0] === 1'b1) ? teBuffer_7_V_15_load_reg_2933 : teBuffer_7_V_155_fu_1267_p3);

assign teBuffer_7_V_157_fu_1281_p3 = ((icmp_ln321_5_fu_1222_p2[0:0] === 1'b1) ? teBuffer_7_V_15_load_reg_2933 : teBuffer_7_V_156_fu_1274_p3);

assign teBuffer_7_V_158_fu_1288_p3 = ((icmp_ln321_6_fu_1235_p2[0:0] === 1'b1) ? teBuffer_7_V_15_load_reg_2933 : teBuffer_7_V_157_fu_1281_p3);

assign teBuffer_7_V_159_fu_1295_p3 = ((icmp_ln321_1_reg_3115[0:0] === 1'b1) ? p_Result_s_fu_1162_p5 : teBuffer_7_V_22_load_reg_2952);

assign teBuffer_7_V_160_fu_1301_p3 = ((icmp_ln321_2_fu_1183_p2[0:0] === 1'b1) ? teBuffer_7_V_22_load_reg_2952 : teBuffer_7_V_159_fu_1295_p3);

assign teBuffer_7_V_161_fu_1308_p3 = ((icmp_ln321_3_fu_1196_p2[0:0] === 1'b1) ? teBuffer_7_V_22_load_reg_2952 : teBuffer_7_V_160_fu_1301_p3);

assign teBuffer_7_V_162_fu_1315_p3 = ((icmp_ln321_4_fu_1209_p2[0:0] === 1'b1) ? teBuffer_7_V_22_load_reg_2952 : teBuffer_7_V_161_fu_1308_p3);

assign teBuffer_7_V_163_fu_1322_p3 = ((icmp_ln321_5_fu_1222_p2[0:0] === 1'b1) ? teBuffer_7_V_22_load_reg_2952 : teBuffer_7_V_162_fu_1315_p3);

assign teBuffer_7_V_164_fu_1329_p3 = ((icmp_ln321_6_fu_1235_p2[0:0] === 1'b1) ? teBuffer_7_V_22_load_reg_2952 : teBuffer_7_V_163_fu_1322_p3);

assign teBuffer_7_V_165_fu_1336_p3 = ((icmp_ln321_2_fu_1183_p2[0:0] === 1'b1) ? p_Result_s_fu_1162_p5 : teBuffer_7_V_28_load_reg_2970);

assign teBuffer_7_V_166_fu_1343_p3 = ((icmp_ln321_3_fu_1196_p2[0:0] === 1'b1) ? teBuffer_7_V_28_load_reg_2970 : teBuffer_7_V_165_fu_1336_p3);

assign teBuffer_7_V_167_fu_1350_p3 = ((icmp_ln321_4_fu_1209_p2[0:0] === 1'b1) ? teBuffer_7_V_28_load_reg_2970 : teBuffer_7_V_166_fu_1343_p3);

assign teBuffer_7_V_168_fu_1357_p3 = ((icmp_ln321_5_fu_1222_p2[0:0] === 1'b1) ? teBuffer_7_V_28_load_reg_2970 : teBuffer_7_V_167_fu_1350_p3);

assign teBuffer_7_V_169_fu_1364_p3 = ((icmp_ln321_6_fu_1235_p2[0:0] === 1'b1) ? teBuffer_7_V_28_load_reg_2970 : teBuffer_7_V_168_fu_1357_p3);

assign teBuffer_7_V_170_fu_1371_p3 = ((icmp_ln321_3_fu_1196_p2[0:0] === 1'b1) ? p_Result_s_fu_1162_p5 : teBuffer_7_V_33_load_reg_2987);

assign teBuffer_7_V_171_fu_1378_p3 = ((icmp_ln321_4_fu_1209_p2[0:0] === 1'b1) ? teBuffer_7_V_33_load_reg_2987 : teBuffer_7_V_170_fu_1371_p3);

assign teBuffer_7_V_172_fu_1385_p3 = ((icmp_ln321_5_fu_1222_p2[0:0] === 1'b1) ? teBuffer_7_V_33_load_reg_2987 : teBuffer_7_V_171_fu_1378_p3);

assign teBuffer_7_V_173_fu_1392_p3 = ((icmp_ln321_6_fu_1235_p2[0:0] === 1'b1) ? teBuffer_7_V_33_load_reg_2987 : teBuffer_7_V_172_fu_1385_p3);

assign teBuffer_7_V_174_fu_1399_p3 = ((icmp_ln321_4_fu_1209_p2[0:0] === 1'b1) ? p_Result_s_fu_1162_p5 : teBuffer_7_V_37_load_reg_3003);

assign teBuffer_7_V_175_fu_1406_p3 = ((icmp_ln321_5_fu_1222_p2[0:0] === 1'b1) ? teBuffer_7_V_37_load_reg_3003 : teBuffer_7_V_174_fu_1399_p3);

assign teBuffer_7_V_176_fu_1413_p3 = ((icmp_ln321_6_fu_1235_p2[0:0] === 1'b1) ? teBuffer_7_V_37_load_reg_3003 : teBuffer_7_V_175_fu_1406_p3);

assign teBuffer_7_V_177_fu_1420_p3 = ((icmp_ln321_5_fu_1222_p2[0:0] === 1'b1) ? p_Result_s_fu_1162_p5 : teBuffer_7_V_40_load_reg_3018);

assign teBuffer_7_V_178_fu_1427_p3 = ((icmp_ln321_6_fu_1235_p2[0:0] === 1'b1) ? teBuffer_7_V_40_load_reg_3018 : teBuffer_7_V_177_fu_1420_p3);

assign teBuffer_7_V_179_fu_1434_p3 = ((icmp_ln321_6_fu_1235_p2[0:0] === 1'b1) ? p_Result_s_fu_1162_p5 : teBuffer_7_V_50_load_reg_3032);

assign teBuffer_7_V_180_fu_1441_p3 = ((savestart_V_reg_3075[0:0] === 1'b1) ? teBuffer_7_V_151_fu_1241_p3 : teBuffer_7_V_1_load_reg_2914);

assign teBuffer_7_V_181_fu_1447_p3 = ((savestart_V_reg_3075[0:0] === 1'b1) ? teBuffer_7_V_158_fu_1288_p3 : teBuffer_7_V_15_load_reg_2933);

assign teBuffer_7_V_182_fu_1453_p3 = ((savestart_V_reg_3075[0:0] === 1'b1) ? teBuffer_7_V_164_fu_1329_p3 : teBuffer_7_V_22_load_reg_2952);

assign teBuffer_7_V_183_fu_1459_p3 = ((savestart_V_reg_3075[0:0] === 1'b1) ? teBuffer_7_V_169_fu_1364_p3 : teBuffer_7_V_28_load_reg_2970);

assign teBuffer_7_V_184_fu_1465_p3 = ((savestart_V_reg_3075[0:0] === 1'b1) ? teBuffer_7_V_173_fu_1392_p3 : teBuffer_7_V_33_load_reg_2987);

assign teBuffer_7_V_185_fu_1471_p3 = ((savestart_V_reg_3075[0:0] === 1'b1) ? teBuffer_7_V_176_fu_1413_p3 : teBuffer_7_V_37_load_reg_3003);

assign teBuffer_7_V_186_fu_1477_p3 = ((savestart_V_reg_3075[0:0] === 1'b1) ? teBuffer_7_V_178_fu_1427_p3 : teBuffer_7_V_40_load_reg_3018);

assign teBuffer_7_V_187_fu_1483_p3 = ((savestart_V_reg_3075[0:0] === 1'b1) ? teBuffer_7_V_179_fu_1434_p3 : teBuffer_7_V_50_load_reg_3032);

assign teBuffer_7_V_189_fu_1498_p3 = ((icmp_ln321_1_reg_3115[0:0] === 1'b1) ? teBuffer_7_V_180_fu_1441_p3 : p_Result_1_fu_1489_p5);

assign teBuffer_7_V_190_fu_1505_p3 = ((icmp_ln321_2_fu_1183_p2[0:0] === 1'b1) ? teBuffer_7_V_180_fu_1441_p3 : teBuffer_7_V_189_fu_1498_p3);

assign teBuffer_7_V_191_fu_1513_p3 = ((icmp_ln321_3_fu_1196_p2[0:0] === 1'b1) ? teBuffer_7_V_180_fu_1441_p3 : teBuffer_7_V_190_fu_1505_p3);

assign teBuffer_7_V_192_fu_1521_p3 = ((icmp_ln321_4_fu_1209_p2[0:0] === 1'b1) ? teBuffer_7_V_180_fu_1441_p3 : teBuffer_7_V_191_fu_1513_p3);

assign teBuffer_7_V_193_fu_1529_p3 = ((icmp_ln321_5_fu_1222_p2[0:0] === 1'b1) ? teBuffer_7_V_180_fu_1441_p3 : teBuffer_7_V_192_fu_1521_p3);

assign teBuffer_7_V_194_fu_1537_p3 = ((icmp_ln321_6_fu_1235_p2[0:0] === 1'b1) ? teBuffer_7_V_180_fu_1441_p3 : teBuffer_7_V_193_fu_1529_p3);

assign teBuffer_7_V_195_fu_1551_p3 = ((icmp_ln321_7_fu_1545_p2[0:0] === 1'b1) ? teBuffer_7_V_180_fu_1441_p3 : teBuffer_7_V_194_fu_1537_p3);

assign teBuffer_7_V_196_fu_1559_p3 = ((icmp_ln321_1_reg_3115[0:0] === 1'b1) ? p_Result_1_fu_1489_p5 : teBuffer_7_V_181_fu_1447_p3);

assign teBuffer_7_V_197_fu_1566_p3 = ((icmp_ln321_2_fu_1183_p2[0:0] === 1'b1) ? teBuffer_7_V_181_fu_1447_p3 : teBuffer_7_V_196_fu_1559_p3);

assign teBuffer_7_V_198_fu_1574_p3 = ((icmp_ln321_3_fu_1196_p2[0:0] === 1'b1) ? teBuffer_7_V_181_fu_1447_p3 : teBuffer_7_V_197_fu_1566_p3);

assign teBuffer_7_V_199_fu_1582_p3 = ((icmp_ln321_4_fu_1209_p2[0:0] === 1'b1) ? teBuffer_7_V_181_fu_1447_p3 : teBuffer_7_V_198_fu_1574_p3);

assign teBuffer_7_V_200_fu_1590_p3 = ((icmp_ln321_5_fu_1222_p2[0:0] === 1'b1) ? teBuffer_7_V_181_fu_1447_p3 : teBuffer_7_V_199_fu_1582_p3);

assign teBuffer_7_V_201_fu_1598_p3 = ((icmp_ln321_6_fu_1235_p2[0:0] === 1'b1) ? teBuffer_7_V_181_fu_1447_p3 : teBuffer_7_V_200_fu_1590_p3);

assign teBuffer_7_V_202_fu_1606_p3 = ((icmp_ln321_7_fu_1545_p2[0:0] === 1'b1) ? teBuffer_7_V_181_fu_1447_p3 : teBuffer_7_V_201_fu_1598_p3);

assign teBuffer_7_V_203_fu_1614_p3 = ((icmp_ln321_2_fu_1183_p2[0:0] === 1'b1) ? p_Result_1_fu_1489_p5 : teBuffer_7_V_182_fu_1453_p3);

assign teBuffer_7_V_204_fu_1622_p3 = ((icmp_ln321_3_fu_1196_p2[0:0] === 1'b1) ? teBuffer_7_V_182_fu_1453_p3 : teBuffer_7_V_203_fu_1614_p3);

assign teBuffer_7_V_205_fu_1630_p3 = ((icmp_ln321_4_fu_1209_p2[0:0] === 1'b1) ? teBuffer_7_V_182_fu_1453_p3 : teBuffer_7_V_204_fu_1622_p3);

assign teBuffer_7_V_206_fu_1638_p3 = ((icmp_ln321_5_fu_1222_p2[0:0] === 1'b1) ? teBuffer_7_V_182_fu_1453_p3 : teBuffer_7_V_205_fu_1630_p3);

assign teBuffer_7_V_207_fu_1646_p3 = ((icmp_ln321_6_fu_1235_p2[0:0] === 1'b1) ? teBuffer_7_V_182_fu_1453_p3 : teBuffer_7_V_206_fu_1638_p3);

assign teBuffer_7_V_208_fu_1654_p3 = ((icmp_ln321_7_fu_1545_p2[0:0] === 1'b1) ? teBuffer_7_V_182_fu_1453_p3 : teBuffer_7_V_207_fu_1646_p3);

assign teBuffer_7_V_209_fu_1662_p3 = ((icmp_ln321_3_fu_1196_p2[0:0] === 1'b1) ? p_Result_1_fu_1489_p5 : teBuffer_7_V_183_fu_1459_p3);

assign teBuffer_7_V_210_fu_1670_p3 = ((icmp_ln321_4_fu_1209_p2[0:0] === 1'b1) ? teBuffer_7_V_183_fu_1459_p3 : teBuffer_7_V_209_fu_1662_p3);

assign teBuffer_7_V_211_fu_1678_p3 = ((icmp_ln321_5_fu_1222_p2[0:0] === 1'b1) ? teBuffer_7_V_183_fu_1459_p3 : teBuffer_7_V_210_fu_1670_p3);

assign teBuffer_7_V_212_fu_1686_p3 = ((icmp_ln321_6_fu_1235_p2[0:0] === 1'b1) ? teBuffer_7_V_183_fu_1459_p3 : teBuffer_7_V_211_fu_1678_p3);

assign teBuffer_7_V_213_fu_1694_p3 = ((icmp_ln321_7_fu_1545_p2[0:0] === 1'b1) ? teBuffer_7_V_183_fu_1459_p3 : teBuffer_7_V_212_fu_1686_p3);

assign teBuffer_7_V_214_fu_1702_p3 = ((icmp_ln321_4_fu_1209_p2[0:0] === 1'b1) ? p_Result_1_fu_1489_p5 : teBuffer_7_V_184_fu_1465_p3);

assign teBuffer_7_V_215_fu_1710_p3 = ((icmp_ln321_5_fu_1222_p2[0:0] === 1'b1) ? teBuffer_7_V_184_fu_1465_p3 : teBuffer_7_V_214_fu_1702_p3);

assign teBuffer_7_V_216_fu_1718_p3 = ((icmp_ln321_6_fu_1235_p2[0:0] === 1'b1) ? teBuffer_7_V_184_fu_1465_p3 : teBuffer_7_V_215_fu_1710_p3);

assign teBuffer_7_V_217_fu_1726_p3 = ((icmp_ln321_7_fu_1545_p2[0:0] === 1'b1) ? teBuffer_7_V_184_fu_1465_p3 : teBuffer_7_V_216_fu_1718_p3);

assign teBuffer_7_V_218_fu_1734_p3 = ((icmp_ln321_5_fu_1222_p2[0:0] === 1'b1) ? p_Result_1_fu_1489_p5 : teBuffer_7_V_185_fu_1471_p3);

assign teBuffer_7_V_219_fu_1742_p3 = ((icmp_ln321_6_fu_1235_p2[0:0] === 1'b1) ? teBuffer_7_V_185_fu_1471_p3 : teBuffer_7_V_218_fu_1734_p3);

assign teBuffer_7_V_220_fu_1750_p3 = ((icmp_ln321_7_fu_1545_p2[0:0] === 1'b1) ? teBuffer_7_V_185_fu_1471_p3 : teBuffer_7_V_219_fu_1742_p3);

assign teBuffer_7_V_221_fu_1758_p3 = ((icmp_ln321_6_fu_1235_p2[0:0] === 1'b1) ? p_Result_1_fu_1489_p5 : teBuffer_7_V_186_fu_1477_p3);

assign teBuffer_7_V_222_fu_1766_p3 = ((icmp_ln321_7_fu_1545_p2[0:0] === 1'b1) ? teBuffer_7_V_186_fu_1477_p3 : teBuffer_7_V_221_fu_1758_p3);

assign teBuffer_7_V_223_fu_1774_p3 = ((icmp_ln321_7_fu_1545_p2[0:0] === 1'b1) ? p_Result_1_fu_1489_p5 : teBuffer_7_V_187_fu_1483_p3);

assign teBuffer_7_V_224_fu_1782_p3 = ((icmp_ln321_reg_3107[0:0] === 1'b1) ? teBuffer_7_V_180_fu_1441_p3 : p_Result_1_fu_1489_p5);

assign teBuffer_7_V_225_fu_1789_p3 = ((icmp_ln321_1_reg_3115[0:0] === 1'b1) ? teBuffer_7_V_180_fu_1441_p3 : teBuffer_7_V_224_fu_1782_p3);

assign teBuffer_7_V_226_fu_1796_p3 = ((icmp_ln321_2_fu_1183_p2[0:0] === 1'b1) ? teBuffer_7_V_180_fu_1441_p3 : teBuffer_7_V_225_fu_1789_p3);

assign teBuffer_7_V_227_fu_1804_p3 = ((icmp_ln321_3_fu_1196_p2[0:0] === 1'b1) ? teBuffer_7_V_180_fu_1441_p3 : teBuffer_7_V_226_fu_1796_p3);

assign teBuffer_7_V_228_fu_1812_p3 = ((icmp_ln321_4_fu_1209_p2[0:0] === 1'b1) ? teBuffer_7_V_180_fu_1441_p3 : teBuffer_7_V_227_fu_1804_p3);

assign teBuffer_7_V_229_fu_1820_p3 = ((icmp_ln321_5_fu_1222_p2[0:0] === 1'b1) ? teBuffer_7_V_180_fu_1441_p3 : teBuffer_7_V_228_fu_1812_p3);

assign teBuffer_7_V_230_fu_1828_p3 = ((icmp_ln321_6_fu_1235_p2[0:0] === 1'b1) ? teBuffer_7_V_180_fu_1441_p3 : teBuffer_7_V_229_fu_1820_p3);

assign teBuffer_7_V_231_fu_1836_p3 = ((icmp_ln321_reg_3107[0:0] === 1'b1) ? p_Result_1_fu_1489_p5 : teBuffer_7_V_181_fu_1447_p3);

assign teBuffer_7_V_232_fu_1843_p3 = ((icmp_ln321_1_reg_3115[0:0] === 1'b1) ? teBuffer_7_V_181_fu_1447_p3 : teBuffer_7_V_231_fu_1836_p3);

assign teBuffer_7_V_233_fu_1850_p3 = ((icmp_ln321_2_fu_1183_p2[0:0] === 1'b1) ? teBuffer_7_V_181_fu_1447_p3 : teBuffer_7_V_232_fu_1843_p3);

assign teBuffer_7_V_234_fu_1858_p3 = ((icmp_ln321_3_fu_1196_p2[0:0] === 1'b1) ? teBuffer_7_V_181_fu_1447_p3 : teBuffer_7_V_233_fu_1850_p3);

assign teBuffer_7_V_235_fu_1866_p3 = ((icmp_ln321_4_fu_1209_p2[0:0] === 1'b1) ? teBuffer_7_V_181_fu_1447_p3 : teBuffer_7_V_234_fu_1858_p3);

assign teBuffer_7_V_236_fu_1874_p3 = ((icmp_ln321_5_fu_1222_p2[0:0] === 1'b1) ? teBuffer_7_V_181_fu_1447_p3 : teBuffer_7_V_235_fu_1866_p3);

assign teBuffer_7_V_237_fu_1882_p3 = ((icmp_ln321_6_fu_1235_p2[0:0] === 1'b1) ? teBuffer_7_V_181_fu_1447_p3 : teBuffer_7_V_236_fu_1874_p3);

assign teBuffer_7_V_238_fu_1890_p3 = ((icmp_ln321_1_reg_3115[0:0] === 1'b1) ? p_Result_1_fu_1489_p5 : teBuffer_7_V_182_fu_1453_p3);

assign teBuffer_7_V_239_fu_1897_p3 = ((icmp_ln321_2_fu_1183_p2[0:0] === 1'b1) ? teBuffer_7_V_182_fu_1453_p3 : teBuffer_7_V_238_fu_1890_p3);

assign teBuffer_7_V_240_fu_1905_p3 = ((icmp_ln321_3_fu_1196_p2[0:0] === 1'b1) ? teBuffer_7_V_182_fu_1453_p3 : teBuffer_7_V_239_fu_1897_p3);

assign teBuffer_7_V_241_fu_1913_p3 = ((icmp_ln321_4_fu_1209_p2[0:0] === 1'b1) ? teBuffer_7_V_182_fu_1453_p3 : teBuffer_7_V_240_fu_1905_p3);

assign teBuffer_7_V_242_fu_1921_p3 = ((icmp_ln321_5_fu_1222_p2[0:0] === 1'b1) ? teBuffer_7_V_182_fu_1453_p3 : teBuffer_7_V_241_fu_1913_p3);

assign teBuffer_7_V_243_fu_1929_p3 = ((icmp_ln321_6_fu_1235_p2[0:0] === 1'b1) ? teBuffer_7_V_182_fu_1453_p3 : teBuffer_7_V_242_fu_1921_p3);

assign teBuffer_7_V_244_fu_1937_p3 = ((icmp_ln321_2_fu_1183_p2[0:0] === 1'b1) ? p_Result_1_fu_1489_p5 : teBuffer_7_V_183_fu_1459_p3);

assign teBuffer_7_V_245_fu_1945_p3 = ((icmp_ln321_3_fu_1196_p2[0:0] === 1'b1) ? teBuffer_7_V_183_fu_1459_p3 : teBuffer_7_V_244_fu_1937_p3);

assign teBuffer_7_V_246_fu_1953_p3 = ((icmp_ln321_4_fu_1209_p2[0:0] === 1'b1) ? teBuffer_7_V_183_fu_1459_p3 : teBuffer_7_V_245_fu_1945_p3);

assign teBuffer_7_V_247_fu_1961_p3 = ((icmp_ln321_5_fu_1222_p2[0:0] === 1'b1) ? teBuffer_7_V_183_fu_1459_p3 : teBuffer_7_V_246_fu_1953_p3);

assign teBuffer_7_V_248_fu_1969_p3 = ((icmp_ln321_6_fu_1235_p2[0:0] === 1'b1) ? teBuffer_7_V_183_fu_1459_p3 : teBuffer_7_V_247_fu_1961_p3);

assign teBuffer_7_V_249_fu_1977_p3 = ((icmp_ln321_3_fu_1196_p2[0:0] === 1'b1) ? p_Result_1_fu_1489_p5 : teBuffer_7_V_184_fu_1465_p3);

assign teBuffer_7_V_250_fu_1985_p3 = ((icmp_ln321_4_fu_1209_p2[0:0] === 1'b1) ? teBuffer_7_V_184_fu_1465_p3 : teBuffer_7_V_249_fu_1977_p3);

assign teBuffer_7_V_251_fu_1993_p3 = ((icmp_ln321_5_fu_1222_p2[0:0] === 1'b1) ? teBuffer_7_V_184_fu_1465_p3 : teBuffer_7_V_250_fu_1985_p3);

assign teBuffer_7_V_252_fu_2001_p3 = ((icmp_ln321_6_fu_1235_p2[0:0] === 1'b1) ? teBuffer_7_V_184_fu_1465_p3 : teBuffer_7_V_251_fu_1993_p3);

assign teBuffer_7_V_253_fu_2009_p3 = ((icmp_ln321_4_fu_1209_p2[0:0] === 1'b1) ? p_Result_1_fu_1489_p5 : teBuffer_7_V_185_fu_1471_p3);

assign teBuffer_7_V_254_fu_2017_p3 = ((icmp_ln321_5_fu_1222_p2[0:0] === 1'b1) ? teBuffer_7_V_185_fu_1471_p3 : teBuffer_7_V_253_fu_2009_p3);

assign teBuffer_7_V_255_fu_2025_p3 = ((icmp_ln321_6_fu_1235_p2[0:0] === 1'b1) ? teBuffer_7_V_185_fu_1471_p3 : teBuffer_7_V_254_fu_2017_p3);

assign teBuffer_7_V_256_fu_2033_p3 = ((icmp_ln321_5_fu_1222_p2[0:0] === 1'b1) ? p_Result_1_fu_1489_p5 : teBuffer_7_V_186_fu_1477_p3);

assign teBuffer_7_V_257_fu_2041_p3 = ((icmp_ln321_6_fu_1235_p2[0:0] === 1'b1) ? teBuffer_7_V_186_fu_1477_p3 : teBuffer_7_V_256_fu_2033_p3);

assign teBuffer_7_V_258_fu_2049_p3 = ((icmp_ln321_6_fu_1235_p2[0:0] === 1'b1) ? p_Result_1_fu_1489_p5 : teBuffer_7_V_187_fu_1483_p3);

assign teBuffer_7_V_259_fu_2057_p3 = ((savestart_V_reg_3075[0:0] === 1'b1) ? teBuffer_7_V_195_fu_1551_p3 : teBuffer_7_V_230_fu_1828_p3);

assign teBuffer_7_V_260_fu_2064_p3 = ((savestart_V_reg_3075[0:0] === 1'b1) ? teBuffer_7_V_202_fu_1606_p3 : teBuffer_7_V_237_fu_1882_p3);

assign teBuffer_7_V_261_fu_2071_p3 = ((savestart_V_reg_3075[0:0] === 1'b1) ? teBuffer_7_V_208_fu_1654_p3 : teBuffer_7_V_243_fu_1929_p3);

assign teBuffer_7_V_262_fu_2078_p3 = ((savestart_V_reg_3075[0:0] === 1'b1) ? teBuffer_7_V_213_fu_1694_p3 : teBuffer_7_V_248_fu_1969_p3);

assign teBuffer_7_V_263_fu_2085_p3 = ((savestart_V_reg_3075[0:0] === 1'b1) ? teBuffer_7_V_217_fu_1726_p3 : teBuffer_7_V_252_fu_2001_p3);

assign teBuffer_7_V_264_fu_2092_p3 = ((savestart_V_reg_3075[0:0] === 1'b1) ? teBuffer_7_V_220_fu_1750_p3 : teBuffer_7_V_255_fu_2025_p3);

assign teBuffer_7_V_265_fu_2099_p3 = ((savestart_V_reg_3075[0:0] === 1'b1) ? teBuffer_7_V_222_fu_1766_p3 : teBuffer_7_V_257_fu_2041_p3);

assign teBuffer_7_V_266_fu_2106_p3 = ((savestart_V_reg_3075[0:0] === 1'b1) ? teBuffer_7_V_223_fu_1774_p3 : teBuffer_7_V_258_fu_2049_p3);

assign teBuffer_7_V_267_fu_2113_p3 = ((savelast_V_reg_3095[0:0] === 1'b1) ? teBuffer_7_V_259_fu_2057_p3 : teBuffer_7_V_180_fu_1441_p3);

assign teBuffer_7_V_268_fu_2120_p3 = ((savelast_V_reg_3095[0:0] === 1'b1) ? teBuffer_7_V_260_fu_2064_p3 : teBuffer_7_V_181_fu_1447_p3);

assign teBuffer_7_V_269_fu_2127_p3 = ((savelast_V_reg_3095[0:0] === 1'b1) ? teBuffer_7_V_261_fu_2071_p3 : teBuffer_7_V_182_fu_1453_p3);

assign teBuffer_7_V_270_fu_2134_p3 = ((savelast_V_reg_3095[0:0] === 1'b1) ? teBuffer_7_V_262_fu_2078_p3 : teBuffer_7_V_183_fu_1459_p3);

assign teBuffer_7_V_271_fu_2141_p3 = ((savelast_V_reg_3095[0:0] === 1'b1) ? teBuffer_7_V_263_fu_2085_p3 : teBuffer_7_V_184_fu_1465_p3);

assign teBuffer_7_V_272_fu_2148_p3 = ((savelast_V_reg_3095[0:0] === 1'b1) ? teBuffer_7_V_264_fu_2092_p3 : teBuffer_7_V_185_fu_1471_p3);

assign teBuffer_7_V_273_fu_2155_p3 = ((savelast_V_reg_3095[0:0] === 1'b1) ? teBuffer_7_V_265_fu_2099_p3 : teBuffer_7_V_186_fu_1477_p3);

assign teBuffer_7_V_274_fu_2162_p3 = ((savelast_V_reg_3095[0:0] === 1'b1) ? teBuffer_7_V_266_fu_2106_p3 : teBuffer_7_V_187_fu_1483_p3);

assign teBuffer_7_V_275_fu_2169_p3 = ((or_ln123_1_reg_2890_pp0_iter2_reg[0:0] === 1'b1) ? teBuffer_7_V_1_load_reg_2914 : teBuffer_7_V_267_fu_2113_p3);

assign teBuffer_7_V_276_fu_2175_p3 = ((or_ln123_1_reg_2890_pp0_iter2_reg[0:0] === 1'b1) ? teBuffer_7_V_15_load_reg_2933 : teBuffer_7_V_268_fu_2120_p3);

assign teBuffer_7_V_277_fu_2181_p3 = ((or_ln123_1_reg_2890_pp0_iter2_reg[0:0] === 1'b1) ? teBuffer_7_V_22_load_reg_2952 : teBuffer_7_V_269_fu_2127_p3);

assign teBuffer_7_V_278_fu_2187_p3 = ((or_ln123_1_reg_2890_pp0_iter2_reg[0:0] === 1'b1) ? teBuffer_7_V_28_load_reg_2970 : teBuffer_7_V_270_fu_2134_p3);

assign teBuffer_7_V_279_fu_2193_p3 = ((or_ln123_1_reg_2890_pp0_iter2_reg[0:0] === 1'b1) ? teBuffer_7_V_33_load_reg_2987 : teBuffer_7_V_271_fu_2141_p3);

assign teBuffer_7_V_280_fu_2199_p3 = ((or_ln123_1_reg_2890_pp0_iter2_reg[0:0] === 1'b1) ? teBuffer_7_V_37_load_reg_3003 : teBuffer_7_V_272_fu_2148_p3);

assign teBuffer_7_V_281_fu_2205_p3 = ((or_ln123_1_reg_2890_pp0_iter2_reg[0:0] === 1'b1) ? teBuffer_7_V_40_load_reg_3018 : teBuffer_7_V_273_fu_2155_p3);

assign teBuffer_7_V_282_fu_2211_p3 = ((or_ln123_1_reg_2890_pp0_iter2_reg[0:0] === 1'b1) ? teBuffer_7_V_50_load_reg_3032 : teBuffer_7_V_274_fu_2162_p3);

assign teBuffer_7_V_fu_1171_p3 = ((icmp_ln321_reg_3107[0:0] === 1'b1) ? teBuffer_7_V_1_load_reg_2914 : p_Result_s_fu_1162_p5);

assign tmp_1_fu_850_p3 = instubinnerdata_dataarray_data_V_q0[32'd3];

assign tmp_2_fu_868_p9 = {{instubinnerdata_dataarray_data_V_q0[6:4]}};

assign tmp_3_fu_882_p9 = {{instubinnerdata_dataarray_data_V_q0[6:4]}};

assign tmp_6_fu_715_p3 = {{ap_phi_mux_p_phi_phi_fu_574_p4}, {ap_phi_mux_t_V14_phi_fu_547_p6}};

assign tmp_7_fu_1144_p5 = {{{{{{56'd0}, {p_phi_reg_570_pp0_iter1_reg}}}, {ibin_V_3_fu_1093_p3}}}, {istubouter_V_fu_266}};

assign tmp_8_fu_2645_p3 = {{p_phi_reg_570_pp0_iter5_reg}, {nstubpairs_V_fu_262}};

assign tmpz_fu_2531_p3 = ((second_V_3_reg_3178[0:0] === 1'b1) ? or_ln_fu_2523_p3 : zext_ln200_fu_2519_p1);

assign trunc_ln209_fu_690_p1 = bx_V[0:0];

assign writeindex_V_fu_746_p2 = (ap_phi_mux_writeindextmp_V12_phi_fu_615_p6 + 3'd2);

assign writeindexplus_V_fu_740_p2 = (ap_phi_mux_writeindextmp_V12_phi_fu_615_p6 + 3'd1);

assign writeindextmp_V_fu_1000_p3 = ((or_ln123_2_fu_988_p2[0:0] === 1'b1) ? select_ln123_fu_982_p3 : select_ln123_1_fu_993_p3);

assign xor_ln123_fu_752_p2 = (ap_phi_reg_pp0_iter1_p_0725_0_i15_reg_626 ^ 1'd1);

assign xor_ln891_fu_2601_p2 = (icmp_ln891_1_reg_3193_pp0_iter5_reg ^ 1'd1);

assign xor_ln899_fu_2596_p2 = (icmp_ln899_reg_3188_pp0_iter5_reg ^ 1'd1);

assign zbinfirst_V_3_fu_2441_p3 = ((icmp_ln879_reg_3132[0:0] === 1'b1) ? zbinfirst_V_fu_2385_p4 : zbinfirst_V_2_fu_250);

assign zbinfirst_V_fu_2385_p4 = {{bufdata_V6_fu_2371_p10[6:4]}};

assign zbinlast_V_fu_862_p2 = (zext_ln209_fu_858_p1 + zbinstart_V_fu_840_p4);

assign zbinstart_V_fu_840_p4 = {{instubinnerdata_dataarray_data_V_q0[6:4]}};

assign zdiffmax_V_3_fu_2434_p3 = ((icmp_ln879_reg_3132[0:0] === 1'b1) ? zdiffmax_V_fu_2361_p4 : zdiffmax_V_2_fu_246);

assign zdiffmax_V_fu_2361_p4 = {{bufdata_V5_fu_2347_p10[13:11]}};

assign zext_ln1467_fu_2538_p1 = zbinfirst_V_3_reg_3172;

assign zext_ln200_fu_2519_p1 = outerstubfinez_V_fu_2515_p1;

assign zext_ln209_fu_858_p1 = tmp_1_fu_850_p3;

assign zext_ln215_1_fu_2541_p1 = tmpz_fu_2531_p3;

assign zext_ln215_2_fu_2545_p1 = zbinfirst_V_3_reg_3172;

assign zext_ln215_fu_1101_p1 = istubouter_V_fu_266;

assign zext_ln321_fu_2653_p1 = tmp_8_fu_2645_p3;

assign zext_ln42_fu_723_p1 = tmp_6_fu_715_p3;

assign zext_ln544_1_fu_2591_p1 = p_Result_3_fu_2582_p4;

assign zext_ln544_fu_2577_p1 = p_Result_2_fu_2569_p4;

assign zext_ln891_fu_1111_p1 = nstubs_V_1_fu_1084_p3;

assign zext_ln899_fu_2554_p1 = zdiffmax_V_3_reg_3167;

endmodule //TrackletEngineTop
